### ISSUE TITLE
Duration: N/A, bitrate: N/A

### ISSUE THREAD

**Issue by gggitpl** [bytedeco/javacv#1006]
```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new FileInputStream("D:\\h264\\1527583512857.h264"));
        grabber.setOption("rtp_transport", "udp");
        grabber.setFormat("H264");
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("rtmp://192.168.0.180/live/hk", 1280, 720, 0);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setFormat("flv");
        try {
            grabber.start();
            recorder.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
```
```
Input #0, h264, from 'java.io.BufferedInputStream@457e2f02':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 1200k tbn, 50 tbc
[libx264 @ 0000000020ec0560] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000000020ec0560] profile High, level 3.1
[libx264 @ 0000000020ec0560] 264 - core 152 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=400 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'rtmp://192.168.0.180/live/hk':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (Constrained Baseline) ([7][0][0][0] / 0x0007), yuv420p, 1280x720, q=2-31, 400 kb/s, 1k tbn
```

Is there any problem with the above content? Now there is a push connection on the media server. It seems that there is no content. It cannot be played with VLC.

**Comment by saudet** [comment]
You need to call grab() and record()...

**Comment by gggitpl** [comment]
```
grabber.start();
            Frame grab = grabber.grab();
            recorder.record(grab);
            recorder.start();
```
Is this called? A new error has occurred

```
org.bytedeco.javacv.FrameRecorder$Exception: No video output stream (Is imageWidth > 0 && imageHeight > 0 and has start() been called?)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:876)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:865)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:858)
	at com.skuo.monitor.sip.mediaserver.Test.main(Test.java:23)
Input #0, h264, from 'java.io.BufferedInputStream@457e2f02':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 1200k tbn, 50 tbc
[swscaler @ 0000000020c85820] deprecated pixel format used, make sure you did set range correctly
```
Playing directly with VLC 1527583512857.h264 is possible
Is there a document description?

**Comment by gggitpl** [comment]
@saudet Hope to get any help from you

**Comment by saudet** [comment]
We need to call start() before grab() and record(). Try to follow the
samples.

**Comment by saudet** [comment]
And there is a sample that does exactly that, thanks for @bennyveo, so you could base your code on it:
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java
