### ISSUE TITLE
avcodec_open2() error -22: Could not open video codec. help wanted

### ISSUE THREAD

**Issue by phoenixxt** [bytedeco/javacv#1026]
The error:
```
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
        at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:687)
        at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:360)
        at biz.mobidev.vladimir.sceneformarcoffeemaker.ArSceneController.record(ArSceneController.kt:153)
```

The code:
```
val file = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "test.mp4")
val recorder = FFmpegFrameRecorder(file, arSceneView.width, arSceneView.height)
		try {
			recorder.timestamp = System.currentTimeMillis()
			recorder.videoCodec = avcodec.AV_CODEC_ID_MPEG4
			recorder.format = "mp4"
			recorder.pixelFormat = avutil.AV_PIX_FMT_ARGB
			//recorder.videoBitrate = 1200
			recorder.frameRate = 25.0
			recorder.start()
			for (i in 0..25) {
				arSceneView.isDrawingCacheEnabled = true
				val bitmap = Bitmap.createBitmap(arSceneView.drawingCache)
				arSceneView.isDrawingCacheEnabled = false
            val frames = bitmapToFrameConverter.convert(bitmap)
				recorder.record(frames)
			}
			recorder.stop()
		} catch (e: Exception) {
			e.printStackTrace()
		}
```

Help find the problem, please.

**Comment by saudet** [comment]
What are the messages that show up in the log, on the console?

**Comment by saudet** [comment]
The issue is probably that AV_CODEC_ID_MPEG4 doesn't support AV_PIX_FMT_ARGB though.

**Comment by saudet** [comment]
Don't try to set anything, start by using the default values.

**Comment by saudet** [comment]
I'm assuming that default values work and you've figured out something, but let me know if this isn't the case! Thanks

**Comment by wld712** [comment]
解决了没,我也同样遇到这样的问题
