### ISSUE TITLE
"method resolution failed" when trying to use face classifier

### ISSUE THREAD

**Issue by AgustinCB** [bytedeco/javacv#1028]
This is the offending code:

```kotlin
    private val recognizer = opencv_face.EigenFaceRecognizer.create()
    fun predict(input: String): String {
        println("FILE $input")
        val mat = opencv_imgcodecs.imread(input, opencv_imgcodecs.CV_LOAD_IMAGE_GRAYSCALE)
        println("MAT ${mat.size().width()} ${mat.size().height()}")
        val ip = IntPointer()
        val dp = DoublePointer()
        val n = intArrayOf()
        val p = doubleArrayOf()
        recognizer.predict(mat, n, p)
        println("RES ${n[0]} ${p[0]}")
        return categories[n[0]]
    }
```

Where the model was previously trained using this

```kotlin
    private val recognizer = opencv_face.EigenFaceRecognizer.create()
    fun train(): opencv_face.FaceRecognizer {
        val imageBuffer = opencv_core.MatVector(totalImages.toLong())
        val intLabels = opencv_core.Mat(totalImages, 1, CV_32SC1)
        val labelsBuf: IntBuffer = intLabels.createBuffer()
        var counter = 0

        labels.forEachIndexed { label,player ->
            faces[player]?.forEach { file ->
                val mat = opencv_imgcodecs.imread(file, opencv_imgcodecs.CV_LOAD_IMAGE_GRAYSCALE)
                imageBuffer.put(counter.toLong(), mat)
                labelsBuf.put(counter, label)
                counter += 1
            }
        }

        recognizer.train(imageBuffer, intLabels)
        return recognizer
    }
```

Running the `predict` function, shows this error:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc9390d0fdf, pid=24818, tid=24831
#
# JRE version: OpenJDK Runtime Environment (9.0+11) (build 9.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libopencv_face.so.3.4+0x61fdf]  cv::face::FaceRecognizer::predict(cv::_InputArray const&, int&, double&) const+0x9f
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /home/agustin/AndroidStudioProjects/HiliteCLI/core.24818)
#
# An error report file with more information is saved as:
# /home/agustin/AndroidStudioProjects/HiliteCLI/hs_err_pid24818.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

When I check the log, I see this errors:

```
Internal exceptions (10 events):
Event: 0.352 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a6656a0}: method resolution failed
> (0x000000057a6656a0) thrown at [/build/java9-openjdk/src/jdk9u-jdk-9.0.4+11/hotspot/src/share/vm/prims/methodHandles.cpp, lin
e 1256]
Event: 0.352 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a668dd8}: java.lang.invoke.DirectM
ethodHandle$Holder.invokeStaticInit(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I> (0x000000057a66
8dd8) thrown at [/build/java9-openjdk/sr
Event: 0.355 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a6786b8}: java.lang.invoke.DirectM
ethodHandle$Holder.invokeInterface(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> (0x000000057a6786b8) thrown at [/bu
ild/java9-openjdk/src/jdk9u-jdk-9.0.4+11
Event: 0.356 Thread 0x00007fc9f8017000 Exception <a 'java/lang/IncompatibleClassChangeError'{0x000000057a67b5b8}: Found class j
ava.lang.Object, but interface was expected> (0x000000057a67b5b8) thrown at [/build/java9-openjdk/src/jdk9u-jdk-9.0.4+11/hotspo
t/src/share/vm/interpreter/linkResolver.
Event: 0.356 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a67f498}: java.lang.invoke.DirectM
ethodHandle$Holder.invokeStaticInit(Ljava/lang/Object;Ljava/lang/Object;)V> (0x000000057a67f498) thrown at [/build/java9-openjd
k/src/jdk9u-jdk-9.0.4+11/hotspot/src/sha
Event: 0.359 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a691c68}: java.lang.invoke.DirectM
ethodHandle$Holder.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)I> (0x000000057a691c68) thrown at [/build/java9-openjdk/sr
c/jdk9u-jdk-9.0.4+11/hotspot/src/share/v
Event: 0.360 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a694e18}: java.lang.invoke.DirectM
ethodHandle$Holder.invokeStaticInit(Ljava/lang/Object;Ljava/lang/Object;)I> (0x000000057a694e18) thrown at [/build/java9-openjd
k/src/jdk9u-jdk-9.0.4+11/hotspot/src/sha
Event: 0.361 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a69d648}: java.lang.invoke.DirectM
ethodHandle$Holder.invokeInterface(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I> (0x000000057a69d648) thrown at [/b
uild/java9-openjdk/src/jdk9u-jdk-9.0.4+1
Event: 0.418 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a230138}: java.lang.Object.of([Lja
va/lang/Object;)Ljava/util/stream/Stream;> (0x000000057a230138) thrown at [/build/java9-openjdk/src/jdk9u-jdk-9.0.4+11/hotspot/
src/share/vm/interpreter/linkResolver.cp
Event: 0.488 Thread 0x00007fc9f8017000 Exception <a 'java/lang/NoSuchMethodError'{0x000000057a0a4758}: method resolution failed
> (0x000000057a0a4758) thrown at [/build/java9-openjdk/src/jdk9u-jdk-9.0.4+11/hotspot/src/share/vm/prims/methodHandles.cpp, lin
e 1256
```

Which I'm not sure how to interpret.

The relevant parts of my gradle file:

```
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.4.1'
}
```

Any idea what's wrong?

Thanks

**Comment by saudet** [comment]
First, call the predict function with Pointer objects instead of arrays.

**Comment by AgustinCB** [comment]
Thank you.

If I do:

```kotlin
    fun predict(input: String): String {
        println("FILE $input")
        val mat = opencv_imgcodecs.imread(input, opencv_imgcodecs.CV_LOAD_IMAGE_GRAYSCALE)
        println("MAT ${mat.size().width()} ${mat.size().height()}")
        val ip = IntPointer()
        val dp = DoublePointer()
        val n = intArrayOf()
        val p = doubleArrayOf()
        recognizer.predict(mat, ip, dp)
        println("RES ${ip.get()} ${dp.get()}")
        return categories[ip.get()]
    }
```

I get the error:

```
Exception in thread "main" java.lang.NullPointerException: Pointer address of argument 1 is NULL.
	at org.bytedeco.javacpp.opencv_face$FaceRecognizer.predict(Native Method)
	at com.hilite.cli.ModelPredictor.predict(ModelPredictor.kt:25)
	at com.hilite.cli.HiliteKt.predictCommand(hilite.kt:21)
	at com.hilite.cli.HiliteKt.processCommand(hilite.kt:46)
	at com.hilite.cli.HiliteKt.main(hilite.kt:53)
```

**Comment by AgustinCB** [comment]
Oh, fuck, I have to pass a size. Adding one as parameter works. Thanks!

**Comment by saudet** [comment]
Passing arrays of size 1 should also work!
