### ISSUE TITLE
FFmpegFrameGrabber.start() fails because can not open input filepath. 

### ISSUE THREAD

**Issue by rexxxx1234** [bytedeco/javacv#1038]
I'm trying to grabFrameImage from an mp4 video file in the raw folder of an Android app, and then want to pass the image's address to a jni native OpenCV code to do some processing.

But FFmpegFrameGrabber.start() failed.

I have read all the related issues and I believe I configure the library right, but still, I couldn't get it to work. I am depressed and really want help.

The code I am running:
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_analyze_video);

        String path = "android.resource://"+ getPackageName()+"/" + R.raw.testvideo;
        //String path = "/Users/mashihao/AndroidStudioProjects/HandTrack/app/src/main/res/raw/testvideo.mp4";
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(path);
        grabber.setFormat("mp4");
        try {
            grabber.start();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }

    }
```

The error I am getting:
```
W/System.err: org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -1330794744: Could not open input "android.resource://com.example.anslab.handtrack/2131558400". (Has setFormat() been called?)
                  at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:754)
                  at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:690)
                  at com.example.anslab.handtrack.AnalyzeVideoModule.AnalyzeVideo.onCreate(AnalyzeVideo.java:58)
                  at android.app.Activity.performCreate(Activity.java:6275)
                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:148)
                  at android.app.ActivityThread.main(ActivityThread.java:5451)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

How I config the libraries:
```
    implementation group: 'org.bytedeco', name: 'javacv', version: '1.4.2'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-arm64'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-x86_64'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-arm64'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-x86_64'
```

Any help will be greated appreciated. Please help me! Thank you.

**Comment by saudet** [comment]
As far as I know, resources are not accessible as files, we have to extract them, but fortunately JavaCPP comes with a handy method for that, Loader.extractResource() as demonstrated in the Demo class of the README.md file: https://github.com/bytedeco/javacv

**Comment by saudet** [comment]
An alternative might be to use "assets" instead:
https://developer.android.com/guide/topics/resources/providing-resources#OriginalFiles

**Comment by saudet** [comment]
You could also try to use the `FFmpegFrameGrabber(InputStream)` constructor, but that doesn't always work very well, especially with MP4 files.
