### ISSUE TITLE
Starting issue. RuntimeException. Seems to be a fix path in the lib

### ISSUE THREAD

**Issue by peymanman** [bytedeco/javacv#1042]
Hi, 

I just tried to use the very first example

```
public static void main(String[] args) {
        opencv_core.IplImage image = cvLoadImage(path);
        if (image != null) {
            cvSmooth(image, image);
            cvSaveImage(path, image);
            cvReleaseImage(image);
        }
    }
```

The exception seems to be related to a fix path in the lib?! Anyone?
 
```
Exception in thread "main" java.lang.RuntimeException: OpenCV(3.4.2) /Users/travis/build/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.4.2/modules/core/src/matrix_wrap.cpp:800: error: (-215:Assertion failed) (flags & FIXED_TYPE) != 0 in function 'type'

	at org.bytedeco.javacpp.opencv_imgcodecs.cvSaveImage(Native Method)
	at ai.peyman.face.Test.main(Test.java:15)
```

**Comment by saudet** [comment]
It's a known bug in the C API of OpenCV that they are not going to fix, see issue #998. I guess this means it's time to update the README.md file of JavaCV and use the C++ API instead...

**Comment by saudet** [comment]
Ok, it's done! Please try with the updated code using the C++ API. Thanks for reporting!

**Comment by cpotter1** [comment]
Sorry for being thick on this, but how do we use this with JavaCV ?

**Comment by saudet** [comment]
@cpotter1 Refer to the new Demo class, it uses the C++ API.
