### ISSUE TITLE
Version 3.4.2-1.4.1 UnsatisfiedLinkError

### ISSUE THREAD

**Issue by monxarat** [bytedeco/javacv#1065]
Hi guys,

How to fix this bugs.

Logs
```
Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at org.bytedeco.javacpp.Loader.load(Loader.java:938)
        at org.bytedeco.javacpp.Loader.load(Loader.java:879)
        at org.bytedeco.javacpp.avformat$Write_packet_Pointer_BytePointer_int.<clinit>(avformat.java:640)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:309)
```

build.gradle
```
// javacpp group
    implementation files('libs/commons-math3-3.5.jar')
    implementation('org.bytedeco:javacv-platform:1.4.1') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }

    // javacpp and ffmpeg
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.2-1.4.1'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.2-1.4.1', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.2-1.4.1', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: 'android-x86'
```

**Comment by saudet** [comment]
Try again with JavaCV 1.4.2 please.

**Comment by monxarat** [comment]
I have using JavaCV 1.4.2 but the same error.

```
implementation files('libs/commons-math3-3.5.jar')
    implementation('org.bytedeco:javacv-platform:1.4.2') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    // javacpp and ffmpeg
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-x86'
```

**Comment by saudet** [comment]
Also include 'android-arm64' and 'android-x86_64'.

**Comment by monxarat** [comment]
after build. libs look like below.

![qaqaqaqaqa](https://user-images.githubusercontent.com/4075787/46195785-350a7080-c340-11e8-9802-558006dd8350.png)

```
implementation('org.bytedeco:javacv-platform:1.4.2') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }

    // javacpp and ffmpeg
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-arm64'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-x86_64'

    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-arm64'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.2-1.4.2', classifier: 'android-x86_64'
```

I ran in Nexus 5.

**Comment by saudet** [comment]
The cause of exception will tell you which library is missing, and if not it will be displayed in the log. Look it up, and add what is missing.

**Comment by saudet** [comment]
Also make sure to disable ProGuard, that's probably the issue you're having here. 
And if that doesn't solve the issue, use ReLinker, that will work for sure:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by saudet** [comment]
Let me know if you're not able to solve the error either though, thanks!
