### ISSUE TITLE
Changing frame properties on the fly is not supported  when mix 2 aac to m4a 

### ISSUE THREAD

**Issue by buhe** [bytedeco/javacv#1080]
hey, i mix 2 m4a to m4a is ok,but mix 2 aac file to m4a throw a exception like:
```
[aac @ 0x7fb7bd9ffc00] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from '/Users/buhe/github/white-audio/./1.aac':
  Duration: 00:00:42.97, bitrate: 72 kb/s
    Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp, 72 kb/s
[aac @ 0x7fb7c0105000] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from '/Users/buhe/github/white-audio/./1.aac':
  Duration: 00:00:42.97, bitrate: 72 kb/s
    Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp, 72 kb/s
[Parsed_amerge_0 @ 0x7fb7bcd5b680] Input channel layouts overlap: output layout will be determined by the number of distinct input channels
Output #0, adts, to '/Users/buhe/github/white-audio/./test2.aac':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 64 kb/s
1 is 0
[0:a @ 0x7fb7bcd5ac40] Changing frame properties on the fly is not supported.
Exception in thread "main" org.bytedeco.javacv.FrameFilter$Exception: av_buffersrc_add_frame_flags() error -22: Error while feeding the filtergraph.
	at org.bytedeco.javacv.FFmpegFrameFilter.pushSamples(FFmpegFrameFilter.java:566)
	at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:471)
	at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:462)
	at com.herewhite.audiomix.JavaCVMixer4.main(JavaCVMixer4.java:85)
```

The full code is 
```java
public class JavaCVMixer4 {

    public static void main(String[] args) throws Exception {
        File tempFile = new File(".", "1.aac");
        File tempFile2 = new File(".", "1.aac");

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(tempFile);
        grabber.start();

        FFmpegFrameGrabber grabberc = new FFmpegFrameGrabber(tempFile2);
        grabberc.start();

        FFmpegFrameFilter filter = new FFmpegFrameFilter(
                null,
                "[0:a][1:a]amerge[a]",
                0, 0, 2);
//        filter.setPixelFormat(grabber.getPixelFormat());
        filter.setSampleFormat(grabber.getSampleFormat());
//        filter.setVideoInputs(2);
        filter.setAudioInputs(2);
        filter.start();


        File tempFile3 = new File(".", "test2.aac");

        FFmpegFrameRecorder recorder2 = new FFmpegFrameRecorder(tempFile3, 0, 0, 2);
//        recorder2.setVideoCodec(AV_CODEC_ID_VP8);
        recorder2.setAudioCodec(AV_CODEC_ID_AAC);
        recorder2.start();

//        FFmpegFrameRecorder audio0 = new FFmpegFrameRecorder("", 1);
//        FFmpegFrameRecorder audio1 = new FFmpegFrameRecorder("", 1);
//
//        audio0.start();
//        audio1.start();
//
//        FFmpegFrameFilter amovie = new FFmpegFrameFilter();

        int a = 0, b = 0, c = 0, d = 0;
        Frame frame2;

        while ((frame2 = grabber.grab()) != null) {
            if (frame2.image != null) {
                a++;
            }
            if (frame2.samples != null) {
                b++;
            }
            System.out.println(b + " is " + grabber.getTimestamp());
            filter.push(0, frame2);



            filter.push(1, grabberc.grab());
            Frame frame3;
            while ((frame3 = filter.pull()) != null) {
                if (frame3.image != null) {
                    c++;
                }
                if (frame3.samples != null) {
                    d++;
                }
                recorder2.record(frame3);
            }
        }


        recorder2.stop();
        recorder2.release();


        System.out.printf("a is %d b is %d c is %d d is ", a, b, c, d);
        filter.stop();
        filter.release();
        grabber.restart();
        grabber.stop();
        grabber.release();

    }
}
```

thank you attention.

**Comment by saudet** [comment]
Since the input files have 1 channel, you'll need to `setAudioChannels(1)`. Those settings are for the input.

**Comment by buhe** [comment]
thanks reply
