### ISSUE TITLE
【windows】Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path

### ISSUE THREAD

**Issue by kigkrazy** [bytedeco/javacv#1085]
May I miss some step? is there some software must be installed?
### dependencies
```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.4.3'
//    compile group: 'org.bytedeco', name: 'javacv', version: '1.4.3'
//    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.3-1.4.3', classifier: 'android-arm'
//    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.3-1.4.3', classifier: 'android-x86'
//    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.2-1.4.3', classifier: 'android-arm'
//    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.2-1.4.3', classifier: 'android-x86'
}

```

### error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1258)
	at org.bytedeco.javacpp.Loader.load(Loader.java:999)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.bytedeco.javacpp.opencv_videoio.<clinit>(opencv_videoio.java:14)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:950)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.bytedeco.javacpp.opencv_highgui.<clinit>(opencv_highgui.java:15)
	at com.reizx.jcveg.TemplateMatching.newStyle(TemplateMatching.java:58)
	at com.reizx.jcveg.TemplateMatching.main(TemplateMatching.java:29)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\kig\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1238)
	... 10 more
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by saudet** [comment]
You're probably on Windows Server right? That happens when `MF.dll` and `MFPlat.dll` are not in the PATH, but they are still usually on the system somewhere in `C:\Windows\WinSxS`. They get added when installing the "Media Foundation" feature, for example, this way: https://help.manycam.com/knowledge-base/media-foundation-missing/#add-media-foundation-via-server-manager
