### ISSUE TITLE
FaceRecognizer train error

### ISSUE THREAD

**Issue by agunin** [bytedeco/javacv#1108]
Hello ,
I am running this the Open CV Face Recognizer example but java returns this runtime error and i am not sue why/how to fix it? Thanks

NetBeans 8.2
Java jdk 1.8 64bits
```
---------------------------------------------
Building demo 1.4.3
------------------------------------------------------------------------

**--- exec-maven-plugin:1.2.1:exec (default-cli) @ demo ---
Exception in thread "main" java.lang.RuntimeException: OpenCV(3.4.3) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.3\modules\core\src\lda.cpp:1075: error: (-5:Bad argument) At least two classes are needed to perform a LDA. Reason: Only one class was given! in function 'cv::LDA::lda'**

	at org.bytedeco.javacpp.opencv_face$FaceRecognizer.train(Native Method)
	at org.bytedeco.javacv.demo.OpenCVFaceRecognizer.main(OpenCVFaceRecognizer.java:88)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.451s
Finished at: Thu Dec 20 17:12:07 GMT-03:00 2018
Final Memory: 7M/220M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project demo: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
"cmd" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
```

**Comment by saudet** [comment]
You'll need to train the classifier first. Here's a good tutorial for that:
https://docs.opencv.org/4.0.0/da/d60/tutorial_face_main.html
