### ISSUE TITLE
Getting issue while converting buffered Image to IplImage

### ISSUE THREAD

**Issue by kundanSingh11** [bytedeco/javacv#1128]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.Pointer.allocate(Ljava/nio/Buffer;)V
	at org.bytedeco.javacpp.Pointer.allocate(Native Method)
	at org.bytedeco.javacpp.Pointer.<init>(Pointer.java:99)
	at org.bytedeco.javacv.OpenCVFrameConverter.convertToIplImage(OpenCVFrameConverter.java:99)
	at org.bytedeco.javacv.Java2DFrameUtils.toIplImage(Java2DFrameUtils.java:72)
	at com.demo.PanCardScannerImpl.getTextFromImage(PanCardScannerImpl.java:40)
	at com.demo.Demo.main(Demo.java:9)

**Comment by kundanSingh11** [comment]
Yes i am using javacv-platform-1.4.4-bin

**Comment by saudet** [comment]
Ok, sounds like you're hitting an edge case. Try to call
Loader.load(opencv_core.class) before.

**Comment by kundanSingh11** [comment]
It worked thanks
