### ISSUE TITLE
EigenFaceRecognizer UnsatisfiedLinkError

### ISSUE THREAD

**Issue by kundanSingh11** [bytedeco/javacv#1130]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.face.EigenFaceRecognizer.create_2()J
	at org.opencv.face.EigenFaceRecognizer.create_2(Native Method)
	at org.opencv.face.EigenFaceRecognizer.create(EigenFaceRecognizer.java:45)
	at com.demo.facial.FacialRecognition.main(FacialRecognition.java:22)

**Comment by saudet** [comment]
You'll need to call `Loader.load(opencv_java.class)` as mentioned here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by kundanSingh11** [comment]
Done thanks
