### ISSUE TITLE
UnsatisfiedLinkError At MAT

### ISSUE THREAD

**Issue by kundanSingh11** [bytedeco/javacv#1135]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_cols(J)I
	at org.opencv.core.Mat.n_cols(Native Method)
	at org.opencv.core.Mat.cols(Mat.java:284)
	at org.opencv.core.Mat.width(Mat.java:1144)
	at com.idmpan.demo.BGRemoval.removeBackground(BGRemoval.java:44)
	at com.idmpan.demo.BGRemoval.main(BGRemoval.java:36)

**Comment by saudet** [comment]
You'll just need to call `Loader.load(opencv_java.class)` as mentioned here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation
