### ISSUE TITLE
Q:how to parse full path[windows] avfilter_graph_parse_ptr() error -2

### ISSUE THREAD

**Issue by mylove984** [bytedeco/javacv#1138]
code like that:
```java
String watermark = "movie=f:/test/timg.jpg[watermark];[in][watermark]overlay=W-w-15:15:format=rgb[out]";
            
            frameFilter = new FFmpegFrameFilter(watermark, width, height);
            frameFilter.setPixelFormat(avutil.AV_PIX_FMT_BGR24);
            
            frameFilter.start();
```

Error info:
```
2019-02-12 17:12:48.744 ssp [http-nio-8881-exec-4][96ab6ceeba9d287c] ERROR c.h.a.b.m.media.av.AVLogCallback - [Parsed_movie_0 @ 0000000041906180] Failed to avformat_open_input 'f'

2019-02-12 17:12:48.744 ssp [http-nio-8881-exec-4][96ab6ceeba9d287c] ERROR c.h.a.b.m.media.av.AVLogCallback - Error initializing filter 'movie'
2019-02-12 17:12:48.744 ssp [http-nio-8881-exec-4][96ab6ceeba9d287c] ERROR c.h.a.b.m.media.av.AVLogCallback -  with args 'f:/test/timg.jpg'
2019-02-12 17:12:48.744 ssp [http-nio-8881-exec-4][96ab6ceeba9d287c] ERROR c.h.a.b.m.media.av.AVLogCallback - 

org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_parse_ptr() error -2
	at org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe(FFmpegFrameFilter.java:341)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:256)
```

**Comment by saudet** [comment]
You'll need to use 2 backslashes after 'f', but before the ':', something like this:
`movie=f\\:/test/timg.jpg...`
See: https://trac.ffmpeg.org/ticket/2166
