### ISSUE TITLE
Converting Image JavaCV UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sphillips9** [bytedeco/javacv#1141]
This is the same stacktrace as #1128, I'm using 1.4.4 already.

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.Pointer.allocate(Ljava/nio/Buffer;)V
	at org.bytedeco.javacpp.Pointer.allocate(Native Method)
	at org.bytedeco.javacpp.Pointer.<init>(Pointer.java:99)
	at org.bytedeco.javacv.OpenCVFrameConverter.convertToIplImage(OpenCVFrameConverter.java:99)
	at org.bytedeco.javacv.OpenCVFrameConverter$ToIplImage.convert(OpenCVFrameConverter.java:47)
	at testing.IntegrationTest.main(IntegrationTest.java:22)

I am attaching my Pom.xml, and my example code that cause this problem, most of the openCV functions seem to work, but this one is the only problem file.

Pom.xml Relevant Sections:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

<dependency>
		    <groupId>org.bytedeco</groupId>
		    <artifactId>javacpp</artifactId>
		    <version>1.4.4</version>
		</dependency>
	  	<dependency>
    		<groupId>org.bytedeco</groupId>
    		<artifactId>javacv-platform</artifactId>
    		<version>1.4.4</version>
  		</dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.0.1-1.4.4</version>
        </dependency>
....

Java code that replicates the error:

public class IntegrationTest {

	// Test to make sure all of the libraries for OpenCV are loaded properly.
	public static void main(String[] args) throws AWTException {
		Rectangle screenRect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
		BufferedImage capture = new Robot().createScreenCapture(screenRect);
		ToIplImage iplConverter = new OpenCVFrameConverter.ToIplImage();
		Java2DFrameConverter java2dConverter = new Java2DFrameConverter();
		
		iplConverter.convert(java2dConverter.convert(capture));
	}
}

Thanks in Advance,
Sean

**Comment by sphillips9** [comment]
After cleaning my project and running another Maven Install, and then adding Loader.load(opencv_core.class) before I called any OpenCV functions, it began working.  This was the workaround suggested by saudet  suggested in #1128 ticket, but was not running properly until i deleted my maven repo, and restart my machine ran another mvn clean install.

**Comment by sphillips9** [comment]
The amount of JARs loaded with my current Mvn setup are un-acceptable for our build, how would I limit it to just be windows 64bit machines, in my pom.xml?

**Comment by sphillips9** [comment]
It apears I just pushed this problem deeper into a different openCV function by loading opencv_core.class manually, as I am now getting:

OpenCV(4.0.1) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.0.1\modules\core\src\array.cpp:1246: error: (-5:Bad argument) Array should be CvMat or IplImage in function 'cvGetSize'

I did not encounter this issue when I was running with JARs:
(I have no idea what versions they were, it all was given to me before version control was implemented...., I guess they just downloaded the JARs manually and added to eclipse)
javacpp.jar
javacv.jar
opencv-macosx-x86_64.jar
opencv-windows-x86.jar
opencv-windowsx86_64.jar
opencv.jar

Now that our project is fully setup in Maven, I am running into this issue with my attached pom.xml in the initial post.

**Comment by saudet** [comment]
As mentioned in the README.md file, try to run Maven with
`-Djavacpp.platform=windows-x86_64`.

**Comment by sphillips9** [comment]
I didn't see any examples in the README.md file to tell me how to integrate it into the pom.xml file.  The snapshots pom.xml doesn't have an example of that there either.

Trying to build it manually with this command gives me an error:

PS C:\Users\Sean\Documents\chipalignmentprocessing> mvn clean install -Djavacpp.platform=windows-x86_64
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.nanocellect:chipalignmentprocessing:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 79, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building chipalignmentprocessing 1.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.075 s
[INFO] Finished at: 2019-02-19T15:15:45-08:00
[INFO] Final Memory: 6M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase ".platform=windows-x86_64". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

**Comment by saudet** [comment]
That might not work as it from PowerShell. Make sure to escape everything properly,
or use the Command Prompt instead.

Sure, there are no complete examples with all and possible instructions and pitfalls.
Someone could create a Wiki page for that :)
https://github.com/bytedeco/javacv/wiki
https://github.com/bytedeco/javacpp-presets/wiki

**Comment by sphillips9** [comment]
Ah that was the problem with running the command was powershell.  I ran it in cmd prompt and it downloaded all the appropriate windows only jar's, thanks for that.

Still running into the error in my  4th post, I'm positive this isn't a bug in javaCV or my code, and think it is a configuration error on my end because I moved from an eclipse project to a maven project.  And there has been no code changed on the branch except the .JAR files and the pom.xml file creation.  I don't know if the error above gives an indication as to what is wrong with my setup, because I can't seem to configure my pom.xml to give me the JARs in the manner I listed above.  I know this because I run both sets of code, and the prior Eclipse Project version runs correctly with the same input, while my new version crashes.

**Comment by saudet** [comment]
Your Robot code above works fine for me. Could you also provide the pom.xml file you are using?

**Comment by sphillips9** [comment]
My first post has the pom.xml I am using attached(had to put it as a txt instead of an xml).  And I was running into issues with the code I posted above, until I did "Loader.load(opencv_core.class)".

I'll get back to you later tomorrow with my code that is not working that is throwing the exception I listed in my 4th post, because my original post code is working fine.

I don't know if you would like me to create a different ticket for  that issue as the first issue I posted this for was resolved.

**Comment by saudet** [comment]
No, just keep posting here, thanks!

**Comment by sphillips9** [comment]
Thanks for helping me with this saudet.

Here is the code I have that reproduces this issue:
Exception in thread "main" java.lang.RuntimeException: OpenCV(4.0.1) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.0.1\modules\core\src\array.cpp:1246: error: (-5:Bad argument) Array should be CvMat or IplImage in function 'cvGetSize'

```
	public static void main(String[] args) throws AWTException {
		Loader.load(opencv_core.class);
		Rectangle screenRect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
		BufferedImage capture = new Robot().createScreenCapture(screenRect);
		ToIplImage iplConverter = new OpenCVFrameConverter.ToIplImage();
		Java2DFrameConverter java2dConverter = new Java2DFrameConverter();
		IplImage src = iplConverter.convert(java2dConverter.convert(capture));
		
		cvCreateImage(cvGetSize(src), IPL_DEPTH_8U, 1);
	}
```
Like I mentioned before I believe this is a configuration issue because when my project is an eclipse project, I don't have issues but once I started building it with Maven, I started running into issues, and can't find what configuration works.  Maven Script is same as attached before.

Best Regards,

Sean

**Comment by saudet** [comment]
I see, this seems to happen only on Windows, so I guess this is a caused by a bug in MSVC's compiler. `cvSize(src.width(), src.height())` works fine on Windows too, so I would just use that, but if `cvGetSize()` is really important to you, please file a bug upstream! Thanks

**Comment by sphillips9** [comment]
But how would this explain that on Windows 10 64bit, I can run it correctly through an eclipse project build, but the Maven build fails.  It is a configuration issue with my pom.xml, not a machine settings problem, or do i need to specify a different compiler for my maven build?

**Comment by sphillips9** [comment]
Well I modified these functions to what you have, and they work fine for my algorithm they are essentially the same thing, one just delegates the responsibility of calculating the image dimensions to the other.

I don't fully understand this issue as my post above suggests.

Please feel free to close this ticket or leave it open as a bug, as I don't have anymore issues with the new function.
