### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed

### ISSUE THREAD

**Issue by vah13** [bytedeco/javacv#120]
Hi i have this issue 

  Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.octoplus.google.camera-1/libavcodec.so" has unexpected e_machine: 40
            at java.lang.Runtime.loadLibrary(Runtime.java:361)
            at java.lang.System.loadLibrary(System.java:525)
            at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
            at org.bytedeco.javacpp.Loader.load(Loader.java:401)
            at org.bytedeco.javacpp.Loader.load(Loader.java:353)
            at org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:12)
            at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:103)
   
how I can fix it?

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile group: 'org.bytedeco', name: 'javacv', version: '0.9'
    compile group: 'org.bytedeco', name: 'javacpp', version: '0.9'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.9-0.9', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.3-0.9', classifier: 'android-arm'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.google.android.gms:play-services:6.5.87'
}

**Comment by saudet** [comment]
It sounds like your device needs the libs for x86. Something like this should work:
```gradle
compile group: 'org.bytedeco', name: 'javacv', version: '0.11'
compile group: 'org.bytedeco', name: 'javacpp', version: '0.11'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.11-0.11', classifier: 'android-x86'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.6.1-0.11', classifier: 'android-x86'
```
