### ISSUE TITLE
Multi-input FFmpegFraneFilter initialization error：avfilter_graph_config() error -22

### ISSUE THREAD

**Issue by ArrowWZC** [bytedeco/javacv#1214]
I wanted to mix two audios into a single one,  I used the FFmpegFrameFilter to do this.

here's my code:

>   val filterStr = "amix=inputs=2"
      val filter = new FFmpegFrameFilter(filterStr, 2)
      filter.start()

when start() executed,  an exception occurred:

>   org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_config() error -22
	at org.bytedeco.javacv.FFmpegFrameFilter.startAudioUnsafe(FFmpegFrameFilter.java:464)
	at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:271)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:251)

But when I change the **filterStr** to "amix=inputs=1",  the input becomes a single one, the exception won't occur.

I tried some other filter strings,  and I found single input works well, but when it comes to multiple input situations,  the filter can't start successfully, and this exception occurs.

 Any Initialization steps I missed when I tried to use the multi-input filter? 
Or the "amix" filter cannot be used yet?

**Comment by ArrowWZC** [comment]
I find an old issue entails this mixing situation, and I  use the code for reference. I know what step I missed.

The fixed code is:
```
val filterStr = "[0:a][1:a]amix=inputs=2[a]"
val filter = new FFmpegFrameFilter(filterStr, 2)
filter.setAudioInputs(2)
filter.start() 
```
I added a set step,  and modified the filter string, finally it worked.

**Comment by ArrowWZC** [comment]
But I still wanna know if there is a reference for filter string composing cause it's different from the original command line I find in the ffmpeg document.

**Comment by saudet** [comment]
Where did you see that example in FFmpeg's documentation?

**Comment by ArrowWZC** [comment]
> Where did you see that example in FFmpeg's documentation?

I saw the amix example in this page: [FFmpegDoc](https://ffmpeg.org/ffmpeg-filters.html#Audio-Filters)

Then I used the command line to mix two audios and it did work, but I need to modify the filter string so that I can make it work in FFmpegFrameFilter.  

The modification I made referred to this issue page: [carsh when recoder output hls](https://github.com/bytedeco/javacv/issues/1082). 

I wonder how can I compose other filter string when I use FFmpegFrameFilter since I can't find any reference  code.

**Comment by saudet** [comment]
I see, thanks! The only issue with these "complex filter" and `FFmpegFrameFilter` is how the input and output pads are named (which has nothing to do with any of the rest of the filter graph). There is no documentation that I could find about that, so I'm just using what shows up most often in these examples. Obviously, it would be great if someone could find out how the `ffmpeg` program names those pads...

**Comment by ArrowWZC** [comment]
I see, thank you so much!
