### ISSUE TITLE
Streaming of video+audio doesn't work (video alone works)

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1219]
I tried to make streaming with `FFmpegFrameRecorder` to work, but for some reason couldn't get it working for video and audio stream (streaming video alone worked fine).

I set the recorder up like so:

```java
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("tcp://127.0.0.1:23000", grabber.getImageWidth(), grabber.getImageHeight());
recorder.setFrameRate(grabber.getFrameRate());
recorder.setVideoBitrate(grabber.getVideoBitrate());
recorder.setOption("listen", "1");
recorder.setFormat("h264");

AVCodec enc = avcodec.avcodec_find_encoder_by_name("h264_videotoolbox");

IntPointer formats = enc.pix_fmts();

int selectedFormat;

int i = 0;
while (true) {
    int format = formats.get(i++);

    // always prefer yuv420p, if available
    if(format == AV_PIX_FMT_YUV420P) {
        selectedFormat = AV_PIX_FMT_YUV420P;
        break;
    }
    if(format ==  AV_PIX_FMT_NONE) {
        selectedFormat = avcodec.avcodec_find_best_pix_fmt_of_list(formats, PIXEL_FORMAT, 0, null);
        break;
    }
}

recorder.setPixelFormat(selectedFormat);
recorder.setVideoCodecName("h264_videotoolbox");
```

and this worked when recording video frames only.

I tired adding audio by changing how recorded is set up like this:

```java
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("tcp://127.0.0.1:23000", grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
recorder.setAudioBitrate(grabber.getAudioBitrate());
recorder.setSampleRate(grabber.getSampleRate());
```

and I got this:
```
Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: avcodec_find_encoder() error: Audio codec not found.
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:620)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:387)
```

I also tried setting audio codec manually like so:
```java
recorder.setAudioCodecName("ac3");
```

and got this strange crash:
```
Output #0, h264, to 'udp://127.0.0.1:23000':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 1920x1080, q=2-31, 12393 kb/s, 29.73 fps, 29.73 tbn, 29.73 tbc
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
[h264_videotoolbox @ 0x7f928d169e00] Color range not set for yuv420p. Using MPEG range.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012b18c726, pid=12560, tid=0x0000000000002403
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libavformat.58.dylib+0xc4726]  av_write_frame+0x946
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/booster/Documents/Java/JavaCV-cli/hs_err_pid12560.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Am I missing something here?

**Comment by saudet** [comment]
It's possible that the AC3 codec doesn't support the tcp and udp formats.
Try another one.

**Comment by b005t3r** [comment]
I tried all audio encoders and different streaming protocols (tcp, udp, rtp), nothing worked, everything resulted in the same crash as the one I posted above. It crashes somewhere in the ffmpeg itself, so maybe it's because how you built this lib? Maybe support for this sort of things is not enabled in the current build?

**Comment by saudet** [comment]
Maybe, give it a try with the ffmpeg program and let's see if that works
better.

**Comment by b005t3r** [comment]
OK, solved it. Looks like audio stream is not supported if output format is set to `h264`. When set to `avi` or `mpegts` audio codecs are selected automatically and everything works as expected.
