### ISSUE TITLE
Missing JavaCameraView library?

### ISSUE THREAD

**Issue by arthad1995** [bytedeco/javacv#1229]
I am working on RTSP client now, I got the frame from my RTSP server, but have no idea how to display it in Android. My idea is to use JavaCameraView and replace the origin data with my processed frame, but I didn't find JavaCameraView in my package(maybe because installation missed that part?), and I tried to use ImageView and doesn't work too.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.rtsp, PID: 3254
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.rtsp/com.example.rtsp.MainActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class org.opencv.android.JavaCameraView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)`

Is there any suggestion for display frames to screen in Android?

**Comment by saudet** [comment]
JavaCameraView requires the Android SDK to compile, which is annoying to say the least, but not undoable. If you would like to make a contribution in that sense, it would be most welcome!

If the only thing you need is to display images though, copy this code into your own projects and adjust accordingly: https://github.com/bytedeco/javacv/blob/master/samples/FacePreview.java

**Comment by arthad1995** [comment]
@saudet Ummm, is that possible to replace the camera video source with my RTSP source? My original thought was in onPreviewFrame method draw do the rtsp and cover all screen, and this seems doesn't work

**Comment by saudet** [comment]
Sure, there is an example of that here: https://github.com/bytedeco/sample-projects/blob/master/javacv-android-video-extract/app/src/main/java/com/baidu/vis/javacv_android_video_grabber/MainActivity.java

**Comment by arthad1995** [comment]
@saudet  Thanks for this link, I am running to issue the video is blur. [I](https://photos.app.goo.gl/CePXpC7MNSVHKSTB6) thought that's because the bitmap is too large and (720P) setBitmap is not efficient enough to render it. I tried to resize it before it render to screen, but also experience issue. I doubt that is decodec issue, I tried to setVideoCodec before grabber start, and doesn't work, any suggestions? (By the way, is that possible to use decoder from hardware?)  Thanks

**Comment by saudet** [comment]
It just looks like your video stream is corrupted. As for hardware acceleration, `FFmpegFrameGrabber.setVideoCodecName("h264_mediacodec")` should work on Android.

**Comment by arthad1995** [comment]
@saudet I think video source is good, I opened VLC in my computer, and it's normal. I was using 1.3 or something and doesn't have setVideoCodecName method, so I upgrade it to 1.5.1 (just simply changed version number on app.gradle) and I got this error:

> E/d_video_grabbe: No implementation found for long org.bytedeco.ffmpeg.global.avutil.AV_NOPTS_VALUE() (tried Java_org_bytedeco_ffmpeg_global_avutil_AV_1NOPTS_1VALUE and Java_org_bytedeco_ffmpeg_global_avutil_AV_1NOPTS_1VALUE__)
I/d_video_grabbe: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.ffmpeg.global.avutil>: java.lang.UnsatisfiedLinkError: No implementation found for long org.bytedeco.ffmpeg.global.avutil.AV_NOPTS_VALUE() (tried Java_org_bytedeco_ffmpeg_global_avutil_AV_1NOPTS_1VALUE and Java_org_bytedeco_ffmpeg_global_avutil_AV_1NOPTS_1VALUE__)
        at long org.bytedeco.ffmpeg.global.avutil.AV_NOPTS_VALUE() (avutil.java:-2)
        at void org.bytedeco.ffmpeg.global.avutil.<clinit>() (avutil.java:268)
        at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/d_video_grabbe:     at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class, java.util.Properties, boolean) (Loader.java:1103)
        at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class) (Loader.java:1052)
        at void org.bytedeco.javacv.FFmpegFrameGrabber.tryLoad() (FFmpegFrameGrabber.java:104)
        at void org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>() (FFmpegFrameGrabber.java:130)
        at void com.baidu.vis.javacv_android_video_grabber.MainActivity.doConvert(java.lang.String) (MainActivity.java:102)
        at void com.baidu.vis.javacv_android_video_grabber.MainActivity.access$000(com.baidu.vis.javacv_android_video_grabber.MainActivity, java.lang.String) (MainActivity.java:27)
        at void com.baidu.vis.javacv_android_video_grabber.MainActivity$1.run() (MainActivity.java:66)
        at void java.lang.Thread.run() (Thread.java:764)
E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.baidu.vis.javacv_android_video_grabber, PID: 20392
    java.lang.NoClassDefFoundError: org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1103)

**Comment by saudet** [comment]
That means you have some old dependency somewhere. We need to upgrade all dependencies as well.
