### ISSUE TITLE
[question][help needed] NoClassDefFoundError on all javacv methods

### ISSUE THREAD

**Issue by denismakogon** [bytedeco/javacv#1254]
Hi, again.
First of all, I'm kinda new to all of this, so, I definitely might be missing something. That's probably the reason for posting my question here.
So, I have a pretty simple app: https://github.com/denismakogon/gif-tracker
It attempts to split up GIF, do some facial recognition and build a final GIF back.
However, I'm facing problems with running this code, seeing the following problem:
```java
java -cp target/gif-processor-1.0-SNAPSHOT.jar com.giphy.app.App giphy.gif 
Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/opencv/global/opencv_imgcodecs
        at com.giphy.app.GifSequenceParser.parseToFrames(GifSequenceParser.java:43)
        at com.giphy.app.App.main(App.java:22)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.opencv.global.opencv_imgcodecs
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more

```
You might like to know which version of OpenCV I have: 4.1.0 with contrib installed.

**Comment by saudet** [comment]
That just means some JAR files are missing. Add all of them to the class
path.

**Comment by saudet** [comment]
We can also solve that by creating an "uber JAR". Instructions for Maven are here:
https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html

**Comment by denismakogon** [comment]
Thanks. It helped.
