### ISSUE TITLE
ffmpeg audio out of sync and error at end of run

### ISSUE THREAD

**Issue by johnestep** [bytedeco/javacv#128]
I have an issue where the audio gets out of sync with the video farther into the video. I have tried many different things to try and fix it and I am at a loss. Anyone that can help I would appreciate it

JAVA-
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

FFMPEG-
ffmpeg version 2.4.1 Copyright (c) 2000-2014 the FFmpeg developers
built on Sep 23 2014 08:09:44 with llvm-gcc 4.2.1 (LLVM build 2336.11.00)

Here is the error I get at the end of the process:
[h264 @ 0x7ff6c4236000] error while decoding MB 25 31, bytestream -18
[h264 @ 0x7ff6c4236000] Cannot use next picture in error concealment
[h264 @ 0x7ff6c4236000] concealing 1144 DC, 1144 AC, 1144 MV errors in P frame

Here is the code use:
As you can see I have tried many different things, moved things around, played with diff settings, etc.

The command line ffmpeg example is:
command line  uses the following switches without any issue at all.

                     "-i", url,
                     "-bsf:a", "aac_adtstoasc",
                     "-vcodec", "copy",
                     "-c", "copy",
                     
HLS is the HTTP Address
________________________________________________________________________________
                 FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(HLS);
                    grabber.start();

                    //grabber.setTimestamp((1 * 60 + 30) * 1000000);
                    FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(output, grabber.getAudioChannels());
                    recorder.setFrameRate(grabber.getFrameRate());

                    recorder.setFormat("mp4");

                    recorder.setImageHeight(grabber.getImageHeight());
                    recorder.setImageWidth(grabber.getImageWidth());

                    recorder.setSampleRate(grabber.getSampleRate());
                    recorder.setVideoBitrate(grabber.getVideoBitrate());
                    //recorder.setInterleaved(false);
                    recorder.setVideoCodec(AV_CODEC_ID_H264);
                    //recorder.setVideoCodecName("x264");

                    recorder.setAudioCodec(grabber.getAudioCodec());
                    recorder.setAudioBitrate(grabber.getAudioBitrate());
                    recorder.setAudioChannels(grabber.getAudioChannels());

                    /*
                     command line        
                     "-i", url,
                     "-bsf:a", "aac_adtstoasc",
                     "-vcodec", "copy",
                     "-c", "copy"
                     */
                    // recorder.setAudioOption("async", "50");
                    //av_bitstream_filter_init("aac_adtstoasc");

                    recorder.setVideoOption("preset", "ultrafast");
                    recorder.setVideoOption("c", "copy");

                    recorder.setVideoCodecName("H.264");
                    recorder.setAudioCodecName("copy");
                    recorder.setAudioOption("bsf:a", "aac_adtstoasc");

                    recorder.setAudioOption("desync", "10");
                    //recorder.setVideoOption("skip_frame", "nokey");
                    //recorder.setVideoOption("qpmax", "51");
                    //recorder.setVideoOption("qpmin", "10");
                    recorder.setVideoOption("audio-sync", "");
                    //recorder.setVideoOption("bframes", "16");
                    //recorder.setVideoOption("keyint_min", "25");
                    //recorder.setVideoOption("keyint", "25");

                    //-skip_frame -nokey 
                    // org.bytedeco.javacpp.avformat.
                    //recorder.setAudioQuality();
                    // recorder.setInterleaved(false);
                    //recorder.setAudioCodec(org.bytedeco.javacpp.avcodec.AV_CODEC_ID_AAC  );//aac_adtstoasc
                    //   recorder.setPixelFormat(avutil.);
                  recorder.setVideoOption("threads", "1");
                    recorder.start();
                    recorder.setPixelFormat(grabber.getPixelFormat());

                    recorder.setTimestamp(grabber.getTimestamp());
                  
                    
                    Frame frame;
                    int allFrames = grabber.getLengthInFrames();

                    float percentage = 0;
                    float lastpercentage = 1;
                    System.out.println("Total frames to process " + grabber.getLengthInFrames());
                    //recorder.setFrameRate();
                    System.out.println("Start Frame = " + grabber.getFrameNumber());
                    while ((frame = grabber.grab()) != null) {
                        recorder.record(frame);
                        // Testing
                        recorder.setSampleRate(grabber.getSampleRate());
                        recorder.setVideoBitrate(grabber.getVideoBitrate());
                        recorder.setAudioBitrate(grabber.getAudioBitrate());
                        recorder.setAudioChannels(grabber.getAudioChannels());
                        recorder.setFrameRate(grabber.getFrameRate());
                        // End Testing

                        percentage = ((float) grabber.getFrameNumber() * 100) / allFrames;
                        if (!String.format("%.0f%%", percentage).equals(String.format("%.0f%%", lastpercentage))) {
                            System.out.println("Percentage Complete " + String.format("%.0f%%", percentage) + "\r");
                            lastpercentage = percentage;
                           }
                      
                        
                    }

                    recorder.stop();
                    recorder.release();
                    grabber.stop();
                    grabber.release();

**Comment by johnestep** [comment]
And latest version of javacv and ffmpeg jars

**Comment by johnestep** [comment]
So I was watching the video to see exactly where it goes out of sync and I see that there is some video pixelation right before the out of sync issue. Is there anyway to capture this and sync back up the video to audio???

**Comment by saudet** [comment]
I don't know, but we're going to need to at least add `av_bitstream_filter_init("aac_adtstoasc")` somewhere in `FFmpegFrameRecorder` to have any hope of getting similar results to the `ffmpeg` command...

**Comment by johnestep** [comment]
Yea, I am using that

It just seems that one particular video I found has a slight issue at a
particular place and that is where it the sync gets off.

:(

**Comment by saudet** [comment]
I guess ffmpeg would try to resync things. I suppose we accomplish that by calling `setTimestamp()` if the images are late, or by padding with empty audio frames, if the audio is late...

**Comment by johnestep** [comment]
The audio is actually early because I think some video frames got dropped, but I can't figure out how to tell, but I am currently going to download all the .ts files and see if that makes a difference. It may be a streaming issue. I will let you know how that goes.

**Comment by saudet** [comment]
What happens if we move `recorder.setTimestamp(grabber.getTimestamp());` inside the loop?

**Comment by johnestep** [comment]
Before or after the recorder.record?

**Comment by johnestep** [comment]
Before the record

[libx264 @ 0x7f99e38f4000] non-strictly-monotonic PTS
[mp4 @ 0x7f99e3bdd600] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 101107006 >= 101107006
Apr 17, 2015 8:59:19 PM tabloexport.MainController$4 call
SEVERE: null
org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:744)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:634)
	at tabloexport.MainController$4.call(MainController.java:636)
	at tabloexport.MainController$4.call(MainController.java:496)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)


After it:

[libx264 @ 0x7f8dcea45000] non-strictly-monotonic PTS
[libx264 @ 0x7f8dcea45000] non-strictly-monotonic PTS
[libx264 @ 0x7f8dcea45000] non-strictly-monotonic PTS
[mp4 @ 0x7f8dd2816c00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 17017 >= 16016
Apr 17, 2015 9:16:23 PM tabloexport.MainController$4 call
SEVERE: null
org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:744)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:634)
	at tabloexport.MainController$4.call(MainController.java:634)
	at tabloexport.MainController$4.call(MainController.java:496)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

[libx264 @ 0x7f8dcea45000] frame I:1     Avg QP:16.17  size: 41804
[libx264 @ 0x7f8dcea45000] frame P:1     Avg QP:21.88  size:  1533
[libx264 @ 0x7f8dcea45000] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x7f8dcea45000] mb P  I16..4:  2.5%  0.0%  0.0%  P16..4: 19.0%  0.0%  0.0%  0.0%  0.0%    skip:78.5%
[libx264 @ 0x7f8dcea45000] coded y,uvDC,uvAC intra: 67.3% 90.9% 41.4% inter: 0.9% 12.5% 0.0%
[libx264 @ 0x7f8dcea45000] i16 v,h,dc,p: 22% 24% 12% 41%
[libx264 @ 0x7f8dcea45000] i8c dc,h,v,p: 28% 26% 22% 24%
[libx264 @ 0x7f8dcea45000] kb/s:inf
[aac @ 0x7f8dd2a71400] 2 frames left in the queue on closing

**Comment by saudet** [comment]
Well, let's try like this then:
```java
long t = grabber.getTimestamp();
if (t > recorder.getTimestamp()) {
    recorder.setTimestamp(t);
}
```

**Comment by johnestep** [comment]
Well, neither before or after record error, but they also do not fix the issue :(

**Comment by saudet** [comment]
So, there's something else FFmpeg is doing. One way to go about it would be to analyze what happens in `ffmpeg.c`, and then implement something similar in `FFmpegFrameRecorder`...

**Comment by johnestep** [comment]
Is there anything in frame.opaque that can tell me if it is a bad frame??

**Comment by johnestep** [comment]
Hey Samuel, I noticed the following in ffmpeg.c but I am not seeing a corresponding one in ffmpegrecorder... is it just me??

if ((avctx->codec_type == AVMEDIA_TYPE_VIDEO && video_sync_method == VSYNC_DROP) ||
        (avctx->codec_type == AVMEDIA_TYPE_AUDIO && audio_sync_method < 0))
        pkt->pts = pkt->dts = AV_NOPTS_VALUE;

**Comment by saudet** [comment]
According to FFmpeg's documentation, it looks like we can check for corrupted frames this way: `((AVFrame)frame.opaque).flags() & AV_FRAME_FLAG_CORRUPT`.

Sure, `FFmpegFrameRecorder` wasn't based on `ffmpeg.c` because the latter is GPL while the former isn't. In any case, if you don't have time to try out things with `FFmpegFrameRecorder`, and `ffmpeg.c` does everything you need, then you might want to consider using that.

**Comment by johnestep** [comment]
I assume you meant 
                       if (((AVFrame)frame.opaque).flags() != AV_FRAME_FLAG_CORRUPT){
 and not
((AVFrame)frame.opaque).flags() & AV_FRAME_FLAG_CORRUPT
??

Since those are int??

**Comment by johnestep** [comment]
or?
                        if ((((AVFrame)frame.opaque).flags() & AV_FRAME_FLAG_CORRUPT) == 1){

**Comment by saudet** [comment]
Yeah, something like that :)

**Comment by johnestep** [comment]
Yea, I figured. Didn't help or work.

I had to go back to using command line ffmpeg as it works without issue. Makes me sad as I wanted my app to be self contained. But I don't have time to do this right now.

**Comment by aydinkn** [comment]
Can we use extra ffmpeg parameters like -map on FFmpegFrameRecorder? Maybe it works.

**Comment by aydinkn** [comment]
I think, on the RecordActivity example, audio thread faster than main (video) thread. Because video encoding process takes time. For this reason, video coming after audio.

**Comment by aydinkn** [comment]
I can reduce CPU usage on main thread but have still audio comes before video (~500 ms) on some device. There are potential timing issues with audio/video synchronicity across threads. Any ideas about to fix this issue?

**Comment by saudet** [comment]
@aydinkn We don't need an option like `-map`, just send the frames that you get from a stream to whichever other stream you wish. If encoding is too slow, you could try to reduce FPS.

**Comment by Iqra786** [comment]
I am having a same issue. When I set Frame rate 30. my video is faster and sound come late. When I set 24 sound is faster and video is late. Any solution? Regards,

**Comment by saudet** [comment]
@Iqra786 Like I said above, call `setTimestamp()` to indicate the exact time of each video frame.

**Comment by lfdversluis** [comment]
I think @aydinkn is right. The video thread does not (always) have a stable FPS, and can lack behind the audio thread. I sometimes too get a `av_interleaved_write_frame() error -32 while writing interleaved audio frame.` because of this. I was looking for a fix or a way to make them synced, but never found a method possibly because of my lack of knowledge of ffmpeg.

**Comment by saudet** [comment]
Maybe the format you need doesn't support variable frame rates well, in
which case we can just encode duplicate frames.

**Comment by lfdversluis** [comment]
Do you mean create a loop that matches the audio FPS and just use the most recent Frame available"?

**Comment by aydinkn** [comment]
If we can buffer audio samples and then compare timestamps audio and video like this:
```
while(audioRecording) {
  if(recording) {
    long audioTimestamp = recorder.getTimestamp();
    do {
      // Buffer audio samples, do not write samples to recorder
    } while(audioRecording && videoTimestamp < audioTimestamp);
    // Write buffered samples to the recorder. Because audio and video timestamps is too close each other.
  }
}
```
May be works.

**Comment by saudet** [comment]
@lfdversluis Sure, sounds like the first thing I would try.

**Comment by JojoLastiko** [comment]
Hello,

We are having the same issue. After capturing a video for our Android app, the sound is not synced with the video anymore. So far, we haven't found anything that works. Did you manage to crack it?

Thanks for letting me know,

Jojo

**Comment by MhtSuthar** [comment]
I am also facing audio and video sync issue, on slow internet speed. I did  tried @aydinkn suggestion, but still sync issue exists. For five minutes of recording i am getting last ~40 seconds video without audio and audio is playing little faster then original audio. Anyone knows how to deal with it please let us know.  

Thanks.

**Comment by davidarchi** [comment]
any solution for this issue ?

**Comment by saudet** [comment]
FYI, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
