### ISSUE TITLE
Contact two videos when call setTimeStamp, But failed.

### ISSUE THREAD

**Issue by cuikangyuan** [bytedeco/javacv#1292]
Hello, i'm using javacv to concat two videos with different frame rate, so i calculate the video and audio timestamp seperately , then call recorder.setTimeStamp() method to set it, when i process the video frames of the first video clip , it failed in certain frame , the log info shows below:
```
2019-09-04 15:04:02.638 11229-11379/  W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -22 while writing video packet.
2019-09-04 15:04:02.638 11229-11379/  W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1191)
2019-09-04 15:04:02.638 11229-11379/  W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:986)
2019-09-04 15:04:02.638 11229-11379/  W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:876)
2019-09-04 15:04:02.638 11229-11379/  W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:869)

```
i'm using the dependencies below:

```
implementation 'org.bytedeco:javacv:1.4.4'
implementation 'com.getkeepsafe.relinker:relinker:1.2.3'
implementation 'org.bytedeco.javacpp-presets:opencv-platform:4.0.1-1.4.4'
implementation 'org.bytedeco.javacpp-presets:ffmpeg-platform:4.1-1.4.4'
```
and my code like this:

```
        double videoWriteTimeStamp = 0;
        Frame videoLastFrame = null;
        long videoLastFrameReadTimeStamp = 0;

        for (int index = 0; index < fgs.size(); index++) {

            FFmpegFrameGrabberWrapper fFmpegFrameGrabberWrapper = fgs.get(index);

            long videoFrameCount = 1;

            while ((frame = fFmpegFrameGrabberWrapper.videoGrabber.grabFrame(false, true, true, false)) != null) {
                
                if (videoLastFrame == null) {
                    
                    videoWriteTimeStamp = 0;

                } else {

                    videoWriteTimeStamp = videoWriteTimeStamp + (fFmpegFrameGrabberWrapper.videoGrabber.getTimestamp() - videoLastFrameReadTimeStamp);

                }
                
                //throws exception when deal with the certain frame in the first video clip
                recorder.setTimestamp((long) videoWriteTimeStamp);
                recorder.record(frame);

                videoFrameCount += 1;
                videoLastFrame = frame;
                videoLastFrameReadTimeStamp = fFmpegFrameGrabberWrapper.videoGrabber.getTimestamp();


            }
            
            fFmpegFrameGrabberWrapper.videoGrabber.stop();

        }

        recorder.stop();
```
could you please give me a hand, i'd appreciate that.

**Comment by saudet** [comment]
Look at the log that FFmpeg outputs to the console. It should tell you what's wrong.

**Comment by cuikangyuan** [comment]
Well, i'll give it a try

**Comment by cuikangyuan** [comment]
Finally, i find out the reason is that when set timestamp, it should follow the rule "pts >= dts", and i add this logic when i set timestamp, currently the output looks good, i will try the code with different video clip, thanks anyway.
