### ISSUE TITLE
couldn't find "libjniavutil.so"

### ISSUE THREAD

**Issue by gilserrancoli** [bytedeco/javacv#1301]
Dear,

I am using Android Studio 3.1.3, API 28, in Windows 10. 
In Project Structure, app dependencies, I have:
org.bytedeco:javacv:1.5.1
org.bytedeco:ffmpeg:4.1.3-1.5.1
org.bytedeco:opencv:4.1.0-1.5.1
among others.

When running the following line:

`videoGrabber = new FFmpegFrameGrabber(selectedVideoPath);`

I get the error I copy below, which makes me think that the issue is within libjniavutil.so.
By the way, in the jniLibs, I have the libopencv_java4.so within the folders: arm64-v8a, armeabi-v7a, x86 and x86_64. 
In the gradle of the app, I also have:
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a', 'x86_64'
            universalApk true
        }
    }

Could you please help me with this issue? I see other had similar issue, but I could not find a solution for this problem.

Thank you very much.

Best regards,

Gil

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.apptutorialasync, PID: 10362
                  java.lang.IllegalStateException: Could not execute method for android:onClick
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
                      at android.view.View.performClick(View.java:6597)
                      at android.view.View.performClickInternal(View.java:6574)
                      at android.view.View.access$3100(View.java:778)
                      at android.view.View$PerformClick.run(View.java:25885)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Method.invoke(Native Method)
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
                      at android.view.View.performClick(View.java:6597) 
                      at android.view.View.performClickInternal(View.java:6574) 
                      at android.view.View.access$3100(View.java:778) 
                      at android.view.View$PerformClick.run(View.java:25885) 
                      at android.os.Handler.handleCallback(Handler.java:873) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:193) 
                      at android.app.ActivityThread.main(ActivityThread.java:6669) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
                   Caused by: java.lang.NoClassDefFoundError: org.bytedeco.ffmpeg.global.avutil
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:453)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
                      at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:44)
                      at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:340)
                      at com.example.apptutorial.MainActivity.loadVideo(MainActivity.java:151)
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
                      at android.view.View.performClick(View.java:6597) 
                      at android.view.View.performClickInternal(View.java:6574) 
                      at android.view.View.access$3100(View.java:778) 
                      at android.view.View$PerformClick.run(View.java:25885) 
                      at android.os.Handler.handleCallback(Handler.java:873) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:193) 
                      at android.app.ActivityThread.main(ActivityThread.java:6669) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/base.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_resources_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/base.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]] couldn't find "libjniavutil.so"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                      at java.lang.System.loadLibrary(System.java:1669)
                      at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1483)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:1186)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
                      at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:12)
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:453)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:1052)
                      at org.bytedeco.javacv.FFmpegFrameGrabber.tryLoad(FFmpegFrameGrabber.java:104)
                      at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:130)
                      	... 14 more
E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/base.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_resources_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/base.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.apptutorialasync-zcIzA1X0-6Z01uzXWQ4t1A==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]] couldn't find "libavutil.so"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                      at java.lang.System.loadLibrary(System.java:1669)
                      at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1483)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:1137)
                      	... 22 more

**Comment by saudet** [comment]
You'll need to add those binaries, something like this usually:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

**Comment by saudet** [comment]
There is now a plugin for Gradle to exclude by platform names:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin
If you try it out and find anything missing, please let me know!

**Comment by jasonakon** [comment]
Hi, Please refer on this sample gradle file https://github.com/Karthi96/Video-Recorder-with-Frames-Analysis/blob/master/app/build.gradle

Although you might find the version is old but its 100% workable and the key note from the changes is to add these line of codes inside your gradle file under android {} :  

```
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi'
            universalApk false
        }
    }
```
