### ISSUE TITLE
Javacpp 1.5 build failed with Gradle

### ISSUE THREAD

**Issue by onionf91** [bytedeco/javacv#1311]
Following configuration work perfect with Javacpp 1.4.x
```
tasks.compileJava.doLast {
    def projectDir = project.projectDir.absolutePath
    def jsonCppIncludeDir = "$projectDir/../external/modules/jsoncpp/include"
    javaexec {
        main 'org.bytedeco.javacpp.tools.Builder'
        classpath files(configurations.javacpp.asPath)
        args '-cp', tasks.compileJava.destinationDir,
             "-Dplatform.includepath=$projectDir/src/main/cpp:$jsonCppIncludeDir",
             "-Dplatform.root=$System.env.NDK/toolchains/llvm/prebuilt/linux-x86_64",
             '-Dplatform.compiler=bin/clang++',
             "-Dplatform.compiler.default=-O3 -s",
             '-Dplatform.compiler.output=-D__ANDROID_API__=28 -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -target aarch64-linux-android28 -march=armv8-a -Wall -static-libstdc++ -fPIC -shared -Wl,--no-undefined -z text -o\u0020',
             '-Dplatform.link=log',
             "-Dplatform.compiler.srcJsonCpp=${jsonCppSource()}",
             '-Dplatform.library.path=lib/arm64-v8a/'
    }
}
```
But I got build failed exception as below since I upgrade Javacpp version to 1.5.x
```
> Task :library:compileJava FAILED
JavaCPP version 1.5.1
Copyright (C) 2011-2019 Samuel Audet <samuel.audet@gmail.com>
Project site: https://github.com/bytedeco/javacpp

Usage: java -jar javacpp.jar [options] [class or package (suffixed with .* or .**)] [commands]

where options include:

    -classpath <path>      Load user classes from path
    -encoding <name>       Character encoding used for input and output files
    -d <directory>         Output all generated files to directory
    -o <name>              Output everything in a file named after given name
    -clean                 Delete the output directory before generating anything in it
    -nogenerate            Do not try to generate C++ source files, only try to parse header files
    -nocompile             Do not compile or delete the generated C++ source files
    -nodelete              Do not delete generated C++ JNI files after compilation
    -header                Generate header file with declarations of callbacks functions
    -copylibs              Copy to output directory dependent libraries (link and preload)
    -copyresources         Copy to output directory resources listed in properties
    -jarprefix <prefix>    Also create a JAR file named "<prefix>-<platform>.jar"
    -properties <resource> Load all platform properties from resource
    -propertyfile <file>   Load all platform properties from file
    -D<property>=<value>   Set platform property to value
    -Xcompiler <option>    Pass option directly to compiler

and where optional commands include:

    -exec [args...]        After build, call java command on the first class
    -print <property>      Print the given platform property, for example, "platform.includepath", and exit
                           "platform.includepath" has jni.h, jni_md.h, etc, and "platform.linkpath", the jvm library


Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
<-------------> 0% WAITING
> :library:compileJava

FAILURE: Build failed with an exception.
```
Is there any migration guide for Gradle users?

**Comment by saudet** [comment]
Nothing major changed. What's the error message?

**Comment by onionf91** [comment]
The error message that gradle return is non-zero exit.
```
> Process 'command '/home/jason/android-studio/jre/bin/java'' finished with non-zero exit value 2
```
and stacktrace as below
```
xecuteActionsTaskExecuter.java:376)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
        ... 35 more
```

**Comment by saudet** [comment]
It doesn't say much. We'll need more information to debug this.

**Comment by onionf91** [comment]
If I add args' `-print` and `/some/where/` then the task just exit and nothing to do. I guess the process exit by following logic:
```java
//org.bytedeco.javacpp.tools.Builder.java
...
        if (printPath != null) {
            Collection<Class> classes = builder.classScanner.getClasses();
            ClassProperties p = Loader.loadProperties(classes.toArray(new Class[classes.size()]), builder.properties, true);
            builder.includeJavaPaths(p, builder.header);
            for (String s : p.get(printPath)) {
                System.out.println(s);
            }
            System.exit(0);
        } else if (!addedClasses) {
            printHelp();
            System.exit(2);
        }
...
```
If I don't put `-print` and `/some/where` as args, then gradle's javaexec just return exit code 2 and help info from javacpp. That's way can't I collect any further error message...

**Comment by onionf91** [comment]
My Gradle configuration is execute javacpp's builder after compile java task, then specific compiled java classes by `-cp` argument. Its seems like 1.5.x version's builder will just exit with 2 and print help info when `*.java` file dons't present on arg list.

**Comment by saudet** [comment]
I see what's missing. It used to process all classes by default, but this behavior was confusing, so now we need to specify the classes we want to process, just like it is for other tools like `java` or `javac`. If you like the previous default behavior, we should be able to add a `.**` as an additional argument to the command, as given by `javaexec` in your build file, but there is a bug preventing this from working actually. I've fixed it in commit https://github.com/bytedeco/javacpp/commit/bdd18ef30b2a7a0b3fb0ac979b4a2c3c931214d5. Thanks for reporting!

**Comment by onionf91** [comment]
Thanks a lot.

**Comment by saudet** [comment]
Bug fix included in just released JavaCPP 1.5.2! Thanks for reporting.

**Comment by saudet** [comment]
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!

**Comment by onionf91** [comment]
I've tried it. It is pretty good and easy to use. I look forward to seeing it release and publish to maven central. Thanks for your effort and time.
