### ISSUE TITLE
Help needed in using JavaCV for Image comparison(2 images) in MAC OSX 

### ISSUE THREAD

**Issue by johnpatrickdev** [bytedeco/javacv#1363]
Hi,
I am trying to develop a module to compare two images and highlight the differences.
I tried a 2 maven samples to get going.
1. Javacv-master -->I used this maven project in eclipse(MAC OSX) and tried to run TemplateMatching.java , beow is the error i faced
      `Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1615)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1263)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1107)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1174)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1107)
	at org.bytedeco.opencv.global.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:17)
	at TemplateMatching.newStyle(TemplateMatching.java:46)
	at TemplateMatching.main(TemplateMatching.java:37)
Caused by: java.lang.UnsatisfiedLinkError: no openblas_nolapack in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1615)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1211)
	... 9 more`

If you can provide a link to a sample/tutorial on how to set-up JavaCV on Mac OSX,Linux we can quickly start implementing our module.

John

**Comment by saudet** [comment]
Don't use Eclipse IDE. It doesn't support Maven well.

**Comment by saudet** [comment]
If you're having problems with other IDEs (Intellij IDEA, NetBeans, etc) or with Maven itself on the command line though, please let me know! Anything other than M2Eclipse should work fine.
