### ISSUE TITLE
Issues after obfuscation

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1393]
I'm trying to obfuscate my app (built as jar-with-dependencies, so everything is in a single large jar), everything except my classes in excluded from processing, so shouldn't be changed, however when I try to run the app I see an exception like this one:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniAbstractArray in java.library.path: [nativeLib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
	at java.base/java.lang.System.loadLibrary(System.java:1902)
	at org.bytedeco.javacpp.Loader.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Unknown Source)
	at org.bytedeco.opencv.opencv_core.AbstractArray.<clinit>(Unknown Source)
	at com.visualvertigo.Main.a(Unknown Source)
	at com.visualvertigo.Main.main(Unknown Source)
```

For some reason it is no longer able to load some native lib, but it looks like every lib is when it should be, nothing is changed.

**Comment by saudet** [comment]
AFAIK, ProGuard doesn't support JNI.

**Comment by saudet** [comment]
You'll need to make sure to exclude those classes from the ones processed by ProGuard:
https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV
