### ISSUE TITLE
FrameGrabber with inputstream

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1395]
Now in Android 10, we cannot use file path, instead URI only.  so to create a frame grabber, i have to do this:

        inputStream = context.getContentResolver().openInputStream(uri);
        frameGrabber = new FFmpegFrameGrabber(inputStream);
        frameGrabber.start();

I found two issues:
1) sometimes the start() will stuck there.
2) Saw some exceptions:
Non-fatal Exception: org.bytedeco.javacv.FrameGrabber$Exception
avformat_open_input() error -2: Could not open input "java.io.BufferedInputStream@db63d24". (Has setFormat() been called?)

**Comment by saudet** [comment]
Could you also provide any error messages that you get in the log?

FYI, InputStream doesn't support seeking, so it does not work well with all file formats, that's normal. You will need to limit the file formats that you use to the ones that you find work well without seeking.

**Comment by xiaos** [comment]
When call start(), I got a lot of OOM error:


Fatal Exception: java.lang.OutOfMemoryError
Physical memory usage is too high: physicalBytes (1088M) > maxPhysicalBytes (1024M)
org.bytedeco.javacpp.Pointer.deallocator (Pointer.java:585)
org.bytedeco.javacpp.Pointer.init (Pointer.java:125)
org.bytedeco.ffmpeg.avcodec.AVPacket.allocate (AVPacket.java)
org.bytedeco.ffmpeg.avcodec.AVPacket.<init> (AVPacket.java:49)
javacv.FFmpegFrameGrabber.startUnsafe (FFmpegFrameGrabber.java:802)
javacv.FFmpegFrameGrabber.start (FFmpegFrameGrabber.java:793)

I don't understand why OOM happened when call start(), it hasn't started to read frame right.

**Comment by saudet** [comment]
Like I said in issue #1394, please use PointerScope. It will help with this.

**Comment by saudet** [comment]
Also, if your stream is large, make sure to set maximumSize to a small number like 0.

**Comment by xiaos** [comment]
Thanks. 

For the PointerScope, from my understanding, we can use it in loop:

while(true){
 try(scope){
 frame=   frameGrabber.read()
  process(frame)
  frameRecorder.record(frame);
 }
}

So for each iteration, the garbage is collected.   But now start() is the 1st method being called, how to use scope?

**Comment by xiaos** [comment]
btw, this is a wonderful project, i am trying to learn more about it and contribute!  Thanks @saudet

**Comment by saudet** [comment]
Yes, that's the idea with PointerScope, but make sure to set maximumSize to 0 as well.

**Comment by xiaos** [comment]
another question about FrameGrabber.start().

Is this thread safe? When i call start() in multiple threads, I found sometimes the start() will be stuck and never return.

**Comment by saudet** [comment]
Check the log for any error message.

**Comment by saudet** [comment]
If you're not seeing any messages, make sure that `FFmpegLogCallback.set()` has been called.

**Comment by DavidMendelovits** [comment]
Hello!

I'm having an issue with input streams as well. Perhaps this something do with the way I'm getting the content::uri but FrameGrabber refuses to work with most files.
code:
`(PointerScope scope0 = new PointerScope()){
                    FFmpegLogCallback.set();
                    avutil.setLogCallback(FFmpegLogCallback.getInstance());
                    InputStream inputStream = context.getContentResolver().openInputStream(Uri.parse(source)); // source=UriAsString
                    FFmpegFrameGrabber producer = new FFmpegFrameGrabber(inputStream, 0);
                    producer.setPixelFormat(AV_PIX_FMT_YUV420P);
                    producer.setVideoCodec(AV_CODEC_ID_MPEG4);
                    producer.setFormat("mp4");

                    producer.start();
...etc 
}
`
error:
`W/System.err: Error: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x71d86d2400] stream 0, offset 0x28: partial file
    Warning: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x71d86d2400] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1920x1080, 9485 kb/s): unspecified pixel format
    Consider increasing the value for the 'analyzeduration' and 'probesize' options
`

**Comment by saudet** [comment]
> FFmpegFrameGrabber producer = new FFmpegFrameGrabber(inputStream, 0);

You'll need a value larger than 0 here.

**Comment by DavidMendelovits** [comment]
> You'll need a value larger than 0 here.
Thank you! this definitely helps.
> Also, if your stream is large, make sure to set maximumSize to a small number like 0.
> Yes, that's the idea with PointerScope, but make sure to set maximumSize to 0 as well.

I suppose I misunderstood your points here. removing maximum size lets me read the rest of the files but also at a much lower pace (because of the maximumSize is then set to a high number (INT MAX-SIZE - 8). Anything higher than 0, and I believe I have to be fairly specific no?

Moving forward, I'm strongly considering ditching inputstream for a path string. Xiaos's point about android 10 scoped storage disallowing file paths seems to be getting fixed in android 11 per https://medium.com/androiddevelopers/android-11-storage-faq-78cefea52b7c. For now, I know a valid workaround is to requestLegacyStorage permissions in the AndroidManifest.xml file.

For context, I'm building a video editor with FFmpegFrameGrabber as the producer and a GLES3 Env as the consumer for previews. Seeking seems to be a no brainer as part of a video editor. As long as scoped storage in android 11 allows the library to work as is, I think using the file path is a justifiable approach in the long term as well.

I understand you are not so involved in android-os specific problems but do you have any insight so far as the most efficient approach to reading (large) files on android given the new standard of scoped storage?

**Comment by saudet** [comment]
If it allows us to get a valid File object, it sounds like we're all set
indeed!

**Comment by Janix520** [comment]
@saudet Can Android obtain FileDescriptor, and does JavaCV support reading FileDescriptor?

**Comment by saudet** [comment]
@Janix520 It looks like we just need to use `"pipe:" + yourFileDescriptor.detachFd()`  as the filename:
https://stackoverflow.com/questions/43815688/passing-a-native-fd-int-to-ffmpeg-from-openable-uri

**Comment by Janix520** [comment]
> [@Janix520](https://github.com/Janix520) It looks like we just need to use `"pipe:" + yourFileDescriptor.detachFd()` as the filename: https://stackoverflow.com/questions/43815688/passing-a-native-fd-int-to-ffmpeg-from-openable-uri

In my impression, Android is not good at this, at least Pipe doesn't support seek either. 
`
String filePath = "/proc/<processId>/fd/" + fd; 
`
Android can use the path to read directly, but I always feel it's not perfect because some ROMs cannot be read. The new version of Android strictly forbids using the File class for reading, which makes it impossible to read large files like audio and video

**Comment by saudet** [comment]
The pipe protocol doesn't support seeking, but the content protocol seems like it does, so I'd just try to use that as filename:
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/file.c#L681

**Comment by Janix520** [comment]
> The pipe protocol doesn't support seeking, but the content protocol seems like it does, so I'd just try to use that as filename: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/file.c#L681

The content protocol is a protocol specific to Android, and it is said that ffmpeg 7.0 already supports it. If you can support this, that would be great. Looking forward to it.

**Comment by saudet** [comment]
That's a feature of FFmpeg. If it works in FFmpeg, it works in JavaCV. Why do you say that it doesn't work?

**Comment by Janix520** [comment]
> That's a feature of FFmpeg. If it works in FFmpeg, it works in JavaCV. Why do you say that it doesn't work?

I haven't tried the content protocol on Android. I saw someone commenting about it, so I'll give it a try first. If it works, I'll reply.

**Comment by Janix520** [comment]
@saudet 
```
I  content://com.android.externalstorage.documents/document/primary%3APMSLLM%2FMusic%2FInspiration.mp3
W  Error: [android_content @ 0xb4000070b3216530] application context is not set
W  Error: [android_content @ 0xb4000070b3216530] application context is not set
D  Shutting down VM
E  FATAL EXCEPTION: main
Process: com.player.apptemplate, PID: 26718
java.lang.RuntimeException: org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -542398533: Could not open input "content://com.android.externalstorage.documents/document/primary%3APMSLLM%2FMusic%2FInspiration.mp3". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
	at com.player.app.activity.MainActivity.lambda$initListeners$4(MainActivity.java:957)
	at com.player.app.activity.MainActivity$$ExternalSyntheticLambda5.onActivityResult(D8$$SyntheticClass:0)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:147)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.kt:121)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1453)
	at android.app.Activity.performStart(Activity.java:8654)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4837)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3098)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:10022)
	at android.app.ActivityThread.main(ActivityThread.java:10011)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1242)
Caused by: org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -542398533: Could not open input "content://com.android.externalstorage.documents/document/primary%3APMSLLM%2FMusic%2FInspiration.mp3". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:989)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:916)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:911)
	at com.player.app.activity.MainActivity.lambda$initListeners$4(MainActivity.java:955)
	at com.player.app.activity.MainActivity$$ExternalSyntheticLambda5.onActivityResult(D8$$SyntheticClass:0) 
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:147) 
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314) 
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251) 
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287) 
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136) 
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119) 
	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192) 
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.kt:121) 
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1453) 
	at android.app.Activity.performStart(Activity.java:8654) 
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4837) 
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235) 
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215) 
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3098) 
	at android.os.Handler.dispatchMessage(Handler.java:117) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:293) 
	at android.app.ActivityThread.loopProcess(ActivityThread.java:10022) 
	at android.app.ActivityThread.main(ActivityThread.java:10011) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1242) 
2026-02-11 00:13:38.859 26718-26718 System.out              com.player.apptemplate           I  thread =org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -542398533: Could not open input "content://com.android.externalstorage.documents/document/primary%3APMSLLM%2FMusic%2FInspiration.mp3". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
2026-02-11 00:13:38.859 26718-26718 System.out              com.player.apptemplate           I  ex =java.lang.RuntimeException: org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -542398533: Could not open input "content://com.android.externalstorage.documents/document/primary%3APMSLLM%2FMusic%2FInspiration.mp3". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
2026-02-11 00:13:38.863 26718-26869 LifecycleTransaction    com.player.apptemplate           I  activityCallbacks TopResumedActivityChangeItem{onTop=false}
2026-02-11 00:13:38.863 26718-26869 LifecycleTransaction    com.player.apptemplate           I  lifecycleStateRequest PauseActivityItem{finished=true,userLeaving=false,configChanges=0,dontReport=false}
2026-02-11 00:13:38.871 26718-26718 Process                 com.player.apptemplate           I  Sending signal. PID: 26718 SIG: 9
```

It seems not. After reporting these errors, Android may need to pass in Context.

**Comment by saudet** [comment]
It looks like we need to give it the application context before. Something like this should work:
```java
Pointer ctx = org.bytedeco.javacpp.Loader.newGlobalRef(getApplicationContext());
org.bytedeco.ffmpeg.global.avcodec.av_jni_set_android_app_ctx(ctx, null);
```

**Comment by Janix520** [comment]
> It looks like we need to give it the application context before. Something like this should work:
> 
> Pointer ctx = org.bytedeco.javacpp.Loader.newGlobalRef(getApplicationContext());
> org.bytedeco.ffmpeg.global.avcodec.av_jni_set_android_app_ctx(ctx, null);

Thank you for your guidance. This indeed makes it workable. Could you please add the method to javacv when you have time.
