### ISSUE TITLE
avcodec_open2() error -1: Could not open video codec. due to timebase not set

### ISSUE THREAD

**Issue by CrazySean007** [bytedeco/javacv#1414]
I got this error when start() function is running. Don't know how to fix it. Can anyone please give me some points on this?

Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -1: Could not open video codec.
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:726)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:384)
	at FindKeyFrames.getIndexByHistogram(FindKeyFrames.java:95)
	at FindKeyFrames.<init>(FindKeyFrames.java:47)
	at GoFindKeyFrame.main(GoFindKeyFrame.java:11)
[huffyuv @ 00000000219487c0] The encoder timebase is not set.
[huffyuv @ 0000000021947a00] ff_frame_thread_encoder_init failed

**Comment by saudet** [comment]
How are you setting the frame rate?

**Comment by CrazySean007** [comment]
> How are you setting the frame rate?

I have found the error because I did not set the framerate correctly. Thanks for replying.

**Comment by nikunjparadva** [comment]
@CrazySean007 how you can solved this issue.. Please share the snippet
