### ISSUE TITLE
FFmpegFrameGrabber  grabber   long time consuming

### ISSUE THREAD

**Issue by Elven-GitHub** [bytedeco/javacv#1429]
I had a problem making the recording screen.
When I capture the screen and execute  grabber.grab(), it takes me about 80 milliseconds. The capture is 1920 * 1080,  30 frames. The time-consuming code is 

       grabber = new FFmpegFrameGrabber("desktop");
       grabber.setImageWidth(1920);
       grabber.setImageHeight(1080);
       grabber.setFrameRate(30);

       capturedFrame = grabber.grab();   //execute this code takes me about 80 milliseconds

.What's the solution？

**Comment by saudet** [comment]
Use DirectShow instead since it's almost certainly faster than GDI:
https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by Elven-GitHub** [comment]
I refer to the above case, but it doesn't work, so I directly report an error. My computer is windows, and here is my code

          //grabber = new FFmpegFrameGrabber("screen-capture-recorder");
        grabber = new FFmpegFrameGrabber("video=screen-capture-recorder");
        grabber.setFormat("dshow");
        grabber.setImageWidth(1920);
        grabber.setImageHeight(1080);

and  here is exception

     org.bytedeco.javacv.FrameGrabber$Exception: Could not grab: No AVFormatContext. (Has start() been called?)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame(FFmpegFrameGrabber.java:1219)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grab(FFmpegFrameGrabber.java:1206)

**Comment by saudet** [comment]
Look at the console for any error message, and if you don't see anything, make sure that `FFmpegLogCallback.set()` has been called.

**Comment by Elven-GitHub** [comment]
When I use the following code

   grabber = new FFmpegFrameGrabber("video=\"screen-capture-recorder\"");
   grabber.setFormat("dshow");

The resulting information is as follows
   
    Error: [dshow @ 000000002d9be9c0] Could not find video device with name ["screen-capture-recorder"] among source devices of type video.
[libx264 @ 000000002d9c12c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000000002d9c12c0] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
[libx264 @ 000000002d9c12c0] 264 - core 157 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=11 lookahead_threads=11 sliced_threads=1 slices=11 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=6 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=25.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0

but When I use the following code

     grabber = new FFmpegFrameGrabber("screen-capture-recorder"); 
     grabber.setFormat("dshow");

The resulting information is as follows
    Error: [dshow @ 000000002df1cb80] Malformed dshow input string.
[libx264 @ 000000002df1f280] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000000002df1f280] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
[libx264 @ 000000002df1f280] 264 - core 157 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=11 lookahead_threads=11 sliced_threads=1 slices=11 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=6 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=25.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0

**Comment by saudet** [comment]
So check which devices are available and use one of those:
https://trac.ffmpeg.org/wiki/Capture/Desktop#Windows

**Comment by saudet** [comment]
This might help too:
https://github.com/rdp/screen-capture-recorder-to-video-windows-free#trouble-shooting

**Comment by Elven-GitHub** [comment]
When I use ffmpeg directly  all right,

 ffmpeg -f dshow  -i video="screen-capture-recorder"  -r 20 -t 10 screen-capture.mp4

But when I use ffmpeg, it is still the previous error. Is it my parameter setting

**Comment by Elven-GitHub** [comment]
i uesed Screen Capturer Recorder   ,However, the time is not reduced. Use the ffmpeg command directly, 

> `.\ffmpeg  -rtbufsize 1024M -f dshow  -i video="screen-capture-recorder"  -r 30  -t  30`

Actually, it's only about 13 frames

>  frame=  381 fps= 13 q=31.0 Lsize=    7684kB time=00:00:29.96 bitrate=2100.5kbits/s speed=   1x
> video:7678kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.080232%
