### ISSUE TITLE
Failed to load class org.bytedeco.javacv.FFmpegFrameGrabber

### ISSUE THREAD

**Issue by banmajio** [bytedeco/javacv#1431]
hello:
When I deploy the service to a Linux system, the following error occurs:
`
org.bytedeco.javacv.FrameGrabber$Exception: Failed to load class org.bytedeco.javacv.FFmpegFrameGrabber
	at org.bytedeco.javacv.FFmpegFrameGrabber.tryLoad(FFmpegFrameGrabber.java:131)
	at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:139)
	at com.junction.CameraRtmpServerApplication.main(CameraRtmpServerApplication.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.UnsatisfiedLinkError: no jniavdevice in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1631)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1265)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.ffmpeg.global.avdevice.<clinit>(avdevice.java:28)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1176
	at org.bytedeco.javacpp.Loader.load(Loader.java:1125)
	at org.bytedeco.javacv.FFmpegFrameGrabber.tryLoad(FFmpegFrameGrabber.java:125)
	... 10 more
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-4.2.2-1.5.3-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavdevice.so: libxcb.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1088)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1581)
	... 18 more
`

How should I solve this mistake? Thank you!

**Comment by saudet** [comment]
Make sure the JAR files for Linux are in the class path.

**Comment by banmajio** [comment]
thank you!

**Comment by saudet** [comment]
Ah, I'm sorry, it's looking for XCB:
> libxcb.so.1: cannot open shared object 
Run something like dnf/yum/apt-get install libxcb to install it.
