### ISSUE TITLE
avio_open2 error() error -541478725: Could not open 'null'

### ISSUE THREAD

**Issue by ai641843909** [bytedeco/javacv#1452]
Warning: [mpeg @ 000000001cb5b540] Stream #0: not enough frames to estimate rate; consider increasing probesize

Info: [mpeg @ 000000001cb5b540] decoding for stream 0 failed

Info: Input #0, mpeg, from 'java.io.BufferedInputStream@dba6b4d':

Info:   Duration: 
Info: N/A
Info: , start: 
Info: 0.000000
Info: , bitrate: 
Info: 64 kb/s
Info: 

Info:     Stream #0:0
Info: [0x1e0]
Info: : Video: h264 (High), yuvj420p(pc, bt709), 1920x1080
Info: , 
Info: 26 tbr, 
Info: 90k tbn, 
Info: 52 tbc
Info: 

Info:     Stream #0:1
Info: [0x1c0]
Info: : Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
Info: 

前：1920
Error: [rtmp @ 000000001cb61dc0] Cannot read RTMP handshake response

org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -541478725: Could not open 'null'
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:939)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:431)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:426)
	at com.junction.play.RtmpPush.push(RtmpPush.java:155)
	at com.junction.play.RealPlay.play(RealPlay.java:80)
	at com.junction.thread.CameraThread$MyRunnable.run(CameraThread.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17:10:04.212 [pool-1-thread-1] ERROR com.junction.play.RtmpPush - avio_open2 error() error -541478725: Could not open 'null'
17:10:05.388 [pool-1-thread-1] INFO com.junction.play.RtmpPush - hcsdk 推流结束 设备信息：[ip:10.20.72.42 port:8000 channel:1 stream:main starttime:null endtime:null url:rtmp://127.0.0.1:8080/live/7c16bc58-2a53-4dcd-aa78-a0b87fb15032]

this.recorder.start(fc);

An error was reported in this step

**Comment by saudet** [comment]
541478725 is "end of file", so that probably means there is a problem with your stream.

**Comment by ai641843909** [comment]
avformat_open_input() error -2: Could not open input "java.io.BufferedInputStream@7bf8f446". (Has setFormat() been called?)

Changed all kinds of ways, keep reporting this error！！！

**Comment by saudet** [comment]
Make sure you're not setting the maximumSize to a small value like 0. Try to use a large value for maximumSize.
