### ISSUE TITLE
why is there a exception when spring boot javacv program run in centos?

### ISSUE THREAD

**Issue by daxue2017** [bytedeco/javacv#1456]
belows:
project type: **sprint boot**
system:centos **7**
dev tools:  **intelij idea**
javacv version: **1.5.3**
maven config;
		**<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.5.3</version>
		</dependency>**

the program package to a .jar by intelij idea.
when run it in centos, there is following exception:

Exception in thread "Thread-7" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1631)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1265)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1176)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1125)
	at org.bytedeco.javacv.OpenCVFrameConverter.<clinit>(OpenCVFrameConverter.java:43)
	at com.winter.Controller.LiveController$2.run(LiveController.java:384)
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/openblas-0.3.9-1.5.3-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libjniopenblas_nolapack.so: libopenblas_nolapack.so.0: 无法打开共享对象文件: 没有那个文件或目录
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1581)
	... 9 more

**Comment by saudet** [comment]
Fixed in recent versions of Spring Boot, but also JavaCPP 1.5.4-SNAPSHOT,
so please give it a try: http://bytedeco.org/builds/

**Comment by saudet** [comment]
The fix has been released with JavaCV 1.5.4. Enjoy!
