### ISSUE TITLE
Question : running javacv app without display

### ISSUE THREAD

**Issue by arvind-das** [bytedeco/javacv#147]
I want to run the app in background with a computer which has no display device attached . It won't run saying , X11 is needed for FrameGrabber to capture . What can I do ?

Please help

**Comment by saudet** [comment]
No, it should not be needed. What error do you get?

**Comment by arvind-das** [comment]
neuron@neuron-ThinkPad-Edge-E440:~/Desktop$ java -jar record0012.jar >> exception.log &
[1] 22841
neuron@neuron-ThinkPad-Edge-E440:~/Desktop$ HIGHGUI ERROR: V4L: Property <unknown property string>(9) not supported by device
HIGHGUI ERROR: V4L: Property <unknown property string>(9) not supported by device
HIGHGUI ERROR: V4L: Property <unknown property string>(16) not supported by device
Output #0, flv, to '/home/neuron/arvind1.flv':
    Stream #0:0: Video: h264 (libx264), yuv420p, 688x360, q=-1--1, 1000 kb/s, 30 tbn, 30 tbc
    Stream #0:1: Audio: aac, 44100 Hz, stereo, fltp, 128 kb/s
[libx264 @ 0x7ffed6244f40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 0x7ffed6244f40] profile High, level 3.0
[libx264 @ 0x7ffed6244f40] 264 - core 142 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x3 me=dia subme=1 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=1 keyint=60 keyint_min=6 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:77)
	at com.rrdtech.recorder.javacv.CanvasFrame.getDefaultScreenDevice(CanvasFrame.java:115)
	at com.rrdtech.recorder.javacv.CanvasFrame.getDefaultGamma(CanvasFrame.java:89)
	at com.rrdtech.recorder.javacv.CustomFFmpegFileSystemRecorder.startRecord(CustomFFmpegFileSystemRecorder.java:203)
	at com.rrdtech.api.reordingapp.App.main(App.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

**Comment by arvind-das** [comment]
OOps i think preview section is enabled, removing that should fix this, let me check!

**Comment by saudet** [comment]
You're trying to use CanvasFrame and that requires X11.

**Comment by arvind-das** [comment]
Yes My Bad, it just striked my mind right now, removed CanvasFrame and that did it. :dart:
