### ISSUE TITLE
Cloud Deployment error - Could not initialize class org.bytedeco.javacpp.opencv_highgui

### ISSUE THREAD

**Issue by josephincture** [bytedeco/javacv#1490]
I had added 		Loader.load(opencv_java.class); 

to my source code and build the .war file for my web app. But the deployment is throwing the following error while loading the class..

DispatcherServlet:1093 - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_highgui

But the web app works fine when it is run on a local server..

kindly help me resolve the issue ASAP..(Deployment pending..PS)

**Comment by saudet** [comment]
Check the cause of the exception, it will tell you what's going on. It
might also be caused by a previous exception, so check the log for all of
them.

**Comment by josephincture** [comment]
Am I supposed to have all these dependancies...

org.bytedeco.javacpp-presets » opencv

org.bytedeco.javacpp-presets » ffmpeg

org.bytedeco » javacv

org.bytedeco » javacpp

Previously I had only 

<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>opencv-platform</artifactId>
    <version>4.0.1-1.4.4</version>
</dependency>

**Comment by josephincture** [comment]
This is the detailed log....

2020-08-10T03:12:15.681+0000 [APP/PROC/WEB/0] ERR  2020-08-10 03:12:15 DEBUG DispatcherServlet:1093 - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_highgui
2020-08-10T03:12:15.682+0000 [APP/PROC/WEB/0] OUT [CONTAINER] tainerBase.[Catalina].[localhost].[/].[dispatcher] SEVERE  Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_highgui] with root cause
2020-08-10T03:12:15.682+0000 [APP/PROC/WEB/0] OUT java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_highgui
2020-08-10T03:12:15.682+0000 [APP/PROC/WEB/0] OUT 	at java.lang.Class.forName0(Native Method)
2020-08-10T03:12:15.682+0000 [APP/PROC/WEB/0] OUT 	at java.lang.Class.forName(Class.java:348)
2020-08-10T03:12:15.682+0000 [APP/PROC/WEB/0] OUT 	at org.bytedeco.javacpp.Loader.load(Loader.java:1176)
2020-08-10T03:12:15.682+0000 [APP/PROC/WEB/0] OUT 	at org.bytedeco.javacpp.Loader.load(Loader.java:1125)

**Comment by saudet** [comment]
You can still just include opencv-platform, that works.

**Comment by josephincture** [comment]
But Still the deployment is throwing error...

**Comment by saudet** [comment]
You'll need to find where the first exception occurs

**Comment by josephincture** [comment]
This is the log...

DispatcherServlet:1093 - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_highgui
2020-08-10T08:57:56.394+0000 [APP/PROC/WEB/0] OUT [CONTAINER] tainerBase.[Catalina].[localhost].[/].[dispatcher] SEVERE  Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_highgui] with root cause
2020-08-10T08:57:56.394+0000 [APP/PROC/WEB/0] OUT java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_highgui
2020-08-10T08:57:56.394+0000 [APP/PROC/WEB/0] OUT 	at java.lang.Class.forName0(Native Method)
2020-08-10T08:57:56.394+0000 [APP/PROC/WEB/0] OUT 	at java.lang.Class.forName(Class.java:348)
2020-08-10T08:57:56.394+0000 [APP/PROC/WEB/0] OUT 	at org.bytedeco.javacpp.Loader.load(Loader.java:1176)
2020-08-10T08:57:56.394+0000 [APP/PROC/WEB/0] OUT 	at org.bytedeco.javacpp.Loader.load(Loader.java:1125)

**Comment by saudet** [comment]
It fails before that. You'll need to look at that stack trace.

**Comment by saudet** [comment]
BTW, what is usually missing for cloud deployment is an installation of GTK.
See, for example, issues #1415 and https://github.com/bytedeco/javacpp-presets/issues/593.

**Comment by saudet** [comment]
I'm assuming that installing GTK solved this issue, but let me know if it doesn't. Thanks!

**Comment by saudet** [comment]
Duplicate of bytedeco/javacpp-presets#593
