### ISSUE TITLE
FFmpegFrameGrabber stop() method crash JVM when we play HLS stream.

### ISSUE THREAD

**Issue by nilkanth0018** [bytedeco/javacv#1521]
I am playing HLS stream which has link of m3u8 file and I am playing it using FFmpegFrameGrabber but when I stop the player sometimes it crashes the JVM. 

this is the error I am getting when it crashes

```
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: -1073741819 (Exit value: -1073741819)
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Here is my stop method, mGrabber is object of FFmpegFrameGrabber, it crash from "mGrabber.stop();" line.

```
public void stop() {
	mImageBuffer.clear();
	mAudioBuffer.clear();
	mFeederExecutor.shutdown();
	mReaderExecutor.shutdown();
	try {
		mReaderExecutor.awaitTermination(1, TimeUnit.SECONDS);
		mFeederExecutor.awaitTermination(1, TimeUnit.SECONDS);
	} catch (InterruptedException e) {
		throw new MediaException("Reader failed to stopped");
	}
	try {
		mGrabber.stop();
		mGrabber.release();
		mGrabber = null;
	} catch (FrameGrabber.Exception e) {
		throw new MediaException("Cannot stop reader.", e);
	}
	super.stop();
}
```

[hs_err_pid16704.log](https://github.com/bytedeco/javacv/files/5346666/hs_err_pid16704.log)

this is another issue with stop method:
One more thing when internet has gone it stuck on "mGrabber.stop();" line and when internet is start working then it will stop properly, in this case jvm is not crashing.

above both issue occur when we play hls stream otherwise it work perfectly fine when we play local media file.

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.4.

**Comment by saudet** [comment]
Actually, it looks like error 1073741819 is "file system error". That's most likely a problem with your hardware.

**Comment by nilkanth0018** [comment]
@saudet but sometime I got error 1 also, Exit value: 1, what about that?

**Comment by saudet** [comment]
Error 1 is "Incorrect function": https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

Still sounds like a network problem to me. It's not crashing in FFmpeg, so the cause is probably somewhere else in your application.

**Comment by nilkanth0018** [comment]
Ok, thank you for quickly answering my question.

**Comment by nilkanth0018** [comment]
One more thing, why FFmpegFrameGrabber is not stopping when there is no internet? only when we play HLS stream.

**Comment by saudet** [comment]
What do you mean not stopping? Did you set a timeout value?

**Comment by nilkanth0018** [comment]
No, I am not aware of timeout, yes it did solve my issue of stopping after I set timout, thank you 👍
