### ISSUE TITLE
java.lang.OutOfMemoryError: Physical memory usage is too high

### ISSUE THREAD

**Issue by iversonx** [bytedeco/javacv#1531]
After running for a period of time， happen java.lang.OutOfMemoryError: Physical memory usage is too high

Memory 16G

![image](https://user-images.githubusercontent.com/13626107/97098634-fd568a00-16b9-11eb-83c0-098fdd9d2ecf.png)

```java

FFmpegFrameGrabber fFmpegFrameGrabber = new FFmpegFrameGrabber(localFile);
try {
            fFmpegFrameGrabber.start();
            int lengthInFrames = fFmpegFrameGrabber.getLengthInFrames();
            int frameRate = (int)fFmpegFrameGrabber.getFrameRate();

} finally {
            try {
                fFmpegFrameGrabber.close();
            } catch (FrameGrabber.Exception e) {
                e.printStackTrace();
            }
}

```

**Comment by saudet** [comment]
Could you provide a small code snippet and a sample video file to reproduce
this issue?

**Comment by iversonx** [comment]
a large number of small  video files, 
```java
FFmpegFrameGrabber fFmpegFrameGrabber = new FFmpegFrameGrabber(localFile);
try {
            fFmpegFrameGrabber.start();
            int lengthInFrames = fFmpegFrameGrabber.getLengthInFrames();
            int frameRate = (int)fFmpegFrameGrabber.getFrameRate(); 
            File file = new File(pathname);
            ImageIO.write(frameToBufferedImage(frame), "jpeg", file);
} finally {
            try {
                fFmpegFrameGrabber.close();
            } catch (FrameGrabber.Exception e) {
                e.printStackTrace();
            }
}

public static BufferedImage frameToBufferedImage(Frame frame) {
        //创建BufferedImage对象
        Java2DFrameConverter converter = new Java2DFrameConverter();
        return converter.getBufferedImage(frame);
    }

````

**Comment by saudet** [comment]
Try to call System.gc() after each call to frameToBufferedImage().

**Comment by iversonx** [comment]
12487393 [ThreadPoolTaskScheduler-68] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task 
java.lang.OutOfMemoryError: Cannot allocate new PointerPointer(8): totalBytes = 24, physicalBytes = 4099M
        at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:149)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:819)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:801)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:796)
        at com.dataeye.image_analysis.processor.VideoFrameGrabProcessor.process(VideoFrameGrabProcessor.java:119)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob.execute(VideoFrameGrabJob.java:46)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob$$FastClassBySpringCGLIB$$c6ce0814.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at com.dataeye.starter.scheduledjob.ScheduledJobInterceptor.around(ScheduledJobInterceptor.java:83)
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob$$EnhancerBySpringCGLIB$$969e5690.execute(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
      handler_name    : SoundHandler
12487393 [ThreadPoolTaskScheduler-68] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task 
java.lang.OutOfMemoryError: Cannot allocate new PointerPointer(8): totalBytes = 24, physicalBytes = 4099M
        at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:149)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:819)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:801)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:796)
        at com.dataeye.image_analysis.processor.VideoFrameGrabProcessor.process(VideoFrameGrabProcessor.java:119)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob.execute(VideoFrameGrabJob.java:46)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob$$FastClassBySpringCGLIB$$c6ce0814.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at com.dataeye.starter.scheduledjob.ScheduledJobInterceptor.around(ScheduledJobInterceptor.java:83)
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob$$EnhancerBySpringCGLIB$$969e5690.execute(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (4099M) > maxPhysicalBytes (4096M)
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:695)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:127)
        at org.bytedeco.javacpp.PointerPointer.allocateArray(Native Method)
        at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:141)
        ... 38 common frames omitted
12501580 [ThreadPoolTaskScheduler-68] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task 
java.lang.OutOfMemoryError: Cannot allocate new PointerPointer(8): totalBytes = 24, physicalBytes = 4101M
        at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:149)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:819)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:801)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:796)
        at com.dataeye.image_analysis.processor.VideoFrameGrabProcessor.process(VideoFrameGrabProcessor.java:119)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob.execute(VideoFrameGrabJob.java:46)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob$$FastClassBySpringCGLIB$$c6ce0814.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at com.dataeye.starter.scheduledjob.ScheduledJobInterceptor.around(ScheduledJobInterceptor.java:83)
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.dataeye.image_analysis.job.VideoFrameGrabJob$$EnhancerBySpringCGLIB$$969e5690.execute(<generated>)
        at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (4101M) > maxPhysicalBytes (4096M)
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:695)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:127)
        at org.bytedeco.javacpp.PointerPointer.allocateArray(Native Method)
        at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:141)
        ... 37 common frames omitted

**Comment by iversonx** [comment]
I have two machines running. Only one machine can have this problem
I want to kown Is this a problem with Java CV or with my code

**Comment by saudet** [comment]
It's probably the GC not running often enough. Like I said, call
System.gc() on every file and it should work...

**Comment by saudet** [comment]
If your application uses memory-mapped files, you may also need to disable JavaCPP's check by setting the "org.bytedeco.javacpp.maxPhysicalBytes" system property to "0".
