### ISSUE TITLE
how to set up java 4.4.0 and start facerecognizing in java?

### ISSUE THREAD

**Issue by nikkisingh111333** [bytedeco/javacv#1538]
i m stuck badly.i was using opencv 4.2.0 lately but currently struglling with facereognization library .i m unable to setting up bytedeco in my java springboot project. kindly guide me :
heres my dependency SS:
![Screenshot (43)](https://user-images.githubusercontent.com/49682940/99903884-43b8fc00-2ced-11eb-800b-f8a3bb7f87ff.png)

heres my code copied from docs:
`System.out.println(Core.NATIVE_LIBRARY_NAME);
 System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
 File root = new File("C:\\Users\\Nikki singh\\Downloads\\FR");
  FilenameFilter imgFilter = new FilenameFilter() {
                public boolean accept(File dir, String name) {
                        name = name.toLowerCase();
                       return name.endsWith(".jpg") || name.endsWith(".pgm") || name.endsWith(".png");
                }
   };
   File[] imageFiles = root.listFiles(imgFilter);
   MatVector images = new MatVector(imageFiles.length);
   System.out.println("My vector:"+imageFiles);
     `
here the error i m getting
`Exception in thread "main" java.lang.NoSuchMethodError: org.bytedeco.javacpp.Loader.checkVersion(Ljava/lang/String;Ljava/lang/String;)Z
	at org.bytedeco.openblas.presets.openblas_nolapack.<clinit>(openblas_nolapack.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:291)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:265)
	at org.bytedeco.javacpp.Loader.load(Loader.java:977)
	at org.bytedeco.javacpp.Loader.load(Loader.java:935)
	at org.bytedeco.opencv.opencv_core.MatVector.<clinit>(MatVector.java:17)
	at GamoneypubgMAI.AI.FaceRecognizers.main(FaceRecognizers.java:26)
`
on matvector what should i do?

**Comment by saudet** [comment]
Make sure to call Loader.load(opencv_java.class) as documented here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by nikkisingh111333** [comment]
`Exception in thread "main" java.lang.NoSuchMethodError: org.bytedeco.javacpp.Loader.checkVersion(Ljava/lang/String;Ljava/lang/String;)Z
	at org.bytedeco.openblas.presets.openblas_nolapack.<clinit>(openblas_nolapack.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:291)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:265)
	at org.bytedeco.javacpp.Loader.load(Loader.java:977)
	at org.bytedeco.javacpp.Loader.load(Loader.java:935)
	at org.bytedeco.opencv.opencv_core.Algorithm.<clinit>(Algorithm.java:30)
	at GamoneypubgMAI.AI.FaceRecognizers.main(FaceRecognizers.java:31)
`
for every function i call this is happening

**Comment by nikkisingh111333** [comment]
i have added lodaer.load(open_cv.class) but again getting this:
`Exception in thread "main" java.lang.NoSuchMethodError: org.bytedeco.javacpp.Loader.checkVersion(Ljava/lang/String;Ljava/lang/String;)Z
	at org.bytedeco.openblas.presets.openblas_nolapack.<clinit>(openblas_nolapack.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:291)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:160)
	at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:265)
	at org.bytedeco.javacpp.Loader.load(Loader.java:977)
	at org.bytedeco.javacpp.Loader.load(Loader.java:951)
	at GamoneypubgMAI.AI.FaceRecognizers.main(FaceRecognizers.java:21)
`

**Comment by saudet** [comment]
That probably means some JAR files are missing from your class path. Make sure all you are putting all JAR files in the class path.

**Comment by nikkisingh111333** [comment]
can you please tell me in what jars i m missing however following github tutorial i cant figure out particularly i have followings jars in my CP:


- javacpp-1.4.4.jar

- org.bytedeco.opencv-4.4.0-1.5.4.jar

- org.bytedeco.javacv-platform-1.5.4.jar
And in extra previously i was using 
opencv-420.jar
I also have OPENCV-440.jar
what i m missing? help me

**Comment by saudet** [comment]
All the JAR files in the ZIP files here: https://github.com/bytedeco/javacv/releases

**Comment by nikkisingh111333** [comment]
but the zip file is 755 mb do i need all jars or just few ones. do i need to download zip of 755 mb long?

**Comment by saudet** [comment]
You can select only the JAR files you need, yes:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by nikkisingh111333** [comment]
so technically 
1.i need to download that 700+ mb zip. then unzip all jars and put them under classpath 
2.and then everything will start working smothly like previosly opencv 
is it what i need to do ?

can you please specify me why opencv 4.5.0 doesnot have org.opencv.face module.?

**Comment by saudet** [comment]
> so technically
> 1.i need to download that 700+ mb zip. then unzip all jars and put them under classpath

No, you should use Maven instead

> 2.and then everything will start working smothly like previosly opencv
> is it what i need to do ?

Previously as in compared to what?

> can you please specify me why opencv 4.5.0 doesnot have org.opencv.face module.?

Yes, it's included. Why do you say that it isn't?

**Comment by nikkisingh111333** [comment]
because opencv 4.5.0 jar inside i was digging and find nothing like face module herez the ss btw your solution worked for me i was missing bytdeco preset platform it solved my problem no more error.. so heres my SS of opencv 4.5.0 jar inside view:
![Screenshot (44)](https://user-images.githubusercontent.com/49682940/99960625-1040a500-2db3-11eb-9bc0-da3cfb331959.png)
as you can see no face module neither on top nor inside core package as a have seen into opencv 4.5.0 documentation why is that ?

**Comment by saudet** [comment]
You're not using the JAR files for JavaCV. Please use the JAR files for JavaCV.

**Comment by nikkisingh111333** [comment]
but opencv 4.5.0 and javacv are diffrent modules right? how can i join them together .and one more question how can i resize image in bytedeto coz its asking for Opencv Mat Mat instead of javaCV Mat  ? what to do

**Comment by saudet** [comment]
Please use the JAR files for OpenCV from JavaCV and everything will work.

**Comment by nikkisingh111333** [comment]
last question please can you explain me in short what this DoublePointer
and IntPointer class in org.bytedo.opencv .why we are using them and how
can i use them i cant get enough view from docs ? please

**Comment by saudet** [comment]
You don't need to use Mat or DoublePointer from JavaCPP if you don't need to.
Feel free to keep using the official Java API of OpenCV if it does everything you need:
http://bytedeco.org/faq/#how-does-it-differ-from-wrappers-in-opencv-tensorflow-etc
