### ISSUE TITLE
BufferUnderflowException from Java2DFrameConverter

### ISSUE THREAD

**Issue by epserv** [bytedeco/javacv#1544]
I'm not sure what should add write here, ask me for details, but here's the stack trace:

```
java.nio.BufferUnderflowException
      at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:694)
      at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:277)
      at org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma(Java2DFrameConverter.java:177)
      at org.bytedeco.javacv.Java2DFrameConverter.copy(Java2DFrameConverter.java:474)
      at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:675)
      at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:588)
      at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:585)
      at org.bytedeco.javacv.Java2DFrameConverter.convert(Java2DFrameConverter.java:67)
      at ru.epserv.cinema.CinemaEP.lambda$0(CinemaEP.java:57)
      at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
      at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
      at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
      at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by saudet** [comment]
That means you'll need to allocate a bigger buffer.

**Comment by epserv** [comment]
> That means you'll need to allocate a bigger buffer.

How can I do it?

Also I get this:

```
[17:35:39 WARN]: java.lang.ArithmeticException: / by zero
[17:35:39 WARN]:        at org.bytedeco.javacv.FFmpegFrameGrabber.processImage(FFmpegFrameGrabber.java:1005)
[17:35:39 WARN]:        at org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame(FFmpegFrameGrabber.java:1182)
[17:35:39 WARN]:        at org.bytedeco.javacv.FFmpegFrameGrabber.grab(FFmpegFrameGrabber.java:1104)
[17:35:39 WARN]:        at ru.epserv.cinema.CinemaEP.lambda$0(CinemaEP.java:58)
[17:35:39 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[17:35:39 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[17:35:39 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:35:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:35:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:35:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by epserv** [comment]
And java has crashed

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3ddf86f2a4, pid=479684, tid=480210
#
# JRE version: OpenJDK Runtime Environment (15.0.1) (build 15.0.1-internal+0-adhoc.boom.jdk15u)
# Java VM: OpenJDK 64-Bit Server VM (15.0.1-internal+0-adhoc.boom.jdk15u, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
   [libavcodec.so.58+0x8452a4]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /mnt/srv/core.479684)
#
# An error report file with more information is saved as:
# /mnt/srv/hs_err_pid479684.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./run: line 21: 479684 Aborted                 (core dumped) /mnt/git/jdk15u/build/linux-x86_64-server-release/jdk/bin/java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOpti
ons -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15
 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar `cat core.txt
` --nogui

**Comment by saudet** [comment]
Are you trying to use those objects with multiple threads? That won't work,
they are not thread-safe.

**Comment by epserv** [comment]
> Are you trying to use those objects with multiple threads? That won't work, they are not thread-safe.

oh thanks, will they work if I put them all to the single thread, but not main java thread?

**Comment by saudet** [comment]
Yes, that's fine of course. You can also use 1 object per thread, that's fine too.

**Comment by epserv** [comment]
that was caused by multiple threads. can be closed now.
