### ISSUE TITLE
Problem FFmpegRecorder setAudioCodec

### ISSUE THREAD

**Issue by HagiBlickle** [bytedeco/javacv#1587]
Hello,
when I try to convert a audiofile to PCM_S32LE (or other codecs except of : AV_CODEC_ID_PCM_S16LE)
I get an error message:
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open audio codec.
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:819)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:406)

code: 
o_FFmpegFrameRecorder = new FFmpegFrameRecorder(p_OutputFile, intChannels);
o_FFmpegFrameRecorder.setFormat("wav");
o_FFmpegFrameRecorder.setSampleRate(intSampleRate);
o_FFmpegFrameRecorder.setAudioCodecName("pcm_s32le");

o_FFmpegFrameRecorder.start();

The error occurs even when i use 
o_FFmpegFrameRecorder.setAudioCodec(avcodec.AV_CODEC_ID_PCM_S32LE);

The only audiocodec that works is: avcodec.AV_CODEC_ID_PCM_S16LE 

can anyone help me?
Thanks a lot
Hagi

**Comment by saudet** [comment]
What is the error message that you get on the console?

**Comment by saudet** [comment]
If you don't see anything displayed on the console, make sure that FFmpegLogCallback.set() gets called.

**Comment by HagiBlickle** [comment]
Hello sudet,

thanks for your answer, please excuse my late answer.
I get following error:

**Try a) convert a PCM_S16_LE file (Bizet_Carmen.wav) to a PCM_S32_LE.** 

Info: Input #0, wav, from 'H:\14 - Bizet_Carmen.wav':

Info:   Duration: 
Info: 00:02:16.33
Info: , bitrate: 
Info: 1411 kb/s
Info: 

Info:     Stream #0:0
Info: : Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Info: 

Error: [pcm_s32le @ 000000001d26ed80] Specified sample format fltp is invalid or not supported


**Try b) convert a mp4 to sound PCM_S32_LE**

Info: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'H:\__TestVideoSurround.mp4':

Info:   Metadata:

Info:     major_brand     : 
Info: avc1
Info: 

Info:     minor_version   : 
Info: 0
Info: 

Info:     compatible_brands: 
Info: isomavc1
Info: 

Info:     creation_time   : 
Info: 2012-05-17T00:54:33.000000Z
Info: 

Info:   Duration: 
Info: 00:00:46.63
Info: , start: 
Info: 0.000000
Info: , bitrate: 
Info: 188 kb/s
Info: 

Info:     Stream #0:0
Info: (und)
Info: : Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 800x600, 26 kb/s
Info: , 
Info: 8 fps, 
Info: 8 tbr, 
Info: 8 tbn, 
Info: 16 tbc
Info:  (default)
Info: 

Info:     Metadata:

Info:       creation_time   : 
Info: 2012-05-17T00:54:33.000000Z
Info: 

Info:       handler_name    : 
Info: GPAC ISO Video Handler
Info: 

Info:     Stream #0:1
Info: (und)
Info: : Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, 5.1, fltp, 159 kb/s
Info:  (default)
Info: 

Info:     Metadata:

Info:       creation_time   : 
Info: 2012-05-17T00:56:13.000000Z
Info: 

Info:       handler_name    : 
Info: GPAC ISO Audio Handler
Info: 

Error: [pcm_s32le @ 0000000028ba4b40] Specified sample format fltp is invalid or not supported



Thank you for your support
Hagi

**Comment by saudet** [comment]
Ok, that probably means you'll need to call setSampleFormat() with something else like maybe AV_SAMPLE_FMT_S32?
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/global/avutil.html#AV_SAMPLE_FMT_S32

**Comment by HagiBlickle** [comment]
Thanks for your answer,

I tried following
o_FFmpegFrameRecorder.setSampleFormat(avutil.AV_SAMPLE_FMT_S32);
o_FFmpegFrameRecorder.setSampleRate(44100);
o_FFmpegFrameRecorder.setAudioChannels(6) //like the input(grabber) file;
o_FFmpegFrameRecorder.setAudioCodec(avcodec.AV_CODEC_ID_PCM_S32LE);

The previous error does not occur, but I get the following error:

Info: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'H:\__TestVideoSurround.mp4':

Info:   Metadata:

Info:     major_brand     : 
Info: avc1
Info: 

Info:     minor_version   : 
Info: 0
Info: 

Info:     compatible_brands: 
Info: isomavc1
Info: 

Info:     creation_time   : 
Info: 2012-05-17T00:54:33.000000Z
Info: 

Info:   Duration: 
Info: 00:00:46.63
Info: , start: 
Info: 0.000000
Info: , bitrate: 
Info: 188 kb/s
Info: 

Info:     Stream #0:0
Info: (und)
Info: : Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 800x600, 26 kb/s
Info: , 
Info: 8 fps, 
Info: 8 tbr, 
Info: 8 tbn, 
Info: 16 tbc
Info:  (default)
Info: 

Info:     Metadata:

Info:       creation_time   : 
Info: 2012-05-17T00:54:33.000000Z
Info: 

Info:       handler_name    : 
Info: GPAC ISO Video Handler
Info: 

Info:     Stream #0:1
Info: (und)
Info: : Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, 5.1, fltp, 159 kb/s
Info:  (default)
Info: 

Info:     Metadata:

Info:       creation_time   : 
Info: 2012-05-17T00:56:13.000000Z
Info: 

Info:       handler_name    : 
Info: GPAC ISO Audio Handler
Info: 

Info: Output #0, wav, to 'H:\__TestVideoSurround_PCM_44100_6_S32LE.wav':

Info:   Metadata:

Info:     ISFT            : 
Info: Lavf58.45.100
Info: 

Info:     Stream #0:0
Info: : Audio: pcm_s32le ([1][0][0][0] / 0x0001), 44100 Hz, 5.1, s32, 8467 kb/s
Info: 

Error: [pcm_s32le @ 00000000296d99c0] User packet is too small (16384 < 65520)

org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_audio2() error -22: Could not encode audio packet.

_Note: I tried to convert the file with ffmpeg directly 
ffmpeg -i 'H:\__TestVideoSurround.mp4 -acode pcm_s32le -ar 44100 __TestVideoSurround_PCM_44100_6_S32LE.wav
this works fine.

I have trouble setting the parameters for FFmpegRecorder that it works_

Many thanks for the effort
Hagi

**Comment by saudet** [comment]
It sounds like all audio frames need to be exactly of size 65520. Did you try to make sure that all your frames are of size 65520?

BTW, if the ffmpeg program does that you need, it's probably easier to just keep using that:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by HagiBlickle** [comment]
Hello audet,

ok - the ffmpeg program works:
String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);
     ProcessBuilder pb = new ProcessBuilder(ffmpeg, "-i", "/path/to/input.mp4", "-vcodec", "h264", "/path/to/output.mp4");
     pb.inheritIO().start().waitFor();

Nevertheless I wonder what a user packet is, what the user packet size is and how I can influence the size ?
My first thought was that the FFmpegGrabber has to be set fine. I tried to set the FFmpegGrabber properties but with no success.
o_FFmpegFrameRecorder.setSampleFormat(AV_SAMPLE_FMT_S32);
o_FFmpegFrameRecorder.setAudioCodec(AV_CODEC_ID_PCM_S32LE);

How can I set the frames to a specific size?

I use follwing code:
			o_FFmpegFrameGrabber = new FFmpegFrameGrabber(p_InputFile);
			o_FFmpegFrameGrabber.start();

			if (o_FFmpegFrameGrabber.hasAudio() == false) {
				try {
					o_FFmpegFrameGrabber.close();
				}
				catch (FrameGrabber.Exception e) {
					
				}
				return null;
			}
			
			o_FFmpegFrameRecorder = new FFmpegFrameRecorder(p_OutputFile, intChannels);
			o_FFmpegFrameRecorder.setSampleRate(intSampleRate);
			o_FFmpegFrameRecorder.setAudioChannels(intChannels);
			o_FFmpegFrameRecorder.setAudioCodec(avcodec.AV_CODEC_ID_PCM_S32LE);
			o_FFmpegFrameRecorder.setSampleFormat(avutil.AV_SAMPLE_FMT_S32);
			o_FFmpegFrameRecorder.setFormat("wav");
		
		
			o_FFmpegFrameRecorder.start();
			s_AudioConvertCancelled = false;
			while (s_AudioConvertCancelled == false) {
				o_Frame = o_FFmpegFrameGrabber.grabSamples();
				if (o_Frame == null || o_Frame.samples == null) {
					break;
				}
				o_FFmpegFrameRecorder.recordSamples(o_Frame.samples);
			}
Thanks
Hagi

**Comment by saudet** [comment]
The packet size depends on the encoder, that's not something we can set. In the case of PCM, since that's what the frames are already encoded in, it basically just copies the frame data, but it looks like it doesn't support frame/packet size smaller than 65520. You might want to try and ask upstream about that to get more information: https://ffmpeg.org/contact.html

However, that's a strange limitation. It sounds as though this "ugly hack" may need to be updated for 32-bit PCM as well:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L832-L847

**Comment by HagiBlickle** [comment]
Thank you very much for your support and your great work.

The method of using the ffmpeg class directly works great for my software.
If I find time, I will ask upstream about the package sizes.

If the hack is changed it might make sense to add not only a hack for 32 bit but also for 24 bit ???

Hagi
