### ISSUE TITLE
NullPointerException from Java2DFrameConverter

### ISSUE THREAD

**Issue by md-y** [bytedeco/javacv#1594]
```Java2DFrameConverter.convert()``` produces a NullPointerException despite every value not being null. I have absolutely no idea why.

```
java.lang.NullPointerException: null
        at java.awt.image.ComponentColorModel.bitsHelper(Unknown Source) ~[?:1.8.0_281]
        at java.awt.image.ComponentColorModel.<init>(Unknown Source) ~[?:1.8.0_281]
        at java.awt.image.ComponentColorModel.<init>(Unknown Source) ~[?:1.8.0_281]
        at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:639) ~[?:?]
        at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:595) ~[?:?]
        at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:592) ~[?:?]
        at org.bytedeco.javacv.Java2DFrameConverter.convert(Java2DFrameConverter.java:67) ~[?:?]
        at io.github.mdy.videoviewer.playback.VideoDecoder.getImageArraySync(VideoDecoder.java:27) ~[?:?]
        at io.github.mdy.videoviewer.playback.PlaybackWorker.loadVideo(PlaybackWorker.java:44) ~[?:?]
        at io.github.mdy.videoviewer.commands.CommandScreen.lambda$playVideoCommand$0(CommandScreen.java:126) ~[?:?]
```

Here's the code:
```java
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(file);
grabber.setImageWidth(width);
grabber.setImageHeight(height);
grabber.setFrameRate(20);
grabber.start();

int frameCount = grabber.getLengthInFrames();
BufferedImage[] frames = new BufferedImage[frameCount];

final Java2DFrameConverter converter = new Java2DFrameConverter();

Frame frame;
int processedFrames = 0;
while ((frame = grabber.grab()) != null) {
    if (frame.image != null) {
        BufferedImage img = converter.convert(frame);
        frames[processedFrames] = img;
        processedFrames++;
    }
}
```

Everything else seems to work other than this.

**Comment by saudet** [comment]
It's probably not receiving frames in a supported format. Try to set the pixel format of the grabber to something that is known to work like this: `grabber.setPixelFormat(AV_PIX_FMT_BGR24)`. That should already be the default though.

**Comment by md-y** [comment]
```AV_PIX_FMT_BGR24``` and other RGB/BGR formats did not work, but other formats worked and solve the issue.

Thank you!

**Comment by saudet** [comment]
It sounds like you have a really strange video file. I've never seen it fail in that way. Could you please provide the video file as well?

**Comment by md-y** [comment]
I was mainly testing with a [youtube video](https://www.youtube.com/watch?v=FtutLA63Cp8) downloaded with the latest version of [youtube-dl](https://github.com/ytdl-org/youtube-dl/). Here is a [dropbox link](https://www.dropbox.com/s/cyl3l5z4y75vo4p/bad_apple.mkv?dl=1) to it.

However, I also tested it with plenty of other videos from different places, formats, sizes, etc. and none of them worked.

**Comment by md-y** [comment]
Im suprised I didn't try this before, but it worked after removing:
```java
grabber.setImageWidth(width);
grabber.setImageHeight(height);
```

**Comment by saudet** [comment]
Either way, it works fine for me. With 120 x 120 and your code above I get this:
```
BufferedImage@4b5d6a01: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@4a22f9e2 transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 120 height = 120
```
I have no way to reproduce this.

**Comment by md-y** [comment]
Huh, that is weird. Either way, I'm now using a filter to scale the image and change the format which solves the problem regardless.

Once again, thank you!
