### ISSUE TITLE
Error when excluding unused .so files from a build

### ISSUE THREAD

**Issue by westy92** [bytedeco/javacv#1610]
If you're using a subset of all OpenCV features (i.e. simple image loading and core color manipulation), is it possible to exclude "unused" `.so` files from the build to decrease APK size?

Reference code:
```gradle
// ...

android {
    // ...
    packagingOptions {
        exclude 'lib/*/lib*opencv_python3.so'
        exclude 'lib/*/lib*opencv_plot.so'
    }
}

dependencies {
    implementation 'org.bytedeco:opencv:4.5.1-1.5.5'
    implementation 'org.bytedeco:opencv:4.5.1-1.5.5:android-arm'
    implementation 'org.bytedeco:opencv:4.5.1-1.5.5:android-arm64'
    implementation 'org.bytedeco:opencv:4.5.1-1.5.5:android-x86_64'
    implementation 'org.bytedeco:opencv:4.5.1-1.5.5:android-x86'
}
```

Used modules:
```kt
// ...
import org.opencv.android.Utils
import org.opencv.core.Core
import org.opencv.core.Mat
import org.opencv.core.Scalar
import org.opencv.imgproc.Imgproc
import org.opencv.osgi.OpenCVNativeLoader
// ...
```

Upon calling `OpenCVNativeLoader().init()`, I get:

```bash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.me.example, PID: 15836
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_plot.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.opencv.osgi.OpenCVNativeLoader.init(OpenCVNativeLoader.java:15)
        at com.me.example.MainActivity.onCreate(MainActivity.kt:196)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by saudet** [comment]
Yes, we can exclude anything we want, but if you get errors like this, you'll need to disable those modules at build time:
https://github.com/bytedeco/javacpp-presets#build-instructions
