### ISSUE TITLE
UnsatisfiedLinkError Maven download

### ISSUE THREAD

**Issue by jiseung2007** [bytedeco/javacv#1613]
I tried everything but I can't seem to find the problem  Whenever I try to  
I am doing this with the Maven project in EclipseIDE

`System.load(Core.NATIVE_LIBRARY_NAME);`

it gives me this error 

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: opencv_java451
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at app.OCV.App.main(App.java:13)`

any Solutions?

Thank you!

**Comment by saudet** [comment]
Please run `Loader.load(opencv_java.class)` as documented here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by jiseung2007** [comment]
Hmm Even that gives me more Error

`Exception in thread "main" java.lang.InternalError: Should not get here
	at sun.nio.fs.WindowsNativeDispatcher.CreateSymbolicLink0(Native Method)
	at sun.nio.fs.WindowsNativeDispatcher.CreateSymbolicLink(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(Unknown Source)
	at java.nio.file.Files.createSymbolicLink(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1619)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1239)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1200)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1148)
	at app.OCV.App.main(App.java:15)`




Am I Installing this Wrong? What I did was put dependency in the pom.xml as Shown and Just press the run button with this command.

`package app.OCV;

import org.bytedeco.javacpp.Loader;
import org.bytedeco.opencv.opencv_java;
import org.opencv.core.Core;

public class App 
{
    public static void main( String[] args )
    {
    	Loader.load(opencv_java.class);
    	System.load(Core.NATIVE_LIBRARY_NAME);
    	System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }
    
}
`


Am I missing the download steps?

Thank you so much

![MavenDependency](https://user-images.githubusercontent.com/73577913/112841015-f4d80480-90da-11eb-8599-4afa6e2699bb.PNG)

**Comment by saudet** [comment]
Don't call `System.loadLibrary()`.

**Comment by jiseung2007** [comment]
hmm This shows again 


`Exception in thread "main" java.lang.InternalError: Should not get here
	at sun.nio.fs.WindowsNativeDispatcher.CreateSymbolicLink0(Native Method)
	at sun.nio.fs.WindowsNativeDispatcher.CreateSymbolicLink(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(Unknown Source)
	at java.nio.file.Files.createSymbolicLink(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1619)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1239)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1200)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1148)
	at app.OCV.App.main(App.java:15)
`

![Capture](https://user-images.githubusercontent.com/73577913/112844919-379bdb80-90df-11eb-89c3-2bd7b7918bf7.PNG)

**Comment by saudet** [comment]
It looks like you're using an old version of the JDK. Please upgrade your JDK.

**Comment by jiseung2007** [comment]
I changed it to 14.0.2 and works like a cham thankyou so much I have been struggling with this for a week
