### ISSUE TITLE
Frame data(imageChannels,imageStride,opaque) lose

### ISSUE THREAD

**Issue by LW-Francis** [bytedeco/javacv#1630]
i do soamething.one thread put frame like this:
public static ConcurrentHashMap<String, Frame> frames = new ConcurrentHashMap<>();
FFmpegFrameProperty.frames.put(id, frame);
get the frame info like this
[http://tiebapic.baidu.com/forum/w%3D580/sign=1d143e0415087bf47dec57e1c2d2575e/311e0c3fb80e7bec546602ae382eb9389a506bdb.jpg](url)
the other thread get frame like this
FFmpegFrameProperty.frames.get(id)
get the frame info like this
[http://tiebapic.baidu.com/forum/w%3D580/sign=5acacc669118367aad897fd51e728b68/b861e78065380cd77bb8a3a2b644ad34588281fe.jpg](url)
the result is imageChannels,imageStride,opaque lose

**Comment by saudet** [comment]
You'll probably need to copy the data, for example, by calling `frame.clone()`.

**Comment by LW-Francis** [comment]
i do you say.and it is ok.but have other question like this
EXCEPTION_ACCESS_VIOLATION

**Comment by saudet** [comment]
That means you're trying to access data that was freed. You need to make sure that you're not trying to access data after calling methods like `stop()` or `close()`.

**Comment by LW-Francis** [comment]
why i use the frame.clone().different frame use different time.and i will get a error 
`Exception in thread "Thread-7" java.lang.OutOfMemoryError: Cannot allocate new BytePointer(6220800): totalBytes = 1785M, physicalBytes = 503M
	at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:132)
	at org.bytedeco.javacv.Frame.cloneBufferArray(Frame.java:287)
	at org.bytedeco.javacv.Frame.clone(Frame.java:223)
	at com.mv.videosplitframe.rabbit.VideoFrameProvider.pullFrame(VideoFrameProvider.java:292)
	at com.mv.controller.VideoController.lambda$pushFrame$0(VideoController.java:33)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes (1785M + 6075K) > maxBytes (1788M)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:696)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:126)
	at org.bytedeco.javacpp.BytePointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:124)
	... 5 more`

**Comment by saudet** [comment]
Be sure that `close()` gets called on the ones you don't need anymore.

**Comment by LW-Francis** [comment]
you mean when i call frame.clone(),i have to call frame.close()?

**Comment by saudet** [comment]
No, please read this:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by LW-Francis** [comment]
thank you! i read the article,and it use PointerScope.but in my code,i still not understand how to use.this is my code
`
while (flag) {
            if (frame != null) {
                try {

                        String id = UUID.randomUUID().toString();
                        frame2 = frame.clone();

                        FFmpegFrameProperty.frames.put(id, frame2);
                        rabbitTemplate.convertAndSend("frame", id); 
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    } finally {

                    }

            } else {

                grabber.restart();

            }
            frame = grabber.grabFrame();
        }
`
and i use rabbitmq to cosume the frame. and the code
`
 //获取对应的FFmpegFrameRecorder进行处理
        FFmpegFrameRecorder recorder = FFmpegFrameProperty.recorders.get("5");
        Frame frame = FFmpegFrameProperty.frames.get(id);
        FFmpegFrameProperty.frames.remove(id);

        try {
            recorder.record(frame);

        } catch (Exception e) {
            e.printStackTrace();
        }
`

**Comment by saudet** [comment]
`PointerScope` may not be useful in your code. It will just end up doing the same thing as `Frame.close()`.

**Comment by LW-Francis** [comment]
where can i use `frame.close()`.i have a try use `frame2.close()` after   `FFmpegFrameProperty.frames.put(id, frame2);` but it get other error

**Comment by saudet** [comment]
When you remove it from `frames`.

**Comment by LW-Francis** [comment]
i add frame.close(),like this
```
FFmpegFrameRecorder recorder = FFmpegFrameProperty.recorders.get("5");
Frame frame = FFmpegFrameProperty.frames.get(id);
FFmpegFrameProperty.frames.remove(id);

    try {
        recorder.record(frame);
        frame.close()
    } catch (Exception e) {
        e.printStackTrace();
    }
```
and the same problem

**Comment by LW-Francis** [comment]
can you tell me what reason result in this problem.and i use  `System.out.println(Pointer.physicalBytes());`  and the value will grow

**Comment by LW-Francis** [comment]
i will save frame to ConcurrentHashMap from grabber.grabFrame(),and get frame from hashmap.is it effected by hashmap?

**Comment by saudet** [comment]
That just means you still have frames taking memory somewhere. Like I keep telling you, make sure to call `close()` on them.

**Comment by saudet** [comment]
If you believe that you are closing everything, please provide a small example that fails, and I will take a look. Thank you!

**Comment by LW-Francis** [comment]
yes.i confirmly close the frame.i will get my code to you ,please help me check,thank you

**Comment by LW-Francis** [comment]
init grabber
```
public FFmpegFrameGrabber initGrabber(String url) throws FFmpegFrameGrabber.Exception {
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);//  rtsp url

        if (url.indexOf("rtsp") >= 0) {

            grabber.setFormat("rtsp");
            grabber.setOption("rtsp_transport", "tcp");
            grabber.setOption("rtsp_flags", "prefer_tcp");
            grabber.setOption("stimeout", "3000000");
        }
        grabber.setFrameRate(25);
        grabber.start();

        audiocodecid = grabber.getAudioCodec();
        pixelFormat = grabber.getPixelFormat();
        codecid = grabber.getVideoCodec();
        framerate = grabber.getVideoFrameRate();
        bitrate = grabber.getVideoBitrate();
        format=grabber.getFormat();


        return grabber;
    }
```
init  recorder

```
public FFmpegFrameRecorder initRecorder(String rtmpUrl, int width, int height) throws FFmpegFrameRecorder.Exception {

        FFmpegFrameRecorder record = new FFmpegFrameRecorder(rtmpUrl, width, height, 1);

        record.setVideoOption("crf", "18");
        record.setGopSize(2);
        record.setFrameRate(25);
        record.setVideoBitrate(bitrate);
        if (rtmpUrl.indexOf("rtmp") >= 0 || rtmpUrl.indexOf("flv") > 0) {
            record.setFormat("flv");
            record.setAudioCodecName("aac");
            record.setVideoCodec(codecid);

        }

        FFmpegLogCallback.set();

        record.start();
        return record;

    }
```

get frame
```
while (flag) {

            if (frame != null) {
                if (pullHandle) {
                    recorder.record(frame);
                    pullHandle = true;
                } else {
                    long t1 = System.currentTimeMillis();
                    Frame frame2 = frame.clone();
                    FFmpegFrameProperty.frameQueue.offer(frame2);
                    long t2 = System.currentTimeMillis();

                    System.out.println(Pointer.physicalBytes());
                }
            } else {
                //当获取的frame为null，要重新start(),保证持续获取视频帧
                grabber.restart();
            }
            //重新获得图片帧
            frame = grabber.grabImage();
        }
```
analysis frame
```
private void analysisFrame() {
        new Thread(() -> {
            FFmpegFrameRecorder recorder = FFmpegFrameProperty.recorders.get("5");
            Tracker tracker = FFmpegFrameProperty.tracker.get("5");

            OpenCVFrameConverter.ToIplImage convert = new OpenCVFrameConverter.ToIplImage();
            Rect rect = new Rect(0, 0, 0, 0);
            try {
                int i = 0;
                while (true) {
                    if (FFmpegFrameProperty.frameQueue.size() == 0) {
                        continue;
                    }
                    i++;
                    Frame frame2 = FFmpegFrameProperty.frameQueue.poll();//获取帧进行处理
                    //每隔5帧进行跟踪处理
                    if (i < FFmpegFrameProperty.INTERVAL_FRAME) {
                        recorder.record(frame2);
                    } else {
                        Mat mat = convert.convertToMat(frame2);
                        boolean is_ok = tracker.update(mat, rect);
                        if (is_ok) {
                            rectangle(mat, rect, Scalar.GREEN);
                        }
                        recorder.record(convert.convert(mat));
                        i = 0;
                    }
                    frame2.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }).start();
    }
```

**Comment by saudet** [comment]
I don't have access to all your code, so I cannot debug this. Can you create a smaller self-contained program that can reproduce this issue?

**Comment by saudet** [comment]
How do you know that analysisFrame() can process images faster than your stream?

**Comment by LW-Francis** [comment]
sorry。it is too late to answer you.what do you mean "analysisFrame() can process images faster than your stream"

**Comment by LW-Francis** [comment]
it is my code

```
@Service
@Slf4j
public class VideoFrameProvider {


    private boolean flag = true;//获取帧线程的标志

    private IMvVideoSourceInfoService mvVideoSourceInfoService;

    private IMvVideoFrameInfoService mvVideoFrameInfoService;

    private RabbitTemplate rabbitTemplate;

    // 视频参数
    protected int audiocodecid;
    protected int codecid;
    protected double framerate;// 帧率
    protected int bitrate;// 比特率

    static {
        System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", "0");
        System.setProperty("org.bytedeco.javacpp.maxbytes", "0");
    }


    @Autowired
    public VideoFrameProvider(RabbitTemplate rabbitTemplate, IMvVideoSourceInfoService mvVideoSourceInfoService, IMvVideoFrameInfoService mvVideoFrameInfoService) {
        rabbitTemplate.setMessageConverter(new FrameMessageConverter());
        this.rabbitTemplate = rabbitTemplate;
        this.mvVideoSourceInfoService = mvVideoSourceInfoService;
        this.mvVideoFrameInfoService = mvVideoFrameInfoService;
    }

    /**
     * 初始化FFmpegFrameGrabber
     *
     * @param url
     * @return
     * @throws FFmpegFrameGrabber.Exception
     */
    public FFmpegFrameGrabber initGrabber(String url) throws FFmpegFrameGrabber.Exception {
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);
//        grabber.setFormat("rtsp");
//        //设置RTSP传输协议为tcp传输模式
//        grabber.setOption("rtsp_transport", "tcp");
//        grabber.setOption("rtsp_flags", RtspFlags.PREFER_TCP.getCode());
        //socket网络超时时间
        grabber.setOption("stimeout", "3000000");
        // 设置缓存大小，提高画质、减少卡顿花屏
        grabber.setOption("buffer_size", "1024000");
        grabber.setFrameRate(FFmpegFrameProperty.FRAME_RATE);

        grabber.start();
        return grabber;
    }

    public FFmpegFrameGrabber initGrabber1(String url) throws FFmpegFrameGrabber.Exception {
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);

        if (url.indexOf("rtsp") >= 0) {

            grabber.setFormat("rtsp");
            grabber.setOption("rtsp_transport", "tcp");
            grabber.setOption("rtsp_flags", "prefer_tcp");
            grabber.setOption("stimeout", "3000000");
        }
        grabber.setFrameRate(25);
        grabber.start();

        // 视频参数
        audiocodecid = grabber.getAudioCodec();
        codecid = grabber.getVideoCodec();
        framerate = grabber.getVideoFrameRate();// 帧率
        bitrate = grabber.getVideoBitrate();// 比特率

        return grabber;
    }

    /**
     * 初始化FFmpegFrameRecorder
     *
     * @param name
     * @param width
     * @param height
     * @return
     * @throws FFmpegFrameRecorder.Exception
     */
    public FFmpegFrameRecorder initRecorder(String name, int width, int height) throws FFmpegFrameRecorder.Exception {

        //创建录制的文件夹
        String filePath = createdRecordDir(name);

        String output = MessageFormat.format(FFmpegFrameProperty.OUTPUT_FORMAT, filePath, name);
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(output, width, height, 0);
        recorder.setFormat("image2");
        recorder.setOption("update", ScreenshotMode.SEQUENCE_MODE.getCode());
        recorder.start();

        return recorder;

    }

    public FFmpegFrameRecorder initRecorder1(String rtmpUrl, int width, int height) throws FFmpegFrameRecorder.Exception {

        //创建录制的文件夹
        FFmpegFrameRecorder record = new FFmpegFrameRecorder(rtmpUrl, width, height, 0);

        record.setVideoOption("crf", "18");
        record.setGopSize(2);
        record.setFrameRate(25);
        record.setVideoBitrate(bitrate);
        if (rtmpUrl.indexOf("rtmp") >= 0 || rtmpUrl.indexOf("flv") > 0) {
            // 封装格式flv
            record.setFormat("flv");
            record.setAudioCodecName("aac");
            record.setVideoCodec(avcodec.AV_CODEC_ID_H264);

        }

        FFmpegLogCallback.set();

        record.start();
        return record;

    }

    /**
     * 创建录制的文件夹
     *
     * @param name
     */
    private String createdRecordDir(String name) {
        String filePath = "D:\\" + name;
        File file = new File(filePath);
        if (!file.exists()) {
            file.mkdir();
        }

        return filePath;
    }

    private static Tracker createdTrackerByName(String type) {

        String[] TRACKER_TYPE = {"KCF", "CSRT"};

        Tracker tracker = null;

        if (type.equals(TRACKER_TYPE[0])) {
            tracker = TrackerKCF.create();
        } else if (type.equals(TRACKER_TYPE[1])) {
            tracker = TrackerCSRT.create();
        }

        return tracker;
    }

    /**
     * 视频快照。生产视频帧，并转给消费者进行处理
     *
     * @param requestDTO
     * @throws IOException
     */
    public void pullFrame(PushFrameRequestDTO requestDTO) throws IOException, InterruptedException {

        //视频源（摄像头）id
        Long videoSourceId = requestDTO.getVideoSourceId();

        //视频源信息信息
        MvVideoSourceInfo mvVideoSourceInfo = mvVideoSourceInfoService.getMvVideoSourceInfo(videoSourceId);

        //初始化grabber
        String rtspUrl = MessageFormat.format(FFmpegFrameProperty.RTSP_URL, mvVideoSourceInfo.getMvVideoSourceUsername(), mvVideoSourceInfo.getMvVideoSourcePassword(), mvVideoSourceInfo.getMvVideoSourceIp(), "Streaming/Channels/101");
        FFmpegFrameGrabber grabber = initGrabber1(rtspUrl);
        FFmpegFrameProperty.grabbers.put(videoSourceId, grabber);

        //初始化recorder
        String rtmpUrl = MessageFormat.format(FFmpegFrameProperty.RSMP_SERVER_URL, videoSourceId);
        FFmpegFrameRecorder recorder = initRecorder1(rtmpUrl, grabber.getImageWidth(), grabber.getImageHeight());
        FFmpegFrameProperty.recorders.put(videoSourceId, recorder);

        //启动分析帧线程
        analysisFrame(videoSourceId);

        Frame frame = grabber.grab();
        while (flag) {

            if (frame != null) {
                long t1 = System.currentTimeMillis();
                Frame frame2 = frame.clone();
                FFmpegFrameProperty.frameQueue.offer(frame2);//将帧存入队列待处理
                long t2 = System.currentTimeMillis();
                System.out.println("取帧时间：" + (t2 - t1));
                System.out.println(Pointer.physicalBytes());
            } else {
                //当获取的frame为null，要重新start(),保证持续获取视频帧
                grabber.restart();
            }
            //重新获得图片帧
            frame = grabber.grab();
        }

    }

    /**
     * 调用盛视AI算法。包括人体检测和人体属性
     *
     * @param frame
     * @return
     */
    private ShengshiBodyFeatureAnalysisNumber doBodyFeatureAnalysis(Frame frame) {
        try {
            Java2DFrameConverter java2DFrameConverter = new Java2DFrameConverter();
            BufferedImage image = java2DFrameConverter.getBufferedImage(frame);//帧转图像

            //进行人体属性检测，获取人体位置和人体属性
            IShengshiApiHandlerFactory shengshiApiHandlerFactory = new ShengshiApiFactory();
            IShengshiApiHandler shengshiApiHandler = shengshiApiHandlerFactory.createShengshiApiHandler(HandlerType.SDK_HANDLER);
            ShengshiBodyFeatureAnalysisNumber data = shengshiApiHandler.doBodyFeatureAnalysis(ImageUtil.getImageToByteArr(image, "jpg"));
            return data;
        } catch (Exception ex) {
            log.error("VideoFrameProvider/doBodyFeatureAnalysis Error");
            ex.printStackTrace();
        }
        return null;
    }

    /**
     * 初始化跟踪器
     *
     * @param frame
     * @param personAttributes
     */
    private Tracker initTracker(Frame frame, List<ShengshiBodyFeatureAnalysisNumber.PersonAttributes> personAttributes) {
        Tracker tracker = null;

        //for (ShengshiBodyFeatureAnalysisNumber.PersonAttributes pa : personAttributes) {
        //初始化跟踪器
        OpenCVFrameConverter.ToIplImage convert = new OpenCVFrameConverter.ToIplImage();
        tracker = createdTrackerByName("KCF");
        ShengshiBodyFeatureAnalysisNumber.PersonPosition personPosition = personAttributes.get(0).getPosition();
        Rect rect = new Rect(personPosition.getX(), personPosition.getY(), personPosition.getW(), personPosition.getH());
        rectangle(convert.convertToMat(frame), rect, Scalar.GREEN);
        tracker.init(convert.convertToMat(frame), rect);

        //}
        return tracker;

    }

    /**
     * 负责分析视频帧
     *
     * @param videoSourceId
     */
    private void analysisFrame(Long videoSourceId) {
        new Thread(() -> {
            try {
                FFmpegFrameRecorder recorder = FFmpegFrameProperty.recorders.get(videoSourceId);
                Tracker tracker = null;
                OpenCVFrameConverter.ToIplImage convert = new OpenCVFrameConverter.ToIplImage();
                Rect rect = new Rect(0, 0, 0, 0);
                int i = 0;
                while (true) {

                    if (FFmpegFrameProperty.frameQueue.size() == 0) {
                        //若队列没有帧数据就等待
                        continue;
                    }

                    //获取帧进行处理
                    Frame frame = FFmpegFrameProperty.frameQueue.poll();
                    i++;
                    //每隔(FFmpegFrameProperty.INTERVAL_FRAME)帧进行跟踪处理
                    if (i <= FFmpegFrameProperty.INTERVAL_FRAME) {
                        recorder.record(frame);
                    } else {
                        //获取人体位置和人体属性
                        ShengshiBodyFeatureAnalysisNumber data = doBodyFeatureAnalysis(frame);

                        //算法检测异常
                        if (data == null) {
                            //若算法检测异常，保证视频流畅播放
                            recorder.record(frame);
                        } else {
                            //算法检测正常
                            int personCount = data.getData().getPersonCount();//人体数量
                            if (personCount > 0 && tracker == null) {
                                List<ShengshiBodyFeatureAnalysisNumber.PersonAttributes> personAttributes = data.getData().getPersonAttributes();
                                //进行初始化跟踪器
                                tracker = initTracker(frame, personAttributes);
                                //异步保存视频帧信息
                                mvVideoFrameInfoService.batchAddMvVideoFrameInfo(videoSourceId, personAttributes);
                                recorder.record(frame);
                            } else {
                                Mat mat = convert.convertToMat(frame);
                                boolean is_ok = tracker.update(mat, rect);
                                if (is_ok) {
                                    rectangle(mat, rect, Scalar.GREEN);
                                }
                                recorder.record(convert.convert(mat));
                            }
                            i = 0;
                        }
                    }
                    frame.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }, "camera-" + videoSourceId).start();
    }
```

in my code,i use opencv tracker and some other algorithm

**Comment by saudet** [comment]
How do you make sure that frameQueue.offer() does not get called more often than frameQueue.poll()? I don't see anything in your code to prevent it from filling your memory with frames.

**Comment by LW-Francis** [comment]
i can not make sure.but i have to do it.i have to one thread to get frame and the other one to use frame.now i use this method.can you get some suggestion to me ?thank you

**Comment by LW-Francis** [comment]
frameQueue.offer() must be get called more often than frameQueue.poll()。because pullFrame() only get frame,not other thing,but
analysisFrame() will get frame and analyse frame.it take much time than pullFrame

**Comment by LW-Francis** [comment]
when pullFrame() only get frame and analysisFrame() only record frame.it is ok and Normal Running

**Comment by steeveen** [comment]
Excuse me. I met the same thing. I use FFmpegFrameGrabber to grab frame and process it.  Here is a short version of my code
```
FFmpegFrameGrabber grabber =new FFmpegFrameGrabber("xxx.m3u8");
Frame aFrame=null;
while((aFrame=grabber.grabFrame(...)){
     Frame bFrame=aFrame.clone();
     bFrame is processed and cloned in other thread, and can be confirmed that bFrame is grabbed earlier than bFrame is processed .
}
grabber.close();
```

The program is fine at first, but after a few days grabber starting and closing, it will report an error at `aFrame.clone()` saying " Failed to allocate memory within limits: totalBytes (xxxx + xxxx) > maxBytes".
My understanding is this, for performance, each aFrame in the while loop will be placed in the same memory (direct memory), but the bFrame from clone is an object on a different memory. So bFrame needs to be closed manually. The shared memory of aFrame will also be closed when grabber.close() is called, so I should no longer need to manually close aFrame everytime. But why is OOM reported now? 
Is there something wrong with my understanding? After each aFrame clone, do I have to close the aFrame? If I closed aFrame，Will it affect the cloned bFrame that has not been used yet? Looking forward to your reply

**Comment by saudet** [comment]
@steeveen It's not necessary to close it manually, but it's certainly recommended. Doing so avoids memory fragmentation, which might be the cause of the OOM you're experiencing.

**Comment by steeveen** [comment]
thx, I will try under your advice.
But this kind of error always occurs after running continuously for several days, and it can recovers after manual restart. I have always wondered if it is my jvm memory configuration problem? My jvm parameters are like this
`-Xmx2790195K -Xmx2790195K -XX:MetaspaceSize=429260K -XX:MaxMetaspaceSize=429260K -Xss1430K -XX:MaxDirectMemorySize=4000M` with total 8G memory in machine.
Do you have any good suggestions?
