### ISSUE TITLE
 how to get the spectrum of the audio processed by the filter 

### ISSUE THREAD

**Issue by Nirvana-feng** [bytedeco/javacv#1639]
Hello, I would like to ask how to get the spectrum of the audio processed by the filter of showwavespic .

**Comment by saudet** [comment]
Documentation is available here with an example:
https://ffmpeg.org/ffmpeg-filters.html#showwavespic

**Comment by Nirvana-feng** [comment]
Hello, I just refer to this implementation, but I don't know how to deal with the pull frame？I used ffmpegframerecorder to collect it,But the following error occurred：
Exception in thread "main" org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_parse_ptr() error -22
	at org.bytedeco.javacv.FFmpegFrameFilter.startAudioUnsafe(FFmpegFrameFilter.java:461)
	at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:271)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:251)
	at showwave.wave(showwave.java:37)
	at showwave.main(showwave.java:57)
[aac @ 000000001b4981c0] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'F:\dashtest\23.aac':
  Duration: 00:02:54.59, bitrate: 71 kb/s
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 71 kb/s
[Parsed_showwavespic_0 @ 000000001b50dbc0] Media type mismatch between the 'Parsed_showwavespic_0' filter output pad 0 (video) and the 'out' filter input pad 0 (audio)
Cannot create the link showwavespic:0 -> abuffersink:0
command:ffmpeg -i  test.mp4 -filter_complex "showwavespic=s=720x180" -frames:v 1 audio.png
code:
/**
 * @program: New_javacv
 * @description:
 * @author: Mr.Wang
 * @create: 2021-04-23 15:41
 **/

import org.bytedeco.ffmpeg.global.avcodec;
import org.bytedeco.ffmpeg.global.avutil;
import org.bytedeco.javacv.*;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;

/**
 * @program: New_javacv
 * @description:
 * @author: li
 * @create: 2021-04-23 15:41
 **/
public class showwave {
    public static void wave(String input, String output, String filtercontent) throws Exception {
        String fileName = output + "/img_" + ".jpg";
        //文件储存对象
        File outPut = new File(fileName);
        FFmpegFrameGrabber grab = new FFmpegFrameGrabber(input);
        grab.start();
        FFmpegFrameRecorder  recorder=new FFmpegFrameRecorder(output,100,100);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_PNG);
        //ico支持bmp和png两种图片编码方式，该示例使用png
        recorder.setPixelFormat(avutil.AV_PIX_FMT_RGBA);//设置像素格式
        //像素宽高都不能超过256，width<=256&&height<=256
//        recorder.setImageWidth(256);
//        recorder.setImageHeight(256);
        FFmpegFrameFilter filter = new FFmpegFrameFilter(filtercontent, grab.getAudioChannels());
        filter.start();
        recorder.start();
        Frame frame = null;
        Frame frame1 = null;
        while ((frame = grab.grabSamples()) != null) {
            filter.push(frame);
            frame1 = filter.pull();
            if(frame1!=null){
                recorder.record(frame1);
            }else{
                System.out.println(frame1);
            }

                }
        grab.close();
        filter.close();
        recorder.close();
    }

    public static void main(String[] args) throws Exception {
        wave("F:\\dashtest\\23.aac", "F:\\dashtest\\audio_1.png", "showwavespic=split_channels=1:s=1024x800");
    }
}
Please help me to see what the problem is，thank you very much!

**Comment by saudet** [comment]
I don't think this is something we can do with FFmpegFrameFilter right now, but we can easily use the ffmpeg from Java:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by Nirvana-feng** [comment]
Thank you very much. It's working
