### ISSUE TITLE
FFmpegFrameFilter with xfade initialization error：avfilter_graph_config() error -22。

### ISSUE THREAD

**Issue by dntbeSris** [bytedeco/javacv#1653]
how can i use FFmpegFrameFilter with the multi input video? 

```
    private static void fade() throws FFmpegFrameRecorder.Exception, FFmpegFrameFilter.Exception {
        FFmpegLogCallback.set();
        OpenCVFrameConverter.ToIplImage toIplImage = new OpenCVFrameConverter.ToIplImage();
        Mat m0 = imread("./dior_0.jpg");
        Mat m = imread("./dior.jpg");
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("./fade.gif",1920,1080,0);
        recorder.setVideoCodec(AV_CODEC_ID_GIF);
        recorder.setPixelFormat(AV_PIX_FMT_RGB4_BYTE);
        recorder.start();
        FFmpegFrameFilter filter = new FFmpegFrameFilter(null,null,recorder.getImageWidth(),recorder.getImageHeight(),0);
        filter.setPixelFormat(recorder.getPixelFormat());
        filter.setVideoInputs(2);
        filter.setFilters("xfade=transition=fade:duration=2:offset=5");
        filter.start();

        filter.push(toIplImage.convert(m0));
        filter.push(toIplImage.convert(m));
        Frame ff;
        while ((ff = filter.pullImage()) != null){
            recorder.record(ff);
        }
        filter.stop();
        filter.release();
        recorder.stop();
        recorder.release();
    }
```

`Exception in thread "main" org.bytedeco.javacv.FFmpegFrameFilter$Exception: avfilter_graph_config() error -22 (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe(FFmpegFrameFilter.java:410)
	at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:308)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:283)`

**Comment by saudet** [comment]
There's an example of that here in the unit tests:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L142

**Comment by dntbeSris** [comment]
> There's an example of that here in the unit tests:
> https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L142

tks ,but it does not worked for me.

**Comment by saudet** [comment]
Did you call FFmpegLogCallback.set()? What error message do you get on the console?

**Comment by dntbeSris** [comment]
> Did you call FFmpegLogCallback.set()? What error message do you get on the console?

yes. i put my code in this question. this all message on my console.

```
Exception in thread "main" org.bytedeco.javacv.FFmpegFrameFilter$Exception: avfilter_graph_config() error -22 (For more details, make sure FFmpegLogCallback.set() has been called.) at org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe(FFmpegFrameFilter.java:410) at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:308) at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:283)

```

**Comment by dntbeSris** [comment]
i guess ,the xfade filter might not in the libavfilter. how can i confirm it.

**Comment by saudet** [comment]
We can check that with the ffmpeg program and its `-filters` option, for example, this way:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by dntbeSris** [comment]
yep. without the xfade filter. and i used the lastest version.

**Comment by saudet** [comment]
Try the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
There's an example of that here in the unit tests:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L142

**Comment by saudet** [comment]
There's an example of that here in the unit tests:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L142

**Comment by dntbeSris** [comment]
> There's an example of that here in the unit tests:
> https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L142

tks,but it doesn't work for me.

**Comment by Hccake** [comment]
I had the same problem 😥

**Comment by saudet** [comment]
What's the error message that you get in the log?

**Comment by Hccake** [comment]
> What's the error message that you get in the log?

**The command line statement expected to be implemented**
```cmd
ffmpeg -i test.mp4 -filter_complex "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]" -map "[v]" -map "[a]" target.mp4
```

**This is the code I'm running：**
```java
 public static void main(String[] args) {

        String inputFilePath = "test.mp4";
        String outputFilePath = "target.mp4";

        FFmpegLogCallback.set();

        try (FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputFilePath);
             FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputFilePath, 1);
        ) {
            grabber.setSampleMode(FrameGrabber.SampleMode.FLOAT);
            grabber.start();

            recorder.setImageWidth(grabber.getImageWidth());
            recorder.setImageHeight(grabber.getImageHeight());

            recorder.setFormat(grabber.getFormat());
            recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
            recorder.setFrameRate(grabber.getFrameRate());
            recorder.setVideoQuality(23);  // 0 ~ 23

            recorder.setAudioChannels(grabber.getAudioChannels());
            recorder.setSampleFormat(grabber.getSampleFormat());
            recorder.setSampleRate(grabber.getSampleRate());
            recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
            recorder.setAudioQuality(23);


            FFmpegFrameFilter filter = new FFmpegFrameFilter(
                    "[0:v]setpts=0.5*PTS[v]",
                    "[0:a]atempo=2[a]",
                    grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
            filter.setPixelFormat(grabber.getPixelFormat());
            filter.setSampleFormat(grabber.getSampleFormat());
            filter.setFrameRate(grabber.getFrameRate());
            filter.setSampleRate(grabber.getSampleRate());

            filter.start(); // An exception is thrown when executing this line of code
            recorder.start();

            Frame frame;
            while ((frame = grabber.grabFrame()) != null) {
                filter.push(frame);
                recorder.record(filter.pull(), filter.getPixelFormat());
            }

            filter.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```


**The following is the exception information：**
```java
Error: Output pad "default" with type video of the filter instance "setpts" of setpts not connected to any destination

org.bytedeco.javacv.FFmpegFrameFilter$Exception: avfilter_graph_config() error -22 (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe(FFmpegFrameFilter.java:410)
	at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:308)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:283)
```
@saudet

**Comment by saudet** [comment]
> **The command line statement expected to be implemented**
> 
> ```batchfile
> ffmpeg -i test.mp4 -filter_complex "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]" -map "[v]" -map "[a]" target.mp4
> ```

BTW, if that command does all you need, we can execute the ffmpeg program from Java very easily:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

> ```java
>                     "[0:v]setpts=0.5*PTS[v]",
>                     "[0:a]atempo=2[a]",
> ```

You'll need to remove `[0:v]`, `[v]`, `[0:a]`, and `[a]`. That's not currently supported by FFmpegFrameFilter, unless you are using multiple inputs.

**Comment by Hccake** [comment]
> > **The command line statement expected to be implemented**
> > ```batchfile
> > ffmpeg -i test.mp4 -filter_complex "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]" -map "[v]" -map "[a]" target.mp4
> > ```
> 
> BTW, if that command does all you need, we can execute the ffmpeg program from Java very easily: http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
> 
> > ```java
> >                     "[0:v]setpts=0.5*PTS[v]",
> >                     "[0:a]atempo=2[a]",
> > ```
> 
> You'll need to remove `[0:v]`, `[v]`, `[0:a]`, and `[a]`. That's not currently supported by FFmpegFrameFilter, unless you are using multiple inputs.

Thanks for your feedback，after i  remove [0:v], [v], [0:a], and [a]，the program does not throw an exception，But I didn't get the video right.

Audio playback speed correctly increased by 2 times, but the video is still playing at its original speed.

**Comment by saudet** [comment]
You'll need to set Frame.timestamp. We can't do anything related to time when all timestamps are 0!

**Comment by saudet** [comment]
Also, FFmpegFrameRecorder doesn't honor Frame.timestamp for historical reasons. Maybe that should be changed, but for now you'll need to call `recorder.setTimestamp(frame.timestamp)`, see issue https://github.com/bytedeco/javacv/issues/1724#issuecomment-981222186.

**Comment by Hccake** [comment]
> recorder.setTimestamp(frame.timestamp)

This does not work, add this statement and throw the following error

```java
Warning: [aac @ 00000204602fbc40] 2 frames left in the queue on closing

org.bytedeco.javacv.FFmpegFrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video packet. (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1312)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1075)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:955)
	at com.study.javacv.Demo.main(Demo.java:77)
	Suppressed: org.bytedeco.javacv.FFmpegFrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video packet. (For more details, make sure FFmpegLogCallback.set() has been called.)
		at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1312)
		at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1075)
		at org.bytedeco.javacv.FFmpegFrameRecorder.flush(FFmpegFrameRecorder.java:923)
		at org.bytedeco.javacv.FFmpegFrameRecorder.stop(FFmpegFrameRecorder.java:937)
		at org.bytedeco.javacv.FrameRecorder.close(FrameRecorder.java:408)
```

**Comment by saudet** [comment]
Like I said before: What's the error message that you get in the log?

**Comment by Hccake** [comment]
```cmd
Info: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:/tiktok/nainai.mp4':

Info:   Metadata:

Info:     major_brand     : 
Info: isom
Info: 

Info:     minor_version   : 
Info: 512
Info: 

Info:     compatible_brands: 
Info: isomiso2avc1mp41
Info: 

Info:     comment         : 
Info: vid:v0d00fg10000c6tgcibc77u8h3p2dtug
Info: 

Info:     encoder         : 
Info: Lavf58.45.100
Info: 

Info:   Duration: 
Info: 00:01:52.13
Info: , start: 
Info: 0.000000
Info: , bitrate: 
Info: 2830 kb/s
Info: 

Info:   Stream #0:0
Info: (und)
Info: : Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920 [SAR 1:1 DAR 9:16], 2695 kb/s
Info: , 
Info: 29.93 fps, 
Info: 30 tbr, 
Info: 15360 tbn, 
Info: 60 tbc
Info:  (default)
Info: 

Info:     Metadata:

Info:       handler_name    : 
Info: VideoHandler
Info: 

Info:       vendor_id       : 
Info: [0][0][0][0]
Info: 

Info:   Stream #0:1
Info: (und)
Info: : Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
Info:  (default)
Info: 

Info:     Metadata:

Info:       handler_name    : 
Info: SoundHandler
Info: 

Info:       vendor_id       : 
Info: [0][0][0][0]
Info: 

Warning: [libx264 @ 00000247f9d09bc0] -qscale is ignored, -crf is recommended.

Info: [libx264 @ 00000247f9d09bc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

Info: [libx264 @ 00000247f9d09bc0] profile High, level 4.0, 4:2:0, 8-bit

Info: [libx264 @ 00000247f9d09bc0] 264 - core 163 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=9 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

Info: Output #0, mp4, to 'E:/tiktok/demo.mp4':

Info:   Metadata:

Info:     encoder         : 
Info: Lavf58.76.100
Info: 

Info:   Stream #0:0
Info: : Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1080x1920, q=2-31, 400 kb/s
Info: , 
Info: 29.93 fps, 
Info: 50310 tbn, 
Info: 29.93 tbc
Info: 

Info:   Stream #0:1
Info: : Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 64 kb/s
Info: 

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Warning: [libx264 @ 00000247f9d09bc0] non-strictly-monotonic PTS

Error: [mp4 @ 00000247f9d08700] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 3362 >= 3362

Error: [mp4 @ 00000247f9d08700] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5043 >= 5043

Info: [libx264 @ 00000247f9d09bc0] frame I:1     Avg QP:17.30  size:  5303

Info: [libx264 @ 00000247f9d09bc0] frame P:1     Avg QP:18.37  size:   162

Info: [libx264 @ 00000247f9d09bc0] frame B:3     Avg QP:13.33  size:    77

Info: [libx264 @ 00000247f9d09bc0] consecutive B-frames: 20.0%  0.0%  0.0% 80.0%

Info: [libx264 @ 00000247f9d09bc0] mb I  I16..4: 49.0% 48.3%  2.7%

Info: [libx264 @ 00000247f9d09bc0] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.1%  0.0%  0.0%  0.0%  0.0%    skip:99.8%

Info: [libx264 @ 00000247f9d09bc0] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  0.1%  0.0%  0.0%  direct: 0.0%  skip:99.9%  L0: 9.5% L1:90.5% BI: 0.0%

Info: [libx264 @ 00000247f9d09bc0] 8x8 transform intra:48.3% inter:10.0%

Info: [libx264 @ 00000247f9d09bc0] coded y,uvDC,uvAC intra: 1.4% 0.2% 0.0% inter: 0.0% 0.0% 0.0%

Info: [libx264 @ 00000247f9d09bc0] i16 v,h,dc,p: 97%  1%  2%  0%

Info: [libx264 @ 00000247f9d09bc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 76%  5% 19%  0%  0%  0%  0%  0%  0%

Info: [libx264 @ 00000247f9d09bc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 56% 18% 13%  4%  2%  1%  1%  4%  1%

Info: [libx264 @ 00000247f9d09bc0] i8c dc,h,v,p: 99%  1%  1%  0%

Info: [libx264 @ 00000247f9d09bc0] Weighted P-Frames: Y:0.0% UV:0.0%

Info: [libx264 @ 00000247f9d09bc0] kb/s:454.60

Info: [aac @ 00000247f9d0b780] Qavg: 2714.000

Warning: [aac @ 00000247f9d0b780] 2 frames left in the queue on closing

org.bytedeco.javacv.FFmpegFrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video packet. (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1312)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1075)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:955)
	at com.study.javacv.Demo.main(Demo.java:76)
	Suppressed: org.bytedeco.javacv.FFmpegFrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video packet. (For more details, make sure FFmpegLogCallback.set() has been called.)
		at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1312)
		at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1075)
		at org.bytedeco.javacv.FFmpegFrameRecorder.flush(FFmpegFrameRecorder.java:923)
		at org.bytedeco.javacv.FFmpegFrameRecorder.stop(FFmpegFrameRecorder.java:937)
		at org.bytedeco.javacv.FrameRecorder.close(FrameRecorder.java:408)
		at com.study.javacv.Demo.main(Demo.java:83)
```

This is all the output from the console

**Comment by saudet** [comment]
> ```
> Error: [mp4 @ 00000247f9d08700] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 3362 >= 3362
> 
> Error: [mp4 @ 00000247f9d08700] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5043 >= 5043
> ```

There's the problem, that's not supported by FFmpeg. You'll need to fix this.

**Comment by Hccake** [comment]
```java
 while ((frame = grabber.grabFrame()) != null) {
                filter.push(frame);
                Frame filterFrame = filter.pull();
                if(filterFrame != null && (filterFrame.image != null || filterFrame.samples != null)){
                    //recorder.setTimestamp(filterFrame.timestamp);
                    recorder.record(filterFrame, filter.getPixelFormat());
                    // recorder.setTimestamp(filterFrame.timestamp);

                    System.out.println("======================");
                    System.out.println("frame timestamp：" + frame.timestamp);
                    System.out.println("filterFrame timestamp：" + filterFrame.timestamp);
                    System.out.println("recorder timestamp：" + recorder.getTimestamp());
                }
            }
```
```cmd
======================
frame timestamp：5503129
filterFrame timestamp：2716734
recorder timestamp：5346054
```

The Recorder timestamp does not follow the filterFrame timestamp , tt has to do with frameRate，
when I set frameRate to double, the recorder timestamp tends to the timestamp of the filterFrame .
```
recorder.setFrameRate(grabber.getFrameRate() * 2);
```
But changing the frame rate wasn't what I wanted

**Comment by saudet** [comment]
If you're not calling setTimestamp() you'll need to call setTimestamp(). See https://github.com/bytedeco/javacv/issues/1653#issuecomment-1001856815. Please call setTimestamp()!

**Comment by Hccake** [comment]
When i call setTimestamp(), the console output the following error:
```cmd
Error: [mp4 @ 000001b165ed8700] Application provided invalid, non monotonically increasing dts to muxer in stream 0: -1681 >= -1681

Error: [mp4 @ 000001b165ed8700] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1681 >= 1681
```
I don't know how to solve this problem

**Comment by saudet** [comment]
Like I said, you'll need to fix that by calling setTimestamp() with some other values that work. If you don't want to figure this out by yourself, it looks like the ffmpeg program already does something, maybe it simply drops those frames, I don't know, but you could simply use the ffmpeg program instead.

**Comment by Hccake** [comment]
Thanks for your help, I decided to use ffmpeg directly to deal with this problem

**Comment by saudet** [comment]
Why are you hesitant in using the ffmpeg program? It's really easy:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by Hccake** [comment]
> Why are you hesitant in using the ffmpeg program? It's really easy: http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

I needed to create a combination of filters based on some conditions, and it was difficult to concatenate commands using ffmPEG directly, but I've solved this problem perfectly using Jaffree.

**Comment by Hccake** [comment]
Javaav is also a great framework, but sadly I'm not very good at using it

**Comment by saudet** [comment]
Jaffree just calls the ffmpeg program, it doesn't do anything that we can't already do with the ffmpeg program. This has nothing to do with JavaCV. We could actually bundle Jaffree with JavaCV, but I'm not sure what would be the point. We can already do everything with the ffmpeg program anyway.

**Comment by Hccake** [comment]
Yes, Jaffree can't do anything FFMPEG can't.
But it has the advantage of abstracting FFMPEG commands, which makes it easier to understand from a coding standpoint.

**Comment by saudet** [comment]
I see. Actually, the JavaCPP Presets for FFmpeg and Jaffree are fully complimentary.
Something like this should just fine out of the box:
```java
     String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);
     FFmpeg.atPath(ffmpeg)...
```
This way, we don't need to have FFmpeg installed on the system.
