### ISSUE TITLE
java.lang.NoClassDefFoundError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [bytedeco/javacv#1663]
Hi, my apologies if this issue already been solved, but I tried everything without result, I'm trying to use the `FFmpegFrameRecorder` : 

```
  FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(videoPath, 320, 240);
  LinearLayout loadingLayout = findViewById(R.id.loadingLayout);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setFormat("mp4");
        recorder.setFrameRate(30);
        recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);

        try {
            recorder.start();
            for (int i = 0; i < 20; i++) {
                Frame frame = convertToFrame(ImageUtils.view2Bitmap(loadingLayout));
                recorder.record(frame);
                Thread.sleep(200);
            }

        } catch (FFmpegFrameRecorder.Exception | InterruptedException e) {
            e.printStackTrace();
        }
```

I've placed all .JAR files to the **Libs** folder as follows : 

![image](https://user-images.githubusercontent.com/24398682/122438273-7466c880-cf92-11eb-87ac-23f65c42da57.png)

Gradle : 
```
    implementation files('libs/opencv.jar')
    implementation files('libs/javacv.jar')
    implementation files('libs/javacpp.jar')
    implementation files('libs/ffmpeg.jar')
```

When I tried to run the app, I get this : 

```
 java.lang.NoClassDefFoundError: org.bytedeco.javacpp.avutil
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at org.bytedeco.javacpp.Loader.load(Loader.java:464)
        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
        at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:126)
        at maa.patpathelper.ui.MainActivity.initializeViews(MainActivity.java:94)
        at maa.patpathelper.ui.MainActivity.onCreate(MainActivity.java:71)
```

**Comment by saudet** [comment]
Please include ALL the JAR files in your class path.
