### ISSUE TITLE
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long org.bytedeco.ffmpeg.global.avutil.AV_NOPTS_VALUE

### ISSUE THREAD

**Issue by axepudding** [bytedeco/javacv#1667]
Hi

I need to combine multiple pictures to composite a video.I got some unsolvable problems when using JavaCV, I hope to get some help, thanks.
The error message I got was "couldn't find "libopenblas.so" at first , then I upgraded JavaCV to 1.5.5, and there are new error message as follow：
=================
Here is some error message that I'd get:
 java.lang.NoClassDefFoundError: org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1200)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
        at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.<clinit>(Write_packet_Pointer_BytePointer_int.java:21)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:335)
        at com.jues.mediemuxerlibrary.utils.test.MyUtils$1.run(MyUtils.java:60)
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long org.bytedeco.ffmpeg.global.avutil.AV_NOPTS_VALUE() (tried Java_org_bytedeco_ffmpeg_global_avutil_AV_1NOPTS_1VALUE and Java_org_bytedeco_ffmpeg_global_avutil_AV_1NOPTS_1VALUE__)
        at org.bytedeco.ffmpeg.global.avutil.AV_NOPTS_VALUE(Native Method)
        at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:270)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1200)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1148)
        at org.bytedeco.javacv.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:110)
========================================================================
This is the setting：
Android studio:4.2
Mac:macOS BigSur version 11.4
Android version：10
Mobile Devices:MI 8 Lite 、Mi 10S
In my Gradle:
dependencies {
     api group: 'org.bytedeco', name: 'javacv', version: '1.5.5'
        api group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-arm'
        api group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-x86'
        api group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.1-1.4.4', classifier: 'android-arm'
        api group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.1-1.4.4', classifier: 'android-x86'
}
===========================================================

**Comment by saudet** [comment]
Use "javacv-platform" instead of "javacv".

**Comment by axepudding** [comment]
> Use "javacv-platform" instead of "javacv".

   Thank you for your reply！
     Unfortunately, I tried as you said, got another error message, and I tried to fix it, but it still failed.I sincerely hope for your help in this issues,thank you very much.The error message is "More than one file was found with OS independent path 'lib/armeabi-v7a/libjniopencv_objdetect.so' ". 
Here is the gradle setting:
    packagingOptions{
      exclude 'META-INF/native-image/**'
        exclude 'lib/arm64-v8a/**'
        exclude 'lib/armeabi-v7a/**'
        exclude 'lib/x86/**'
        exclude 'lib/x86_64/**'
        exclude 'lib/armeabi-v7a/libjniopencv_objdetect.so'
        exclude 'lib/x86-v7a/libjniopencv_objdetect.so'
  } 

dependencies {
 api group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.5'
    api group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-arm'
    api group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-x86'
    api group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.1-1.4.4', classifier: 'android-arm'
    api group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.1-1.4.4', classifier: 'android-x86'
}

**Comment by saudet** [comment]
You'll probably need to remove the "exclude lib/..." lines.

**Comment by saudet** [comment]
Since you're using JavaCV 1.5.5, you will not be able to use the binaries from 1.4.4.
Please remove all the lines other than "javacv-platform" from your dependencies.

**Comment by axepudding** [comment]
> Since you're using JavaCV 1.5.5, you will not be able to use the binaries from 1.4.4.
> Please remove all the lines other than "javacv-platform" from your dependencies.

         Thank you so much for your help. Do as you said, but there is a new error message as follow:"__No implementation found for void org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate()  (tried Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate and Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate__)_"
I've searched the Internet, but there's nothing to refer to, and  I have tried several methods and still can’t solve it. Would you please do me a favor? Thank you.
     my grade setting:
        dependencies {
       //I've also tried to put  'org.bytedeco:javacv-platform:1.5.5' here and make the same error
        api 'org.bytedeco:javacv:1.5.5'
       }
     packagingOptions{
      // There is nothing, I've removed the "exclude lib/..." lines
   }

######### ### The error message:---Start-----##############################################
**### 2021-07-04 21:18:20.219 24325-24360/com.jues.vidoeandaudiomuxer E/Perf: Fail to get file list lib
2021-07-04 21:18:20.219 24325-24360/com.jues.vidoeandaudiomuxer E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-07-04 21:18:20.219 24325-24360/com.jues.vidoeandaudiomuxer E/Perf: Fail to get file list com.jues.vidoeandaudiomuxer
2021-07-04 21:18:20.219 24325-24360/com.jues.vidoeandaudiomuxer E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-07-04 21:18:20.220 24325-24360/com.jues.vidoeandaudiomuxer E/Perf: Fail to get file list com.jues.vidoeandaudiomuxer
2021-07-04 21:18:20.220 24325-24360/com.jues.vidoeandaudiomuxer E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-07-04 21:18:20.549 24325-24325/com.jues.vidoeandaudiomuxer E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
2021-07-04 21:18:20.549 24325-24325/com.jues.vidoeandaudiomuxer E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
2021-07-04 21:18:23.478 24325-24375/com.jues.vidoeandaudiomuxer E/oeandaudiomuxe: No implementation found for org.bytedeco.javacpp.Pointer org.bytedeco.javacpp.Loader.getJavaVM() (tried Java_org_bytedeco_javacpp_Loader_getJavaVM and Java_org_bytedeco_javacpp_Loader_getJavaVM__)
2021-07-04 21:18:23.482 24325-24375/com.jues.vidoeandaudiomuxer E/oeandaudiomuxe: No implementation found for void org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate() (tried Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate and Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate__)
    
    --------- beginning of crash
2021-07-04 21:18:23.483 24325-24375/com.jues.vidoeandaudiomuxer E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.jues.vidoeandaudiomuxer, PID: 24325
    java.lang.UnsatisfiedLinkError: No implementation found for void org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate() (tried Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate and Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate__)
        at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate(Native Method)
        at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.<init>(Write_packet_Pointer_BytePointer_int.java:24)
        at org.bytedeco.javacv.FFmpegFrameRecorder$WriteCallback.<init>(FFmpegFrameRecorder.java:313)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:329)
        at com.jues.mediemuxerlibrary.utils.test.MyUtils$1.run(MyUtils.java:62)
2021-07-04 21:18:23.486 24325-24375/com.jues.vidoeandaudiomuxer E/MQSEventManagerDelegate: failed to get MQSService.**

#########################The error message:---End-----###################################

**Comment by saudet** [comment]
Make sure that all the files in the `lib` subdirectory found in the JAR files are also in the final APK file. If your build system doesn't copy all the resources from the JAR files to the APK file for some reason, it will not work.

**Comment by saudet** [comment]
If you can give me a list of files you end up with in your APK, I can tell you which ones are missing.

**Comment by axepudding** [comment]
> Make sure that all the files in the `lib` subdirectory found in the JAR files are also in the final APK file. If your build system doesn't copy all the resources from the JAR files to the APK file for some reason, it will not work.

The first time I used Gradle Auto Integration and got these errors. Now I install it manually ，I get the same errors, I don't know which jar I missed importing or something else? Really looking forward to your reply and help, thank you！ 

Here's how I do it：
_A、 import the javacv.jar, javacpp.jar, opencv.jar, ffmpeg.jar into the libs package.
B、 Unzip the ffmpeg-android-arm.jar和opencv-android-arm.jar,
Then copy the .so files which from  the two jar file  into the armeabi-v7a package under the Android project libs._

The error message:
    "__No implementation found for void org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate()  (tried Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate and Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate__)_"

**Comment by saudet** [comment]
Doing it manually like that is going to be harder, but if you want to do it that way, you're still going to need to include all the JAR files. Adding just 6 or so of them isn't enough. Please copy all the JAR files.

**Comment by axepudding** [comment]
Sorry for the late reply. I imported all the JARs into the libs ,at first I put all the JARs in libs ,but it didn't work,noticed that there were duplicate packages. Then I removed the JARs  that do not support Android  . I still got the same  error message.
![image](https://user-images.githubusercontent.com/12405684/124690472-d8830980-df0c-11eb-8ceb-e266dcd2eb55.png)


The error message:
### "No implementation found for void org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate() (tried Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate and Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate)_"

**Comment by axepudding** [comment]
Sorry for the late reply. I imported all the JARs into the libs ,at first I put all the JARs in libs ,but it didn't work,noticed that there were duplicate packages. Then I removed the JARs  that do not support Android  . I still got the same  error message.
![image](https://user-images.githubusercontent.com/12405684/124690472-d8830980-df0c-11eb-8ceb-e266dcd2eb55.png)


The error message:
### "No implementation found for void org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate() (tried Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate and Java_org_bytedeco_ffmpeg_avformat_Write_1packet_1Pointer_1BytePointer_1int_allocate)_"

**Comment by saudet** [comment]
The libs are probably not in the right place. Like I said, if you can give
me the list of files that end up in the final APK, I will be able to tell
you what's missing.

**Comment by axepudding** [comment]
Hi ,This is my apk directory file
![image](https://user-images.githubusercontent.com/12405684/124711418-a2578100-df30-11eb-8598-e64ebf4bdcb6.png)

**Comment by saudet** [comment]
There is no "lib" directory in there, that's your problem. You'll need to figure out how to fix your build system to bundle the native libraries inside the "lib" directory, just like they are in the JAR files.

**Comment by axepudding** [comment]
OK，I‘ll check it .Thank you so much.

**Comment by saudet** [comment]
BTW, I've confirmed that this sample project for Android works fine, so if you're still having issues, please start with this:
https://github.com/bytedeco/sample-projects/tree/master/JavaCV-android-example
Please let me know if it doesn't work for you for some reason though.

**Comment by axepudding** [comment]
> works fine

Thank you so much for your help, I have learned a lot. As I said in the issue I submitted, at first I used the automatic integration 1.5.5 and found it didn't work, then I lowered it to 1.5.3 and it still didn't work, so I used the manual integration and unfortunately it still failed. Finally I chose to use automatic integration and changed the version to 1.4.2 and it finally worked!
