### ISSUE TITLE
Not compatible with spring on MacBook

### ISSUE THREAD

**Issue by flyhigher139** [bytedeco/javacv#1710]
I initialize a spring boot project with spring initializer, it works fine; 
Then I add javacv dependency to it, it failed with the following message.

But the above code javacv works fine with spring on Windows and Linux, you can test it yourself

```
2021-10-19 16:32:18.068  WARN 95163 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
```

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	.....

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager

......
```

I'll paste my pom file and full error message in the comment below.

**Comment by flyhigher139** [comment]
@saudet I tried  JavaCV 1.5.6, it does not work, either

**Comment by flyhigher139** [comment]
In java-cv `1.5.6`, I exclude `hibernate-validator` in `spring-boot-starter-web`，the problem could be solved.

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by chenqi146** [comment]
In java-cv 1.5.6, I exclude hibernate-validator in spring-boot-starter-web, but not.
```
aused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.validation.beanvalidation.MethodValidationPostProcessor]: Factory method 'methodValidationPostProcessor' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
```

**Comment by chenqi146** [comment]
The error message doesn't sound related to JavaCV.
![image](https://user-images.githubusercontent.com/36069431/144698648-8b567adf-2d73-413f-8b71-1729e13813f7.png)

But it dosen't work where related to JavaCV.
![image](https://user-images.githubusercontent.com/36069431/144698732-370e2848-e9a4-49d0-ae2d-31520198a8ec.png)

The same code only happens on  m1 macBook,  not linux and windows.

**Comment by YiuTerran** [comment]
same problem, any idea?

**Comment by YiuTerran** [comment]
I changed to run it on my Linux virtual machine(arm64), it's ok, but not a good solution.

**Comment by softwarebb** [comment]
@YiuTerran  Hi, did you find a good solution now, I got the same problems.

**Comment by ha-na-bi** [comment]
I also encountered the same issue. My application runs on both Windows and Linux machines, but it fails to run in a Docker container.

Eventually, I found that upgrading to **JDK 11** solves the problem! 

If you encounter the `java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter` error after the upgrade, please include the following dependencies:
```xml
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.1</version>
</dependency>
```
