### ISSUE TITLE
opencv_imgcodecs.imwrite NullPointerException

### ISSUE THREAD

**Issue by lzhpo** [bytedeco/javacv#1723]
Hello, I am saving the pictures at intervals of frames or seconds. There is no problem in a single thread, but when I write it as a multi-thread, some pictures can be successfully saved, but there are also some picture cannot be saved. 

May I ask what causes this problem? Thanks!

## Core code
```java
Frame frame = fFmpegFrameGrabber.grabImage();
final Mat mat = cvCoreMat.convertToMat(frame);
boolean result = opencv_imgcodecs.imwrite(cutImageFileAbsPath, mat);
```

## Exception
```java
java.lang.NullPointerException: Pointer address of argument 1 is NULL.
	at org.bytedeco.opencv.global.opencv_imgcodecs.imwrite(Native Method)
	at com.lzhpo.cv.convert.VideoCutAsyncTask.run(VideoCutAsyncTask.java:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
04:05:29.853 [video-cut-image-1] ERROR com.lzhpo.cv.convert.CvThreadFactory - video-cut-image-1 error!
java.lang.NullPointerException: null
	at org.bytedeco.javacv.OpenCVFrameConverter.isEqual(OpenCVFrameConverter.java:143)
	at org.bytedeco.javacv.OpenCVFrameConverter.convertToMat(OpenCVFrameConverter.java:152)
	at com.lzhpo.cv.convert.VideoCutAsyncTask.run(VideoCutAsyncTask.java:100)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```java
java.lang.RuntimeException: OpenCV(4.5.3) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.3\modules\imgcodecs\src\loadsave.cpp:739: error: (-215:Assertion failed) image.channels() == 1 || image.channels() == 3 || image.channels() == 4 in function 'cv::imwrite_'

	at org.bytedeco.opencv.global.opencv_imgcodecs.imwrite(Native Method)
	at com.lzhpo.cv.convert.VideoCutAsyncTask.run(VideoCutAsyncTask.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Dependency
```xml
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.5.6</version>
</dependency>
```

## Screenshot
It seems that the conversion of frame to mat failed, but sometimes it can succeed again!
The converter I use:
```java
final OpenCVFrameConverter.ToOrgOpenCvCoreMat cvCoreMat = new OpenCVFrameConverter.ToOrgOpenCvCoreMat();
```
![01](https://user-images.githubusercontent.com/42663571/143496358-cab9ec7e-f427-40a9-a465-c7db3ecd23df.png)
![02](https://user-images.githubusercontent.com/42663571/143496369-d638fbbe-110e-418e-bb8c-0ad6679d905d.png)

**Comment by saudet** [comment]
OpenCVFrameConverter is not thread safe. Make sure to use a new instance for each thread.

**Comment by kurihom123** [comment]
hi guys am facing a challenge in maven through spring boot application about  Cannot resolve com.lzhpo please any help

**Comment by lzhpo** [comment]
> hi guys am facing a challenge in maven through spring boot application about Cannot resolve com.lzhpo please any help

Hey, this is javacv project, you need use `org.bytedeco` in your maven groupId if you want use javacv.
