### ISSUE TITLE
avio_open2 error() error -13:

### ISSUE THREAD

**Issue by mohitsuppal** [bytedeco/javacv#1725]
2021-12-04 12:11:14.485 8438-8438/com.example.javacv W/.example.javacv: type=1400 audit(0.0:2244720): avc: denied { read } for name="sdcard" dev="tmpfs" ino=12475 scontext=u:r:untrusted_app:s0:c25,c258,c512,c768 tcontext=u:object_r:mnt_sdcard_file:s0 tclass=lnk_file permissive=0 app=com.example.javacv
2021-12-04 12:11:14.498 8438-8438/com.example.javacv W/System.err: org.bytedeco.javacv.FFmpegFrameRecorder$Exception: avio_open2 error() error -13: Could not open '/mnt/sdcard/stream.flv' (For more details, make sure FFmpegLogCallback.set() has been called.)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:893)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:413)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at com.example.javacv.RecordActivity.startRecording(RecordActivity.java:233)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at com.example.javacv.RecordActivity.onClick(RecordActivity.java:338)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.view.View.performClick(View.java:7505)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.view.View.performClickInternal(View.java:7477)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.view.View.access$3600(View.java:824)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.view.View$PerformClick.run(View.java:28669)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.os.Looper.loop(Looper.java:257)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8104)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-04 12:11:14.499 8438-8438/com.example.javacv W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
2021-12-04 12:11:14.500 8438-8438/com.example.javacv W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
2021-12-04 12:11:14.500 8438-8438/com.example.javacv W/RecordActivity: Start Button Pushed

**Comment by mohitsuppal** [comment]
**Manifest : -** 
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.javacv">

    <uses-sdk android:minSdkVersion="4" />

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-feature android:name="android.hardware.camera" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.JavaCV">
        <activity
            android:name=".RecordActivity"
            android:exported="true"
            android:screenOrientation="landscape">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Build.gradle :-** 

plugins {
    id 'com.android.application'
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.example.javacv"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'org.bytedeco:javacv:1.5.6'
    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.4-1.5.6', classifier: 'android-arm'
    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.4-1.5.6', classifier: 'android-x86'
    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.4-1.5.6', classifier: 'android-arm64'
    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.4-1.5.6', classifier: 'android-x86_64'
    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
error arises when I press record button

Note : - I grant all the permissions

**Comment by saudet** [comment]
> <uses-sdk android:minSdkVersion="4" />

You'll need at least 21 here.

**Comment by mohitsuppal** [comment]
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err: org.bytedeco.javacv.FFmpegFrameRecorder$Exception: **avio_open2 error() error -13: Could not open '/mnt/sdcard/stream.flv'** (For more details, make sure FFmpegLogCallback.set() has been called.)
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:893)
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:413)
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err:     at com.example.javacv.RecordActivity.startRecording(RecordActivity.java:233)
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err:     at com.example.javacv.RecordActivity.onClick(RecordActivity.java:338)
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err:     at android.view.View.performClick(View.java:7505)
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err:     at android.view.View.performClickInternal(View.java:7477)
2021-12-04 14:31:09.103 31606-31606/com.example.javacv W/System.err:     at android.view.View.access$3600(View.java:824)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at android.view.View$PerformClick.run(View.java:28669)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at android.os.Looper.loop(Looper.java:257)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8104)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
2021-12-04 14:31:09.104 31606-31606/com.example.javacv W/RecordActivity: Start Button Pushed

2021-12-04 14:31:09.093 31606-31606/com.example.javacv W/.example.javacv: type=1400 audit(0.0:2274748): **avc: denied { read } for name="sdcard" dev="tmpfs" ino=12475 scontext=u:r:untrusted_app:s0:c26,c258,c512,c768 tcontext=u:object_r:mnt_sdcard_file:s0 tclass=lnk_file permissive=0 app=com.example.javacv**

Error is still there......

**Comment by mohitsuppal** [comment]
My issue is resolved, I had to change the file's path value. (as I didn't have sdcard,so I had to use internal storage path instead of external storage path. )
