### ISSUE TITLE
Error: No such filter: 'boxblur'

### ISSUE THREAD

**Issue by ncepuwanghui** [bytedeco/javacv#1733]
ffmpeg version: 4.4
javacv version: 1.5.6
os: macos 11.6

javacv and ffmpeg version:
```
<os-name-arch>macosx-x86_64</os-name-arch>
<ffmpeg.version>4.4</ffmpeg.version>
<javacv.version>1.5.6</javacv.version>

<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv</artifactId>
    <version>${javacv.version}</version>
</dependency>
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>ffmpeg</artifactId>
    <version>${ffmpeg.version}-${javacv.version}</version>
    <classifier>${os-name-arch}</classifier>
</dependency>
```

code:
```
FFmpegFrameFilter frameFilter = new FFmpegFrameFilter("boxblur=10", frame.imageWidth, frame.imageHeight);
frameFilter.start();
frameFilter.push(frame);
Frame newFrame = frameFilter.pullImage();
```

error log:
```
Error: No such filter: 'boxblur'
org.bytedeco.javacv.FFmpegFrameFilter$Exception: avfilter_graph_parse_ptr() error -22 (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe(FFmpegFrameFilter.java:407)
	at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:308)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:283)
```

**Comment by ncepuwanghui** [comment]
The filter `delogo` has the same error.

**Comment by saudet** [comment]
Those filters will need to be enabled by updating somehow this build script for FFmpeg accordingly:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh
Contributions are welcome! If you give it a try, but encounter any issues, please let me know. I'll be here to help.

**Comment by saudet** [comment]
It looks like the delogo and boxblur filters are licensed under GPL. You will find those in the GPL builds, which you can get, for example, by adding a dependency like this, as indicated in the README.md file:
```xml
        <!-- Optional GPL builds with (almost) everything enabled -->
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>4.4-1.5.6</version>
        </dependency>
```
Enjoy! Please let me know if you encounter any issues with this though.
