### ISSUE TITLE
imshow:java.lang.RuntimeException: Unknown exception.

### ISSUE THREAD

**Issue by goldenduo** [bytedeco/javacv#1741]
My kotlin code:
```
import org.bytedeco.opencv.global.opencv_highgui.cvWaitKey
import org.bytedeco.opencv.global.opencv_highgui.imshow
import org.bytedeco.opencv.global.opencv_imgcodecs
import org.bytedeco.opencv.global.opencv_imgproc
import org.bytedeco.opencv.opencv_core.Size

object Smoother {
    fun smooth(filename: String?) {
        val image = opencv_imgcodecs.imread(filename)
        if (image != null) {
            opencv_imgproc.GaussianBlur(image, image, Size(3, 3), 0.0)
            opencv_imgcodecs.imwrite("test.png", image)
            imshow("test",image)
            cvWaitKey(0);
        }
    }
}
fun main(){
    Smoother.smooth("card.png")
}
```
But run with exception:
```
Exception in thread "main" java.lang.RuntimeException: Unknown exception.
	at org.bytedeco.opencv.global.opencv_highgui.imshow(Native Method)
	at Smoother.smooth(Main.kt:13)
	at MainKt.main(Main.kt:19)
	at MainKt.main(Main.kt)
```

**Comment by saudet** [comment]
I'm guessing you're trying to run that on Mac?
OpenCV HighGUI is not compatible with Java on Mac.
Please use CanvasFrame instead.

**Comment by goldenduo** [comment]
Thanks.
