### ISSUE TITLE
FIJI error with cvMatch_Template/Align slices in stack" plugin 

### ISSUE THREAD

**Issue by simone-1991** [bytedeco/javacv#1743]
I get the following error on my Desktop Fiji application when I run the "cvMatch_Template/Align slices in stack" plugin - 

(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 140MB of 12044MB (1%)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_core
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:994)
	at org.bytedeco.javacpp.Loader.load(Loader.java:951)
	at TemplateMatching.cvMatch_Template.doMatch(cvMatch_Template.java:232)
	at TemplateMatching.Align_slices.alignSlices(Align_slices.java:152)
	at TemplateMatching.Align_slices.run(Align_slices.java:107)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:265)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:243)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:748)

Can someone please help with why I am seeing the above error?

**Comment by saudet** [comment]
What are the JAR files in the class path?

**Comment by saudet** [comment]
Also, before using the plugin, please set the "org.bytedeco.javacpp.logger.debug" system property to "true", and copy/paste here the messages that you get from the log or on the console.

**Comment by NTssr-19** [comment]
I have exactly the same issue.

**Comment by saudet** [comment]
Please answer the questions above.

**Comment by NTssr-19** [comment]
I don't known if i understand what you mean by "JAR files" : Template_matching.jar; javacv.jar; opencv.jar; javacpp.jar; poencv-windows-x86_64.jar. 
The plugin worked few weeks ago... before christmas.

**Comment by simone-1991** [comment]
Hi All,

I could resolve the issue a week ago by updating the websites on Fiji updater as mentioned on the Template Matching plugin's website.

@NTssr-19 - if you are using a higher version of Java, the webpage recommends an extra step. I hope this works for you.
