### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.presets.javacpp

### ISSUE THREAD

**Issue by mohitsuppal** [bytedeco/javacv#1770]
I am developing an android app and have used following library to record videos, but getting following error - 

Fatal Exception: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.presets.javacpp
       at org.bytedeco.javacpp.Loader.load(Loader.java:211)
       at org.bytedeco.javacpp.Loader.load(Loader.java:1)
       at org.bytedeco.javacpp.Loader.load(Loader.java:11)
       at org.bytedeco.ffmpeg.avutil.LogCallback.<clinit>(LogCallback.java)
       at org.bytedeco.javacv.FFmpegLogCallback.set(FFmpegLogCallback.java)
       at android.app.Activity.performCreate(Activity.java:8099)
       at android.app.Activity.performCreate(Activity.java:8083)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3886)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8132)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

Gradle dependencies - 

    implementation 'org.bytedeco:javacv:1.5.6'
    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.4-1.5.6', classifier: 'android-arm'
    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.4-1.5.6', classifier: 'android-arm64'

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.7.

**Comment by mohitsuppal** [comment]
Error still not solved after updating version.

**Comment by saudet** [comment]
Add a dependency on javacv-platform or ffmpeg-platform.

**Comment by saudet** [comment]
Alternatively, you can also add the dependencies listed here: https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

**Comment by mohitsuppal** [comment]
it is still not working after adding the dependency for javacpp.....

**Comment by saudet** [comment]
It you have an x86 device, it won't work with the binaries for arm.

**Comment by mohitsuppal** [comment]
I have tried adding dependency for x86 and x86_64 platforms also......

**Comment by saudet** [comment]
Look at the log for more messages that could help

**Comment by saudet** [comment]
If you're not seeing any helpful messages in the log, make sure that the "org.bytedeco.javacpp.logger.debug" system property has been set to "true".

**Comment by Code-Lonely** [comment]
@saudet 
I also encountered this problem. Have you solved it

**Comment by Code-Lonely** [comment]
Here is my specific description of the problem
https://github.com/bytedeco/javacv/issues/1831

**Comment by saudet** [comment]
Make sure ProGuard is disabled: https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV
