### ISSUE TITLE
Error using dilate

### ISSUE THREAD

**Issue by MAOTIANSHAN** [bytedeco/javacv#1840]
```java
    //static{ System.loadLibrary(Core.NATIVE_LIBRARY_NAME); }

    public static void main(String[] args) throws IOException {
        String readPath = "C:\\Users\\admin\\Desktop\\test\\test\\aaa.png";
        String dilatePath = "C:\\Users\\admin\\Desktop\\test\\test\\dilateMask.jpg";
// code A
//        Mat mat = imread(readPath);
//        Mat kernel = Imgproc.getStructuringElement(Imgproc.MORPH_CROSS, new Size(10, 10));
//        Imgproc.dilate(mat, mat, kernel);
//        imwrite(dilatePath, mat);
// code B
        org.bytedeco.opencv.opencv_core.Mat mat = opencv_imgcodecs.imread(readPath);
        org.bytedeco.opencv.opencv_core.Mat kernel = getStructuringElement(MORPH_CROSS, new org.bytedeco.opencv.opencv_core.Size(3, 3));
        dilate(mat, mat,kernel);
        opencv_imgcodecs.imwrite(dilatePath, mat);
    }
Running code A (opencv) program is no problem, but running code B (javacv) reports an error:
Exception in thread "main" java.lang.RuntimeException: vector too long
	at org.bytedeco.opencv.global.opencv_ximgproc.dilate(Native Method)
	at com.deeplor.matting.controller.TestDilate.main(TestDilate.java:34)
```
ask for help

**Comment by saudet** [comment]
What you want to call are probably the `opencv_imgproc.getStructuringElement()` and `opencv_imgproc.dilate()` functions, and **NOT** the ones from the  opencv_ximgproc module.
