### ISSUE TITLE
FFmpegFramegrabber can't find x11grab

### ISSUE THREAD

**Issue by Nycrera** [bytedeco/javacv#1850]
Hi, I am trying to capture my screen using the x11grab on Manjaro Linux. My project is built with Maven and I do have dependencies such as javacv-platform. But for some reason when I try to use x11grab, I get the error:

```
org.bytedeco.javacv.FFmpegFrameGrabber$Exception:
av_find_input_format() error: Could not find input format "x11grab". (For more details, make sure FFmpegLogCallback.set() has been called.)
```

FFmpegLogCallback is set but that doesn't print any errors or anything at all.

I am trying to use it like this:
```java
		FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(":0.0");
		grabber.setFormat("x11grab");
		grabber.setFrameRate(30);
		grabber.setImageWidth(1920);
		grabber.setImageHeight(1080);
		grabber.start();
```

And the previously mentioned exception is thrown after the start is called.
I tried checking the ffmpeg, if x11grab is in the devices list or not like:

```java
	     String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);
	     ProcessBuilder pb = new ProcessBuilder(ffmpeg, "-hide_banner", "-devices");
	     try {
			pb.inheritIO().start().waitFor();
		} catch (Exception e1) {
			e1.printStackTrace();
		}
```
And got the result:

```
Devices:
 D. = Demuxing supported
 .E = Muxing supported
 --
 DE alsa            ALSA audio output
 DE fbdev           Linux framebuffer
 D  lavfi           Libavfilter virtual input device
 DE oss             OSS (Open Sound System) playback
 DE video4linux2,v4l2 Video4Linux2 output device
 D  x11grab         X11 screen capture, using XCB
```

What am I missing here?

**Comment by saudet** [comment]
"x11grab" is no longer available in FFmpeg 5.0, please use "xcbgrab" instead.

**Comment by Nycrera** [comment]
Thanks for the quick response but It seems that the error persists with the:
`av_find_input_format() error: Could not find input format "xcbgrab"`

I just replaced .setFormat("x11grab") with .setFormat("xcbgrab")
Do I need any other configurations?

And yeah, it seems that javacv uses the version 5.0:
`ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (GCC)`

**Comment by saudet** [comment]
There's a bug in JavaCV 1.5.7, see issue #1756, make sure to call FFmpegFrameGrabber.tryLoad() before creating an instance.

**Comment by Nycrera** [comment]
Hey, that makes sense.

So, calling FFmpegFrameGrabber.tryLoad() at the start of my app should solve this?
However, I have added loader first thing into my main, but I still get the same error.

```java
	public static void main(String[] args) {
		FFmpegLogCallback.set(); // Sets FFMpeg to direct its logs.
		try {
			FFmpegFrameGrabber.tryLoad();
		} catch (org.bytedeco.javacv.FFmpegFrameGrabber.Exception e1) {
			e1.printStackTrace();
		}
```

**Comment by Nycrera** [comment]
Here is how I produce this.
```java
	public static void main(String[] args) {
		try {
			FFmpegFrameGrabber.tryLoad();
			FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(":0.0");
			grabber.setFormat("xcbgrab");
			grabber.setFrameRate(30);
			grabber.setImageWidth(1920);
			grabber.setImageHeight(1080);
			grabber.start();
			
		} catch (org.bytedeco.javacv.FFmpegFrameGrabber.Exception e1) {
			e1.printStackTrace();
		}	
	}
```

**Comment by saudet** [comment]
It's possible libxcb isn't installed on your machine. Set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information about that on the console.

**Comment by Nycrera** [comment]
I have checked and I have libxcb-1.15-1 installed on my machine.
And the result of the debug:
```
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Loader
Debug: Loading /home/nycrera/.javacpp/cache/javacpp-1.5.7-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva.so.1
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so.1
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.57
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libswresample.so.4
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniswresample.so
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.59
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavcodec.so
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.59
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavformat.so
Debug: Loading class org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int
Debug: Registering org.bytedeco.javacv.FFmpegFrameGrabber$ReadCallback[address=0x7fd920b71c10,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920b71c10,deallocatorAddress=0x7fd8f808cdd0]]
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.ffmpeg.avformat.Seek_Pointer_long_int
Debug: Registering org.bytedeco.javacv.FFmpegFrameGrabber$SeekCallback[address=0x7fd920b90da0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920b90da0,deallocatorAddress=0x7fd8f808d1d0]]
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swscale
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swscale
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libswscale.so.6
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniswscale.so
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.ffmpeg.global.postproc
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.postproc
Debug: Loading /usr/lib64/libpostproc.so.56
Debug: Loading library jnipostproc
Debug: Failed to load for jnipostproc: java.lang.UnsatisfiedLinkError: no jnipostproc in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Debug: Loading class org.bytedeco.ffmpeg.global.swscale
Debug: Loading class org.bytedeco.ffmpeg.global.avfilter
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.ffmpeg.global.postproc
Debug: Loading class org.bytedeco.ffmpeg.global.swscale
Debug: Loading class org.bytedeco.ffmpeg.global.avfilter
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavfilter.so.8
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavfilter.so
Debug: Loading class org.bytedeco.ffmpeg.global.avdevice
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.ffmpeg.global.postproc
Debug: Loading class org.bytedeco.ffmpeg.global.swscale
Debug: Loading class org.bytedeco.ffmpeg.global.avfilter
Debug: Loading class org.bytedeco.ffmpeg.global.avdevice
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavdevice.so.59
Debug: Loading /home/nycrera/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavdevice.so
Debug: Opening org.bytedeco.javacpp.PointerScope@6ef888f6
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.ffmpeg.avformat.AVFormatContext
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.PointerPointer
Debug: Registering org.bytedeco.javacpp.PointerPointer[address=0x7fd920ba5400,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920ba5400,deallocatorAddress=0x7fd8da3b2700]]
Debug: Attaching org.bytedeco.javacpp.PointerPointer[address=0x7fd920ba5400,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920ba5400,deallocatorAddress=0x7fd8da3b2700]] to org.bytedeco.javacpp.PointerScope@6ef888f6
Debug: Registering org.bytedeco.javacpp.PointerPointer[address=0x7fd920ba5450,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920ba5450,deallocatorAddress=0x7fd8da3b2700]]
Debug: Attaching org.bytedeco.javacpp.PointerPointer[address=0x7fd920ba5450,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920ba5450,deallocatorAddress=0x7fd8da3b2700]] to org.bytedeco.javacpp.PointerScope@6ef888f6
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.avcodec.AVPacket
Debug: Registering org.bytedeco.ffmpeg.avcodec.AVPacket[address=0x7fd920ba55d0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920ba55d0,deallocatorAddress=0x7fd91fe48870]]
Debug: Attaching org.bytedeco.ffmpeg.avcodec.AVPacket[address=0x7fd920ba55d0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fd920ba55d0,deallocatorAddress=0x7fd91fe48870]] to org.bytedeco.javacpp.PointerScope@6ef888f6
Debug: Closing org.bytedeco.javacpp.PointerScope@6ef888f6
org.bytedeco.javacv.FFmpegFrameGrabber$Exception: av_find_input_format() error: Could not find input format "xcbgrab". (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:881)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:849)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:844)
	at com.alperen.streammod.App.main(App.java:20)
```

From these I can see that jnipostproc is missing, but other than that I can't see libxcb being registered or anything.

**Comment by saudet** [comment]
Ah, wait a minute, the FFmpeg device name is still "x11grab", so try to use that instead.

**Comment by Nycrera** [comment]
Yeah, It appears that was the case. It's all good now.
Thanks for the help.
