### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by Zeroxcv** [bytedeco/javacv#1859]
Why can the same jar package have no problems in windows and x86 architecture, but it will report errors in arm architecture.

the error:
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:468)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:462)

my maven:
<dependency>
	<groupId>org.bytedeco</groupId>
	<artifactId>javacv-platform</artifactId>
	<version>1.3.1</version>
</dependency>

**Comment by saudet** [comment]
We'll need to add builds for Windows
on ARM. Contributions welcome!
