### ISSUE TITLE
FFmpegFrameRecorder return error message when record encoded AVPacket

### ISSUE THREAD

**Issue by SonMinSang** [bytedeco/javacv#1861]
After I decoded the grabbed packets and encoded the decoded byte array to AVPacket, I attempted record the encoded packets.  It makes error code and recorded video did not play properly. But, when I tried recording the grabbed packets directly, it was work well.  

So I think I have a problem with the encoding process. I wonder what value should be added or what process should be added in encoded AVPacket.

I used 1.5.7 version of javacv-platform

```
 public static void main(String[] args) throws Exception {
        avutil.logCallback();
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://~~~/~~~");
        grabber.setFormat("rtsp");
        grabber.start();
        AVFormatContext context = grabber.getFormatContext();
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("C:\\test\\aaa.mp4", 1920, 1080, 0);
        recorder.start(context);
        AVPacket pkt = null;
        Long millis = System.currentTimeMillis();
        while (System.currentTimeMillis() - millis < 15000L) {
            pkt = grabber.grabPacket();
            Packet decoded = Decoding.decode(pkt);
            AVBufferRef av = pkt.buf();
            AVPacket packet = Encoding.encode(decoded.getData());
            packet.buf(av);
            recorder.recordPacket(packet);
        }
        recorder.flush();
        recorder.close();
}
```

```
 public static AVPacket encode(byte[] data){
        AVPacket avPacket = av_packet_alloc();

        int size = Utils.byteToInt(data, Utils.SIZE_FIELD);
        int stream_index = Utils.byteToInt(data, Utils.STREAM_INDEX_FIELD);
        long dts = Utils.byteToLong(data, Utils.DTS_FIELD);
        long pts = Utils.byteToLong(data, Utils.PTS_FIELD);
        int flag = Utils.byteToInt(data, Utils.FLAGS_FIELD);
        long pos = Utils.byteToLong(data, Utils.POS_FIELD);

        byte content[] = new byte[size];

        System.arraycopy(data, Utils.DATA_OFFSET, content, 0, size);
        BytePointer bp = new BytePointer(content);
        bp.capacity(content.length);
        avPacket.data(bp);
        avPacket.size(content.length);
        avPacket.pts(pts);
        avPacket.dts(dts);
        avPacket.flags(flag);
        avPacket.pos(pos);
        avPacket.stream_index(stream_index);
        avPacket.duration(3000);
        avPacket.position(0);
        avPacket.capacity(1);
        return avPacket;
    }

```

> Input #0, rtsp, from 'rtsp://~~~/~~~':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.066667, bitrate: N/A
  Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn
Output #0, mp4, to 'C:\test\aaa.mp4':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, q=2-31, 30 fps, 15360 tbn

> [mp4 @ 0000029a2d689e80] Application provided duration: 12297829382474058 / timestamp: 1024 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value
[mp4 @ 0000029a2d689e80] Application provided duration: 12297829382474569 / timestamp: 1536 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value
[mp4 @ 0000029a2d689e80] Application provided duration: 12297829382475080 / timestamp: 2048 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value
[mp4 @ 0000029a2d689e80] Application provided duration: 12297829382475591 / timestamp: 2560 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value
[mp4 @ 0000029a2d689e80] Application provided duration: 12297829382476102 / timestamp: 3072 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value
[mp4 @ 0000029a2d689e80] Application provided duration: 12297829382476613 / timestamp: 3584 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value
[mp4 @ 0000029a2d689e80] Application provided duration: 12297829382477124 / timestamp: 4096 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value
[mp4 @ 0000029a2d689e80] Application provided duration: 12297829382477635 / timestamp: 4608 is out of range for mov/mp4 format
[mp4 @ 0000029a2d689e80] pts has no value

**Comment by saudet** [comment]
What happens if you use grabFrame() and recordFrame() instead?

**Comment by SonMinSang** [comment]
When I use record() instead of recordFrame(),  it return error message.

> _Input #0, rtsp, from 'rtsp://~~~/~~~':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.066667, bitrate: N/A
  Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn
Output #0, mp4, to 'C:\test\aaa.mp4':
  Metadata:
    encoder         : Lavf59.1

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.bytedeco.ffmpeg.avutil.AVFrame.linesize()" because "this.tmp_picture" is null
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1021)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:961)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:954)
	at rtsp.Test.main(Test.java:51)

6.100
  Stream #0:0: Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, q=2-31, 30 fps, 15360 tbn_

**Comment by saudet** [comment]
You'll need to call start() before calling record().

**Comment by SonMinSang** [comment]
I'm sorry to keep bothering you.... But, as you can see from the code in the question, I did it..

**Comment by saudet** [comment]
You did not provide your code, please provide it.

**Comment by SonMinSang** [comment]
**Main method**
```
public static void main(String[] args) throws Exception {
        avutil.logCallback();
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://~~~/~~~");
        grabber.setFormat("rtsp");
        grabber.start();
        AVFormatContext context = grabber.getFormatContext();
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("C:\\test\\aaa.mp4", 1920, 1080, 0);
        recorder.start(context);
        AVPacket pkt = null;
        Long millis = System.currentTimeMillis();
        while (System.currentTimeMillis() - millis < 15000L) {
            pkt = grabber.grabPacket();
            Packet encoded = Encoding.encode(pkt); // encoding to save packets in database
            AVBufferRef av = pkt.buf();
            AVPacket packet = Decoding.decode(encoded.getData()); // decoding to record
            packet.buf(av);
            recorder.recordPacket(packet);
        }

        recorder.flush();
        recorder.close();
    }

```

**Decoding.decode()**
```
 public static AVPacket decode(byte[] data){
        AVPacket avPacket = av_packet_alloc();

        int size = Utils.byteToInt(data, Utils.SIZE_FIELD);
        int stream_index = Utils.byteToInt(data, Utils.STREAM_INDEX_FIELD);
        long dts = Utils.byteToLong(data, Utils.DTS_FIELD);
        long pts = Utils.byteToLong(data, Utils.PTS_FIELD);
        int flag = Utils.byteToInt(data, Utils.FLAGS_FIELD);
        long pos = Utils.byteToLong(data, Utils.POS_FIELD);

        byte content[] = new byte[size];

        System.arraycopy(data, Utils.DATA_OFFSET, content, 0, size);
        BytePointer bp = new BytePointer(content);
        bp.capacity(content.length);
        avPacket.data(bp);
        avPacket.size(content.length);
        avPacket.pts(pts);
        avPacket.dts(dts);
        avPacket.flags(flag);
        avPacket.pos(pos);
        avPacket.stream_index(stream_index);
        avPacket.duration(3000);
        avPacket.position(0);
        avPacket.capacity(1);
        return avPacket;
    }

```

**Encoding.encode()**
```
public static Packet encode(AVPacket pkt) {
        if (pkt != null) {
            BytePointer data = pkt.data();
            data.capacity((long)pkt.size());
            byte[] content = data.getStringBytes();
            int size = pkt.size();
            long pts = pkt.pts();
            long dts = pkt.dts();
            int flag = pkt.flags();
            int stream_index = pkt.stream_index();
            long pos = pkt.pos();
            byte[] result = new byte[size + 36];
            result[0] = (byte)(size >>> 24);
            result[1] = (byte)(size >>> 16);
            result[2] = (byte)(size >>> 8);
            result[3] = (byte)(size >>> 0);
            Utils.intToByte(result, 4, stream_index);
            Utils.intToByte(result, 24, flag);
            Utils.longToByte(result, 8, dts);
            Utils.longToByte(result, 16, pts);
            Utils.longToByte(result, 28, pos);
            System.arraycopy(content, 0, result, 36, size);
            return new Packet(System.currentTimeMillis(), flag != 0, result);
        } else {
            return null;
        }
    }
```

**Test code for grabFrame() and record()**
```
public static void main(String[] args) throws Exception {
        avutil.logCallback();
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://~~~/~~~");
        grabber.setFormat("rtsp");
        grabber.start();
        AVFormatContext context = grabber.getFormatContext();
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("C:\\test\\aaa.mp4", 1920, 1080, 0);
        recorder.start(context);
        Frame frame = null;
        Long millis = System.currentTimeMillis();
        while (System.currentTimeMillis() - millis < 15000L) {
            frame = grabber.grabFrame();
            recorder.record(frame );
        }
        recorder.flush();
        recorder.close();
}
```

**Comment by saudet** [comment]
> recorder.start(context);

You'll need to call start(), not start(context).

**Comment by SonMinSang** [comment]
Thank you @saudet. However, when this method is used, the video quality is inferior to that of the method using grabpacket(). Is there a way to resolve this issue while maintaining grabPacket()?

**Comment by saudet** [comment]
It sounds like we need to set the pts field on those AVPacket.

**Comment by SonMinSang** [comment]
So, when I made a new packet, I put the pts and dts of the packet that I received as grabPacket(). However, when I checked the timestamp of the created video with ffprobe, the duration was too small even though the frame rate was 30.

![image](https://user-images.githubusercontent.com/74538618/182768854-8a7810f6-bacf-4de3-aaba-187aab3806ed.png)

**Comment by saudet** [comment]
BTW, it might be easier to do what you need to do using the ffmpeg program instead:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by SonMinSang** [comment]
Thank you for your continued concern. And I'm sorry for the constant questions. However, streams are currently coming in through self-produced rtsp servers. If this stream goes through ffmpeg one more, the quality of the video gets worse. And packet data will be stored in the database in byte array format and used again later. So I think I should implement the code in the way I'm currently doing. In this case, is there a way or an example to change the timebase of the stream from the rtsp server to the timebase suitable for mp4 when recording?

**Comment by saudet** [comment]
I don't have an answer for you, but @alicanalbayrak might be able to help you

**Comment by SonMinSang** [comment]
This problem was solved using grabber.setTimestamp(); Thank you for trying to solve the question!!
