### ISSUE TITLE
Loading native ffmpeg not working

### ISSUE THREAD

**Issue by Ashesh3** [bytedeco/javacv#1910]
Related to #1874

@saudet Thank you for the instructions on the above issue, unfortunately I can't seem to get it work on my machine. I have a working ffmpeg with all the required DLLs, even then it fails to load them and falls back to the inbuilt libraries.

```
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Loader
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-locale-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-string-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-stdio-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-math-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-heap-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-runtime-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-convert-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-environment-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-time-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-filesystem-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-utility-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-multibyte-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-conio-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-private-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-crt-process-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-console-l1-2-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-string-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-errorhandling-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-timezone-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-file-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-namedpipe-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-handle-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-file-l2-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-heap-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-libraryloader-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-synch-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-processthreads-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-processenvironment-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-datetime-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-localization-l1-2-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-sysinfo-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-synch-l1-2-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-console-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-debug-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-rtlsupport-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-processthreads-l1-1-1.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-file-l1-2-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-profile-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-memory-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-util-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\api-ms-win-core-interlocked-l1-1-0.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\ucrtbase.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\vcruntime140.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\vcruntime140_1.dll
Debug: Loading D:\Program Files\Java\jdk-18.0.1.1\bin\msvcp140.dll
Debug: Loading C:\WINDOWS\system32\msvcp140_1.dll
Debug: Loading C:\WINDOWS\system32\concrt140.dll
Debug: Loading C:\WINDOWS\system32\vcomp140.dll
Debug: Loading C:\Users\Ash\.javacpp\cache\Project.jar\org\bytedeco\javacpp\windows-x86_64\jnijavacpp.dll
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading C:\Users\Ash\ffmpeg\avutil-57.dll
Debug: Loading library avutil
Debug: Failed to load for avutil@.57: java.lang.UnsatisfiedLinkError: no avutil in java.library.path: D:\Program Files\Java\jdk-18.0.1.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Ash\ffmpeg\;.
Debug: Loading C:\Users\Ash\.javacpp\cache\Project.jar\org\bytedeco\ffmpeg\windows-x86_64\jniavutil.dll
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading C:\Users\Ash\ffmpeg\swresample-4.dll
Debug: Loading library swresample
Debug: Failed to load for swresample@.4: java.lang.UnsatisfiedLinkError: no swresample in java.library.path: D:\Program Files\Java\jdk-18.0.1.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Ash\ffmpeg\;.
Debug: Loading C:\Users\Ash\.javacpp\cache\Project.jar\org\bytedeco\ffmpeg\windows-x86_64\jniswresample.dll
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading C:\Users\Ash\ffmpeg\avcodec-59.dll
Debug: Loading library avcodec
Debug: Failed to load for avcodec@.59: java.lang.UnsatisfiedLinkError: no avcodec in java.library.path: D:\Program Files\Java\jdk-18.0.1.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Ash\ffmpeg\;.
Debug: Loading C:\Users\Ash\.javacpp\cache\Project.jar\org\bytedeco\ffmpeg\windows-x86_64\jniavcodec.dll
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading C:\Users\Ash\ffmpeg\avformat-59.dll
Debug: Loading library avformat
Debug: Failed to load for avformat@.59: java.lang.UnsatisfiedLinkError: no avformat in java.library.path: D:\Program Files\Java\jdk-18.0.1.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Ash\ffmpeg\;.
Debug: Loading C:\Users\Ash\.javacpp\cache\Project.jar\org\bytedeco\ffmpeg\windows-x86_64\jniavformat.dll
Debug: Loading class org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int
Debug: Registering org.bytedeco.javacv.FFmpegFrameGrabber$ReadCallback[address=0x1ecbd36dc80,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36dc80,deallocatorAddress=0x6abc75d0]]
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.ffmpeg.avformat.Seek_Pointer_long_int
Debug: Registering org.bytedeco.javacv.FFmpegFrameGrabber$SeekCallback[address=0x1ecbd36da80,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36da80,deallocatorAddress=0x6abc77f0]]
Debug: Opening org.bytedeco.javacpp.PointerScope@79250ca5
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.global.avformat
Debug: Loading class org.bytedeco.ffmpeg.avformat.AVFormatContext
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.PointerPointer
Debug: Registering org.bytedeco.javacpp.PointerPointer[address=0x1ecbd36eea0,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36eea0,deallocatorAddress=0x6fe7aae0]]
Debug: Attaching org.bytedeco.javacpp.PointerPointer[address=0x1ecbd36eea0,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36eea0,deallocatorAddress=0x6fe7aae0]] to org.bytedeco.javacpp.PointerScope@79250ca5
Debug: Registering org.bytedeco.javacpp.PointerPointer[address=0x1ecbd36eef0,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36eef0,deallocatorAddress=0x6fe7aae0]]
Debug: Attaching org.bytedeco.javacpp.PointerPointer[address=0x1ecbd36eef0,position=0,limit=8,capacity=8,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36eef0,deallocatorAddress=0x6fe7aae0]] to org.bytedeco.javacpp.PointerScope@79250ca5
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec
Debug: Loading class org.bytedeco.ffmpeg.avcodec.AVPacket
Debug: Registering org.bytedeco.ffmpeg.avcodec.AVPacket[address=0x1ecbd36ef40,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36ef40,deallocatorAddress=0x6a1c1500]]
Debug: Attaching org.bytedeco.ffmpeg.avcodec.AVPacket[address=0x1ecbd36ef40,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x1ecbd36ef40,deallocatorAddress=0x6a1c1500]] to org.bytedeco.javacpp.PointerScope@79250ca5
Debug: Closing org.bytedeco.javacpp.PointerScope@79250ca5
Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: av_find_input_format() error: Could not find input format "lavfi". (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:881)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:849)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:844)
        at com.myproject.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)
```
Format: `lavfi`
Input: `ddagrab`

My custom ffmpeg is just the official ffmpeg built from source on master branch. (Includes the new [ddagrab](http://ffmpeg.org/ffmpeg-all.html#toc-ddagrab)) 

![image](https://user-images.githubusercontent.com/3626859/196042922-dbc2946c-ac70-41b9-9e91-a9f084ff4dbb.png)

Running ffmpeg directly from my terminal works:
```
C:\Users\Ash>ffmpeg -f lavfi -i ddagrab -c:v h264_nvenc -cq 18 output.mp4
ffmpeg version N-108654-gfd5c273f26-20221016 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20221016
  libavutil      57. 39.101 / 57. 39.101
  libavcodec     59. 50.101 / 59. 50.101
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.101 /  8. 49.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, lavfi, from 'ddagrab':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, d3d11, 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1000k tbn
File 'output.mp4' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
Output #0, mp4, to 'output.mp4':
  Metadata:
    encoder         : Lavf59.34.101
  Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), d3d11(pc, gbr/bt709/iec61966-2-1, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc59.50.101 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 4000000 vbv_delay: N/A
frame=  474 fps=205 q=13.0 Lsize=    1080kB time=00:00:15.66 bitrate= 564.9kbits/s dup=445 drop=3 speed=6.76x
video:1076kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.428641%
```

**Comment by saudet** [comment]
The DLLs need to be from the same version of FFmpeg. If you can't get that, you'll need to build the JNI libraries from source as well: https://github.com/bytedeco/javacpp-presets#build-instructions

**Comment by Ashesh3** [comment]
> The DLLs need to be from the same version of FFmpeg. If you can't get that, you'll need to build the JNI libraries from source as well: https://github.com/bytedeco/javacpp-presets#build-instructions

Makes sense, thanks.
