### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniavutil.so" not found while using FFmpegFrameRecorder

### ISSUE THREAD

**Issue by s2g090123** [bytedeco/javacv#1911]
When I use FFmpegFrameRecorder, I have this problem.
```
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(...)
```

platform: android
environment: mac os m2
device: android studio emulator

gradle
```
implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.7'
```

logcat
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniavutil.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1800)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1402)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
        at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1269)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
        at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.<clinit>(Write_packet_Pointer_BytePointer_int.java:21)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:336)
```

Please let me know if further information is required, thank you

**Comment by saudet** [comment]
Please add a dependency on javacv-platform

**Comment by saudet** [comment]
For Android with Gradle, using a task like javacppExtract works best: 
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin
