### ISSUE TITLE
grabber.start() loop Throwing OutOfMemoryError

### ISSUE THREAD

**Issue by s894792409** [bytedeco/javacv#1922]
Hello, I use FFmpegFrameGrabber to read a big video(397M,10s,mov format). When calling grabber.start(), it is blocked all the time. Cyclically print 'Throwing OutOfMemoryError' and 'Starting a blocking GC Alloc' without stopping or throwing exceptions. How do I solve this problem? My version is 1.5.7,on Android.

`grabber = new FFmpegFrameGrabber(fileInputStream);
                grabber.start();
recorder = new FFmpegFrameRecorder(outPath, grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
                //设置输出的视频参数与原视频相同
                recorder.setFrameRate(grabber.getFrameRate());
                recorder.setVideoBitrate(grabber.getVideoBitrate());
                recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
                recorder.setAudioBitrate(grabber.getAudioBitrate());
                recorder.setAudioCodec(grabber.getAudioCodec());
                recorder.setSampleRate(grabber.getSampleRate());
                recorder.start();
`

log:
` Starting a blocking GC Alloc
09:47:42.504     I  Alloc concurrent copying GC freed 3(16KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 269MB/293MB, paused 90us total 54.308ms
09:47:42.504     I  Forcing collection of SoftReferences for 512MB allocation
09:47:42.504     I  Starting a blocking GC Alloc
09:47:42.752     I  Alloc concurrent copying GC freed 6(16KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 269MB/293MB, paused 83us total 248.210ms
09:47:42.753     W  Throwing OutOfMemoryError "Failed to allocate a 536870928 byte allocation with 25165824 free bytes and 242MB until OOM, target footprint 307650936, growth limit 536870912" (VmSize 8224484 kB)
09:47:42.753 System.err   com.hbbc.spzzzj    W  Error on InputStream.reset() or skip(): java.lang.OutOfMemoryError: Failed to allocate a 536870928 byte allocation with 25165824 free bytes and 242MB until OOM, target footprint 307650936, growth limit 536870912
09:47:42.753     I  Starting a blocking GC Alloc
09:47:42.753     I  Starting a blocking GC Alloc
09:47:42.767     I  Alloc young concurrent copying GC freed 23(46KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 269MB/293MB, paused 98us total 14.144ms
09:47:42.767     I  Starting a blocking GC Alloc
09:47:42.822     I  Alloc concurrent copying GC freed 6(16KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 269MB/293MB, paused 99us total 54.765ms
09:47:42.822     I  Forcing collection of SoftReferences for 512MB allocation
09:47:42.822     I  Starting a blocking GC Alloc
09:47:43.071     I  Alloc concurrent copying GC freed 37(17KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 269MB/293MB, paused 87us total 249.032ms
09:47:43.072     W  Throwing OutOfMemoryError "Failed to allocate a 536870924 byte allocation with 25165824 free bytes and 242MB until OOM, target footprint 307634552, growth limit 536870912" (VmSize 8222436 kB)
09:47:43.072     I  Starting a blocking GC Alloc
09:47:43.072     I  Starting a blocking GC Alloc`

**Comment by saudet** [comment]
Set the maximumSize to 0.

**Comment by s894792409** [comment]
> 

if set maximumSize to 0. Call grabber Grab() will throw an exception

**Comment by s894792409** [comment]
> if set maximumSize to 0. Call grabber Grab() will throw an exception

I'm sorry, I remember wrong No exception is thrown, but the video generation will be unsuccessful, because I need to transcode the video. It seems that the frame cannot be captured after setting to 0. If a value greater than 0 is set, the Throwing OutOfMemoryError will still be printed circularly, but after a period of time, an exception will be thrown to exit

**Comment by saudet** [comment]
That probably means you're trying to use a format like avi or mp4 that
doesn't support streams very well. Try to use another format like flv or
mkv.

**Comment by s894792409** [comment]
> 这可能意味着您正在尝试使用像avi或mp4这样的格式 不太支持流。尝试使用其他格式，如 flv 或 MKV。

It may be, but I need to convert any format video to MP4 format, or compress the size. Any video may be imported here, so what should I do? Is there any way to stop or solve the problem after OOM is detected

**Comment by saudet** [comment]
That means you'll need to ability to seek on the file system, which isn't something that the InputStream interface can support. You'll need to use a File instead.

**Comment by saudet** [comment]
Actually, it should be possible to implement an InputStream based on MappedByteBuffer. You might want to try to do that.

**Comment by s894792409** [comment]
> Actually, it should be possible to implement an InputStream based on MappedByteBuffer. You might want to try to do that.

Ok, I get it now, thanks！I'm try use file instead,but after running normally for a while, an exception is thrown

log:
` D  --- Failed to create image decoder with message 'unimplemented'
11:48:11.348 DRM/D...oder     D  decodeDrmImageIfNeeded: header = [B@727775c
11:48:11.348 DRM/D...oder     D  decodeDrmImageIfNeeded: [0][0][68][91][109]
11:48:11.348 DRM/D...oder     D  decodeDrmImageIfNeeded: headerSize = 0
11:48:11.348 DRM/D...oder     D  decodeDrmImageIfNeeded: after header = [B@f540a65
11:48:11.368 DRM_D..._JNI     D  nativeDecryptDcfFile: size = 4768164, action = 1
11:48:11.369 DRM_D..._JNI     D  nativeDecryptDcfFile: openDecryptSession with offset = 0
11:48:11.373 DRM_D..._JNI     E  nativeDecryptDcfFile: failed to openDecryptSession, trigger showDrmDialogIfNeed
11:48:11.385 DRM/D...oder     E  decodeDrmImage native decrypt failed 
11:48:11.388 skia             D  --- Failed to create image decoder with message 'unimplemented'
11:48:11.388 DRM/D...oder     D  decodeDrmImageIfNeeded: header = [B@727775c
11:48:11.388 DRM/D...oder     D  decodeDrmImageIfNeeded: [0][0][68][91][109]
11:48:11.388 DRM/D...oder     D  decodeDrmImageIfNeeded: headerSize = 0
11:48:11.388 DRM/D...oder     D  decodeDrmImageIfNeeded: after header = [B@111633a
11:48:11.391 com.h...pzzz     I  Background concurrent copying GC freed 87573(5261KB) AllocSpace objects, 30(49MB) LOS objects, 27% free, 63MB/87MB, paused 5.546ms total 243.622ms
11:48:11.398 DRM_D..._JNI     D  nativeDecryptDcfFile: size = 4768164, action = 0
11:48:11.399 DRM_D..._JNI     D  nativeDecryptDcfFile: openDecryptSession with offset = 0
11:48:11.402 DRM_D..._JNI     E  nativeDecryptDcfFile: failed to openDecryptSession, trigger showDrmDialogIfNeed
11:48:11.411 DRM/D...oder     E  decodeDrmImage native decrypt failed 
11:48:11.436 skia             D  --- Failed to create image decoder with message 'unimplemented'
11:48:11.436 DRM/D...oder     D  decodeDrmImageIfNeeded with fd
11:48:11.436 DRM_D..._JNI     D  nativeDecryptDcfFile: size = 0, action = 1
11:48:11.438 DRM_D..._JNI     D  nativeDecryptDcfFile: openDecryptSession with offset = 0
11:48:11.440 DRM_D..._JNI     E  nativeDecryptDcfFile: failed to openDecryptSession, trigger showDrmDialogIfNeed
11:48:11.442 DRM/D...oder     E  decodeDrmImage native decrypt failed 
11:48:11.447 skia             D  --- Failed to create image decoder with message 'unimplemented'
11:48:11.447 DRM/D...oder     D  decodeDrmImageIfNeeded with fd
11:48:11.447 DRM_D..._JNI     D  nativeDecryptDcfFile: size = 0, action = 0
11:48:11.457 DRM_D..._JNI     D  nativeDecryptDcfFile: openDecryptSession with offset = 0
11:48:11.461 DRM_D..._JNI     E  nativeDecryptDcfFile: failed to openDecryptSession, trigger showDrmDialogIfNeed
11:48:11.471 DRM/D...oder     E  decodeDrmImage native decrypt failed 
11:48:11.495 BpBinder         W  Slow Binder: BpBinder transact took 419 ms, interface=android.media.IMediaMetadataRetriever, code=3 oneway=false
11:48:11.672 BpBinder         W  Slow Binder: BpBinder transact took 371 ms, interface=android.media.IMediaMetadataRetriever, code=3 oneway=false
11:48:11.698 BpBinder         W  Slow Binder: BpBinder transact took 219 ms, interface=android.media.IMediaMetadataRetriever, code=3 oneway=false
11:48:11.959 BpBinder         W  Slow Binder: BpBinder transact took 242 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
11:48:12.733 LOG              E  org.bytedeco.javacv.FFmpegFrameRecorder$Exception: avcodec_send_frame() error -541478725: Error sending a video frame for encoding. (For more details, make sure FFmpegLogCallback.set() has been called.)
                                                	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1056)
                                                	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:961)
                                                	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:954)
`

**Comment by saudet** [comment]
> (For more details, make sure FFmpegLogCallback.set() has been called.)

**Comment by s894792409** [comment]
> > (For more details, make sure FFmpegLogCallback.set() has been called.)

more details:
`
Create ARC handle: 0xb400007d11de7540
13:12:43.751 BpBinder         W  Slow Binder: BpBinder transact took 368 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
13:12:43.752 Media...rJNI     E  getFrameAtTime: videoFrame is a NULL pointer
13:12:43.915 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] using cpu capabilities: ARMv8 NEON
13:12:43.939 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] profile High, level 6.2, 4:2:0, 8-bit
13:12:43.939 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] 264 - core 163 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=333270 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
13:12:43.956 System.err       W  Info: Output #0, mp4, to '/storage/emulated/0/spzzzj/out/42/2022年11月03日13点12分42秒.mp4':
13:12:43.956 System.err       W  Info:   Metadata:
13:12:43.956 System.err       W  Info:     encoder         : 
13:12:43.957 System.err       W  Info: Lavf59.16.100
13:12:43.957 System.err       W  Info: 
13:12:43.957 System.err       W  Info:   Stream #0:0
13:12:43.957 System.err       W  Info: : Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, q=2-31, 333270 kb/s
13:12:43.957 System.err       W  Info: , 
13:12:43.957 System.err       W  Info: 30 fps, 
13:12:43.957 System.err       W  Info: 15360 tbn
13:12:43.957 System.err       W  Info: 
13:12:44.104 BpBinder         W  Slow Binder: BpBinder transact took 290 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
13:12:44.105 Media...rJNI     E  getFrameAtTime: videoFrame is a NULL pointer
13:12:44.172 com.h...pzzz     I  NativeAlloc concurrent copying GC freed 35006(1430KB) AllocSpace objects, 5(23MB) LOS objects, 49% free, 13MB/26MB, paused 4.066ms total 226.082ms
13:12:44.198 System           W  A resource failed to call close. 
13:12:44.207 chatty           I  uid=10225() FinalizerDaemon identical 2 lines
13:12:44.207 System           W  A resource failed to call close. 
13:12:44.212 System           W  A resource failed to call release. 
13:12:44.214 System           W  A resource failed to call close. 
13:12:44.214 System           W  A resource failed to call close. 

 org.bytedeco.javacv.FFmpegFrameRecorder$Exception: avcodec_send_frame() error -541478725: Error sending a video frame for encoding. (For more details, make sure FFmpegLogCallback.set() has been called.)
                                                	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1056)
                                                	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:961)
                                                	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:954)
                                                	at .product.hotTools.HotToolsUtil.lambda$videoToMp4$1(HotToolsUtil.java:193)
                                                	at .product.hotTools.-$$Lambda$HotToolsUtil$2XU8XtvzmBplNqZx_z9dKozHpCk.run(Unknown Source:8)
                                                	at java.lang.Thread.run(Thread.java:923)
13:12:51.072 LOG              I  [HttpUtil][Request] URL:http://pa.handbbc.com/spzzpi//mi.Main.uploadBusinessLog.hf  POSTDATA:{"MemberID":42,"LogContent":"用户在 [选择文件] 页面，视频转MP4 [失败] ","AppID":1}
13:12:51.088 View             D  [Warning] assignParent to null: this = DecorView@7930b5a[SelectLocalFile]
13:12:51.088 System.out       I  [socket]:check permission begin!
13:12:51.099 Input...port     I  Destroy ARC handle: 0xb400007d11de7540
13:12:51.102 Compa...rter     D  Compat change id reported: 147798919; UID 10225; state: ENABLED
13:12:51.147 LOG              I  [HttpUtil][Response] {"Notice":"操作成功","Result":true}
13:12:51.148 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] frame I:1     Avg QP: 1.70  size:760668
13:12:51.149 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] frame P:6     Avg QP: 1.86  size:734735
13:12:51.149 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] frame B:16    Avg QP: 2.30  size:671167
13:12:51.150 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] consecutive B-frames:  4.3%  8.7%  0.0% 87.0%
13:12:51.150 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] mb I  I16..4:  4.5%  6.0% 89.5%
13:12:51.150 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] mb P  I16..4:  2.2%  2.8% 34.9%  P16..4:  5.2% 19.3% 35.5%  0.0%  0.0%    skip: 0.1%
13:12:51.151 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] mb B  I16..4:  0.8%  0.8% 15.7%  B16..8:  5.5% 21.3% 52.6%  direct: 3.0%  skip: 0.2%  L0:50.5% L1:38.7% BI:10.7%
13:12:51.151 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] final ratefactor: -12.22
13:12:51.151 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] 8x8 transform intra:5.8% inter:7.7%
13:12:51.152 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] coded y,uvDC,uvAC intra: 87.4% 0.0% 0.0% inter: 79.3% 0.0% 0.0%
13:12:51.152 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] i16 v,h,dc,p: 46% 30% 16%  8%
13:12:51.152 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 22% 22%  5%  6%  8%  5%  5%  6%
13:12:51.153 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 20% 15%  5%  9% 10%  6%  6%  6%
13:12:51.153 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] i8c dc,h,v,p: 100%  0%  0%  0%
13:12:51.153 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] Weighted P-Frames: Y:33.3% UV:0.0%
13:12:51.154 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] ref P L0: 36.8%  7.0% 27.0% 24.7%  4.6%
13:12:51.154 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] ref B L0: 70.6% 21.0%  8.3%
13:12:51.154 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] ref B L1: 88.4% 11.6%
13:12:51.155 System.err       W  Info: [libx264 @ 0xb400007cbd32d000] kb/s:165993.91
13:12:51.631 com.h...pzzz     W  JNI critical lock held for 27.134ms on Thread[79,tid=13054,Runnable,Thread*=0xb400007d1f3fbc00,peer=0x13140298,"RxNewThreadScheduler-2"]
13:12:53.904 com.h...pzzz     W  JNI critical lock held for 27.219ms on Thread[1,tid=12781,Runnable,Thread*=0xb400007db4dd0c00,peer=0x71ba7bd8,"main"]
13:12:53.931 libc             E  Access denied finding property "ro.vendor.pref_scale_resolution"
13:12:53.935 chatty           I  uid=10225() identical 1 line
13:12:53.936 libc             E  Access denied finding property "ro.vendor.pref_scale_resolution"
13:12:54.140 skia             D  --- Failed to create image decoder with message 'unimplemented'
13:12:54.140 skia             D  --- Failed to create image decoder with message 'unimplemented'
13:12:54.140 DRM/D...oder     D  decodeDrmImageIfNeeded: header = [B@92a3c0d
13:12:54.140 DRM/D...oder     D  decodeDrmImageIfNeeded: [102][114][101][101][0]
13:12:54.140 DRM/D...oder     D  decodeDrmImageIfNeeded: headerSize = 29286
13:12:54.141 DRM/D...oder     D  decodeDrmImageIfNeeded: header = [B@aa646a4
13:12:54.141 DRM/D...oder     D  decodeDrmImageIfNeeded: [0][1][73][92][109]
13:12:54.141 DRM/D...oder     D  decodeDrmImageIfNeeded: headerSize = 256
13:12:54.142 skia             D  --- Failed to create image decoder with message 'unimplemented'
13:12:54.142 DRM/D...oder     D  decodeDrmImageIfNeeded: header = [B@455b7c2
13:12:54.142 DRM/D...oder     D  decodeDrmImageIfNeeded: [102][114][101][101][0]
13:12:54.142 DRM/D...oder     D  decodeDrmImageIfNeeded: headerSize = 29286
13:12:54.146 skia             D  --- Failed to create image decoder with message 'unimplemented'
13:12:54.147 DRM/D...oder     D  decodeDrmImageIfNeeded: header = [B@88889d3
13:12:54.147 DRM/D...oder     D  decodeDrmImageIfNeeded: [102][114][101][101][0]
13:12:54.147 DRM/D...oder     D  decodeDrmImageIfNeeded: headerSize = 29286
13:12:54.158 DRM_D..._JNI     D  nativeDecryptDcfFile: size = 796032, action = 1
13:12:54.159 DRM_D..._JNI     D  nativeDecryptDcfFile: openDecryptSession with offset = 0
13:12:54.160 DRM_D..._JNI     D  nativeDecryptDcfFile: size = 811065, action = 1
13:12:54.161 DRM_D..._JNI     E  nativeDecryptDcfFile: failed to openDecryptSession, trigger showDrmDialogIfNeed
13:12:54.161 DRM_D..._JNI     D  nativeDecryptDcfFile: openDecryptSession with offset = 0
13:12:54.162 DRM/D...oder     E  decodeDrmImage native decrypt failed 
13:12:54.162 DRM_D..._JNI     D  nativeDecryptDcfFile: size = 790337, action = 1
13:12:54.162 DRM_D..._JNI     E  nativeDecryptDcfFile: failed to openDecryptSession, trigger showDrmDialogIfNeed
13:12:54.163 DRM_D..._JNI     D  nativeDecryptDcfFile: openDecryptSession with offset = 0
13:12:54.163 DRM/D...oder     E  decodeDrmImage native decrypt failed 
13:12:54.164 DRM_D..._JNI     E  nativeDecryptDcfFile: failed to openDecryptSession, trigger showDrmDialogIfNeed
13:12:54.165 DRM/D...oder     E  decodeDrmImage native decrypt failed 
`
