### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: java.net.URISyntaxException: Illegal character in opaque part

### ISSUE THREAD

**Issue by danrossi** [bytedeco/javacv#1930]
I'm trying to integrate my test code into a java server which I believe runs Tomcat. On Windows. And upon making calls to the recorder code I get this error. 

```
java.lang.UnsatisfiedLinkError: java.net.URISyntaxException: Illegal character in opaque part at index 20: jar:file:/C:/lib/dep-libs/ffmpeg-5.0-1.5.7-windows-x86_64.jar!/org/bytedeco/ffmpeg/windows-x86_64/jniavutil.dll|at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1821)|at org.bytedeco.javacpp.Loader.load(Loader.java:1402)|at org.bytedeco.javacpp.Loader.load(Loader.java:1214)|at org.bytedeco.javacpp.Loader.load(Loader.java:1190)|at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)|at java.base/java.lang.Class.forName0(Native Method)|at java.base/java.lang.Class.forName(Unknown Source)|at org.bytedeco.javacpp.Loader.load(Loader.java:1269)|at org.bytedeco.javacpp.Loader.load(Loader.java:1214)|at org.bytedeco.javacpp.Loader.load(Loader.java:1190)|at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.<clinit>(Write_packet_Pointer_BytePointer_int.java:21)|at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:336)
```

I start a new thread in a class method

```
try (PointerScope scope = new PointerScope()) {	
new Thread(new PacketTranscoder(strm, websocket)).start();
}
```

The runnable code

```
public void run()
    {
		try {

			
	    	FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("D:\\test.webm", 1);
	    	recorder.setFormat("ogg");
	    	recorder.setAudioCodec(AV_CODEC_ID_OPUS);
	    	recorder.setAudioOption("crf", "0");
	        recorder.setAudioQuality(10);                    
	        recorder.setAudioBitrate(16000);
	        recorder.setSampleRate(16000);
	        recorder.setAudioChannels(1);
	       
   
			recorder.start();
		} catch (Exception e) {
			
		}
    	
    }
```

**Comment by danrossi** [comment]
It seems I have worked around the problem causing process to hang and not output the internal exception when in a windows service. By setting my maven class path to C:\lib\dep-libs. I have to copy out all the maven dependencies because the server doesnt run on maven. And easy for deployment. The original classpath location was in the base dir where the jar is loaded from, and the native library loader doesnt like windows class path with spaces ie C:\Program Files\server\lib. 

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.0.2</version>
                <configuration>
                    <forceCreation>true</forceCreation>
                    <finalName>${project.artifactId}</finalName>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>/C:/lib/dep-libs/</classpathPrefix>
                        </manifest>
                     
                    </archive>
                </configuration>
            </plugin>
```

**Comment by danrossi** [comment]
I get this error instead now though that isn't showing up in a standalone spring test app.

```
avcodec_open2() error -22: Could not open audio codec. (For more details, make sure FFmpegLogCallback.set() has been called.)
```

**Comment by saudet** [comment]
I'm pretty sure we can use paths with spaces in them just fine. That sounds like a bug in your JDK. Try a different version.
