### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no opencv_java460 in java.library.path

### ISSUE THREAD

**Issue by caomingjie-code** [bytedeco/javacv#1947]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java460 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.javaoffers.material.sample.MatSample.main(MatSample.java:21)

**Comment by saudet** [comment]
It doesn't look like you're using JavaCV...

**Comment by caomingjie-code** [comment]
> 

hello,  Can I use opencv's api in javacv

**Comment by saudet** [comment]
Sure, just make sure to follow the instructions in the README.md file here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by caomingjie-code** [comment]
![图片](https://user-images.githubusercontent.com/63859342/204097283-d3b625bf-b783-44e3-8abb-4a13f7dff966.png)

**Comment by saudet** [comment]
Where are you calling Loader.load(opencv_java.class)?

**Comment by thhart** [comment]
Where is this documented?

**Comment by saudet** [comment]
Yes, we could have more documentation and samples. Contributions are welcome!

**Comment by thhart** [comment]
How about to add this call into the samples of the main page here. I can not see this call anywhere or is it not applicable for these samples?

**Comment by saudet** [comment]
Not applicable, yes.
