### ISSUE TITLE
javacv 0.11: OpenCVFaceRecognizer to predict the face

### ISSUE THREAD

**Issue by chinadragon0515** [bytedeco/javacv#201]
As I failed to use javacv 1.0, I change to try 0.11 version. I download the image from http://www.cl.cam.ac.uk/Research/DTG/attarchive:pub/data/att_faces.zip  for testing, 

1. When I run with FaceRecognizer faceRecognizer = createFisherFaceRecognizer(); I got this exception,
OpenCV Error: Bad argument (Wrong input image size. Reason: Training and Test images must be of equal size! Expected an image with 10304 elements, but got 0.) in cv::Fisherfaces::predict, file ..\..\..\..\opencv\modules\contrib\src\facerec.cpp, line 623
Exception in thread "main" java.lang.RuntimeException: ..\..\..\..\opencv\modules\contrib\src\facerec.cpp:623: error: (-5) Wrong input image size. Reason: Training and Test images must be of equal size! Expected an image with 10304 elements, but got 0. in function cv::Fisherfaces::predict

	at org.bytedeco.javacpp.opencv_contrib$FaceRecognizer.predict(Native Method)
	at javacvtest.OpenCVFaceRecognizer.main(OpenCVFaceRecognizer.java:80)

2. When I run with FaceRecognizer faceRecognizer = createEigenFaceRecognizer();, I got this exception,
OpenCV Error: Bad argument (Wrong input image size. Reason: Training and Test images must be of equal size! Expected an image with 10304 elements, but got 0.) in cv::Eigenfaces::predict, file ..\..\..\..\opencv\modules\contrib\src\facerec.cpp, line 489
Exception in thread "main" java.lang.RuntimeException: ..\..\..\..\opencv\modules\contrib\src\facerec.cpp:489: error: (-5) Wrong input image size. Reason: Training and Test images must be of equal size! Expected an image with 10304 elements, but got 0. in function cv::Eigenfaces::predict

	at org.bytedeco.javacpp.opencv_contrib$FaceRecognizer.predict(Native Method)
	at javacvtest.OpenCVFaceRecognizer.main(OpenCVFaceRecognizer.java:80)

3. When I run with FaceRecognizer faceRecognizer = createLBPHFaceRecognizer();, I got this exception,
OpenCV Error: Assertion failed (s >= 0) in cv::setSize, file ..\..\..\..\opencv\modules\core\src\matrix.cpp, line 116
Exception in thread "main" java.lang.RuntimeException: ..\..\..\..\opencv\modules\core\src\matrix.cpp:116: error: (-215) s >= 0 in function cv::setSize

	at org.bytedeco.javacpp.opencv_contrib$FaceRecognizer.predict(Native Method)
	at javacvtest.OpenCVFaceRecognizer.main(OpenCVFaceRecognizer.java:80)

My questions are,
1. Do we have a common test image for this class?
2. Anything i did not wrong? How I can get the test pass with three different recognizer ? 

thanks.

**Comment by saudet** [comment]
Follow the tutorial and it should work:
http://docs.opencv.org/modules/contrib/doc/facerec/facerec_tutorial.html

**Comment by chinadragon0515** [comment]
I made a mistake, specify the wrong test image path (miss a slash). close the issue.

**Comment by chinadragon0515** [comment]
I made a mistake, specify the wrong test image path (miss a slash). close the issue.thanks.

**Comment by hokage4** [comment]
i want to make face recoginition using hadoop (Hipi) ,could you give me some suggestions .thank you very much .
