### ISSUE TITLE
UnsatisfiedLinkError with ffmpeg version 6.0-1.5.9

### ISSUE THREAD

**Issue by mahozad** [bytedeco/javacv#2039]
Hi. I'm using `org.bytedeco:ffmpeg` library like so:

```kotlin
implementation("org.bytedeco:ffmpeg:6.0-1.5.9")
implementation("org.bytedeco:ffmpeg:6.0-1.5.9:windows-x86_64-gpl")
```

```kotlin
val ffmpegPath = Loader.load(ffmpeg::class.java)
ProcessBuilder().command(ffmpegPath, /*...*/)
```

Version 5.1.2-1.5.8 worked as expected. Updating to 6.0-1.5.9 throws exception:

```stacktrace
Exception in thread "DefaultDispatcher-worker-1" java.lang.UnsatisfiedLinkError: no jniavfilter in java.library.path: ...
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.ffmpeg.global.avfilter.<clinit>(avfilter.java:26)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1226)
	...
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\admin\.javacpp\cache\ffmpeg-6.0-1.5.9-windows-x86_64-gpl-647649a0235f2d9d6ced9e2e992ffacd.jar\org\bytedeco\ffmpeg\windows-x86_64-gpl\jniavfilter.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1779)
	... 22 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\admin\.javacpp\cache\ffmpeg-6.0-1.5.9-windows-x86_64-gpl-647649a0235f2d9d6ced9e2e992ffacd.jar\org\bytedeco\ffmpeg\windows-x86_64-gpl\jniavfilter.dll: Can't find dependent libraries
```

I inspected the `C:\Users\admin\.javacpp\cache\ffmpeg-6.0-1.5.9-windows-x86_64-gpl-647649a0235f2d9d6ced9e2e992ffacd.jar\org\bytedeco\ffmpeg\windows-x86_64-gpl\` directory and it did not contain the following files (which are available in the `ffmpeg-6.0-1.5.9-windows-x86_64-gpl` JAR file):

- avdevice-60.dll
- ffmpeg.exe
- ffprobe.exe
- jniavdevice.dll

**Comment by mahozad** [comment]
Thanks.

**Comment by saudet** [comment]
Fixed in commit https://github.com/bytedeco/javacpp-presets/commit/56806a7689d997bace5e9dbfaf7d12af245648f2.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by mahozad** [comment]
I tried the snapshot version:
```kotlin
implementation("org.bytedeco:ffmpeg:6.0-1.5.10-SNAPSHOT")
implementation("org.bytedeco:ffmpeg:6.0-1.5.10-SNAPSHOT:windows-x86_64-gpl")
```
and it seems to work correctly for my use cases.
Thanks.

**Comment by mahozad** [comment]
@saudet 
Hello. It seems that a similar error happens in Android as well.
It worked well in the couple of first executions but today I'm getting the error. Maybe it's something related to caches.

```
CANNOT LINK EXECUTABLE "/data/user/0/ir.mahozad.../cache/.javacpp-root/cache/base.apk/lib/x86_64/ffmpeg": library "libpostproc.so" not found: needed by /data/user/0/ir.mahozad.../cache/.javacpp-root/cache/base.apk/lib/x86_64/libavfilter.so in namespace (default)
```

These are my dependencies:

```kotlin
implementation("org.bytedeco:ffmpeg:6.1.1-1.5.10")
implementation("org.bytedeco:ffmpeg:6.1.1-1.5.10:android-arm64-gpl")
implementation("org.bytedeco:ffmpeg:6.1.1-1.5.10:android-x86_64-gpl")
```

And this is the code (Kotlin):

```kotlin
val ffmpegPath = Loader.load(ffmpeg::class.java)
ProcessBuilder()
    .command(ffmpegPath)
    .start()
    .errorStream
    .reader()
    .useLines { lines ->
        println(lines.toList().toString())
    }
```

**Comment by saudet** [comment]
@mahozad see issue https://github.com/bytedeco/javacv/issues/1410
