### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

### ISSUE THREAD

**Issue by manju22412** [bytedeco/javacv#2059]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.openblas.global.openblas.<clinit>(openblas.java:13)
	at smile.math.blas.openblas.OpenBLAS.gemv(OpenBLAS.java:106)
	at smile.math.matrix.Matrix.mv(Matrix.java:1491)
	at smile.math.matrix.IMatrix.mv(IMatrix.java:271)
	at smile.neighbor.lsh.Hash.hash(Hash.java:146)
	at smile.neighbor.lsh.Hash.add(Hash.java:164)
	at smile.neighbor.LSH.put(LSH.java:209)
	at smile.neighbor.LSH.<init>(LSH.java:116)
	at temp.LSHTest.<init>(LSHTest.java:25)
	at temp.ClientCode.main(ClientCode.java:5)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jniopenblas_nolapack in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1799)
	... 19 more

**Comment by saudet** [comment]
Please add all the dependencies of openblas-platform to your class path.
