### ISSUE TITLE
Failed to load XXXX when running on docker; runs fine on local windows IDE. 

### ISSUE THREAD

**Issue by jAsve66** [bytedeco/javacv#2190]
```
2024-02-21 22:31:32 2024-02-21T21:31:32.418Z  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.ffmpeg.global.avutil
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.ffmpeg.global.avutil
2024-02-21 22:31:34 Debug: Loading library va
2024-02-21 22:31:34 Debug: Failed to load for va@.1: java.lang.UnsatisfiedLinkError: no va in java.library.path: /opt/openjdk-17/lib/server:/opt/openjdk-17/lib:/opt/openjdk-17/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2024-02-21 22:31:34 Debug: Locking /tmp/.javacpp-root/cache before extracting
2024-02-21 22:31:34 Debug: Extracting jar:file:/app.jar!/BOOT-INF/lib/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2
2024-02-21 22:31:34 Debug: Loading /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2
2024-02-21 22:31:34 Debug: Failed to load /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: java.lang.UnsatisfiedLinkError: /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: Error loading shared library /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: Operation not permitted
2024-02-21 22:31:34 Debug: Loading /usr/lib/libdrm.so.2
2024-02-21 22:31:34 Debug: Loading library va-drm
2024-02-21 22:31:34 Debug: Failed to load for va-drm@.1: java.lang.UnsatisfiedLinkError: no va-drm in java.library.path: /opt/openjdk-17/lib/server:/opt/openjdk-17/lib:/opt/openjdk-17/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2024-02-21 22:31:34 Debug: Locking /tmp/.javacpp-root/cache before extracting
2024-02-21 22:31:34 Debug: Extracting jar:file:/app.jar!/BOOT-INF/lib/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.58
2024-02-21 22:31:34 Debug: Creating symbolic link /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2 to /usr/lib/libdrm.so.2
2024-02-21 22:31:34 Debug: Loading /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.58
2024-02-21 22:31:34 Debug: Failed to load /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.58: java.lang.UnsatisfiedLinkError: /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.58: Error loading shared library /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.58: Operation not permitted
2024-02-21 22:31:34 Debug: Loading library avutil
2024-02-21 22:31:34 Debug: Failed to load for avutil@.58: java.lang.UnsatisfiedLinkError: no avutil in java.library.path: /opt/openjdk-17/lib/server:/opt/openjdk-17/lib:/opt/openjdk-17/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2024-02-21 22:31:34 Debug: Locking /tmp/.javacpp-root/cache before extracting
2024-02-21 22:31:34 Debug: Extracting jar:file:/app.jar!/BOOT-INF/lib/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
2024-02-21 22:31:34 Debug: Loading /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
2024-02-21 22:31:34 Debug: Failed to load /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: java.lang.UnsatisfiedLinkError: /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: Error loading shared library /tmp/.javacpp-root/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: Operation not permitted
2024-02-21 22:31:34 Debug: Loading library jniavutil
2024-02-21 22:31:34 Debug: Failed to load for jniavutil: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path: /opt/openjdk-17/lib/server:/opt/openjdk-17/lib:/opt/openjdk-17/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.javacpp.Pointer
2024-02-21 22:31:34 Debug: Locking /tmp/.javacpp-root/cache before extracting
2024-02-21 22:31:34 Debug: Extracting jar:file:/app.jar!/BOOT-INF/lib/javacpp-1.5.10-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
2024-02-21 22:31:34 Debug: Loading /tmp/.javacpp-root/cache/javacpp-1.5.10-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
2024-02-21 22:31:34 Debug: Failed to load /tmp/.javacpp-root/cache/javacpp-1.5.10-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: java.lang.UnsatisfiedLinkError: /tmp/.javacpp-root/cache/javacpp-1.5.10-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: Error loading shared library /tmp/.javacpp-root/cache/javacpp-1.5.10-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: Operation not permitted
2024-02-21 22:31:34 Debug: Loading library jnijavacpp
2024-02-21 22:31:34 Debug: Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: /opt/openjdk-17/lib/server:/opt/openjdk-17/lib:/opt/openjdk-17/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2024-02-21 22:31:34 Debug: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: /opt/openjdk-17/lib/server:/opt/openjdk-17/lib:/opt/openjdk-17/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-02-21 22:31:34 Debug: Loading class org.bytedeco.ffmpeg.global.avutil
2024-02-21 22:31:34 2024-02-21T21:31:34.970Z ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/api/v1] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil] with root cause
2024-02-21 22:31:34 
2024-02-21 22:31:34 java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
2024-02-21 22:31:34     at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
2024-02-21 22:31:34     at java.base/java.lang.Class.forName(Class.java:466) ~[na:na]
2024-02-21 22:31:34     at org.bytedeco.javacpp.Loader.load(Loader.java:1289) ~[javacpp-1.5.10.jar!/:1.5.10]
2024-02-21 22:31:34     at org.bytedeco.javacpp.Loader.load(Loader.java:1234) ~[javacpp-1.5.10.jar!/:1.5.10]
2024-02-21 22:31:34     at org.bytedeco.javacpp.Loader.load(Loader.java:1210) ~[javacpp-1.5.10.jar!/:1.5.10]
2024-02-21 22:31:34     at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45) ~[ffmpeg-6.1.1-1.5.10.jar!/:6.1.1-1.5.10]
2024-02-21 22:31:34     at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:366) ~[javacv-1.5.10.jar!/:1.5.10]
```

I get the pasted stack trace when attempting to execute a functionality in my application on docker and AWS. Everything runs as expected on local, Windows 11 machine through intellij. These are debug logs. 
I've added all dependencies mentioned on other issues. 

```
implementation 'org.bytedeco:javacv:1.5.10'
implementation 'org.bytedeco:javacv-platform:1.5.10'
implementation 'org.bytedeco:ffmpeg-platform:6.1.1-1.5.10'
implementation 'org.bytedeco:ffmpeg:6.1.1-1.5.10'
mplementation 'org.bytedeco:javacpp:1.5.10'
```

I'm using `loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC` due to a security issue. 

Tried multiple other docker images but same issue. 

Any ideas/suggestions? 

I'm afraid I'm going to have to build the binaries...

**Comment by saudet** [comment]
It just looks like your environnement is configured to disallow loading libraries dynamically like that

**Comment by jAsve66** [comment]
> It just looks like your environnement is configured to disallow loading libraries dynamically like that

Really? Apologies but I'm not an expert on docker/devops. Where should I start looking to allow such a thing?

**Comment by saudet** [comment]
I guess this maybe? https://stackoverflow.com/a/57796840/523744

**Comment by jAsve66** [comment]
Appears that permissions were indeed not set on docker. Only had to mount a volume to use specifically for this reason. Thanks for the help.
