### ISSUE TITLE
javaCV 1.5.10 + openCV 4.9.0-1.5.10 error: java.lang.UnsatisfiedLinkError: no opencv_java490 in java.library.path

### ISSUE THREAD

**Issue by phial3** [bytedeco/javacv#2207]
```java
 static {
        // load OpenCV native library
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }
```

```text
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java490 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
```

**Comment by saudet** [comment]
Please call instead Loader.load(opencv_java.class):
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by phial3** [comment]
> Please call instead Loader.load(opencv_java.class): https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

thank you, that's ok

**Comment by phial3** [comment]
ok
