### ISSUE TITLE
UnsatisfiedLinkError when using ORB from opencv_cudafeatures2d

### ISSUE THREAD

**Issue by daife** [bytedeco/javacv#2259]
I am experiencing an  UnsatisfiedLinkError  when trying to use the  ORB  class from the  opencv_cudafeatures2d  package in my Java application. The application is unable to find the implementation for certain native methods, which suggests that the corresponding native library is not being loaded correctly.

enviroment:  redmi phone k70

 And its trace:
java.lang.UnsatisfiedLinkError: No implementation found for int org.bytedeco.opencv.opencv_cudafeatures2d.ORB.X_ROW() (tried Java_org_bytedeco_opencv_opencv_1cudafeatures2d_ORB_X_1ROW and Java_org_bytedeco_opencv_opencv_1cudafeatures2d_ORB_X_1ROW__) - is the library loaded, e.g. System.loadLibrary?
	at org.bytedeco.opencv.opencv_cudafeatures2d.ORB.X_ROW(Native Method)
	at org.bytedeco.opencv.opencv_cudafeatures2d.ORB.<clinit>(ORB.java:49)
	at com.example.myapplication.CameraMovementEstimator.<init>(CameraMovementEstimator.java:22)
	at com.example.myapplication.CameraMovementExample.main(CameraMovementExample.java:16)
	at com.example.myapplication.MainActivity.lambda$onCreate$0(MainActivity.java:21)
	at com.example.myapplication.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7798)
	at android.view.View.performClickInternal(View.java:7775)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31139)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by saudet** [comment]
I'm not aware of any phones supporting CUDA

**Comment by daife** [comment]
> I'm not aware of any phones supporting CUDA

Oh,sorry,I easily understood the cuda as Gpu boost,my fault haha😅
