### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack

### ISSUE THREAD

**Issue by dcosio** [bytedeco/javacv#2284]
This is related to(if not exactly) [https://github.com/bytedeco/javacv/issues/1435](1435).

Im upgrading upgrading my java RT to java 17.. the application is still compiled on java 1.8. 
I use these dependencies.. When i start an ocr process im getting
`	<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>leptonica-platform</artifactId>
            <version>1.83.0-1.5.9</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>tesseract-platform</artifactId>
            <version>5.3.1-1.5.9</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.7.0-1.5.9</version>
        </dependency>`

When i start an ocr process im gettin
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /Users/dan.cosio/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1993)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1226)

The issue link i referred too looked like the same issue. After reading through it, I wasn't clear if there was a resolution but it sounding like you were close.. if there a document resolution to this issue.

Also, when i build my code I use either -Djavacpp.platform=macosx-x86_64 or -Djavacpp.platform=linux-x86_64 depending on if im running local(macos) or deploying(linux)

**Comment by dcosio** [comment]
Im closing this issue.. So I did a test without the javacpp-platform so to get all the jars and the code worked..
I noticed that there is a macos-arm64.. my mac is an M1 so i used the macos-arm64 and the code works.. In my testing im switching between java 1.8 and java 17.. the x86 platform worked on 1.8 but not on java 17.. anyway.. problem solved.

**Comment by dcosio** [comment]
Im closing this issue.. So I did a test without the javacpp-platform so to get all the jars and the code worked..
I noticed that there is a macos-arm64.. my mac is an M1 so i used the macos-arm64 and the code works.. In my testing im switching between java 1.8 and java 17.. the x86 platform worked on 1.8 but not on java 17.. anyway.. problem solved.
