### ISSUE TITLE
NullPointerException with setPreviewCallbackWithBuffer()

### ISSUE THREAD

**Issue by aydinkn** [bytedeco/javacv#241]
Hi,

I try setPreviewCallbackWithBuffer to improve preview efficiency and frame rate by allowing preview frame memory reuse. But when I change code

```
mCamera.setPreviewCallback(CameraView.this);
```

to

```
mCamera.setPreviewCallbackWithBuffer(CameraView.this);

int videoBufferSize = previewWidth * previewHeight * ImageFormat.getBitsPerPixel(cameraParameters.getPreviewFormat()) / 8;
byte[] videoBuffer = new byte[videoBufferSize];
mCamera.addCallbackBuffer(videoBuffer);
```

I've got this error sometimes:

```
09-29 17:20:35.551  18050-18050/W/System.err﹕ java.lang.NullPointerException: This pointer address is NULL.
09-29 17:20:35.551  18050-18050/W/System.err﹕ at org.bytedeco.javacpp.BytePointer.put(Native Method)
09-29 17:20:35.551  18050-18050/W/System.err﹕ at org.bytedeco.javacpp.BytePointer.put(BytePointer.java:203)
09-29 17:20:35.551  18050-18050/W/System.err﹕ at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:82)
09-29 17:20:35.551  18050-18050/W/System.err﹕ at org.bytedeco.javacv.FFmpegFrameFilter.pushImage(FFmpegFrameFilter.java:263)
09-29 17:20:35.551  18050-18050/W/System.err﹕ at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:252)
09-29 17:20:35.551  18050-18050/W/System.err﹕ at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:248)
```

Error point:

```
filter.push(yuvImage);
```

If I remove filter then error point:

```
recorder.record(yuvImage);
```

Any ideas?

**Comment by saudet** [comment]
How do you initialize yuvImage?

**Comment by aydinkn** [comment]
My code similar RecordActivity example and on the initrecorder function:
```
yuvImage = new Frame(previewWidth, previewHeight, Frame.DEPTH_UBYTE, 2);
```
I think, GC collect yuvImage buffer. Because I test yuvImage == null, always return false.

**Comment by saudet** [comment]
Could you call `System.out.println(yuvImage.image[0])` just before calling `.FFmpegFrameFilter.pushImage()` and let me know the result? Thanks

**Comment by saudet** [comment]
Let's see, you're not using the latest version of JavaCPP. You should try the latest version of that, at least 1.0.1-SNAPSHOT available here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.0.1-SNAPSHOT/

**Comment by aydinkn** [comment]
While NullPointer error
```
Log.i(LOG_TAG, "image: " + yuvImage.image[0]); // result: java.nio.DirectByteBuffer[position=3110400,limit=4147200,capacity=4147200]
```
I pulled JavaCPP, JavaCPP-Presets and JavaCV master repositories and build all native libraries myself but I still got this error after 1~2 minutes when camera.addCallbackWithBuffer() function. With camera.addCallback() function works perfectly (exact fps lost).

**Comment by saudet** [comment]
Well, there's obviously something you're not doing correctly. I'm afraid I can't debug code that you have written without seeing the given code.

**Comment by aydinkn** [comment]
I test this issue on the RecordActivity example. If you change setPreviewCallback to setPreviewCallbackWithBuffer and addCallbackBuffer then get this issue after 1~2 min.

But I see, on the RecordActivity example, when I change imageWidth=1920, imageHeight=1080, I got this error with setPreviewCallbackWithBuffer. Before NullPointer Error, I see: Shutting Down VM message. I am watching CPU and Memory usage but they are not critical level (with preset=ultrafast). Why VM Shutting Down and I got NullPointer Exception I don't understand.

**Comment by saudet** [comment]
What happens if you remove all calls to JavaCV? If it still fails after 1~2 minutes, then your problem has nothing to do with JavaCV.

**Comment by aydinkn** [comment]
I removed all JavaCV calls. NullPointer is not thrown by application. Because this error throws in the filter.push(yuvImage) or recorder.record(yuvImage) functions. This functions take yuvImage parameter and this issue about yuvImage buffer I think.
```
((ByteBuffer) yuvImage.image[0].position(0)).put(data); // This process doesn't thrown any error.
```
After that, when using yuvImage, I got NullPointer 1~2 min later. But when I use setPreviewCallback function, everything ok.

**Comment by saudet** [comment]
Well, like I said, I can't help you if I can't see your code. You're obviously doing something wrong, but if I can't see your code, there is no chance that I will ever be able to help you. You need to provide something I can work with.

**Comment by aydinkn** [comment]
Here is my test code:
```
package net.test.javacvtest;

import android.app.Activity;
import android.content.Context;
import android.content.pm.ActivityInfo;
import android.graphics.ImageFormat;
import android.hardware.Camera;
import android.hardware.Camera.PreviewCallback;
import android.media.AudioFormat;
import android.media.AudioRecord;
import android.media.MediaRecorder;
import android.os.Bundle;
import android.os.PowerManager;
import android.util.Log;
import android.view.Display;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ShortBuffer;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.bytedeco.javacpp.avcodec;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FFmpegFrameRecorder;

public class MainActivity extends Activity implements View.OnClickListener {
  
  private final static String CLASS_LABEL = "RecordActivity";
  private final static String LOG_TAG = CLASS_LABEL;

  private PowerManager.WakeLock mWakeLock;

  private String ffmpeg_link = "/mnt/sdcard/stream.flv";

  long startTime = 0;
  boolean recording = false;

  private FFmpegFrameRecorder recorder;

  private boolean isPreviewOn = false;

  private int sampleAudioRateInHz = 44100;
  private int imageWidth = 1920;
  private int imageHeight = 1080;
  private int frameRate = 30;

  /* audio data getting thread */
  private AudioRecord audioRecord;
  private AudioRecordRunnable audioRecordRunnable;
  private Thread audioThread;
  volatile boolean runAudioThread = true;

  /* video data getting thread */
  private Camera cameraDevice;
  private CameraView cameraView;

  private Frame yuvImage = null;

  /* layout setting */
  private final int bg_screen_bx = 232;
  private final int bg_screen_by = 128;
  private final int bg_screen_width = 700;
  private final int bg_screen_height = 500;
  private final int bg_width = 1123;
  private final int bg_height = 715;
  private final int live_width = 640;
  private final int live_height = 480;
  private int screenWidth, screenHeight;
  private Button btnRecorderControl;

  /* The number of seconds in the continuous record loop (or 0 to disable loop). */
  final int RECORD_LENGTH = 0;
  Frame[] images;
  long[] timestamps;
  ShortBuffer[] samples;
  int imagesIndex, samplesIndex;

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

    setContentView(R.layout.activity_main);

    PowerManager pm = (PowerManager) getSystemService(Context.POWER_SERVICE);
    mWakeLock = pm.newWakeLock(PowerManager.SCREEN_BRIGHT_WAKE_LOCK, CLASS_LABEL);
    mWakeLock.acquire();

    initLayout();
  }


  @Override
  protected void onResume() {
    super.onResume();

    if (mWakeLock == null) {
      PowerManager pm = (PowerManager) getSystemService(Context.POWER_SERVICE);
      mWakeLock = pm.newWakeLock(PowerManager.SCREEN_BRIGHT_WAKE_LOCK, CLASS_LABEL);
      mWakeLock.acquire();
    }
  }

  @Override
  protected void onPause() {
    super.onPause();

    if (mWakeLock != null) {
      mWakeLock.release();
      mWakeLock = null;
    }
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();

    recording = false;

    if (cameraView != null) {
      cameraView.stopPreview();
    }

    if(cameraDevice != null) {
      cameraDevice.stopPreview();
      cameraDevice.release();
      cameraDevice = null;
    }

    if (mWakeLock != null) {
      mWakeLock.release();
      mWakeLock = null;
    }
  }


  private void initLayout() {

        /* get size of screen */
    Display display = ((WindowManager) getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();
    screenWidth = display.getWidth();
    screenHeight = display.getHeight();
    RelativeLayout.LayoutParams layoutParam = null;
    LayoutInflater myInflate = null;
    myInflate = (LayoutInflater) getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    RelativeLayout topLayout = new RelativeLayout(this);
    setContentView(topLayout);
    LinearLayout preViewLayout = (LinearLayout) myInflate.inflate(R.layout.activity_main, null);
    layoutParam = new RelativeLayout.LayoutParams(screenWidth, screenHeight);
    topLayout.addView(preViewLayout, layoutParam);

        /* add control button: start and stop */
    btnRecorderControl = (Button) findViewById(R.id.recorder_control);
    btnRecorderControl.setText("Start");
    btnRecorderControl.setOnClickListener(this);

        /* add camera view */
    int display_width_d = (int) (1.0 * bg_screen_width * screenWidth / bg_width);
    int display_height_d = (int) (1.0 * bg_screen_height * screenHeight / bg_height);
    int prev_rw, prev_rh;
    if (1.0 * display_width_d / display_height_d > 1.0 * live_width / live_height) {
      prev_rh = display_height_d;
      prev_rw = (int) (1.0 * display_height_d * live_width / live_height);
    } else {
      prev_rw = display_width_d;
      prev_rh = (int) (1.0 * display_width_d * live_height / live_width);
    }
    layoutParam = new RelativeLayout.LayoutParams(prev_rw, prev_rh);
    layoutParam.topMargin = (int) (1.0 * bg_screen_by * screenHeight / bg_height);
    layoutParam.leftMargin = (int) (1.0 * bg_screen_bx * screenWidth / bg_width);

    cameraDevice = Camera.open();
    Log.i(LOG_TAG, "cameara open");
    cameraView = new CameraView(this, cameraDevice);
    topLayout.addView(cameraView, layoutParam);
    Log.i(LOG_TAG, "cameara preview start: OK");
  }

  //---------------------------------------
  // initialize ffmpeg_recorder
  //---------------------------------------
  private void initRecorder() {

    Log.w(LOG_TAG, "init recorder");

    if (RECORD_LENGTH > 0) {
      imagesIndex = 0;
      images = new Frame[RECORD_LENGTH * frameRate];
      timestamps = new long[images.length];
      for (int i = 0; i < images.length; i++) {
        images[i] = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 2);
        timestamps[i] = -1;
      }
    } else if (yuvImage == null) {
      yuvImage = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 2);
      Log.i(LOG_TAG, "create yuvImage");
    }

    Log.i(LOG_TAG, "ffmpeg_url: " + ffmpeg_link);
    recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);
    recorder.setFormat("flv");
    recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
    recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
    recorder.setVideoOption("preset", "veryfast");
    recorder.setSampleRate(sampleAudioRateInHz);
    // Set in the surface changed method
    recorder.setFrameRate(frameRate);

    Log.i(LOG_TAG, "recorder initialize success");

    audioRecordRunnable = new AudioRecordRunnable();
    audioThread = new Thread(audioRecordRunnable);
    runAudioThread = true;
  }

  public void startRecording() {

    initRecorder();

    try {
      recorder.start();
      startTime = System.currentTimeMillis();
      recording = true;
      audioThread.start();

    } catch (FFmpegFrameRecorder.Exception e) {
      e.printStackTrace();
    }
  }

  public void stopRecording() {

    runAudioThread = false;
    try {
      audioThread.join();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    audioRecordRunnable = null;
    audioThread = null;

    if (recorder != null && recording) {
      if (RECORD_LENGTH > 0) {
        Log.v(LOG_TAG,"Writing frames");
        try {
          int firstIndex = imagesIndex % samples.length;
          int lastIndex = (imagesIndex - 1) % images.length;
          if (imagesIndex <= images.length) {
            firstIndex = 0;
            lastIndex = imagesIndex - 1;
          }
          if ((startTime = timestamps[lastIndex] - RECORD_LENGTH * 1000000L) < 0) {
            startTime = 0;
          }
          if (lastIndex < firstIndex) {
            lastIndex += images.length;
          }
          for (int i = firstIndex; i <= lastIndex; i++) {
            long t = timestamps[i % timestamps.length] - startTime;
            if (t >= 0) {
              if (t > recorder.getTimestamp()) {
                recorder.setTimestamp(t);
              }
              recorder.record(images[i % images.length]);
            }
          }

          firstIndex = samplesIndex % samples.length;
          lastIndex = (samplesIndex - 1) % samples.length;
          if (samplesIndex <= samples.length) {
            firstIndex = 0;
            lastIndex = samplesIndex - 1;
          }
          if (lastIndex < firstIndex) {
            lastIndex += samples.length;
          }
          for (int i = firstIndex; i <= lastIndex; i++) {
            recorder.recordSamples(samples[i % samples.length]);
          }
        } catch (FFmpegFrameRecorder.Exception e) {
          Log.v(LOG_TAG,e.getMessage());
          e.printStackTrace();
        }
      }

      recording = false;
      Log.v(LOG_TAG,"Finishing recording, calling stop and release on recorder");
      try {
        recorder.stop();
        recorder.release();
      } catch (FFmpegFrameRecorder.Exception e) {
        e.printStackTrace();
      }
      recorder = null;

    }
  }

  @Override
  public boolean onKeyDown(int keyCode, KeyEvent event) {

    if (keyCode == KeyEvent.KEYCODE_BACK) {
      if (recording) {
        stopRecording();
      }

      finish();

      return true;
    }

    return super.onKeyDown(keyCode, event);
  }


  //---------------------------------------------
  // audio thread, gets and encodes audio data
  //---------------------------------------------
  class AudioRecordRunnable implements Runnable {

    @Override
    public void run() {
      android.os.Process.setThreadPriority(android.os.Process.THREAD_PRIORITY_URGENT_AUDIO);

      // Audio
      int bufferSize;
      ShortBuffer audioData;
      int bufferReadResult;

      bufferSize = AudioRecord.getMinBufferSize(sampleAudioRateInHz,
          AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT);
      audioRecord = new AudioRecord(MediaRecorder.AudioSource.MIC, sampleAudioRateInHz,
          AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT, bufferSize);

      if (RECORD_LENGTH > 0) {
        samplesIndex = 0;
        samples = new ShortBuffer[RECORD_LENGTH * sampleAudioRateInHz * 2 / bufferSize + 1];
        for (int i = 0; i < samples.length; i++) {
          samples[i] = ShortBuffer.allocate(bufferSize);
        }
      } else {
        audioData = ShortBuffer.allocate(bufferSize);
      }

      Log.d(LOG_TAG, "audioRecord.startRecording()");
      audioRecord.startRecording();

            /* ffmpeg_audio encoding loop */
      while (runAudioThread) {
        if (RECORD_LENGTH > 0) {
          audioData = samples[samplesIndex++ % samples.length];
          audioData.position(0).limit(0);
        }
        //Log.v(LOG_TAG,"recording? " + recording);
        bufferReadResult = audioRecord.read(audioData.array(), 0, audioData.capacity());
        audioData.limit(bufferReadResult);
        if (bufferReadResult > 0) {
          Log.v(LOG_TAG,"bufferReadResult: " + bufferReadResult);
          // If "recording" isn't true when start this thread, it never get's set according to this if statement...!!!
          // Why?  Good question...
          if (recording) {
            if (RECORD_LENGTH <= 0) try {
              recorder.recordSamples(audioData);
              //Log.v(LOG_TAG,"recording " + 1024*i + " to " + 1024*i+1024);
            } catch (FFmpegFrameRecorder.Exception e) {
              Log.v(LOG_TAG,e.getMessage());
              e.printStackTrace();
            }
          }
        }
      }
      Log.v(LOG_TAG,"AudioThread Finished, release audioRecord");

            /* encoding finish, release recorder */
      if (audioRecord != null) {
        audioRecord.stop();
        audioRecord.release();
        audioRecord = null;
        Log.v(LOG_TAG,"audioRecord released");
      }
    }
  }

  //---------------------------------------------
  // camera thread, gets and encodes video data
  //---------------------------------------------
  class CameraView extends SurfaceView implements SurfaceHolder.Callback, Camera.PreviewCallback {

    private SurfaceHolder mHolder;
    private Camera mCamera;
    private byte[] buffer;

    public CameraView(Context context, Camera camera) {
      super(context);
      Log.w("camera","camera view");
      mCamera = camera;
      mHolder = getHolder();
      mHolder.addCallback(CameraView.this);
      mHolder.setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS);
      mCamera.setPreviewCallbackWithBuffer(CameraView.this);
    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
      try {
        stopPreview();
        mCamera.setPreviewDisplay(holder);
      } catch (IOException exception) {
        mCamera.release();
        mCamera = null;
      }
    }

    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
      Camera.Parameters camParams = mCamera.getParameters();
      List<Camera.Size> sizes = camParams.getSupportedPreviewSizes();
      // Sort the list in ascending order
      Collections.sort(sizes, new Comparator<Camera.Size>() {

        public int compare(final Camera.Size a, final Camera.Size b) {
          return a.width * a.height - b.width * b.height;
        }
      });

      // Pick the first preview size that is equal or bigger, or pick the last (biggest) option if we cannot
      // reach the initial settings of imageWidth/imageHeight.
      for (int i = 0; i < sizes.size(); i++) {
        if ((sizes.get(i).width >= imageWidth && sizes.get(i).height >= imageHeight) || i == sizes.size() - 1) {
          imageWidth = sizes.get(i).width;
          imageHeight = sizes.get(i).height;
          Log.v(LOG_TAG, "Changed to supported resolution: " + imageWidth + "x" + imageHeight);
          break;
        }
      }
      camParams.setPreviewSize(imageWidth, imageHeight);

      Log.v(LOG_TAG,"Setting imageWidth: " + imageWidth + " imageHeight: " + imageHeight + " frameRate: " + frameRate);

      camParams.setPreviewFrameRate(frameRate);
      Log.v(LOG_TAG,"Preview Framerate: " + camParams.getPreviewFrameRate());

      mCamera.setParameters(camParams);
      startPreview();
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {
      try {
        mHolder.addCallback(null);
        mCamera.setPreviewCallbackWithBuffer(null);
      } catch (RuntimeException e) {
        // The camera has probably just been released, ignore.
      }
    }

    public void startPreview() {
      if (!isPreviewOn && mCamera != null) {
        buffer = new byte[imageWidth * imageHeight * ImageFormat.getBitsPerPixel(mCamera.getParameters().getPreviewFormat()) / 8];
        mCamera.addCallbackBuffer(buffer);
        isPreviewOn = true;
        mCamera.startPreview();
      }
    }

    public void stopPreview() {
      if (isPreviewOn && mCamera != null) {
        isPreviewOn = false;
        mCamera.stopPreview();
      }
    }

    @Override
    public void onPreviewFrame(byte[] data, Camera camera) {
      mCamera.addCallbackBuffer(data);
      if (audioRecord == null || audioRecord.getRecordingState() != AudioRecord.RECORDSTATE_RECORDING) {
        startTime = System.currentTimeMillis();
        return;
      }
      if (RECORD_LENGTH > 0) {
        int i = imagesIndex++ % images.length;
        yuvImage = images[i];
        timestamps[i] = 1000 * (System.currentTimeMillis() - startTime);
      }
            /* get video data */
      if (yuvImage != null && recording) {
        ((ByteBuffer)yuvImage.image[0].position(0)).put(data);

        if (RECORD_LENGTH <= 0) try {
          Log.v(LOG_TAG,"Writing Frame");
          long t = 1000 * (System.currentTimeMillis() - startTime);
          if (t > recorder.getTimestamp()) {
            recorder.setTimestamp(t);
          }
          recorder.record(yuvImage);
        } catch (FFmpegFrameRecorder.Exception e) {
          Log.v(LOG_TAG,e.getMessage());
          e.printStackTrace();
        }
      }
    }
  }

  @Override
  public void onClick(View v) {
    if (!recording) {
      startRecording();
      Log.w(LOG_TAG, "Start Button Pushed");
      btnRecorderControl.setText("Stop");
    } else {
      // This will trigger the audio recording loop to stop and then set isRecorderStart = false;
      stopRecording();
      Log.w(LOG_TAG, "Stop Button Pushed");
      btnRecorderControl.setText("Start");
    }
  }
}

```

**Comment by saudet** [comment]
So it looks like `Buffer.hasArray()` is sometimes returning true, when it should always be false. What version of Android are you running? Android 4.0 is known to have issues with `Buffer.hasArray()`: https://github.com/bytedeco/javacpp/issues/39. If you are using Android 4.0, you may want to try to upgrade to 4.1.

**Comment by aydinkn** [comment]
I test many device this issue with Android 4.1+ All versions have this problem when addPreviewCallbackWithBuffer used.

**Comment by saudet** [comment]
Ok, so Android doesn't just shutdown the VM without a stack trace or
something. Please figure out how to get the whole log from the development
environment you are using.

**Comment by aydinkn** [comment]
I checked out android logs, memory and cpu usages on Android Studio, everything is ok, but I got NullPointer exception. Can you debug my test code?

**Comment by aydinkn** [comment]
I removed all filter and record function calls and test it (No memory and cpu overload and VM shutdown):
```
public void onPreviewFrame(final byte[] data, final Camera camera) {
    if (yuvImage != null) {
        ByteBuffer byteBuffer = (ByteBuffer) yuvImage.image[0].position(0);
        byteBuffer.put(data);
        BytePointer test = new BytePointer(byteBuffer);
    }
}
// I've got NullPointer error after a while:
// org.bytedeco.javacpp.BytePointer.put(Native Method)
// org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:82)
```

**Comment by saudet** [comment]
If `byteBuffer` is a direct NIO buffer, there is no way it could get to line 82. If `byteBuffer.hasArray()` returns true, but `byteBuffer.array()` returns null, then this is a bug in Android, so if this is what is happening, I urge you to report it as a bug upstream.

**Comment by aydinkn** [comment]
Ok,
If I change yuvImage frame depth UBYTE to USHORT, everything is OK. But result image is not well aligned.

**Comment by saudet** [comment]
Could you try again with version 1.2? There has been a few fixes around those functions, so it might have done something to fix this issue as well.

**Comment by aresa7796** [comment]
I have the same problem

       public static void convertMp4(String url, String outFile, VideoParams params) {

        File file = new File(outFile);
        FFmpegFrameRecorder mRecorder = new FFmpegFrameRecorder(file, params.width, params.height);
        mRecorder.setFormat("mp4");
        mRecorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
        mRecorder.setSampleRate(params.sampleAudioRateInHz);
        // Set in the surface changed method
        mRecorder.setFrameRate(params.frameRate);
        try {
            mRecorder.start();
        } catch (FrameRecorder.Exception e) {
            e.printStackTrace();
        }
        AndroidFrameConverter converter = new AndroidFrameConverter();

        int frameCount = 5 * params.frameRate;
        float time = 5000 / frameCount;

        Bitmap bmp = BitmapFactory.decodeFile(url);
        Frame frame = converter.convert(bmp);
        for (int i = 1; i <= frameCount; i++) {
            try {
                mRecorder.setTimestamp((long)(time * i * 1000));
                mRecorder.record(frame);
            } catch (FrameRecorder.Exception e) {
                e.printStackTrace();
            }catch (NullPointerException e){
                e.printStackTrace();
            }
        }

        try {
            mRecorder.stop();
            mRecorder.release();
        } catch (FrameRecorder.Exception e) {
            e.printStackTrace();
        }
    }

**Comment by saudet** [comment]
@aresa7796 could you provide a bit more details?

**Comment by alexisv6** [comment]
Any update on a fix for using setPreviewCallbackWithBuffer?

**Comment by saudet** [comment]
@alexisv6 Could you ask the developers of Android why this is happening? It looks like a bug in Android.

**Comment by saudet** [comment]
Thanks to @hnvn and @djalmaafilho, we now have working sample projects using setPreviewCallbackWithBuffer():
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-camera-preview
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-recognize
