### ISSUE TITLE
 No JNI_OnLoad found problem

### ISSUE THREAD

**Issue by VincentVivian** [bytedeco/javacv#280]
Hi, i'm using javacv-1.1 for android ffmpegFramerecording,  it show exceptions below when device is 4.0.3,   but when switch to 5.0  it's ok, why?

I add 

``` groovy
compile files('libs/javacpp.jar')
compile files('libs/javacv.jar')
compile files('libs/ffmpeg.jar')
compile files('libs/opencv.jar')
```

into libs and extract ffmpeg-android-arm.jar and opencv-android-arm.jar so into jniLibs/armeabi

why 5.0 is ok, and 4.0.3 is not ??

```
11-18 10:26:23.780 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/libc.so 0x4136cf68, skipping init
11-18 10:26:23.780 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/libm.so 0x4136cf68, skipping init
11-18 10:26:23.790 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/libz.so 0x4136cf68, skipping init
11-18 10:26:23.790 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/libdl.so 0x4136cf68, skipping init
11-18 10:26:23.790 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/liblog.so 0x4136cf68, skipping init
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: Trying to load lib /data/data/org.bytedeco.javacv_android_example/lib/libavutil.so 0x4136cf68
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: Added shared lib /data/data/org.bytedeco.javacv_android_example/lib/libavutil.so 0x4136cf68
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /data/data/org.bytedeco.javacv_android_example/lib/libavutil.so 0x4136cf68, skipping init
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: Trying to load lib /data/data/org.bytedeco.javacv_android_example/lib/libjniavutil.so 0x4136cf68
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/bytedeco/javacpp/avutil;
11-18 10:26:23.820 14422-14422/org.bytedeco.javacv_android_example I/dalvikvm: Rejecting re-init on previously-failed class Lorg/bytedeco/javacpp/avutil; v=0x0
11-18 10:26:23.820 14422-14422/org.bytedeco.javacv_android_example W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lorg/bytedeco/javacpp/avcodec$AVPacket;
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example D/AndroidRuntime: Shutting down VM
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40a5e1f8)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime: FATAL EXCEPTION: main
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime: java.lang.ExceptionInInitializerError
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:415)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.forName(Class.java:217)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:413)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.classForName(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.forName(Class.java:217) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:413) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.classForName(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.forName(Class.java:217) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:413) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by saudet** [comment]
Please let me know if you figure out why it's not working on your 4.03 device! Thanks

**Comment by VincentVivian** [comment]
Hi @saudet thanks for your reply, i'm not solve it yeat, it really take me too much time,  so, please help me how to solve this problem. i test it on many device( 4.1.* ~ 5.0), but the error Log shows above only on 4.0.3(Api ) device, thanks

**Comment by VincentVivian** [comment]
(4.0.3 ~ 5.0)

**Comment by saudet** [comment]
Is it something you can reproduce in the emulator? If so, please provide the spec of the emulator. With this info, I might be able to debug this.

**Comment by saudet** [comment]
Could you try again with version 1.2 and check if this is still an issue?

**Comment by saudet** [comment]
This sounds like a problem that can be fixed with ReLinker:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
