### ISSUE TITLE
Error in pushing stream:     av_interleaved_write_frame() error -110

### ISSUE THREAD

**Issue by fifa1016** [bytedeco/javacv#308]
Hi all,
First thanks for your great work. 

I encounter a problem , it seems no one else encountered: error always happened in several minutes or more after started pushing.

Could you give some advice?

here is my project, I use javacv1.1, so  ignore the project name:
https://github.com/fifa1016/streamer_test

and here is the error log:
```
01-11 11:04:10.209 25574-30435/com.example.javacv05streamtest W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -110 while writing interleaved audio frame.
01-11 11:04:10.209 25574-30435/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:970)
01-11 11:04:10.209 25574-30435/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.recordSamples(FFmpegFrameRecorder.java:935)
01-11 11:04:10.209 25574-30435/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.recordSamples(FFmpegFrameRecorder.java:808)
01-11 11:04:10.209 25574-30435/com.example.javacv05streamtest W/System.err:     at com.example.javacv05streamtest.MainActivity$AudioRecordRunnable.run(MainActivity.java:290)
01-11 11:04:10.209 25574-30435/com.example.javacv05streamtest W/System.err:     at java.lang.Thread.run(Thread.java:818)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -110 while writing interleaved video frame.
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:796)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:686)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:679)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at com.example.javacv05streamtest.MainActivity$2.onPreviewFrame(MainActivity.java:375)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1110)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-11 11:04:10.233 25574-25574/com.example.javacv05streamtest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
01-11 11:04:10.234 25574-25574/com.example.javacv05streamtest W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-11 11:04:10.234 25574-25574/com.example.javacv05streamtest W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-11 11:04:10.234 25574-25574/com.example.javacv05streamtest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-11 11:04:10.235 25574-25574/com.example.javacv05streamtest D/MainActivity: onPreviewFrame()
```

**Comment by saudet** [comment]
Error 110 is "Connection timed out", so it looks like a problem with your network.

**Comment by fifa1016** [comment]
saudet：
I try reconnect again, and it works.  
THANKS.

**Comment by surabhi1694** [comment]
com.googlecode.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -32 while writing interleaved audio frame.

what error is this ? how to solve it ?
