### ISSUE TITLE
ScreenCapture on Windows using `new FFmpegFrameGrabber("screen-capture-recorder");`

### ISSUE THREAD

**Issue by Nackloose** [bytedeco/javacv#31]
Apparently ffmpeg supports screen capture on Windows according to this:
https://trac.ffmpeg.org/wiki/Capture/Desktop

Attempting to do so using:
```
        FrameGrabber grabber = new FFmpegFrameGrabber("screen-capture-recorder");// As well as FFmpegFrameGrabber("UScreenCapture");
        grabber.setFormat("dshow");
        grabber.setFrameRate(30);
        grabber.start();
```

Results in:
```
run:
Exception in thread "main" org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "screen-capture-recorder". (Has setFormat() been called?)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:368)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:318)
	at testarea.JavaCVDemo.main(JavaCVDemo.java:40)
[dshow @ 154dc160] Malformed dshow input string.
[dshow @ 154dc160] Malformed dshow input string.
Java Result: 1
BUILD SUCCESSFUL (total time: 9 seconds)
```

This may possibly have something to do with(maybe???): https://trac.ffmpeg.org/wiki/DirectShow#Specifyinginputframerate

This is here as a resource in case other people experience this error and wish to look into it, as well as a reminder to myself to do so in the future.
If you find any solutions or fixes, please let me know.

**Comment by saudet** [comment]
BTW, would one of you be willing to write a nice wiki page here https://github.com/bytedeco/javacv/wiki to explain how to do screen capture under Windows? Everyone should have write access, so let me know! It would make a great addition, thanks.

**Comment by paksv** [comment]
Sorry for missing the thread. Here's the output: https://gist.github.com/paksv/58ff6022ae72dd2cb8b3

Here's the test java code that works for me: https://gist.github.com/paksv/877c7e87779ed289778d

**Comment by saudet** [comment]
@paksv Could you put this up on the wiki? Everyone has write access, thank you!

**Comment by Nackloose** [comment]
three years later he returns.
It seems you guys figured it out. Glad I could point it out. If I have the time in the next few days I'll try and put your findings up on the wiki.

**Comment by madie89** [comment]
screen recorder works for windows provided you have your desktop input registered as screen recorder. I was facing similar issues. If you run this on ffmpeg CLI. You will get list of input devices. If you see any device listed as screen recorder you can use dshow. Dshow can be used for any input provided the input specified in the call is registered.
https://ffmpeg.org/ffmpeg-devices.html#dshow

              ffmpeg -list_devices true -f dshow -i dummy

For windows GdiGrab should be preferred.
https://ffmpeg.org/ffmpeg-devices.html#gdigrab

just use below code it will work for sure.
              
                FrameGrabber grabber = new FFmpegFrameGrabber("desktop");
                 grabber.setFormat("gdigrab");
                 grabber.setFrameRate(30);
                 grabber.start();

**Comment by saudet** [comment]
@madie89 Great, thanks for the info! Would you also be able to put this up on the wiki?
https://github.com/bytedeco/javacv/wiki
Everyone has write access...

**Comment by Jire** [comment]
@madie89 Thanks so much! Could you explain how to get a `BufferedImage` from the `Frame` (after using `grabber.grabImage()`?

**Comment by saudet** [comment]
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by Jire** [comment]
@saudet Edited my question, but thanks!

**Comment by saudet** [comment]
Windows probably doesn't support that, but ask some Windows forum about that somewhere.

**Comment by Jire** [comment]
@saudet How do I configure options for an `FFmpegFrameGrabber`? I'd like to use the options as shown here: https://ffmpeg.org/ffmpeg-devices.html#Options-7

**Comment by saudet** [comment]
@Jire That would be `FFmpegFrameGrabber.setOption()`.

**Comment by jliu666** [comment]
How to use javacv to ScreenCapture on Mac OS? Thanks!

**Comment by Nackloose** [comment]
@jliu666 it looks like you should be using the 'avfoundation' format [as stated here.](https://www.ffmpeg.org/ffmpeg-devices.html#avfoundation)
This should probably be explained/merged into the wiki page as well.
