### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by coralinejones1985** [bytedeco/javacv#310]
Hi, I get this kind of error on devices, while on emulator everything works fine (proGuard is disabled):
```
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:309)
at org.bytedeco.javacpp.Loader.load(Loader.java:413)
at org.bytedeco.javacpp.Loader.load(Loader.java:381)
at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:123)
at com.wachanga.pregnancy.utils.VideoUtils.downloadVideo(VideoUtils.java:39)
at com.wachanga.pregnancy.activity.CameraSettingsActivity.onClick(CameraSettingsActivity.java:147)
at android.view.View.performClick(View.java:4856)
at android.view.View$PerformClick.run(View.java:19956)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5389)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```
I've already included libraries as described here: https://github.com/bytedeco/javacv
my dependencies:
```groovy
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')
    compile files('libs/ffmpeg.jar')
    compile files('libs/opencv.jar')
    compile files('libs/ffmpeg-android-arm.jar')
    compile files('libs/ffmpeg-android-x86.jar')
    compile files('libs/opencv-android-arm.jar')
    compile files('libs/opencv-android-x86.jar')
```
my code:
```java
public static void downloadVideo(Context context, ArrayList<String> imageUriList) {
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(SDPathToFile("", APP_NAME + "." + FORMAT), 480, 640);
        try {

            OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
            recorder.setFormat(FORMAT);
            recorder.setVideoQuality(0);
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
            recorder.setVideoBitrate(10 * 1024 * 1024);
            recorder.setFrameRate(10);
            recorder.start();

            if (imageUriList.size() < 2) {
                Toast.makeText(context, "Not enough photos for video", Toast.LENGTH_SHORT).show();
                return;
            }

            int stamp = 1000000;
            for (int i = 0; i < imageUriList.size(); i++) {
                String path = getPath(context, Uri.parse(imageUriList.get(i)));
                opencv_core.IplImage image = cvLoadImage(path);
                recorder.setTimestamp(stamp);
                recorder.record(converter.convert(image));
                stamp += 1000000;
                if (i == imageUriList.size() - 1) {
                    recorder.setTimestamp(stamp);
                    recorder.record(converter.convert(image));
                }
            }

            recorder.stop();
            saveVideoToGallery(context);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Comment by saudet** [comment]
Make sure your device installs the native libraries properly:
https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db

**Comment by coralinejones1985** [comment]
Ok, I did the trick from #133 and extracted opencv-android-arm.jar and ffmpeg-android-arm.jar, moved *.so files to "app/src/main/jniLibs/armeabi-v7a" and "app/src/main/jniLibs/armeabi" folders and it seems to work. 
Thank you.
