### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_input_audio_device_next" referenced by "libjniavdevice.so"...

### ISSUE THREAD

**Issue by shirensong** [bytedeco/javacv#33]
When I use FFmpegFrameGrabber function, I met below errors:  
FrameGrabber grabber1 = new FFmpegFrameGrabber("/mnt/sdcard/1.mp4");

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_input_audio_device_next" referenced by "libjniavdevice.so"...
            at java.lang.Runtime.loadLibrary(Runtime.java:361)
            at java.lang.System.loadLibrary(System.java:525)
            at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
            at org.bytedeco.javacpp.Loader.load(Loader.java:410)
            at org.bytedeco.javacpp.Loader.load(Loader.java:353)
            at org.bytedeco.javacpp.avdevice.<clinit>(avdevice.java:18)
            at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:104)
            at com.test.MainActivity.recordImage(MainActivity.java:118)
            at com.test.MainActivity.onCreate(MainActivity.java:67)
            at android.app.Activity.performCreate(Activity.java:5161)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5119)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:749)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Couldn't load gnustl_static from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ltest-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.est-2, /vendor/lib, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:355)
            at java.lang.System.loadLibrary(System.java:525)
            at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
            at org.bytedeco.javacpp.Loader.load(Loader.java:401)
            at org.bytedeco.javacpp.Loader.load(Loader.java:353)
            at org.bytedeco.javacpp.avdevice.<clinit>(avdevice.java:18)
            at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:104)
            at com.test.MainActivity.recordImage(MainActivity.java:118)
            at com.test.MainActivity.onCreate(MainActivity.java:67)
            at android.app.Activity.performCreate(Activity.java:5161)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5119)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:749)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Ragghwendra** [comment]
Hello I have read all the comment above 
 I am try to do the same thing and getting the same kind of error can you please help me to go ahead.
I have android project in which i am trying to convert images to video. 
I have added dependency for this are 
 `**dependencies**
    compile group: 'org.bytedeco', name: 'javacv', version: '0.9'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.9-0.9', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.3-0.9.1-SNAPSHOT', classifier: 'android-arm'

	
**With audio**	
**Error code	**
    FrameGrabber audioGrabber;
	FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(videoPath, context.getResources().getDisplayMetrics().widthPixels, context.getResources().getDisplayMetrics().heightPixels);
    audioGrabber = new FFmpegFrameGrabber(this.audiopath); 
	
	
**Error Log**

  E/art: dlopen("/data/app/com.myApp-2/lib/arm/**libjniavdevice**.so", RTLD_LAZY) failed: dlopen failed: **cannot locate symbol "av_input_audio_device_next" referenced by "libjniavdevice.so"**...
  E/AndroidRuntime: FATAL EXCEPTION: Thread-1
  E/AndroidRuntime: Process: com.myApp, PID: 20176
  E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_input_audio_device_next" referenced by "libjniavdevice.so"...
  E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:371)
  E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:988)
  E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
  E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:410)
  E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:353)
  E/AndroidRuntime:     at org.bytedeco.javacpp.avdevice.<clinit>(avdevice.java:18)
  E/AndroidRuntime:     at org.bytedeco.javacpp.avdevice.avdevice_register_all(Native Method)
  E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:104)
  E/AndroidRuntime:     at com.myApp.TestActivity.makeVideo(TestActivity.java:401)
  E/AndroidRuntime:     at com.myApp.TestActivity.access$300(TestActivity.java:55)
  E/AndroidRuntime:     at com.myApp.TestActivity$RunnableDemo.run(TestActivity.java:689)
  E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
`

Please help me, Waiting for your solution.

**Comment by saudet** [comment]
Try with a newer version; that's been fixed.

**Comment by Ragghwendra** [comment]
hello Saudet, 
    Thanks for the response 

**# Error cause by code** 
	FrameGrabber grabber = new FFmpegFrameGrabber(new File(audioPath));

internaly on this block of **FFmpegFrameGrabber.java** file in package org.bytedeco.javacv;

	static {
        // Register all formats and codecs
        avcodec_register_all();
        avdevice_register_all();
        av_register_all();
        avformat_network_init();
    }

**Error Log**
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_input_audio_device_next" referenced by "libjniavdevice.so"...
  at java.lang.Runtime.loadLibrary(Runtime.java:371)
  at java.lang.System.loadLibrary(System.java:988)
  at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
  at org.bytedeco.javacpp.Loader.load(Loader.java:410)
  at org.bytedeco.javacpp.Loader.load(Loader.java:353)
  at org.bytedeco.javacpp.avdevice.<clinit>(avdevice.java:18)
  at org.bytedeco.javacpp.avdevice.avdevice_register_all(Native Method)
  at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:104)
  
I just come to conclusion that my android project( android studio) **unable to create .so or jniLibs   files**
Can you please send me some link or step to configure this error since **i have manually added the jniLibs** file to project which was copy from another code.


I have try with **another jniLibs** which contain folders
**arm64-v8a**
**armeabi-v7a**
**x86**
then i got the error like 

**Error log**
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.**PathClassLoader[DexPathList[[zip file "/data/app/com.myApp/base.apk"],nativeLibraryDirectories=[/data/app/com.myApp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libjniavutil.so"**
      at java.lang.Runtime.loadLibrary(Runtime.java:366)
      at java.lang.System.loadLibrary(System.java:988)
      at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
      at org.bytedeco.javacpp.Loader.load(Loader.java:410)
      at org.bytedeco.javacpp.Loader.load(Loader.java:353)
      at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
      at java.lang.Class.classForName(Native Method)
      at java.lang.Class.forName(Class.java:309)
      at org.bytedeco.javacpp.Loader.load(Loader.java:385)
      at org.bytedeco.javacpp.Loader.load(Loader.java:353)
      at org.bytedeco.javacpp.avformat.<clinit>(avformat.java:13)
      at org.bytedeco.javacpp.avformat.av_register_all(Native Method)
      at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:106)

I may missing some very simple thing. Please help me to solve this.
If i have use the **newer version so which be better**

**Comment by saudet** [comment]
@Ragghwendra Yes, you are using an old version of the library. Please try the most recent version, and it will work.

**Comment by Ragghwendra** [comment]
Hey Saudet 
Thanks **Its work with new version**
