### ISSUE TITLE
Why I can not use the FFmpegFrameFilter? java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.postproc

### ISSUE THREAD

**Issue by lmylr** [bytedeco/javacv#366]
Why I can not use the FFmpegFrameFilter?
`java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.postproc
                                                                   at java.lang.Class.classForName(Native Method)
                                                                   at java.lang.Class.forName(Class.java:308)
                                                                   at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                                   at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                                   at org.bytedeco.javacpp.avfilter.<clinit>(avfilter.java:17)
                                                                   at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:169)
                                                                   at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)`

This is my code:
`
        mFilter = new FFmpegFrameFilter("transpose=clock", mFrameGrabber.getImageWidth(), mFrameGrabber.getImageHeight());
        try {
            mFilter.start();
        } catch (FrameFilter.Exception e) {
            e.printStackTrace();
        }`

**Comment by saudet** [comment]
Simply remove lines with `postproc.class` from `avfilter.java` and `FFmpegFrameFilter.java` and rebuild those too.
