### ISSUE TITLE
Question: When I use the FFmpegFrameFilter,it print this error! Can you help me?

### ISSUE THREAD

**Issue by lmylr** [bytedeco/javacv#368]
When I use the FFmpegFrameFilter like this.It print an error.
`try {
            mFilter = new FFmpegFrameFilter("crop=w=200:h=100:x=100:y=100", mFrameGrabber.getImageWidth(), mFrameGrabber.getImageHeight());
            mFilter.start();
        } catch (FrameFilter.Exception e) {
            e.printStackTrace();
        }`

`java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.postproc
                                                                     at java.lang.Class.classForName(Native Method)
                                                                     at java.lang.Class.forName(Class.java:308)
                                                                     at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                                     at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                                     at org.bytedeco.javacpp.avfilter.<clinit>(avfilter.java:17)
                                                                     at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:169)
                                                                     at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)`
![qq 20160325125922](https://cloud.githubusercontent.com/assets/8625662/14038324/0c6a2fbe-f28a-11e5-8c18-c9de10012d2d.png)

Can you help me?
Thanks you!

**Comment by lmylr** [comment]
This problem has troubled me for a long time.Anyone can help me?Thank you very much.

**Comment by saudet** [comment]
Could you also who the list of files in your APK? Thanks

**Comment by lmylr** [comment]
Sorry so long to reply.This is a list of files in my APK.
![qq 20160328105217](https://cloud.githubusercontent.com/assets/8625662/14070007/97c3ce58-f4d3-11e5-9b70-3d6e8c67d035.png)
![qq 20160328105254](https://cloud.githubusercontent.com/assets/8625662/14070008/9802c932-f4d3-11e5-8cf6-db1845582619.png)

Thank you. @saudet

**Comment by saudet** [comment]
So it just like the `libpostproc.so` and `libjnipostproc.so` files are missing...

**Comment by lmylr** [comment]
呃呃呃T_T，Thank you very much. @saudet

**Comment by saudet** [comment]
But like I said, if you don't need `postproc`, just remove all the references to it from the source code in Java, and that will work too!
