### ISSUE TITLE
Question to solve this Error :Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by trianindiaputra** [bytedeco/javacv#369]
Hi, @saudet  
i just try to install javaCV 1.1 in android studio and using your sample OpenCVFaceRecognizer. im follow your instruction from this link https://github.com/bytedeco/javacv  but i get error runtime... may you help me to solve this problem... im using OSX 10.11.3
this error : 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
	at org.bytedeco.javacpp.Loader.load(Loader.java:438)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at org.bytedeco.javacpp.Loader.load(Loader.java:413)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13)
	at com.example.trian.myapplication.OpenCVFaceRecognizer.main(OpenCVFaceRecognizer.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
	at org.bytedeco.javacpp.Loader.load(Loader.java:429)
	... 13 more

**Comment by saudet** [comment]
Make sure to include all the JAR files in your class path.

**Comment by trianindiaputra** [comment]
@saudet saudet im already include all the JAR files in class patch like this...

`compile files('libs/ffmpeg.jar')
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')
    compile files('libs/opencv.jar')`

**Comment by saudet** [comment]
That's not all the JAR files. Here's an example for `android-arm`:
https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV#gradle-settings
Now do the same thing for `macosx-x86_64`.

**Comment by trianindiaputra** [comment]
hi @saudet '
its still doesn't work and make new error like this 

Error:Gradle: Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/org.bytedeco/javacpp/pom.properties
  	File1: /Users/Trian/Documents/MyApplication/app/libs/javacpp.jar
  	File2: /Users/Trian/.gradle/caches/modules-2/files-2.1/org.bytedeco/javacpp/1.1/1cc4b5dd88edd3dd3d6f4cdbd3c23c7273ebf0ea/javacpp-1.1.jar

**Comment by saudet** [comment]
There's already being discussed in #353. Please post your questions about that there, thanks.

**Comment by trianindiaputra** [comment]
Big Thanks my bro @saudet  its working....  now im already install javacv 1.1 in my android studio... PROBLEM SOLVED
