### ISSUE TITLE
BufferOverflowException

### ISSUE THREAD

**Issue by mghaffari** [bytedeco/javacv#381]
Hi, I have a problem with get video data:

```
    FATAL EXCEPTION: main
    	Process: org.bytedeco.javacv.recordactivity, PID: 6998
    	java.nio.BufferOverflowException
            at java.nio.Buffer.checkPutBounds(Buffer.java:183)
            at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:356)
            at java.nio.ByteBuffer.put(ByteBuffer.java:721)
            at org.bytedeco.javacv.recordactivity$CameraView.onPreviewFrame(RecordActivity.java:496)
            at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1223)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5272)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

Error refers to this line:

```
    /* get video data */
                if (yuvImage != null && recording) {
                    ((ByteBuffer) yuvImage.image[0].position(0)).put(data);
                    if (RECORD_LENGTH <= 0) try {
                        Log.v(LOG_TAG, "Writing Frame");
                        long t = 1000 * (System.currentTimeMillis() - startTime);
                        if (t > recorder.getTimestamp()) {
                            recorder.setTimestamp(t);
                        }
                        recorder.record(yuvImage);
                    } catch (FFmpegFrameRecorder.Exception e) {
                        Log.v(LOG_TAG, e.getMessage());
                        e.printStackTrace();
                    }
                }
```

You can via the link below to access relevant class file

http://paste.ubuntu.com/15758243/

**Comment by saudet** [comment]
What was the issue?

**Comment by mghaffari** [comment]
@saudet For now solved
