### ISSUE TITLE
labels.getIntBuffer() cause java.lang.NullPointerException

### ISSUE THREAD

**Issue by keai4le** [bytedeco/javacv#403]
as the sample does:
opencv_core.Mat labels = new opencv_core.Mat(imageFiles.length, 1, opencv_core.CV_32SC1);
IntBuffer labelsBuf = labels.getIntBuffer();
when I run this at android M,the app crash:

java.lang.NullPointerException: Attempt to invoke virtual method 'org.bytedeco.javacpp.BytePointer org.bytedeco.javacpp.BytePointer.position(int)' on a null object reference
                                                                             at org.bytedeco.javacpp.helper.opencv_core$AbstractArray.getByteBuffer(opencv_core.java:200)
                                                                             at org.bytedeco.javacpp.helper.opencv_core$AbstractArray.getIntBuffer(opencv_core.java:204)
                                                                             at org.bytedeco.javacpp.helper.opencv_core$AbstractArray.getIntBuffer(opencv_core.java:214)
                                                                             at com.keai4le.fr.facereco.PersonRecognizer.train(PersonRecognizer.java:96)

**Comment by saudet** [comment]
That method is deprecated. Please use createBuffer().

**Comment by keai4le** [comment]
@saudet Thanks,finally I fund that the exception caused by imageFiles.length==0.

**Comment by keai4le** [comment]
@saudet Why not use Vector<int> to save labels but Mat?thanks.

**Comment by saudet** [comment]
We could, please send a pull request with the patch!

**Comment by keai4le** [comment]
@saudet Thanks! if there is a api reference for Javacv？

**Comment by saudet** [comment]
http://bytedeco.org/javacv/apidocs/
http://bytedeco.org/javacpp/apidocs/
http://bytedeco.org/javacpp-presets/opencv/apidocs/
