### ISSUE TITLE
Package Exe with OpenCV natives

### ISSUE THREAD

**Issue by supertick** [bytedeco/javacv#405]
Hi,
Thanks for this great library, its a wonderful service to the community.

I was wondering if it would be possible to package a single OpenCV example executable with the native builds (such as lkdemo).  Since some of the native error messages do not always propagate to the Java application layer, it would save considerable time and effort to be able to run a native application built with the opencv libraries to quickly flush out problems.

This strategy works on all platforms without the need for development tools like Dependency Walker.

Troubleshooting step would be :
     1. Unzip the jar, run the exe, look at the error message, resolve.

Regards,
Greg

**Comment by saudet** [comment]
BTW, this is only a problem on Windows. I would rather have Oracle fix that in the JDK, so could you report that upstream to them?

**Comment by supertick** [comment]
It has been my experience (at least in the past) dependencies missing in Linux do not always get reported in Java-land.  It has not always been a Windows problem.

But, I'm speaking about my experience in the past. Perhaps this has changed?

**Comment by saudet** [comment]
Yes, it reports them just fine on Linux. For example, if I move the library for FlyCapture and try to run something that uses the API, I get the following exception:
```
java.lang.UnsatisfiedLinkError: no jniFlyCapture2 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:636)
	at org.bytedeco.javacpp.Loader.load(Loader.java:474)
	at org.bytedeco.javacpp.Loader.load(Loader.java:411)
	at org.bytedeco.javacpp.FlyCapture2.<clinit>(FlyCapture2.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:446)
	at org.bytedeco.javacpp.Loader.load(Loader.java:411)
	at org.bytedeco.javacpp.FlyCapture2$FC2Version.<clinit>(FlyCapture2.java:709)
	at FlyCapture2Test.PrintBuildInfo(FlyCapture2Test.java:28)
	at FlyCapture2Test.main(FlyCapture2Test.java:135)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp3216546462129/libjniFlyCapture2.so: libflycapture.so.2: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:619)
	... 16 more
```

**Comment by saudet** [comment]
It looks like we can get back the useful dialog on Windows by calling `SetErrorMode(0)`:
http://stackoverflow.com/questions/4265874/attempting-to-load-a-dll-on-windows-using-loadlibrary-when-a-dependent-dll-is-mi
I'm not sure when the JVM disables it, but could you try to output it somewhere in the generated C++ code (by modifying `Generator.java`) and see if we can get something useful that way? I think that would be the ideal solution.

**Comment by saudet** [comment]
Looks like we might have to create our own little custom `java.exe` if we want to do that. BTW, it would be something useful for developers to use with AddressSanitizer as well: https://github.com/google/sanitizers/issues/271

Want to give it a try? It's really easy with JavaCPP to cook up without even touching raw JNI:
https://github.com/bytedeco/javacpp#creating-callback-functions

**Comment by saudet** [comment]
Actually, it does not seem possible to do anything when calling `LoadLibrary()`:
https://blogs.msdn.microsoft.com/oldnewthing/20131127-00/?p=2553

BTW, what about http://www.dependencywalker.com/? It basically does exactly what you're asking here.

**Comment by saudet** [comment]
Here's a neat trick:
1. Download http://www.dependencywalker.com/depends22_x64.zip and extract it somewhere
2. Call the following at the beginning of the `main()` method:
```java
try {
    Loader.load(opencv_core.class);
} catch (UnsatisfiedLinkError e) {
    new ProcessBuilder("c:/path/to/depends.exe", Loader.getTempDir() + "/jniopencv_core.dll").start().waitFor();
}
```
And a nice window telling you what the problem is pops up right away!

@supertick Would this resolve this issue?

**Comment by saudet** [comment]
I've created a new wiki page with this info assuming it resolves this issue:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

Thanks for the feedback!
