### ISSUE TITLE
UnsatisfiedLinkError, thanks

### ISSUE THREAD

**Issue by junyongyou** [bytedeco/javacv#420]
I did everything as in the tutorial. I tried with Gradle first, and another try was to clone the code from here and then create a new project based on POM. I tried them both in Intellij. However, when I ran the test code, I both got the exceptions. I am using JDK64 and under windows7. Is there something I did wrong? Thanks a lot.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
    at org.bytedeco.javacpp.Loader.load(Loader.java:492)
    at org.bytedeco.javacpp.Loader.load(Loader.java:409)
    at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.bytedeco.javacpp.Loader.load(Loader.java:464)
    at org.bytedeco.javacpp.Loader.load(Loader.java:409)
    at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13)
    at org.bytedeco.javacv.Test.main(Test.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc310 in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
    at org.bytedeco.javacpp.Loader.load(Loader.java:483)
    ... 13 more
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
```

**Comment by saudet** [comment]
Are you saying that even this stitching sample as is does not work?
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#sample-usage

**Comment by saudet** [comment]
Given the lack of feedback, I am assuming you got it working, but please let me know if you still have trouble, thanks!

**Comment by RohitDeshmukh-1997** [comment]
Try Figuring Out your Os architecture whether it is x86 or 64 bit and use the corresponding jar files
For x86 Use jar files :
opencv-2.4.8-windows-x86.jar
javacv-windows-x86.jar
ffmpeg-2.1.1-windows-x86.jar

For 64 Use jar files :
opencv-2.4.8-windows-x86_64.jar
javacv-windows-x86_64.jar
ffmpeg-2.1.1-windows-x86_64.jar
