### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "../../lib/libtbb.so" not found

### ISSUE THREAD

**Issue by findxain** [bytedeco/javacv#434]
I am using javaCV 0.3 when i change target sdk to 23 then app crash on nexus device but works well on other devices. Kindly help guys  due to playstore restriction i cannot downgrade to target sdk 22 i have to stick with 23. :(
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.streamer, PID: 30984
                                                              java.lang.UnsatisfiedLinkError: dlopen failed: library "../../lib/libtbb.so" not found
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                  at java.lang.System.loadLibrary(System.java:1076)
                                                                  at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:701)
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:578)
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:532)
                                                                  at com.googlecode.javacv.cpp.opencv_core.<clinit>(opencv_core.java:134)
                                                                  at java.lang.Class.classForName(Native Method)
                                                                  at java.lang.Class.forName(Class.java:324)
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:553)
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:532)
                                                                  at com.googlecode.javacv.cpp.opencv_core$CvArr.<clinit>(opencv_core.java:156)
                                                                  at com.streamer.MainActivity$CameraView.surfaceChanged(MainActivity.java:348)
                                                                  at android.view.SurfaceView.updateWindow(SurfaceView.java:594)
                                                                  at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
                                                                  at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2063)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "../../lib/libtbb.so" not found
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                  at java.lang.System.loadLibrary(System.java:1076)
                                                                  at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:701)
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:569)
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:532) 
                                                                  at com.googlecode.javacv.cpp.opencv_core.<clinit>(opencv_core.java:134) 
                                                                  at java.lang.Class.classForName(Native Method) 
                                                                  at java.lang.Class.forName(Class.java:324) 
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:553) 
                                                                  at com.googlecode.javacpp.Loader.load(Loader.java:532) 
                                                                  at com.googlecode.javacv.cpp.opencv_core$CvArr.<clinit>(opencv_core.java:156) 
                                                                  at com.streamer.MainActivity$CameraView.surfaceChanged(MainActivity.java:348) 
                                                                  at android.view.SurfaceView.updateWindow(SurfaceView.java:594) 
                                                                  at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177) 
                                                                  at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944) 
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2063) 
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115) 
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023) 
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858) 
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606) 
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by saudet** [comment]
Could you try again with JavaCV 1.2?

**Comment by findxain** [comment]
@saudet  can you please give link of javacv 1.2 ? because i only found 0.3 :(

**Comment by saudet** [comment]
https://github.com/bytedeco/javacv#downloads

**Comment by findxain** [comment]
Dear i used exactly the same but did't work :(

**Comment by saudet** [comment]
Make sure to use JavaCPP 1.2.1 though: https://github.com/bytedeco/javacv/issues/412

**Comment by findxain** [comment]
@saudet im using the latest version it works on mostly devices but the same build doesnot work on X64 architecture ...and the second thing when i change the target sdk from 23 to 22 it works fine on all the devices but going beyond 22 it crash and gives the same error on x64 device like motrola droid, note 5, etc

**Comment by saudet** [comment]
Maybe your 64-bit devices don't support 32-bit binaries, it's possible. Marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/52
https://github.com/bytedeco/javacv/issues/467
etc

**Comment by saudet** [comment]
And the problem with SDK > 22 is already fixed so please update to the latest version: https://github.com/bytedeco/javacv/issues/245

**Comment by saudet** [comment]
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/

**Comment by 9729806859** [comment]
Hello dear I am also facing the same issue can anyone help me for solving this issue. or if anyone have the working code of Facerecognition android application then please send me ASAP on my emailId mentioned below:-

rajattyagi.anything@gmail.com

**Comment by agiratech-sankar** [comment]
Hi saudet,

I couldn't fix this issue - dlopen failed: library "../../lib/libtbb.so" not found.
Kindly share me the step by step process. my emailId mentioned 

Sankardev73@gmail.com

**Comment by saudet** [comment]
@9729806859 @agiratech-sankar This is fixed, just use the latest version.
