### ISSUE TITLE
Unable to run RecordActivity.java (Exception thrown)

### ISSUE THREAD

**Issue by ywj7931** [bytedeco/javacv#440]
**I tried to install on my adnroid, but when i open the app, it throws exception; when click record button, it throws exception again and force quit.
Can anyone help me?**

Log:
06-26 18:49:30.135 11916-11916/org.bytedeco.javacv.recordactivity I/RecordActivity: cameara open
06-26 18:49:30.155 11916-11926/org.bytedeco.javacv.recordactivity W/art: Suspending all threads took: 6.857ms
06-26 18:49:30.165 11916-11916/org.bytedeco.javacv.recordactivity W/camera: camera view
06-26 18:49:30.165 11916-11916/org.bytedeco.javacv.recordactivity I/RecordActivity: cameara preview start: OK
06-26 18:49:30.175 11916-11916/org.bytedeco.javacv.recordactivity D/Atlas: Validating map...
06-26 18:49:30.195 11916-12003/org.bytedeco.javacv.recordactivity I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030_msm8974_refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030__release_AU ()
                                                                                OpenGL ES Shader Compiler Version: E031.25.03.00
                                                                                Build Date: 12/11/14 Thu
                                                                                Local Branch: 
                                                                                Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030
                                                                                Local Patches: NONE
                                                                                Reconstruct Branch: NOTHING
06-26 18:49:30.245 11916-11916/org.bytedeco.javacv.recordactivity V/RecordActivity: Changed to supported resolution: 320x240
06-26 18:49:30.245 11916-11916/org.bytedeco.javacv.recordactivity V/RecordActivity: Setting imageWidth: 320 imageHeight: 240 frameRate: 30
06-26 18:49:30.255 11916-11916/org.bytedeco.javacv.recordactivity V/RecordActivity: Preview Framerate: 30
06-26 18:49:31.075 11916-11916/org.bytedeco.javacv.recordactivity I/Camera: hasFeature com.htc.vtetrue
06-26 18:49:31.185 11916-11916/org.bytedeco.javacv.recordactivity I/Choreographer: Skipped 56 frames!  The application may be doing too much work on its main thread.
06-26 18:49:31.245 11916-11916/org.bytedeco.javacv.recordactivity D/Camera: HTC_CALLBACK: callbackType=12 arg1=0 arg2=0 mHtcCallback=null
06-26 18:49:31.905 11916-11916/org.bytedeco.javacv.recordactivity I/Camera: hasFeature com.htc.vtetrue
06-26 18:49:31.905 11916-11916/org.bytedeco.javacv.recordactivity I/Camera: hasFeature com.htc.vtetrue
06-26 18:49:32.275 11916-11916/org.bytedeco.javacv.recordactivity I/RecordActivity: cameara open
06-26 18:49:32.275 11916-11916/org.bytedeco.javacv.recordactivity W/camera: camera view
06-26 18:49:32.275 11916-11916/org.bytedeco.javacv.recordactivity I/RecordActivity: cameara preview start: OK
06-26 18:49:32.405 11916-11916/org.bytedeco.javacv.recordactivity I/Choreographer: Skipped 72 frames!  The application may be doing too much work on its main thread.
06-26 18:49:32.455 11916-11916/org.bytedeco.javacv.recordactivity V/RecordActivity: Changed to supported resolution: 320x240
06-26 18:49:32.455 11916-11916/org.bytedeco.javacv.recordactivity V/RecordActivity: Setting imageWidth: 320 imageHeight: 240 frameRate: 30
06-26 18:49:32.455 11916-11916/org.bytedeco.javacv.recordactivity V/RecordActivity: Preview Framerate: 30
06-26 18:49:33.255 11916-11916/org.bytedeco.javacv.recordactivity I/Camera: hasFeature com.htc.vtetrue
06-26 18:49:33.265 11916-11916/org.bytedeco.javacv.recordactivity I/Choreographer: Skipped 51 frames!  The application may be doing too much work on its main thread.
06-26 18:49:33.295 11916-11916/org.bytedeco.javacv.recordactivity D/Camera: HTC_CALLBACK: callbackType=12 arg1=0 arg2=0 mHtcCallback=null
06-26 18:49:36.865 11916-11916/org.bytedeco.javacv.recordactivity W/RecordActivity: init recorder
06-26 18:49:36.945 11916-11916/org.bytedeco.javacv.recordactivity I/RecordActivity: ffmpeg_url: /mnt/sdcard/stream.flv
06-26 18:49:37.265 11916-11916/org.bytedeco.javacv.recordactivity I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
06-26 18:49:37.265 11916-11916/org.bytedeco.javacv.recordactivity E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: org.bytedeco.javacv.recordactivity, PID: 11916
                                                                                    java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                        at java.lang.Class.classForName(Native Method)
                                                                                        at java.lang.Class.forName(Class.java:308)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:464)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
                                                                                        at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
                                                                                        at **org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                                        at org.bytedeco.javacv.recordactivity.RecordActivity.initRecorder(RecordActivity.java:177)
                                                                                        at org.bytedeco.javacv.recordactivity.RecordActivity.startRecording(RecordActivity.java:192)
                                                                                        at org.bytedeco.javacv.recordactivity.RecordActivity.onClick(RecordActivity.java:488)**
                                                                                        at android.view.View.performClick(View.java:4785)
                                                                                        at android.view.View$PerformClick.run(View.java:19858)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:155)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
06-26 18:49:39.955 11916-11916/org.bytedeco.javacv.recordactivity D/Process: killProcess, pid=11916
06-26 18:49:39.955 11916-11916/org.bytedeco.javacv.recordactivity D/Process: com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 
06-26 18:50:34.795 12988-12988/org.bytedeco.javacv.recordactivity I/RecordActivity: cameara open
06-26 18:50:34.815 12988-12988/org.bytedeco.javacv.recordactivity W/camera: camera view
06-26 18:50:34.815 12988-12988/org.bytedeco.javacv.recordactivity I/RecordActivity: cameara preview start: OK
06-26 18:50:34.825 12988-12988/org.bytedeco.javacv.recordactivity D/Atlas: Validating map...
06-26 18:50:34.865 12988-13062/org.bytedeco.javacv.recordactivity I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030_msm8974_refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030__release_AU ()
                                                                                OpenGL ES Shader Compiler Version: E031.25.03.00
                                                                                Build Date: 12/11/14 Thu
                                                                                Local Branch: 
                                                                                Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030
                                                                                Local Patches: NONE
                                                                                Reconstruct Branch: NOTHING
06-26 18:50:34.915 12988-12988/org.bytedeco.javacv.recordactivity V/RecordActivity: Changed to supported resolution: 320x240
06-26 18:50:34.915 12988-12988/org.bytedeco.javacv.recordactivity V/RecordActivity: Setting imageWidth: 320 imageHeight: 240 frameRate: 30
06-26 18:50:34.915 12988-12988/org.bytedeco.javacv.recordactivity V/RecordActivity: Preview Framerate: 30
06-26 18:50:35.645 12988-12988/org.bytedeco.javacv.recordactivity I/Camera: hasFeature com.htc.vtetrue
06-26 18:50:35.655 12988-12988/org.bytedeco.javacv.recordactivity I/Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
06-26 18:50:35.705 12988-12988/org.bytedeco.javacv.recordactivity D/Camera: HTC_CALLBACK: callbackType=12 arg1=0 arg2=0 mHtcCallback=null
06-26 18:50:53.475 12988-12988/org.bytedeco.javacv.recordactivity W/RecordActivity: init recorder
06-26 18:50:53.575 12988-12988/org.bytedeco.javacv.recordactivity I/RecordActivity: ffmpeg_url: /mnt/sdcard/stream.flv
06-26 18:50:53.935 12988-12988/org.bytedeco.javacv.recordactivity I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
06-26 18:50:53.935 12988-12988/org.bytedeco.javacv.recordactivity E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: org.bytedeco.javacv.recordactivity, PID: 12988
                                                                                    java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                        at java.lang.Class.classForName(Native Method)
                                                                                        at java.lang.Class.forName(Class.java:308)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:464)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
                                                                                        at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
                                                                                        at **org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                                        at org.bytedeco.javacv.recordactivity.RecordActivity.initRecorder(RecordActivity.java:177)
                                                                                        at org.bytedeco.javacv.recordactivity.RecordActivity.startRecording(RecordActivity.java:192)
                                                                                        at org.bytedeco.javacv.recordactivity.RecordActivity.onClick(RecordActivity.java:488)**
                                                                                        at android.view.View.performClick(View.java:4785)
                                                                                        at android.view.View$PerformClick.run(View.java:19858)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:155)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
06-26 18:50:56.305 12988-12988/org.bytedeco.javacv.recordactivity D/Process: killProcess, pid=12988
06-26 18:50:56.305 12988-12988/org.bytedeco.javacv.recordactivity D/Process: com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 

**Just to make sure if I install correct, I only copy, for example, opencv.jar and opencv-android-arm.jar(mine is htc one m8)
here is my build.gradle**

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "org.bytedeco.javacv.recordactivity"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
   // compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile files('libs/javacv.jar')
    compile files('libs/ffmpeg.jar')
    compile files('libs/flandmark.jar')
    compile files('libs/libfreenect.jar')
    compile files('libs/javacpp.jar')
    compile files('libs/artoolkitplus.jar')
    compile files('libs/libdc1394.jar')
    compile files('libs/flycapture.jar')
    compile files('libs/opencv.jar')
    compile files('libs/videoinput.jar')
}
`

**Comment by saudet** [comment]
You'll need to add the android JAR files to your build file.

**Comment by ywj7931** [comment]
@saudet 
Thanks for the speedy reply,
what do you mean?
I copy all .jar file except windows, linux, mac, android-x86 into my lib
and then in android studio, I right click those files and choose "add as library",
Did I do wrong>

**Comment by ywj7931** [comment]
Should I import all jar files including windows mac and android-x86?
Now I only import regular and android-arm ones

**Comment by saudet** [comment]
No, you're probably hitting this bug in Android Studio: https://github.com/bytedeco/javacv/issues/133  Follow the work around explained there and it should work.
