### ISSUE TITLE
Could not open 'rtsp://...' (Wowza) - avio_open error()

### ISSUE THREAD

**Issue by bajicdusko** [bytedeco/javacv#443]
Hello,

I am using AndroidStudio. Target compatibility is SDK23. I have downloaded latest jar files for javacv (1.2), javacpp(1.2.1), ffmpeg, and latest .so files.

This is how my gradle looks like.

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.example.javacv05streamtest"
        minSdkVersion 18
        targetSdkVersion 23
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    configurations {
        all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
    }

    packagingOptions {
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
    }
}

dependencies {
    compile 'com.android.support:support-v4:23.3.0'
    compile files('libs/ffmpeg-android-arm.jar')
    compile files('libs/ffmpeg-android-x86.jar')
    compile files('libs/ffmpeg.jar')
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')
}
```

I am using RecordActivity from samples, and i have not changed anything, except ffmpeg_url value.
When i use file system path and execute recording, file is created without errors.

But when i set rtsp url as ffmped_url value, i am getting error below:

Url:
`private String ffmpeg_link = "rtsp://192.168.0.35:1935/live/android";`

Recorder setting (note that i have replaced format to 'mp4'
```
Log.i(LOG_TAG, "ffmpeg_url: " + ffmpeg_link);
//recorder = new FFmpegFrameRecorder(Environment.getExternalStorageDirectory() + "/recording.mp4", imageWidth, imageHeight, 1);
recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);
recorder.setFormat("mp4");
recorder.setSampleRate(sampleAudioRateInHz);
```

Stacktrace:
```
06-29 13:17:01.860 6174-6174/? I/art: Late-enabling -Xcheck:jni
06-29 13:17:02.252 6174-6174/com.example.javacv05streamtest I/RecordActivity: cameara open
06-29 13:17:02.253 6174-6174/com.example.javacv05streamtest W/camera: camera view
06-29 13:17:02.254 6174-6174/com.example.javacv05streamtest I/RecordActivity: cameara preview start: OK
06-29 13:17:02.263 6174-6224/com.example.javacv05streamtest D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
06-29 13:17:02.994 6174-6174/com.example.javacv05streamtest I/RecordActivity: cameara open
06-29 13:17:02.995 6174-6174/com.example.javacv05streamtest W/camera: camera view
06-29 13:17:02.995 6174-6174/com.example.javacv05streamtest I/RecordActivity: cameara preview start: OK
06-29 13:17:03.004 6174-6174/com.example.javacv05streamtest I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
06-29 13:17:03.017 6174-6224/com.example.javacv05streamtest I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
06-29 13:17:03.019 6174-6224/com.example.javacv05streamtest I/OpenGLRenderer: Initialized EGL, version 1.4
06-29 13:17:03.051 6174-6174/com.example.javacv05streamtest V/RecordActivity: Changed to supported resolution: 320x240
06-29 13:17:03.051 6174-6174/com.example.javacv05streamtest V/RecordActivity: Setting imageWidth: 320 imageHeight: 240 frameRate: 30
06-29 13:17:03.051 6174-6174/com.example.javacv05streamtest V/RecordActivity: Preview Framerate: 30
06-29 13:17:11.342 6174-6174/com.example.javacv05streamtest W/RecordActivity: init recorder
06-29 13:17:11.387 6174-6174/com.example.javacv05streamtest I/RecordActivity: ffmpeg_url: rtsp://192.168.0.35:1935/live/android
06-29 13:17:11.546 6174-6174/com.example.javacv05streamtest W/linker: /data/app/com.example.javacv05streamtest-1/lib/arm/libjniavutil.so: unused DT entry: type 0x1d arg 0x17f1f
06-29 13:17:11.648 6174-6174/com.example.javacv05streamtest W/linker: /data/app/com.example.javacv05streamtest-1/lib/arm/libjniswresample.so: unused DT entry: type 0x1d arg 0x2b2d
06-29 13:17:11.740 6174-6174/com.example.javacv05streamtest W/linker: /data/app/com.example.javacv05streamtest-1/lib/arm/libjniavcodec.so: unused DT entry: type 0x1d arg 0x19493
06-29 13:17:11.873 6174-6174/com.example.javacv05streamtest W/linker: /data/app/com.example.javacv05streamtest-1/lib/arm/libjniavformat.so: unused DT entry: type 0x1d arg 0x1761c
06-29 13:17:12.030 6174-6174/com.example.javacv05streamtest W/linker: /data/app/com.example.javacv05streamtest-1/lib/arm/libjniswscale.so: unused DT entry: type 0x1d arg 0x3cb4
06-29 13:17:12.141 6174-6174/com.example.javacv05streamtest I/RecordActivity: recorder initialize success
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -1330794744: Could not open 'rtsp://192.168.0.35:1935/live/android'
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:700)
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:294)
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at com.example.javacv05streamtest.RecordActivity.startRecording(RecordActivity.java:259)
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at com.example.javacv05streamtest.RecordActivity.onClick(RecordActivity.java:636)
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at android.view.View.performClick(View.java:5204)
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at android.view.View$PerformClick.run(View.java:21153)
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
06-29 13:17:12.463 6174-6174/com.example.javacv05streamtest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-29 13:17:12.464 6174-6174/com.example.javacv05streamtest W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-29 13:17:12.464 6174-6174/com.example.javacv05streamtest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-29 13:17:12.464 6174-6174/com.example.javacv05streamtest W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-29 13:17:12.464 6174-6174/com.example.javacv05streamtest W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-29 13:17:12.464 6174-6174/com.example.javacv05streamtest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-29 13:17:12.464 6174-6174/com.example.javacv05streamtest W/RecordActivity: Start Button Pushed
```

Result is the same whether source authentication is turned on or off. I have tested this endpoint with GoCoder app (which is wowza official), and stream is working as it should.

**Comment by bajicdusko** [comment]
To answer to myself, by changing protocol to RTMP, i do not have avio_open_error. Instead it looks like streaming starts to run, (a lot ot "V/RecordActivity: bufferReadResult: 3584" messages in console) which is message from AudioRecordRunnable.

Additional problem is that stream cannot be played. Wowza reports that there is a connection on RTMP, but size of incoming data is way to small for video stream. Its starts to work, but after a minute, wowza reports thats stream stopped. But, android console keeps running with messages from above.

![image](https://cloud.githubusercontent.com/assets/1321796/16451700/dca8a942-3e04-11e6-999b-fd865c8069ab.png)

I really dont know what to do right now. Here is additional setting for stream encoding:

```
recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);
recorder.setFormat("mp4");
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setVideoBitrate(500 * 1000);
recorder.setAudioBitrate(8 * 1000);
//recorder.setAudioChannels(1);
recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
recorder.setSampleRate(44100);
// Set in the surface changed method
recorder.setFrameRate(20);
```

**Comment by bajicdusko** [comment]
And once again, to answer to myself, stream was not working because of this line:

`long startTime = 10;`

should be changed to 0, in order to stream continuously

**Comment by saudet** [comment]
Ok, cool. I don't see where `startTime` gets used in your code, but good to know! Thanks

**Comment by bajicdusko** [comment]
@saudet I have edited my answer above, lapsus. I have pushed [boilerplate](https://github.com/bajicdusko/JavaCVWowzaStarterKit) app for JavaCV-Wowza (i hope its ok with you?). Thank you very much for your work btw, really appreciate it! 

I still do have some issues with arm-v7 chips. 
As you can see in project, i have manually imported jar (javacpp-1.2.1, javacv-1.2, ffmpeg) files and manually extracted .so files for armeabi and x86 (from ffmpeg-android-arm and ffmpeg-android-x86 archives). Additionaly, i have copied .so files from armeabi to armeabi-v7a (identical files).

When initiating recording on armv7 device, i am getting:

`Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bytedeco.javacpp.avutil" on path: DexPathList`

I saw other issues with same error, but it seams that all solutions does not make change in my case. Could you give me a hand on this one also. Thank you.

**Comment by saudet** [comment]
Sounds like an issue with ProGuard: https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV

**Comment by saudet** [comment]
Hey BTW, if you could submit your "boilerplate" to this repo, it'd be awesome: https://github.com/bytedeco/sample-projects

**Comment by bajicdusko** [comment]
I wish that it would be proguard, but i am not obfuscating my code (not yet), as visible here: [build.gradle](https://github.com/bajicdusko/JavaCVWowzaStarterKit/blob/master/app/build.gradle). 

As for boilerplate/starterkit submit, i'd be honored to do :). I'll fix few issues, that i am aware of and i'll PR it to you.

**Comment by bajicdusko** [comment]
@saudet i still have this issue with class not found. As you can see in my previous answer, proguard should not be issue since i am not minifyng code on publish..

**Comment by saudet** [comment]
Maybe your device is not capable of installing native libraries properly:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-(a-real-experience)
