### ISSUE TITLE
ELF file OS ABI invalid

### ISSUE THREAD

**Issue by Sheepzez** [bytedeco/javacv#457]
I'm receiving an error running my JavaCV program on a different host than my local machine. 

It works on my local machine which uses Linux kernel 4.2, but the new host uses 4.4.5 (could this be the source of the error?). Or is the issue just a path one?

I'm using the pre-built binaries.

Caused an ERROR
      no jniopencv_core in java.library.path
      java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
          at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
          at java.lang.Runtime.loadLibrary0(Runtime.java:870)
          at java.lang.System.loadLibrary(System.java:1122)
          at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
          at org.bytedeco.javacpp.Loader.load(Loader.java:492)
          at org.bytedeco.javacpp.Loader.load(Loader.java:409)
          at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
          at java.lang.Class.forName0(Native Method)
          at java.lang.Class.forName(Class.java:348)
          at org.bytedeco.javacpp.Loader.load(Loader.java:464)
          at org.bytedeco.javacpp.Loader.load(Loader.java:409)
          at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13)
          at ...
      Caused by: java.lang.UnsatisfiedLinkError: /.../libjniopencv_core.so: /.../libopencv_imgproc.so.3.1: ELF file OS ABI invalid
          at java.lang.ClassLoader$NativeLibrary.load(Native Method)
          at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
          at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
          at java.lang.Runtime.load0(Runtime.java:809)
          at java.lang.System.load(System.java:1086)
          at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637) 

Any debug help is greatly appreciated.

**Comment by saudet** [comment]
It's not a kernel issue, but something related to the loader. Not sure what the issue is here, but it looks like your new Linux distribution doesn't support binaries compiled in CentOS. Can you confirm this?

**Comment by saudet** [comment]
Could you try again with the just released JavaCV 1.3?

**Comment by Sheepzez** [comment]
Unfortunately I'm no longer working on a project using this library, and don't have the source code for it previously. So I can't reproduce. Feel free to close if you feel this isn't an issue anymore.
