### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by balatextcomputing** [bytedeco/javacv#48]
i'm using javacv 0.9 and installed opencv2.4.9, 

i have C:\opencv\build\x64\vc10\bin; in my windows system path

Am i  missing anything ? please guide

i'm getting the following error when i tried to run an example

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1738)
    at java.lang.Runtime.loadLibrary0(Runtime.java:823)
    at java.lang.System.loadLibrary(System.java:1028)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
    at org.bytedeco.javacpp.Loader.load(Loader.java:410)
    at org.bytedeco.javacpp.Loader.load(Loader.java:353)
    at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.bytedeco.javacpp.Loader.load(Loader.java:385)
    at org.bytedeco.javacpp.Loader.load(Loader.java:353)
    at org.bytedeco.javacpp.opencv_highgui.<clinit>(opencv_highgui.java:13)
    at draw.main(draw.java:10)
Caused by: java.lang.UnsatisfiedLinkError: C:\opencv\build\x64\vc10\bin\opencv_core249.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1807)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1732)
    at java.lang.Runtime.loadLibrary0(Runtime.java:823)
    at java.lang.System.loadLibrary(System.java:1028)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
    at org.bytedeco.javacpp.Loader.load(Loader.java:401)
    ... 8 more

**Comment by HADES-S** [comment]
I have faced the same problem when i call the Frame convert function


java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.pathat java.lang.ClassLoader.loadLibrary(ClassLoader.java:1897)at java.lang.Runtime.loadLibrary0(Runtime.java:882)at java.lang.System.loadLibrary(System.java:1143)at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)at org.bytedeco.javacpp.Loader.load(Loader.java:764)at org.bytedeco.javacpp.Loader.load(Loader.java:671)at org.bytedeco.javacpp.opencv_core.(opencv_core.java:10)at java.lang.Class.forName0(Native Method)at java.lang.Class.forName(Class.java:348)at org.bytedeco.javacpp.Loader.load(Loader.java:726)at org.bytedeco.javacpp.Loader.load(Loader.java:671)at org.bytedeco.javacpp.helper.opencv_core$AbstractArray.(opencv_core.java:109)at org.bytedeco.javacv.OpenCVFrameConverter.convertToIplImage(OpenCVFrameConverter.java:91)at org.bytedeco.javacv.OpenCVFrameConverter$ToIplImage.convert(OpenCVFrameConverter.java:44)
--

**Comment by saudet** [comment]
@HADES-S Please try to follow the instructions in the README.md file. If you are still have problems after that, let me know, thanks!

**Comment by 805447391** [comment]
I have this same error today.
When I use Intellij IDEA to make Artifacts to my file system, i got a jar package.
But when i run this jar using code ```java -jar Face.jar```,I got :
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1191)
        at org.bytedeco.javacpp.Loader.load(Loader.java:953)
        at org.bytedeco.javacpp.Loader.load(Loader.java:854)
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:913)
        at org.bytedeco.javacpp.Loader.load(Loader.java:854)
        at org.bytedeco.javacpp.opencv_core$RectVector.<clinit>(opencv_core.java:405)
        at ui.PreviewFrame.<init>(PreviewFrame.java:32)
        at Launcher.main(Launcher.java:18)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc340 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1191)
        at org.bytedeco.javacpp.Loader.load(Loader.java:940)
```
AND: In my home dir, do not contains any javacpp cache files, in other words, C:\User\{MY_DIR}\.javacpp\cache is a empty folder 👎 
So I guess its happend with some preblems when extract *.so or *.dll file when Class is Loading.
Please note me, thanks very much!

**Comment by 805447391** [comment]
By the way, extracts all library such as *.so to the folder contains  built jar file and run ```java -jar this.jar``` is OK. so this problem maybe related to these *.so files.
tks

**Comment by saudet** [comment]
You need to put ALL the JAR files in your class path.

**Comment by 805447391** [comment]
@saudet you are right
I have found where error is just now, i am using 32 bit JRE but configure 64 bit binary library in my system, so JavaCPP do not call Loader.cacheResource() normally so that cache dir do not contains platform package, when i using 64 bit JRE or maven depend 'opencv-platform', it will download all supported platform library jar pack to local maven repo, re run this, worked will ~
very thanks for your reply~have a nice day.

**Comment by saudet** [comment]
@SnehaJagtap For some reason `opencv-3.4.1-1.4.1-windows-x86_64.jar` is missing from your class path, so please add it manually.

**Comment by SnehaJagtap** [comment]
Ok. Thank you, sir. 
Could you please provide me the steps for manually adding this jar file?. Actually, I am new user for a dl4j library as well as IntelliJ.

**Comment by RohitDeshmukh-1997** [comment]
Try Figuring Out your Os architecture whether it is x86 or 64 bit and use the corresponding jar files
For x86 Use jar files :
opencv-2.4.8-windows-x86.jar
javacv-windows-x86.jar
ffmpeg-2.1.1-windows-x86.jar

For 64 Use jar files :
opencv-2.4.8-windows-x86_64.jar
javacv-windows-x86_64.jar
ffmpeg-2.1.1-windows-x86_64.jar
