### ISSUE TITLE
Mat Indexer IndexOutOfBounds Exception

### ISSUE THREAD

**Issue by Luonic** [bytedeco/javacv#483]
Hello
I occurred strange problem, with all checks my code goes out of bounds
I am using javacv 1.2 with javacpp 1.2.3 and Android 6.0.1 
Here is some code:
```java
private static Mat calculateFrame(Mat sourceFrameMat, Mat opticalFlow, int frameIndex, int totalFrames) {
        //Creating indexer for calculated optical flow
        UByteBufferIndexer opticalFlowIndexer = opticalFlow.createIndexer();

        //Creatring indexer for source matrix
        UByteBufferIndexer sourceFrameMatIndexer = sourceFrameMat.createIndexer();

        //Matrix and indexer for destination matrix
        Mat dstFrameMat = sourceFrameMat.clone();
        UByteBufferIndexer dstFrameMatIndexer = dstFrameMat.createIndexer();

        for (long y = 0; y < sourceFrameMat.arrayHeight(); y++) {
            for (long x = 0; x < sourceFrameMat.arrayWidth(); x++) {
                int flowVecX = opticalFlowIndexer.get(x, y, 0);
                int flowVecY = opticalFlowIndexer.get(x, y, 1);

                //If index not out of bounds
                int matW = sourceFrameMat.arrayWidth();
                int matH = sourceFrameMat.arrayHeight();

                if (x + flowVecX < matW &&
                        y + flowVecY < matH) {
                    Log.d("Point", "X=" + x + " Y=" + y + " FlowX=" + flowVecX + " FlowY=" + flowVecY);
                    //Moving pixels by channel
                    for (int c = 0; c < sourceFrameMat.channels(); c++) {
                        //Getting value of channel "c"
                        int val = sourceFrameMatIndexer.get(x, y, c);
                        //Setting value of channel "c"
                        dstFrameMatIndexer.put(x + flowVecX, y + flowVecY, c, val);
                    }
                }
            }
        }

        return dstFrameMat;
}

```
Last point logged by Log.d was "Point: X=975 Y=0 FlowX=105 FlowY125"
Exception itself: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.sleepycatstudios.slowy, PID: 14884
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.sleepycatstudios.slowy/com.sleepycatstudios.slowy.Render}:
java.lang.IndexOutOfBoundsException: index=6221175, limit=6220800
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IndexOutOfBoundsException: index=6221175, limit=6220800
at java.nio.Buffer.checkIndex(Buffer.java:150)
at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:346)
at org.bytedeco.javacpp.indexer.UByteBufferIndexer.put(UByteBufferIndexer.java:104)
at com.sleepycatstudios.slowy.VideoProcessor.calculateFrame(VideoProcessor.java:145)
at com.sleepycatstudios.slowy.VideoProcessor.calculateFrames(VideoProcessor.java:187)
at com.sleepycatstudios.slowy.VideoProcessor.startProcessing(VideoProcessor.java:227)
at com.sleepycatstudios.slowy.Render.onCreate(Render.java:13)
at android.app.Activity.performCreate(Activity.java:6251)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
at android.app.ActivityThread.-wrap11(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5417) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Thanks

**Comment by saudet** [comment]
`x` and `y` are reversed. Try to call `get(y, x, ...)` instead.

**Comment by Luonic** [comment]
@saudet why parameters are reversed? Is there any purpose to do that?
