### ISSUE TITLE
 "java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil" with IntelliJ

### ISSUE THREAD

**Issue by miketrab** [bytedeco/javacv#498]
Hi,

I saw the issue #109, and tried the follow the advice. It doesn't work for me. 

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2719)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:391)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:385)
	at com.job.rand.main(rand.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Error putting member offsets for class org/bytedeco/javacpp/avutil$Pool_free_Pointer.

I'm not using a pom (Maven), simply a direct download on my pc of all the javacv jars and referencing them through a IntelliJ project. 

Would you have any ideas?

Thanks!

**Comment by miketrab** [comment]
javacpp-presets/issues/225 provided the reference to the patch. 

And a choir of angels flooded my ears.

Merci beaucoup - arigato gozaimashita Samuel!

**Comment by saudet** [comment]
Great to hear you were able to resolve this!

**Comment by wooden1985** [comment]
In Android Studio I have the same error
