### ISSUE TITLE
Problem with jniopencv_core

### ISSUE THREAD

**Issue by TheSuperPlayer** [bytedeco/javacv#511]
I am creating a face recoginition programm with Intellij. When running my code through Intellij it works totally fine. When exporting it as a .jar file I am getting this error. 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
        at org.bytedeco.javacpp.Loader.load(Loader.java:492)
        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:464)
        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
        at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.<clinit>(opencv_objdetect.java:566)
        at FaceIdentifier.trainClassifier(FaceIdentifier.java:87)
        at Main.main(Main.java:14)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc310 in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
        at org.bytedeco.javacpp.Loader.load(Loader.java:483)
        ... 9 more
```

I have included all .jar files which are coming with javacv into the project as dependencies. 
I also searched by whole computer for jniopencv_core but it doesnt seem to exist.
I am using Win10.

Thanks in advance

**Comment by saudet** [comment]
That sounds like a problem with your IDE. Please ask in forums related to your IDE...

**Comment by saudet** [comment]
Given the lack of feedback, I am assuming you were able to resolve this issue.

**Comment by thiageshthg** [comment]
Got the same java.lang.UnsatisfiedLinkError: no opencv_imgproc310 in version 1.3
Downgraded to 1.2 and its working fine.
