### ISSUE TITLE
cvCvtColor Assertion failed

### ISSUE THREAD

**Issue by Cir0X** [bytedeco/javacv#520]
I'm trying to create a MotionDetector with the Raspberry Pi and the [Camera 2](https://www.raspberrypi.org/products/camera-module-v2/).
To grab images I'm using [JRPiCam](https://github.com/Hopding/JRPiCam) library.

Furthermore as a guideline I use the [MotionDetector](https://github.com/bytedeco/javacv/blob/master/samples/MotionDetector.java) example.

Unfortunately this error occurs:
```java
OpenCV Error: Assertion failed (dst.data == dst0.data) in cvCvtColor, file /home/ubuntu/javacpp-presets/opencv/cppbuild/linux-armhf/opencv-3.1.0/modules/imgproc/src/color.cpp, line 8479
Exception in thread "main" java.lang.RuntimeException: /home/ubuntu/javacpp-presets/opencv/cppbuild/linux-armhf/opencv-3.1.0/modules/imgproc/src/color.cpp:8479: error: (-215) dst.data == dst0.data in function cvCvtColor

        at org.bytedeco.javacpp.opencv_imgproc.cvCvtColor(Native Method)
        at de.cir0x.camerapi.Main.motionDetection(Main.java:74)
        at de.cir0x.camerapi.Main.main(Main.java:52)
```

I'm kinda new to the opencv world, but I guess there is a mistake in the conversion from BufferdImage to IplImage.

My code so far:
```java
package de.cir0x.camerapi;

import com.hopding.jrpicam.RPiCamera;
import com.hopding.jrpicam.exceptions.FailedToRunRaspistillException;
import org.bytedeco.javacpp.Loader;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.Java2DFrameConverter;
import org.bytedeco.javacv.OpenCVFrameConverter;

import java.awt.image.BufferedImage;
import java.io.IOException;

import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgcodecs.cvSaveImage;
import static org.bytedeco.javacpp.opencv_imgproc.*;

public class Main {

    private final static String SAVE_DIR = "/home/pi/Pictures";

    public static void main(String[] args) throws FailedToRunRaspistillException, IOException, InterruptedException {
        long start = now();

        RPiCamera camera = new RPiCamera();

        BufferedImage bufferedImage1 = camera.takeBufferedStill(1920, 1080);
        IplImage image1 = toIplImage(bufferedImage1);

        sleep(500);

        BufferedImage bufferedImage2 = camera.takeBufferedStill(1920, 1080);
        IplImage image2 = toIplImage(bufferedImage2);

//        ImageIO.write(bufferedImage, "jpg", new File(SAVE_ORIG_FILENAME));
//        System.out.println("Saved Orig Image");

//        IplImage img = cvLoadImage(SAVE_ORIG_FILENAME);

//        cvFlip(image2, image2, 0);

        int detections = motionDetection(image1, image2);
        System.out.println("detections = " + detections);

        cvSaveImage(SAVE_DIR + "/image1.jpg", image1);
        cvSaveImage(SAVE_DIR + "/image2.jpg", image2);
        System.out.println("Saved Images");

        long end = now();
        System.out.println("Time spend " + (end - start) + " ms");

    }

    private static int motionDetection(IplImage image, IplImage prevImage) {
        CvMemStorage storage = CvMemStorage.create();
        cvClearMemStorage(storage);

        cvSmooth(image, image, CV_GAUSSIAN, 9, 9, 2, 2);
        cvSmooth(prevImage, prevImage, CV_GAUSSIAN, 9, 9, 2, 2);

        cvCvtColor(image, image, CV_RGB2GRAY);
        cvCvtColor(prevImage, prevImage, CV_RGB2GRAY);

        IplImage diff = IplImage.create(image.width(), image.height(), IPL_DEPTH_8U, 1);

        cvAbsDiff(image, prevImage, diff);
        cvThreshold(diff, diff, 64, 255, CV_THRESH_BINARY);

        CvSeq contour = new CvSeq(null);
        return cvFindContours(diff, storage, contour, Loader.sizeof(CvContour.class), CV_RETR_LIST, CV_CHAIN_APPROX_SIMPLE);
    }

    private static Java2DFrameConverter converter = new Java2DFrameConverter();
    private static OpenCVFrameConverter<IplImage> cvFrameConverter = new OpenCVFrameConverter.ToIplImage();

    private static Frame toFrame(BufferedImage image) {
        return converter.convert(image);
    }

    private static IplImage toIplImage(BufferedImage image) {
        Frame frame = toFrame(image);
        return cvFrameConverter.convert(frame);
    }

    private static long now() {
        return System.currentTimeMillis();
    }

    private static void sleep(long ms) {
        try {
            Thread.sleep(ms);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

An similar Error occurs with `cvAbsDiff`, when I comment the `cvCvtColor` calls out.

**Comment by saudet** [comment]
The error is pretty clear: You can't use the same Mat object for both `src` and `dst`.
