### ISSUE TITLE
Perspective Transformation

### ISSUE THREAD

**Issue by ElchinValiyev** [bytedeco/javacv#521]
Currently, I'm trying to play around with javaCV and parse sudoku grid

``` scala
val src: Mat = imread("one,jpg", IMREAD_GRAYSCALE)
val canny = new Mat()
Canny(src, canny, 75, 100, 3, true )

val contours = new MatVector()
findContours(canny, contours, RETR_LIST, CV_CHAIN_APPROX_SIMPLE)
val filteredContoursSeq = toSeq(contours).sortBy(x => -contourArea(x))
val grid = filteredContoursSeq.head // biggest contour - sudoku grid

val approx = new Mat( )
approxPolyDP(grid, approx, 0.01 * arcLength(grid, true), true) //bounding polygon

val y = new Mat(new Size(2, 4), CV_32F, new FloatPointer(0, 0, 300, 0, 0, 300, 300, 300)) 

val img = new Mat()
val transform = getPerspectiveTransform(approx, y)
warpPerspective(src, img, transform, new Size(300, 300))

val result = loadOrExit(new File(image_name), IMREAD_COLOR)
drawContours(result, toMatVector(List(approx)), 0, Blue)
show(result, "Result")
```
And I get error:
```
OpenCV Error: Assertion failed (src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4) in getPerspectiveTransform, file /bytedeco/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp, line 6353
Exception in thread "main" java.lang.RuntimeException: /bytedeco/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:6353: error: (-215) src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4 in function getPerspectiveTransform

	at org.bytedeco.javacpp.opencv_imgproc.getPerspectiveTransform(Native Method)
	at Main$.delayedEndpoint$Main$1(Main.scala:67)
	at Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Main$.main(Main.scala:14)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
A little bit of debugging showed that 
```
src = org.bytedeco.javacpp.opencv_core$Mat[width=419,height=423,depth=8,channels=1]
canny = org.bytedeco.javacpp.opencv_core$Mat[width=419,height=423,depth=8,channels=1]
grid = org.bytedeco.javacpp.opencv_core$Mat[width=1,height=165,depth=-2147483616,channels=2]
approx = org.bytedeco.javacpp.opencv_core$Mat[width=1,height=4,depth=-2147483616,channels=2]
y = org.bytedeco.javacpp.opencv_core$Mat[width=2,height=4,depth=32,channels=1]
```
There is no error if you write :  
```scala 
val transform = getPerspectiveTransform(y, y)
 ```

**Comment by saudet** [comment]
So, make `approx` the same kind of Mat as `y` and it will work!

**Comment by ElchinValiyev** [comment]
I tried to use approx.reshape(1), approx.convertTo(approx, CV_32F) and error disappeared.  However,  resulting image is now looks corrupted and grid seems cutted out from image.
