### ISSUE TITLE
FFmpegFrameGrabber and FFmpegFrameRecorder upload local video to rtmp server

### ISSUE THREAD

**Issue by liangkuai** [bytedeco/javacv#525]
Hi, I get the following error
```
org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -1 while writing video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:795)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:681)
	at com.RtmpOperator.thread.PushRtmp.run(PushRtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Please help me.

**Comment by saudet** [comment]
Please copy/paste the errors that you get on the console as well.

**Comment by liangkuai** [comment]
```
WriteN, RTMP send error 10053 (129 bytes)
WriteN, RTMP send error 10053 (129 bytes)
WriteN, RTMP send error 10053 (44 bytes)
WriteN, RTMP send error 10053 (45 bytes)
WriteN, RTMP send error 10038 (42 bytes)
WriteN, RTMP send error 10038 (42 bytes)
WriteN, RTMP send error 10053 (129 bytes)
WriteN, RTMP send error 10053 (45 bytes)
WriteN, RTMP send error 10038 (42 bytes)
WriteN, RTMP send error 10053 (129 bytes)
WriteN, RTMP send error 10053 (45 bytes)
WriteN, RTMP send error 10038 (42 bytes)
WriteN, RTMP send error 10053 (129 bytes)
WriteN, RTMP send error 10053 (45 byorg.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -1 while writing video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:795)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:681)
	at com.RtmpOperator.thread.PushRtmp.run(PushRtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -1 while writing video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:795)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:681)
	at com.RtmpOperator.thread.PushRtmp.run(PushRtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -1 while writing video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:795)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:681)
	at com.RtmpOperator.thread.PushRtmp.run(PushRtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -1 while writing video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:795)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:681)
	at com.RtmpOperator.thread.PushRtmp.run(PushRtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -1 while writing video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:795)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:681)
	at com.RtmpOperator.thread.PushRtmp.run(PushRtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -1 while writing video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:795)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:681)
	at com.RtmpOperator.thread.PushRtmp.run(PushRtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by saudet** [comment]
"WriteN, RTMP send error 10038 (42 bytes)" -> Looks like there is a problem with your network. I'm afraid this isn't related to JavaCV or FFmpeg.

**Comment by Achilles2012** [comment]
i find the reason because "int nBytesRead = line.read(audioBytes, 0, line.available());"
nBytesRead 等于0

**Comment by Achilles2012** [comment]
i find the reason because "int nBytesRead = line.read(audioBytes, 0, line.available());"
nBytesRead ==0

**Comment by saudet** [comment]
@Achilles2012 So it's an issue with the example? Could you send a patch? Thanks!

**Comment by Achilles2012** [comment]
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java
