### ISSUE TITLE
aar dependency not working

### ISSUE THREAD

**Issue by matart15** [bytedeco/javacv#534]
Then i tried to make this app(https://github.com/CrazyOrr/FFmpegRecorder) into aar library and call it from myApplication.
This library uses javacv as dependency.

structure is something like this

`JavaCV.jar -> FFmpegRecorder.aar -> my nativescript`

But app can't find dependency of aar.

```
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.Class.forName(Class.java:324)
                                                     at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                     at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
                                                     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                                                     at com.example.matar.testapplication.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:337)
                                                     at com.example.matar.testapplication.FFmpegRecordActivity.access$000(FFmpegRecordActivity.java:50)
                                                     at com.example.matar.testapplication.FFmpegRecordActivity$2.run(FFmpegRecordActivity.java:162)
```

I already tried this and `{transitive=true}`
http://stackoverflow.com/questions/34872382/manually-adding-aar-with-dependency-pom-iml-file

What am i doing wrong

This is my build.gradle to create aar file 
```
apply plugin: 'com.android.library'
apply plugin: 'maven-publish'
apply plugin: 'maven'
//apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 22
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
//    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.jakewharton:butterknife:7.0.1'
//    compile files('libs/ffmpeg.jar')
//    compile files('libs/javacpp.jar')
//    compile files('libs/javacv.jar')

    compile group: 'org.bytedeco', name: 'javacv', version: '1.1'
    compile group: 'org.bytedeco', name: 'javacpp', version: '1.1'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'

}

uploadArchives {
    repositories{
        mavenDeployer {
            pom.groupId = 'com.example.matar'
            pom.artifactId = 'testapplication'
            pom.version = '0.0.1-SNAPSHOT'
            // Add other pom properties here if you want (developer details / licenses)
            repository(url: "file://${System.env.HOME}/.m2/repository/")
        }
    }
}
publishing {
    publications {
        maven(MavenPublication) {
            groupId 'com.example.matar' //You can either define these here or get them from project conf elsewhere
            artifactId 'testapplication'
            version '0.0.1-SNAPSHOT'
            artifact "$buildDir/outputs/aar/app-release.aar" //aar artifact you want to publish

            //generate pom nodes for dependencies
            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')
                configurations.compile.allDependencies.each { dependency ->
                    def dependencyNode = dependenciesNode.appendNode('dependency')
                    dependencyNode.appendNode('groupId', dependency.group)
                    dependencyNode.appendNode('artifactId', dependency.name)
                    dependencyNode.appendNode('version', dependency.version)
                }
            }
        }
    }

    //publish to filesystem repo
    repositories{
        maven {
            url "$buildDir/repo"
        }
    }
}
```

here is my application using this aar

```
package com.example.matar.myapplication;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Intent intent = new Intent(this, com.example.matar.testapplication.FFmpegRecordActivity.class);
        intent.addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(intent);
    }
}
```
```
apply plugin: 'com.android.application'
//apply plugin: 'com.android.library'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"
    defaultConfig {
        applicationId "com.example.matar.myapplication"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'libs'
        }
//        maven {
//            url "file://${System.env.HOME}/.m2/repository/"
//        }
//        maven {
//            url "/Users/matar/workplace/android/test/TestApplication/app/build/repo"
//        }
    }
}

dependencies {
//    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    testCompile 'junit:junit:4.12'
    compile(name:'app-release', ext:'aar'){ transitive = true }

    compile group: 'org.bytedeco', name: 'javacv', version: '1.1'
    compile group: 'org.bytedeco', name: 'javacpp', version: '1.1'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'

//    compile ('com.example.matar:testapplication:0.0.1-SNAPSHOT@aar'){transitive=true}
}
```

------
I also tried copying `*.so` files too

**Comment by saudet** [comment]
> I also tried copying *.so files too

Well you probably didn't get them in the right directory:
https://github.com/bytedeco/javacpp-presets/wiki/Issues-with-Build-Tools

**Comment by matart15** [comment]
@saudet thank you for looking into it.

My *.so files are in `app/src/main/jniLibs/armeabi` just like this.
https://github.com/CrazyOrr/FFmpegRecorder/tree/master/app/src/main/jniLibs/armeabi

and they work with this case
JavaCV.jar -> FFmpegRecorder as application

and does not work with this case
JavaCV.jar -> FFmpegRecorder.aar -> myApplication as application

I copied *.so files to `app/src/main/jniLibs/armeabi` directory of both ` FFmpegRecorder.aar` and `myApplication`.

**Comment by matart15** [comment]
I used this app to see copied libs.
https://play.google.com/store/apps/details?id=com.xh.nativelibsmonitor.app&hl=en
![screenshot_20161017-121132](https://cloud.githubusercontent.com/assets/17027219/19424334/38d59856-9463-11e6-8f50-2491416d2ea5.png)

if this app working right then *.so files seems copied.

Is it possible that *.so files are copied and not being referenced?
