### ISSUE TITLE
dshow format not starting Windows 10 x64

### ISSUE THREAD

**Issue by Jonatino** [bytedeco/javacv#543]
I'd like to use this library for my remote desktop software but it does not seem to be working.

Here is my test class:

````
public class FFMPEG {
	
	public static void main(String[] args) throws Exception {
		FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("video=\"screen-capture-recorder\"");
		grabber.setFormat("dshow");
		grabber.setImageWidth(2560);
		grabber.setImageHeight(1440);
		grabber.start();
		
		CanvasFrame frame = new CanvasFrame("Screen Capture");
		while (frame.isVisible()) {
			frame.showImage(grabber.grab());
		}
		frame.dispose();
		grabber.stop();
	}
	
}
```


and here is what I have in my gradle.build

````
repositories {
    mavenCentral()
}

configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}

dependencies {
    compile "org.bytedeco:javacv:1.2"
    compile "org.bytedeco:javacpp:1.2.1"

    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'windows-x86_64'
}
````

Here is the error I get when running that class:
````
Exception in thread "main" org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "video="screen-capture-recorder"". (Has setFormat() been called?)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:437)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:385)
	at FFMPEG.main(FFMPEG.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[dshow @ 000000000179c5e0] Could not enumerate video devices (or none found).
[dshow @ 000000000179c5e0] Could not enumerate video devices (or none found)
````

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/307
