### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil in Marshmallow 

### ISSUE THREAD

**Issue by FasdAR** [bytedeco/javacv#552]
Log

```
`   [ 11-07 23:26:40.586 11348:11348 W/         ]
                                                                         Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
11-07 23:26:40.586 11348-11348/ru.landmarkstd.influence.influence W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
11-07 23:26:40.596 11348-11348/ru.landmarkstd.influence.influence W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
11-07 23:26:40.596 11348-11348/ru.landmarkstd.influence.influence W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
11-07 23:26:40.636 11348-11348/ru.landmarkstd.influence.influence I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
11-07 23:26:40.636 11348-11348/ru.landmarkstd.influence.influence D/AndroidRuntime: Shutting down VM
11-07 23:26:40.636 11348-11348/ru.landmarkstd.influence.influence E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: ru.landmarkstd.influence.influence, PID: 11348
                                                                                    java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                        at java.lang.Class.classForName(Native Method)
                                                                                        at java.lang.Class.forName(Class.java:324)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:464)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
                                                                                        at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
                                                                                        at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                                        at ru.landmarkstd.influence.influence.RecordActivity.initRecorder(RecordActivity.java:190)
                                                                                        at ru.landmarkstd.influence.influence.RecordActivity.startRecording(RecordActivity.java:213)
                                                                                        at ru.landmarkstd.influence.influence.RecordActivity.onClick(RecordActivity.java:526)
                                                                                        at android.view.View.performClick(View.java:5697)
                                                                                        at android.widget.TextView.performClick(TextView.java:10826)
                                                                                        at android.view.View$PerformClick.run(View.java:22526)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                        at 

com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`
```

Code 

`recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);`

Gradle

```
`compile group: 'org.bytedeco', name: 'javacv', version: '1.2'

 compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-arm'

 compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-x86'

 compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'

 compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-x86'`

```
```
` defaultConfig {
        applicationId "ru.landmarkstd.influence.influence"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        ndk { abiFilters "armeabi-v7a" }
    }`
```

```
` packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
    }`
```

**Comment by saudet** [comment]
Ok, do you get the same thing with JavaCV 1.2?

**Comment by saudet** [comment]
And with `ffmpeg-3.1.2-1.2` and `opencv-3.1.0-1.2`?

**Comment by FasdAR** [comment]
Yes, and this does not help

**Comment by saudet** [comment]
What error do you get?

**Comment by FasdAR** [comment]
Full Log 
```
``I/RecordActivity: ffmpeg_url: rtmp://influence:az35289621@192.168.1.4:1935/live/test
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:50.966 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:51.116 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:51.166 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:51.176 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:51.196 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:51.196 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.236 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.236 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.256 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.256 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.266 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.266 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.276 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.296 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.296 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:09:52.306 31142:31142 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ru.landmarkstd.influence.influence, PID: 31142
                  java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:324)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:464)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:409)
                      at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1672)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                      at ru.landmarkstd.influence.influence.RecordActivity.initRecorder(RecordActivity.java:188)
                      at ru.landmarkstd.influence.influence.RecordActivity.startRecording(RecordActivity.java:211)
                      at ru.landmarkstd.influence.influence.RecordActivity.onClick(RecordActivity.java:524)
                      at android.view.View.performClick(View.java:5697)
                      at android.widget.TextView.performClick(TextView.java:10826)
                      at android.view.View$PerformClick.run(View.java:22526)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7224)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by saudet** [comment]
That doesn't look like the full log, but anyway did you also make sure to
use the latest version of JavaCPP?

**Comment by FasdAR** [comment]
Log
```
`V/FA: onActivityCreated
I/RecordActivity: cameara open
W/camera: camera view
I/RecordActivity: cameara preview start: OK
V/FA: Activity resumed, time: 164552978
D/SecWifiDisplayUtil: Metadata value : none
D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{63b00d1 I.E...... R.....ID 0,0-0,0}
I/Choreographer: Skipped 71 frames!  The application may be doing too much work on its main thread.
V/RecordActivity: Changed to supported resolution: 320x240
V/RecordActivity: Setting imageWidth: 320 imageHeight: 240 frameRate: 30
V/RecordActivity: Preview Framerate: 30
V/FA: Activity paused, time: 164553493
D/ViewRootImpl: #3 mView = null
W/ResourcesManager: getTopLevelResources: /data/app/ru.landmarkstd.influence.influence-2/base.apk / 1.0 running in ru.landmarkstd.influence.influence rsrc of package null
W/ResourcesManager: getTopLevelResources: /data/app/ru.landmarkstd.influence.influence-2/base.apk / 1.0 running in ru.landmarkstd.influence.influence rsrc of package null
V/FA: onActivityCreated
I/RecordActivity: cameara open
W/camera: camera view
I/RecordActivity: cameara preview start: OK
V/FA: Activity resumed, time: 164554106
D/SecWifiDisplayUtil: Metadata value : none
D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{847ae72 I.E...... R.....ID 0,0-0,0}
I/Choreographer: Skipped 67 frames!  The application may be doing too much work on its main thread.
V/RecordActivity: Changed to supported resolution: 320x240
V/RecordActivity: Setting imageWidth: 320 imageHeight: 240 frameRate: 30
V/RecordActivity: Preview Framerate: 30
E/ViewRootImpl: sendUserActionEvent() mView == null
E/ViewRootImpl: sendUserActionEvent() mView == null
V/FA: Inactivity, disconnecting from AppMeasurementService
W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=2
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@87d3f8 time:74021671
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@87d3f8 time:74021671
D/ViewRootImpl: #3 mView = null
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
W/RecordActivity: init recorder
I/RecordActivity: create yuvImage
I/RecordActivity: ffmpeg_url: /mnt/sdcard/stream.flv
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:41:27.383 12584:12584 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:41:27.393 12584:12584 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

       [ 11-08 15:41:27.423 12584:12584 W/         ]
       Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
I/art: Background sticky concurrent mark sweep GC freed 18652(1726KB) AllocSpace objects, 67(4MB) LOS objects, 18% free, 25MB/30MB, paused 539us total 109.308ms
I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ru.landmarkstd.influence.influence, PID: 12584
                  java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:324)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:474)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:419)
                      at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1672)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                      at ru.landmarkstd.influence.influence.RecordActivity.initRecorder(RecordActivity.java:190)
                      at ru.landmarkstd.influence.influence.RecordActivity.startRecording(RecordActivity.java:213)
                      at ru.landmarkstd.influence.influence.RecordActivity.onClick(RecordActivity.java:526)
                      at android.view.View.performClick(View.java:5697)
                      at android.widget.TextView.performClick(TextView.java:10826)
                      at android.view.View$PerformClick.run(View.java:22526)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7224)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
I/Process: Sending signal. PID: 12584 SIG: 9
Application terminated.
`
```

JavaCPP in 1.2.4

```
` compile group: 'org.bytedeco', name: 'javacpp', version: '1.2.4'
    compile group: 'org.bytedeco', name: 'javacv', version: '1.2'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-x86'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-x86'`
```

**Comment by saudet** [comment]
Could you provide the complete stack trace of the exception?

**Comment by saudet** [comment]
Looks like you simply forgot to add the Java artifacts for OpenCV and FFmpeg:
```gradle
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2'
```

**Comment by FasdAR** [comment]
Sense? I added them. Here is my artifacts

```
compile group: 'org.bytedeco', name: 'javacpp', version: '1.2.4'
    compile group: 'org.bytedeco', name: 'javacv', version: '1.2'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-x86'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-x86'
```

**Comment by saudet** [comment]
So try this:
```gradle
compile group: 'org.bytedeco', name: 'javacpp', version: '1.2.4'
compile group: 'org.bytedeco', name: 'javacv', version: '1.2'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-x86'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-x86'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2'
```

**Comment by FasdAR** [comment]
The same does not help

**Comment by saudet** [comment]
So try some more stuff, read up:
https://github.com/bytedeco/javacpp-presets/wiki/Issues-with-Build-Tools#android-studio
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
