### ISSUE TITLE
Could not import javacv 1.2 into eclipse

### ISSUE THREAD

**Issue by jiekechoo** [bytedeco/javacv#578]
When I import javacv 1.2 maven package into eclipse IDE , could not import osx platform jars,

change javacv to 1.1 , it runs ok.

**Comment by saudet** [comment]
Could you try again with the just released JavaCV 1.3?

**Comment by jiekechoo** [comment]
When  I try JavaCV 1.3, count not import osx platform jars again, run as java application, it shows: 

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:613)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:546)
	at com.sectong.firstcv.RecordCamera.recordCamera(RecordCamera.java:26)
	at com.sectong.firstcv.RecordCamera.main(RecordCamera.java:75)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:604)
	... 8 more

**Comment by saudet** [comment]
What do you get if you use the `pom.xml` file included in the README.md file?
https://github.com/bytedeco/javacv#sample-usage

**Comment by jiekechoo** [comment]
`<dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.3</version>
        </dependency>
</dependencies>`

I change artifactid from ‘javacv’ to ‘javacv-platform’ , fixed it.
