### ISSUE TITLE
lib/arm/libjniavutil.so: unused DT entry: type 0xf arg 0x18b9d   art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>

### ISSUE THREAD

**Issue by yangchaoxun** [bytedeco/javacv#579]
Xiao mi MI NOTE LTE

12-08 19:40:55.306 13056-13056/com.pocketsocial.pocketlive W/linker: /data/app/com.pocketsocial.pocketlive-1/lib/arm/libjniavutil.so: unused DT entry: type 0xf arg 0x18b9d
12-08 19:40:55.333 13056-13056/com.pocketsocial.pocketlive I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
12-08 19:40:55.333 13056-13056/com.pocketsocial.pocketlive D/AndroidRuntime: Shutting down VM
12-08 19:40:55.334 13056-13056/com.pocketsocial.pocketlive E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.pocketsocial.pocketlive, PID: 13056
                                                                             java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                 at java.lang.Class.classForName(Native Method)
                                                                                 at java.lang.Class.forName(Class.java:324)
                                                                                 at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                                                                                 at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                                                 at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                                                                                 at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                                 at com.pocketsocial.pocketlive.presentation.view.fragments.liveNewView.golive.GoLiveHandler.initRecorder(GoLiveHandler.java:126)
                                                                                 at com.pocketsocial.pocketlive.presentation.view.fragments.liveNewView.golive.GoLiveHandler.startRecording(GoLiveHandler.java:155)
                                                                                 at com.pocketsocial.pocketlive.presentation.view.fragments.liveNewView.golive.GoLiveFragment.goLive(GoLiveFragment.java:288)
                                                                                 at com.pocketsocial.pocketlive.presentation.view.fragments.liveNewView.golive.GoLiveFragment.access$900(GoLiveFragment.java:69)
                                                                                 at com.pocketsocial.pocketlive.presentation.view.fragments.liveNewView.golive.GoLiveFragment$1.onClick(GoLiveFragment.java:240)
                                                                                 at android.view.View.performClick(View.java:5207)
                                                                                 at android.view.View$PerformClick.run(View.java:21177)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
12-08 19:40:55.360 13056-13056/com.pocketsocial.pocketlive I/Process: Sending signal. PID: 13056 SIG: 9
Can you help me？thanks。

**Comment by saudet** [comment]
Could you try again with the just released JavaCV 1.3?

**Comment by yangchaoxun** [comment]
yes

**Comment by yangchaoxun** [comment]
compile group: 'org.bytedeco', name: 'javacpp', version: '1.3'
    compile group: 'org.bytedeco', name: 'javacv', version: '1.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3', classifier: 'android-arm'

**Comment by yangchaoxun** [comment]
compile group: 'org.bytedeco', name: 'javacv', version: '1.1'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'    ---This version is ok

**Comment by saudet** [comment]
Probably caused by a bad device. Try to use ReLinker:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by yangchaoxun** [comment]
Thanks you very much！ again linker it's ok
