### ISSUE TITLE
Could not seek to timestamp xxx using InputStream

### ISSUE THREAD

**Issue by Ali-RS** [bytedeco/javacv#610]
Hi 

When using File, I can seek or restart video (in my player) without problem but when loading it as InputStream (I am loading video from a jar file and you can only read it as InputStream )

Video playing works fine but I am getting error when seeking or restarting video. 
(It seems problem relates to InputStream mark operation)

I am loading video file as below 

`InputStream is = getClass().getResourceAsStream("/cutscenes/oow2010-2.flv"));`

Error on restart : 
```
org.bytedeco.javacv.FrameGrabber$Exception: Error on InputStream.close(): 
	at org.bytedeco.javacv.FFmpegFrameGrabber.releaseUnsafe(FFmpegFrameGrabber.java:206) ~[javacv-1.3.1.jar:1.3.1]
	at org.bytedeco.javacv.FFmpegFrameGrabber.release(FFmpegFrameGrabber.java:133) ~[javacv-1.3.1.jar:1.3.1]
	at org.bytedeco.javacv.FFmpegFrameGrabber.stop(FFmpegFrameGrabber.java:654) ~[javacv-1.3.1.jar:1.3.1]
	at org.bytedeco.javacv.FrameGrabber.restart(FrameGrabber.java:459) ~[javacv-1.3.1.jar:1.3.1]
	at com.overthemoon.jme3.media.javacv.FFmpegMediaPlayer.update(FFmpegMediaPlayer.java:239) [jme3-media-player-0.1-SNAPSHOT.jar:?]
	at com.overthemoon.jme3.media.gui.LemurMediaPlayerGUI.update(LemurMediaPlayerGUI.java:227) [jme3-media-player-0.1-SNAPSHOT.jar:?]
	at com.overthemoon.core.state.cutscene.CutsceneState.update(CutsceneState.java:52) [main/:?]
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:287) [jme3-core-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:236) [jme3-core-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151) [jme3-lwjgl-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197) [jme3-lwjgl-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232) [jme3-lwjgl-3.2.0-SNAPSHOT.jar:3.2-6142]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.io.IOException: Resetting to invalid mark
	at java.io.BufferedInputStream.reset(BufferedInputStream.java:448) ~[?:1.8.0_112]
	at org.bytedeco.javacv.FFmpegFrameGrabber.releaseUnsafe(FFmpegFrameGrabber.java:203) ~[javacv-1.3.1.jar:1.3.1]
	... 12 more
```

Error on seeking 

```
Error on InputStream.reset() or skip(): java.io.IOException: Resetting to invalid mark
12:05:38,193 ERROR [FFmpegMediaPlayer] null
org.bytedeco.javacv.FrameGrabber$Exception: avformat_seek_file() error -1: Could not seek file to timestamp 31000000.
	at org.bytedeco.javacv.FFmpegFrameGrabber.setTimestamp(FFmpegFrameGrabber.java:420) ~[javacv-1.3.1.jar:1.3.1]
	at com.overthemoon.jme3.media.javacv.FFmpegMediaPlayer.seek(FFmpegMediaPlayer.java:208) [jme3-media-player-0.1-SNAPSHOT.jar:?]
	at com.overthemoon.jme3.media.gui.LemurMediaPlayerGUI$4.execute(LemurMediaPlayerGUI.java:130) [jme3-media-player-0.1-SNAPSHOT.jar:?]
	at com.overthemoon.jme3.media.gui.LemurMediaPlayerGUI$4.execute(LemurMediaPlayerGUI.java:122) [jme3-media-player-0.1-SNAPSHOT.jar:?]
	at com.simsilica.lemur.core.CommandMap.runCommands(CommandMap.java:61) [lemur-1.10.1-SNAPSHOT.jar:?]
	at com.simsilica.lemur.Button.setPressed(Button.java:325) [lemur-1.10.1-SNAPSHOT.jar:?]
	at com.simsilica.lemur.Button$ButtonMouseHandler.mouseButtonEvent(Button.java:418) [lemur-1.10.1-SNAPSHOT.jar:?]
	at com.simsilica.lemur.event.MouseEventControl.mouseButtonEvent(MouseEventControl.java:122) [lemur-1.10.1-SNAPSHOT.jar:?]
	at com.simsilica.lemur.event.PickEventSession.buttonEvent(PickEventSession.java:625) [lemur-1.10.1-SNAPSHOT.jar:?]
	at com.simsilica.lemur.event.MouseAppState.dispatch(MouseAppState.java:98) [lemur-1.10.1-SNAPSHOT.jar:?]
	at com.simsilica.lemur.event.MouseAppState$MouseObserver.onMouseButtonEvent(MouseAppState.java:114) [lemur-1.10.1-SNAPSHOT.jar:?]
	at com.jme3.input.InputManager.processQueue(InputManager.java:831) [jme3-core-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.input.InputManager.update(InputManager.java:907) [jme3-core-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.app.LegacyApplication.update(LegacyApplication.java:725) [jme3-core-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:227) [jme3-core-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151) [jme3-lwjgl-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197) [jme3-lwjgl-3.2.0-SNAPSHOT.jar:3.2-6142]
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232) [jme3-lwjgl-3.2.0-SNAPSHOT.jar:3.2-6142]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

Here is my player code: 

```

import com.jme3.texture.Image;
import com.jme3.texture.Texture2D;
import com.overthemoon.jme3.media.MediaPlayer;
import com.overthemoon.jme3.media.SeekTime;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.util.logging.Level;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Ali-RS <ali_codmw@yahoo.com>
 */
public class FFmpegMediaPlayer implements MediaPlayer {

    static Logger log = LoggerFactory.getLogger(FFmpegMediaPlayer.class);

    private FFmpegFrameGrabber grabber;
    private Texture2D texture;
    private Image image;
    private boolean looped = false;
    private boolean autoPlay = true;
    private boolean playing = false;
    private boolean stopped = true;
    private boolean mute;
    private int framesNb;
    private long lengthIntime;
    private int frameRate;
    private float delay;
    private String file;
    private Runnable OnEndOfMediaEvent;

    /**
     * Note: if video file is inside jar file the you should set it as
     * InputStrem. (Using second constructor)
     *
     * @param file path to file, ex (linux): /home/idea/Desktop/oow2010-2.flv
     *
     * @throws FileNotFoundException
     */
    public FFmpegMediaPlayer(String file) throws FileNotFoundException {
        this.file = file;
        File videofile = new File(file);
        if (!videofile.exists()) {
            throw new FileNotFoundException(file);
        }
        grabber = new FFmpegFrameGrabber(file);
        setupGrapper();
    }

    /**
     *
     * @param is
     * @param fileName file name should contains the file format, ex: foo.flv
     */
    public FFmpegMediaPlayer(InputStream is, String fileName) {
        if (is == null) {
            throw new NullPointerException("Video input stream is null!");
        }
        this.file = fileName;
        grabber = new FFmpegFrameGrabber(is);
        setupGrapper();
    }

    public FFmpegFrameGrabber getFrameGrabber() {
        return (FFmpegFrameGrabber) grabber;
    }

    @Override
    public void play() {

        if (grabber != null) {
//            if (isStopped()) {
//                try {
//                    grabber.start();
//                } catch (FrameGrabber.Exception ex) {
//                    log.error("Failed to start grabber!", ex);
//                    playing = false;
//                    stopped = true;
//                    return;
//                }
//            }

            playing = true;
            stopped = false;

        } else {
            log.error("No grabber found!");
        }

    }

    @Override
    public void pause() {
        if (isPlaying()) {
            playing = false;
        }
    }

    @Override
    public void stop() {
        if (grabber != null) {

            stopped = true;
            playing = false;
            try {
                grabber.setFrameNumber(0);
//            try {
//                grabber.stop();
//                stopped = true;
//                playing = false;
//            } catch (FrameGrabber.Exception ex) {
//                log.error("Failed to stop grabber!", ex);
//            }
            } catch (FrameGrabber.Exception ex) {
                java.util.logging.Logger.getLogger(FFmpegMediaPlayer.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            log.error("No grabber found!");
        }

    }

    @Override
    public void mute(boolean mute) {
        this.mute = mute;
    }

    @Override
    public Texture2D getTexture() {
        return texture;
    }

    @Override
    public long getLengthInTime() {
        return lengthIntime;
    }

    @Override
    public int getLengthInFrame() {
        return grabber.getLengthInFrames();
    }

    @Override
    public long getCurrentTime() {
        return grabber.getTimestamp() / 1000000l; //currentTime in second
    }

    @Override
    public int getCurrentFrameNumber() {
        return grabber.getFrameNumber();
    }

    @Override
    public boolean isLooped() {
        return looped;
    }

    @Override
    public void setLooped(boolean looped) {
        this.looped = looped;
    }

    @Override
    public boolean isAutoPlay() {
        return autoPlay;
    }

    @Override
    public void autoPlay() {
        this.autoPlay = true;
        this.playing = true;
    }

    @Override
    public boolean isPlaying() {
        return playing;
    }

    @Override
    public boolean isStopped() {
        return stopped;
    }

    @Override
    public boolean isMute() {
        return mute;
    }

    @Override
    public void seek(SeekTime frame) {
     
        try {
            grabber.setTimestamp(frame.getSecound().longValue()*1000000);
        } catch (FrameGrabber.Exception ex) {
            java.util.logging.Logger.getLogger(FFmpegMediaPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public String getMediaName() {
        return file;
    }

    private float delta = 0.0f;

    @Override
    public void update(float tpf) {

        if (grabber != null) {
            if (isPlaying()) {
                delta += tpf;
                try {

                    if (delta >= delay && grabber.getFrameNumber() < framesNb) {
                        delta = 0.0f;
                        Frame frame = grabber.grabImage();
                        if (frame != null && frame.image != null) {
                            image.setData((ByteBuffer) frame.image[0]);
                        }

                    } else if (grabber.getFrameNumber() == framesNb) {
                        if (isLooped()) {
                            grabber.restart(); 
                        } else {
                            stop();
                            OnEndOfMediaEvent.run();
                        }

                    }

                } catch (FrameGrabber.Exception ex) {
                    log.error("Exception grabbing", ex);
                } 
            }
        } else {
            log.error("No grabber found!");
        }

    }

    @Override
    public void dispose() {
        try {
            grabber.stop();
            grabber.close();
            grabber.release();
        } catch (FrameGrabber.Exception ex) {
            log.error("Could not dispose player!", ex);
        }
    }

    @Override
    public void setOnReady(Runnable value) {
        value.run();
    }

    @Override
    public boolean isReady() {
        return true;
    }

    @Override
    public void setOnEndOfMedia(Runnable value) {
        this.OnEndOfMediaEvent = value;
    }

    private void setupGrapper() {
        try {

            String format = file.substring(file.lastIndexOf('.') + 1);
            grabber.setFormat(format);
            grabber.start();

            framesNb = grabber.getLengthInFrames();
            lengthIntime = grabber.getLengthInTime() / 1000000l; //lengthIntime in second
            frameRate = (int) grabber.getFrameRate();
            delay = 1.0f / (float) grabber.getFrameRate(); // secound

            texture = new Texture2D();
            image = new Image();
            image.setWidth(grabber.getImageWidth());
            image.setHeight(grabber.getImageHeight());
            image.setFormat(Image.Format.BGR8);
            texture.setImage(image);
        } catch (FrameGrabber.Exception ex) {
            log.error("Failed to start grabber!", ex);

        }

        OnEndOfMediaEvent = new Runnable() {
            @Override
            public void run() {
                //Do Nothing
            }
        };
    }

}
```

**Comment by saudet** [comment]
InputStream doesn't really support streaming, that's normal.

**Comment by gkozyryatskyy** [comment]
@saudet this means we can`t use FFmpegFrameGrabber with InputStream at all?
For example, I have a file on aws s3, and I want to take a simple frame of it with FFmpegFrameGrabber. How can I do this not downloading the full file?

**Comment by saudet** [comment]
If you need seeking, yes, but the whole file gets cached in memory anyway
in the case of InputStream, so it shouldn't be an issue, in the case of
files. If your stream isn't a file, then that's another case that will
depend on the format you need to use.
