### ISSUE TITLE
Record Video at higher frame rate in RecordActivity

### ISSUE THREAD

**Issue by vishalghor** [bytedeco/javacv#613]
Hi ALL,

i was working on the RecordActivity sample.There i tried setting the record frame to more than 30 such as 60 and 120 but the app crashes when i try to do that.Is it possible to record videos at 60 or 120 framerate using the same sample?

Thank You

**Comment by saudet** [comment]
Sure, why not? Could you provide the log of the crash?

**Comment by vishalghor** [comment]
Hi samuel,

Thank you responding fast.Here is the crash log.
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.a7000011608.mynewapplication, PID: 29503
                  java.lang.RuntimeException: setParameters failed
                      at android.hardware.Camera.native_setParameters(Native Method)
                      at android.hardware.Camera.setParameters(Camera.java:1932)
                      at com.example.a7000011608.mynewapplication.RecordActivity$CameraView.surfaceChanged(RecordActivity.java:518)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:591)
                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:948)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1974)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5901)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                      at android.view.Choreographer.doFrame(Choreographer.java:550)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:211)
                      at android.app.ActivityThread.main(ActivityThread.java:5389)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
`

What could be he reason for this?

Thank you again

**Comment by saudet** [comment]
Looks like your camera doesn't support those framerates.

**Comment by vishalghor** [comment]
Hi samuel,

I checked for supported fps range on my device, it gave the following as the fps range;
[1,15],[1,30],[1,60],[1,120]. 

I found them by using the android api which gives the  suitable fps range for the device.


Also i had one more issue using putText() in my code to write a text on an image.
Can u please help me with this as well.In putText (),i had written like this: 

```
opencv_core.putText(yuvImage, "Sometext", new opencv_core.Point(10,5 ),
                                    FONT_HERSHEY_PLAIN, 1.0, new opencv_core.Scalar(0, 255, 0, 2.0));
```

but its showing error.

Thank you

**Comment by saudet** [comment]
Well, you'll need to figure out why your device doesn't do what it says it can do.

As for drawing text, just use the API offered by Android instead:
https://developer.android.com/guide/topics/graphics/2d-graphics.html
It is a lot better than OpenCV at drawing anyway.
