### ISSUE TITLE
java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by rajkumarmishra** [bytedeco/javacv#615]
Not able to solve this since one week. Extracted all jar files, put it under lib folder and add dependencies, able to access all methods and classes, throwing this error

` FATAL EXCEPTION: main
                                                                         Process: com.tracker.camera, PID: 5514
                                                                         java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:717)
                                                                             at org.bytedeco.javacpp.Loader.load(Loader.java:657)
                                                                             at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
                                                                             at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:468)
                                                                             at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:462)
                                                                             at com.com.tracker.camera.CameraActivity$1.onClick(CameraActivity.java:108)`

I trying to grab each frames form a video, here is the code:

`Button click = (Button) findViewById(R.id.click);
        click.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(cVideoFilePath);
                try {

                    OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
                    grabber.start();

                    opencv_core.IplImage frame = converter.convert(grabber.grab());

                    if (frame != null) {
                        Log.i("FFmp", frame.toString());

                    }

                } catch (FrameGrabber.Exception e) {
                    e.printStackTrace();
                }
            }

        });`

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
