### ISSUE TITLE
FrameRecorder$Exception: avio_open2 error() error -13: Could not open 'null'

### ISSUE THREAD

**Issue by MischaRo** [bytedeco/javacv#632]
Hi there, 
I am trying to use JavaCV together with BoofCV with the goal to stream the visual output of BoofCV via rtmp. Right now, as a first step, I am trying to capture the visual output of BoofCV and write it to a flv-file. I used parts from the RecordActivity.java class in my project.

When I start the recording process I get an FrameRecorder$Exception: avio_open2 error() error -13: Could not open 'null' Error:
```
org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -13: Could not open 'null'
at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:784)
at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:351)
at cswlabs.boofcvtest.MainActivity.startRecording(MainActivity.java:310)
at cswlabs.boofcvtest.MainActivity.onClick(MainActivity.java:451)
at android.view.View.performClick(View.java:4273)
at android.view.View$PerformClick.run(View.java:17802)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5162)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
at cswlabs.boofcvtest W/RecordActivity: Start Button Pushed
```
I basically use the init Methods from the RecordActivity.java class.
The error gets thrown at the recorder.start()- command:
```
initRecorder();
        //System.out.println("2: "+recorder.toString());
        try {
            //System.out.println("3: "+recorder.toString());
            recorder.start();
            startTime = System.currentTimeMillis();
            recording = true;
            //audioThread.start();

            if(addFilter) {
                filter.start();
            }

        } catch (FFmpegFrameRecorder.Exception | FrameFilter.Exception e) {
            e.printStackTrace();
        }
    }
```
where initRecorder() is:

```
private void initRecorder() {

        av_log_set_level(AV_LOG_TRACE);

        Log.w(LOG_TAG,"init recorder");

        if (RECORD_LENGTH > 0) {

            //Log.w(LOG_TAG,"Debug1");

            imagesIndex = 0;
            images = new Frame[RECORD_LENGTH * frameRate];
            timestamps = new long[images.length];
            for (int i = 0; i < images.length; i++) {
                images[i] = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 2);
                timestamps[i] = -1;
            }
        } else if (yuvImage == null) {
            Log.w(LOG_TAG,"Debug2");
            yuvImage = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 2);
            Log.i(LOG_TAG, "create yuvImage");
        }

        Log.i(LOG_TAG, "ffmpeg_url: " + ffmpeg_link);
        recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);
        recorder.setFormat("flv");
        recorder.setSampleRate(sampleAudioRateInHz);
        // Set in the surface changed method
        recorder.setFrameRate(frameRate);

        //System.out.println("1:"+recorder.toString());

        // The filterString  is any ffmpeg filter.
        // Here is the link for a list: https://ffmpeg.org/ffmpeg-filters.html
        filterString = "transpose=0";
        filter = new FFmpegFrameFilter(filterString, imageWidth, imageHeight);

        //default format on android
        filter.setPixelFormat(avutil.AV_PIX_FMT_NV21);

        Log.i(LOG_TAG, "recorder initialize success");

        //audioRecordRunnable = new AudioRecordRunnable();
        //audioThread = new Thread(audioRecordRunnable);
        //runAudioThread = true;
    }
```

I have uploaded the project to github so maybe someone can check it out:
[https://github.com/MischaRo/BoofCVTest](https://github.com/MischaRo/BoofCVTest)

Thanks in advance for any Help

**Comment by saudet** [comment]
You'll need to provide a valid URL to ffmpeg_link the variable.

**Comment by MischaRo** [comment]
Yea, i did that.
the url is :
```
private String ffmpeg_link = "/mnt/sdcard/BoofCvRecord.flv";
```

**Comment by MischaRo** [comment]
I figured it out, sorry, it was a stupid mistake on my end.
I forgot to give file writing Permissions in the manifest.xml
Adding those fixed the issue.
