### ISSUE TITLE
Crash on Xiaomi Mi4

### ISSUE THREAD

**Issue by hnvn** [bytedeco/javacv#674]
JavaCV crashes when deploy in Xiaomi Mi4: 

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.verime.v2, PID: 8871
                                                             java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                 at org.bytedeco.javacpp.avutil.av_frame_alloc(Native Method)
                                                                 at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:159)
                                                                 at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:155)`

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
