### ISSUE TITLE
RecordActivity sample issue - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by anonym24** [bytedeco/javacv#689]
Sample example RecordActivity crashes when I stop recording a video:

```
FATAL EXCEPTION: main
                                                                                    Process: com.github.crazyorr.ffmpegrecorder, PID: 23433
                                                                                    java.lang.ArrayIndexOutOfBoundsException: length=300; index=-1
                                                                                        at com.github.crazyorr.ffmpegrecorder.RecordActivity.stopRecording(RecordActivity.java:251)
                                                                                        at com.github.crazyorr.ffmpegrecorder.RecordActivity.onClick(RecordActivity.java:549)
```

https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java#L308

**Comment by saudet** [comment]
Have you found out what causes this error? If so, please let me know so we can fix the example! Thanks

**Comment by anonym24** [comment]
I don't have such checks in my code like in this example, just stopping recording (audio/video threads), releasing ffmpeg recorder. I think I just tried this example (RecordActivity.java) that time but didn't really use further
