### ISSUE TITLE
Opencv runnable jar Native Library error

### ISSUE THREAD

**Issue by mnh-aj123** [bytedeco/javacv#704]
My hadoop application is working perfectly when using eclipse . Its image processing actually  I was creating runnable jar  but when i tried to run the jar file using terminal and Hadoop
it gives error 

 ```
hduser@master:/home/mnh/Desktop$ hadoop jar carCount1.jar /usr/local/hadoop/input/cars.mp4 /usr/local/hadoop/carCount2
Error: No definition for the class found : org.bytedeco.javacpp.opencv_core
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.opencv_core.CV_MAKETYPE(II)I
	at org.bytedeco.javacpp.opencv_core.CV_MAKETYPE(Native Method)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:746)
	at anotherfyp.AnotherFYP.main(AnotherFYP.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

    ```

Kindly give me some proper way to create exactly working runnable Jar file .

**Comment by saudet** [comment]
Please try to use the latest version of JavaCV.

**Comment by mnh-aj123** [comment]
i am already using latest 1.3.2

**Comment by saudet** [comment]
Good! Please also use the latest version
of JavaCPP.

**Comment by mnh-aj123** [comment]
I am using latest version both . But As i told you its working properly while executing it in eclipse but problem lies when i make a runnable jar file i used all three options but result still the same @saudet

**Comment by mnh-aj123** [comment]
i Think it might be permission problem as i have created new user (hduser) and given sudo rights but when i  execute application using sudo command it works well but only when i executed simple javacv jar not hadoop application

**Comment by saudet** [comment]
Be sure to check JavaCPP's debug log as well.

**Comment by mnh-aj123** [comment]
@saudet  do you have any idea about hadoop ? jars execution?

**Comment by saudet** [comment]
It's possible you don't have execute permission of native libraries, yes,
so check the log!

**Comment by mnh-aj123** [comment]
where i can find the logs ? 
@saudet

**Comment by saudet** [comment]
Try to set the system properties "org.bytedeco.javacpp.logger" to "slf4j" and "org.bytedeco.javacpp.logger.debug" to "true": 
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/Logger.html

**Comment by mnh-aj123** [comment]
@saudet  Dont i need javacv-presets ?

**Comment by saudet** [comment]
Yes, of course.

**Comment by mnh-aj123** [comment]
Allright i'll use it and then i'll reply :)

**Comment by mnh-aj123** [comment]
I have used it 


`
hduser@master:/home/mnh/Desktop$ hadoop jar hadoop5.jar
Exception in thread "main" java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:80)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:107)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:81)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:209)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

`
