### ISSUE TITLE
Could not grab frame from http mp4 url InputStream

### ISSUE THREAD

**Issue by Qamar4P** [bytedeco/javacv#714]
Code:
```
url = new URL("http://dev.exiv2.org/attachments/372/3D_L0064.MP4");
//
              urlConnection = (HttpURLConnection) url.openConnection();
              InputStream inputStream = urlConnection.getInputStream();

              FFmpegFrameGrabber grabber= new FFmpegFrameGrabber(inputStream);
              grabber.setFormat("mp4");
              grabber.start();
              grabber.setFrameNumber(100000);

              Frame frame = grabber.grab();

              frameBitmap = new AndroidFrameConverter().convert(frame);

              grabber.stop();
```

Error:
```
/data/app/com.citrusbits.javacvapp-2/lib/arm/libjniavdevice.so: unused DT entry: type 0xf arg 0x47e3
06-07 17:39:39.987 5473-5527/com.citrusbits.javacvapp V/RenderScript: 0xb3704000 Launching thread(s), CPUs 4
06-07 17:39:40.003 5473-5526/com.citrusbits.javacvapp W/System.err: org.bytedeco.javacv.FrameGrabber$Exception: Error on InputStream.close(): 
06-07 17:39:40.004 5473-5526/com.citrusbits.javacvapp W/System.err:     at org.bytedeco.javacv.FFmpegFrameGrabber.releaseUnsafe(FFmpegFrameGrabber.java:206)
06-07 17:39:40.004 5473-5526/com.citrusbits.javacvapp W/System.err:     at org.bytedeco.javacv.FFmpegFrameGrabber.release(FFmpegFrameGrabber.java:133)
06-07 17:39:40.004 5473-5526/com.citrusbits.javacvapp W/System.err:     at com.citrusbits.javacvapp.MainActivity$SavingThread.run(MainActivity.java:97)
06-07 17:39:40.004 5473-5526/com.citrusbits.javacvapp W/System.err: Caused by: java.io.IOException: Mark has been invalidated.
06-07 17:39:40.004 5473-5526/com.citrusbits.javacvapp W/System.err:     at java.io.BufferedInputStream.reset(BufferedInputStream.java:336)
06-07 17:39:40.004 5473-5526/com.citrusbits.javacvapp W/System.err:     at org.bytedeco.javacv.FFmpegFrameGrabber.releaseUnsafe(FFmpegFrameGrabber.java:203)
```

**Comment by saudet** [comment]
Already fixed with pull #703.

**Comment by Qamar4P** [comment]
Code:
  ```
url = new URL("http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_5mb.mp4");
                urlConnection = (HttpURLConnection) url.openConnection();
                InputStream inputStream = urlConnection.getInputStream();
                FFmpegFrameGrabber grabber= new FFmpegFrameGrabber(inputStream);
                grabber.setFormat("mp4");
                grabber.start();

                Frame frame = grabber.grab();

                frameBitmap = new AndroidFrameConverter().convert(frame);

                grabber.stop();
```
Error after taking time:
```
Error on InputStream.read(): java.lang.ArrayIndexOutOfBoundsException: length=2097152; index=-1
06-13 13:45:56.437 13745-17875/com.citrusbits.mymediaapp W/System.err: org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -2: Could not open input "java.io.BufferedInputStream@c947612". (Has setFormat() been called?)
06-13 13:45:56.437 13745-17875/com.citrusbits.mymediaapp W/System.err:     at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:572)
```

**Comment by saudet** [comment]
It's still a duplicate of pull #703...

**Comment by Qamar4P** [comment]
@saudet Using latest java code from javacv and javacpp-presets and .so libraries. Network is okay, everything is properly configured then why I'm getting this exception? I'll will share sample on github soon.

**Comment by saudet** [comment]
Does it happen only with Android?

**Comment by Qamar4P** [comment]
Yes, it happen only with Android. I didn't test it on java JRE. It's working in Android with java.io.File and FileStream but not HttpStream confusing.
By the way,
I'm expecting a faster frame retrieval compare to Android API [MediaMetadataRetriever](https://developer.android.com/reference/android/media/MediaMetadataRetriever.html).

**Comment by saudet** [comment]
So, it might a bug in Android...

**Comment by citrusbits** [comment]
[Top Mobile App Development Company San Francisco](https://citrusbits.com)

**Comment by skeshavan** [comment]
I am facing a similar issue on my windows 7 setup.

When I debugged, there were some differences in how a file got processed & how the custom i/p stream got processed.

With the file, around 5 MB was read and 3 nb_streams were detected.

With the custom i/p stream, 1 MB was read and 1 nb_stream was detected, whose codec_type was neither video nor audio.

The comments in FFmpegFrameGrabber say that "Find the first video and audio stream, unless the user specified otherwise". I also read about this in https://www.codeproject.com/Tips/489450/Creating-Custom-FFmpeg-IO-Context but it is in C/C++. How does the user specify these?

**Comment by saudet** [comment]
setAudioStream() and setVideoStream()

**Comment by skeshavan** [comment]
Thanks for the response! There was another bug in the code as well. In nio, data gets copied into and from ByteBuffer. -1 is a valid byte but an invalid integer. So, any byte that is read from bytebuffer has to be and-ed with & 0xFF and returned by InputStream.read.

After this change, things are working great without any change. Thanks for the great product!

**Comment by saudet** [comment]
Something like this: http://bytedeco.org/news/2014/12/23/third-release/
