### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avformat$AVIOContext

### ISSUE THREAD

**Issue by Nikita-Ustinov** [bytedeco/javacv#715]
Hi, can anyone help me?
In this cod :
```java
public class Player {
     public static void main(String[] args) throws FrameGrabber.Exception {
        FFmpegFrameGrabber g = new FFmpegFrameGrabber("1.MP4");
      }
 }
```
i have this error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avformat$AVIOContext
	at com.mycompany.maven_player.Player.main(Player.java:11)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avformat$AVIOContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

windows 7(x64) 
```xml
<dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>javacv-platform</artifactId>
        <version>1.3.2</version>
 </dependency>
```

**Comment by saudet** [comment]
Please try to use the pom.xml file from README.md: https://github.com/bytedeco/javacv

**Comment by Nikita-Ustinov** [comment]
It didn't help

**Comment by saudet** [comment]
What about this?
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by Nikita-Ustinov** [comment]
In my case <modul> = avformat$AVIOContext ?

**Comment by saudet** [comment]
Just "avformat", that's part of the filenames of the DLLs.

**Comment by Nikita-Ustinov** [comment]
Again error

Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avformat
	at com.mycompany.maven_player.Player.main(Player.java:14)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avformat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by saudet** [comment]
And what does Dependency Walker say?

**Comment by Nikita-Ustinov** [comment]
I apologize for the stupid question, i'm a newcomer. What exactly should i open with Dependency Walker?

**Comment by saudet** [comment]
Try to follow the instructions on the site.

**Comment by Nikita-Ustinov** [comment]
I tried. Dependency Walker should start automatically or from that code (try/catch)? It is normal, that the project is compiled but does not run (try/catch - code)?

**Comment by saudet** [comment]
You're saying it's throwing an error but not catching it? Or are you saying
it's not throwing any errors anymore?

**Comment by Nikita-Ustinov** [comment]
It builds, but when i want to run the project it shows an error
Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avformat

**Comment by saudet** [comment]
So please try to follow the instructions on this page:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by saudet** [comment]
Ah, I see, your problem is caused by a `java.lang.ClassNotFoundException`. That just means the `avformat.class` file is not in your class path. You're going to need to put that file in the class path.
