### ISSUE TITLE
FaceRecognizer runtime error

### ISSUE THREAD

**Issue by lquinn2015** [bytedeco/javacv#729]
I am running this the Open CV Face Recognizer example right now with just directories hardset like this..

```
String trainningDir = "trainningDir/";
Mat testImage = imread("test-folder/general-test/Interns.jpg", V_LOAD_IMAGE_GRAYSCALE);
```

but java returns this runtime error and i am not sue why/how to fix it?

OpenCV Error: Bad argument (At least two classes are needed to perform a LDA. Reason: Only one class was given!) in lda, file /projects/bytedeco/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/core/src/lda.cpp, line 1016
Exception in thread "main" java.lang.RuntimeException: /projects/bytedeco/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/core/src/lda.cpp:1016: error: (-5) At least two classes are needed to perform a LDA. Reason: Only one class was given! in function lda

	at org.bytedeco.javacpp.opencv_face$FaceRecognizer.train(Native Method)
	at OpenCVFaceRecognizer.main(OpenCVFaceRecognizer.java:65)

**Comment by saudet** [comment]
Please try to follow the tutorial here:
http://docs.opencv.org/2.4/modules/contrib/doc/facerec/facerec_tutorial.html

**Comment by Looper360** [comment]
hlw....were u able to solve ur issue ??
