### ISSUE TITLE
Linux FFMPEG Issue in 1.3.2 with OpenCV

### ISSUE THREAD

**Issue by ghost** [bytedeco/javacv#742]
Unfortunately, I need JavaCV 1.3.2. FFmpegFrameGrabber is stalling with some serious issues. FFmpeg is installed on my Linux Ubuntu system. 

I use the following code:
```

 private var grabber : FrameGrabber = null
 grabber = new FFmpegFrameGrabber(f)
 grabber.start()

```
This produces the following error:
```
Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:712)
	at org.bytedeco.javacpp.Loader.load(Loader.java:657)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:468)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:462)
	at org.goat.akka.etl.VideoFileSource$$anon$10.onPull(Sources.scala:1099)
```

I have no idea what to do at this point as I have:

- Added the path to avutil 
- Installed an updated version of ffmpeg
- Tested with OpenCVFrameGrabber

I am using IntelliJ. How can I resolve this without changing my OpenCV version to anything less than the most recent version.

**Comment by saudet** [comment]
This just means the right JAR files are not in your class path. Try to add all JAR files to your class path.

**Comment by saudet** [comment]
BTW, this should be better with JavaCV 1.3.3, so please try with that version.
