### ISSUE TITLE
I have the below problem can any one help?

### ISSUE THREAD

**Issue by abrahman05** [bytedeco/javacv#758]
I have the below problem can any one help?
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2169)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:391)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:385)
	at videoframe.Read.main(Read.java:17)

**Comment by saudet** [comment]
No one will be able to help you if you don't provide more information. In
any case, please start by following the instructions in the README.md file.

**Comment by abrahman05** [comment]
I want to extract frames from video and this is my code:
public class Read{
    public static void main(String []args) throws IOException, Exception
    {
        FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("file.mp4");       
        frameGrabber.start(); 
        IplImage i;
        try {
            OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
            //i = frameGrabber.grab();
            i = converter.convert(frameGrabber.grab());
            BufferedImage  bi = i.getBufferedImage();
            ImageIO.write(bi,"png", new File("D:/Img.png"));
            frameGrabber.stop();
        } catch (FrameGrabber.Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
But when I run this, I get the error that I had mentioned above, I am using java netbeans.
I don't know that what should I do.

**Comment by saudet** [comment]
Like I said, please start by following the instructions in the README.md
file. If that's what you think you did, explain what you did!

**Comment by saudet** [comment]
Please follow the instructions here and it will work:
https://github.com/bytedeco/javacv/#manual-installation
