### ISSUE TITLE
FFmpegFrameRecorder rtmp stream

### ISSUE THREAD

**Issue by lsv12** [bytedeco/javacv#767]
HI 
I am trying to  stream rtmp using FFmpegFrameRecorder  with WEBCAM but it's not work
javacv version: 1.3.2
my code is: 
Loader.load(opencv_objdetect.class);  
     FrameGrabber grabber = FrameGrabber.createDefault(0);
     grabber.start();

     OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage(); 
     IplImage grabbedImage = converter.convert(grabber.grab());
     int width = grabbedImage.width();  
     int height = grabbedImage.height();  
   
     FrameRecorder recorder = FrameRecorder.createDefault(file1, width, height);  
     recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); 
     recorder.setFormat("mp4");
     recorder.setFrameRate(25);  
     recorder.setGopSize(25);
     
     new Red5TestRtmp();
       
     recorder.start();
     long startTime=0;  
     long videoTS=0;  
     CanvasFrame frame = new CanvasFrame("camera", CanvasFrame.getDefaultGamma() / grabber.getGamma());  
     frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
     frame.setAlwaysOnTop(true);  
     Frame rotatedFrame=converter.convert(grabbedImage);//不知道为什么这里不做转换就不能推到rtmp  
     while (frame.isVisible() && (grabbedImage = converter.convert(grabber.grab())) != null) {  
         rotatedFrame = converter.convert(grabbedImage);  
         frame.showImage(rotatedFrame);  
         if (startTime == 0) {  
             startTime = System.currentTimeMillis();  
         }  
         videoTS = 1000 * (System.currentTimeMillis() - startTime);  
         recorder.setTimestamp(videoTS);  
         recorder.record(rotatedFrame);  
         Thread.sleep(40);  
     }  
     frame.dispose();  
     recorder.stop();  
     recorder.release();  
     grabber.stop();  

error info is :
org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -5: Could not open 'null'
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:800)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:351)
	at DemoTest.recordtest(DemoTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

end  console info is 

VIDEOINPUT SPY MODE!

SETUP: Looking For Capture Devices
SETUP: 0) USB2.0 Camera 
SETUP: 1 Device(s) found

***** VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****

SETUP: Setting up device 0
SETUP: USB2.0 Camera
SETUP: Couldn't find preview pin using SmartTee
SETUP: Default Format is set to 640 by 480 
SETUP: trying requested format RGB24 @ 640 by 480
SETUP: trying format RGB24 @ 640 by 480
SETUP: trying format RGB32 @ 640 by 480
SETUP: trying format RGB555 @ 640 by 480
SETUP: trying format RGB565 @ 640 by 480
SETUP: trying format YUY2 @ 640 by 480
SETUP: Capture callback set
SETUP: Device is setup and ready to capture.

[libx264 @ 0000000020669cc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0000000020669cc0] profile High, level 3.0
[libx264 @ 0000000020669cc0] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=25 keyint_min=2 scenecut=40 intra_refresh=0 rc_lookahead=25 rc=abr mbtree=1 bitrate=400 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 0000000020669cc0] final ratefactor: 31.54

hope same one can help me  thanks

**Comment by saudet** [comment]
You'll need to provide a `file1 != null`.

**Comment by lsv12** [comment]
this is file1 = "rtmp://192.168.0.11/live/test11"

**Comment by lsv12** [comment]
but if the file1="/usr/local/test1" is work

**Comment by saudet** [comment]
Ok, what are the messages you get in the log?

**Comment by Achilles2012** [comment]
FFmpegFrameRecorder rtmp stream how can i encryption?
