### ISSUE TITLE
org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -101: Could not open 'null'

### ISSUE THREAD

**Issue by bridsj** [bytedeco/javacv#792]
Hi,
when I am trying to use the JavaCV to call the record video API via rtmp .
When I start the recording process in AndroidSDK >=21, I get an FrameRecorder$Exception: avio_open2 error() error -101: Could not open 'null' Error:
```
org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -101: Could not open 'null' 
at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:806) 
at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:357) 
at cn.campusapp.rtmprecorder.RecordActivity.startRecording(RecordActivity.java:207) 
at cn.campusapp.rtmprecorder.RecordActivity.onClick(RecordActivity.java:304) 
at android.view.View.performClick(View.java:4780) 
at android.view.View$PerformClick.run(View.java:19866) 
at android.os.Handler.handleCallback(Handler.java:739) 
at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5254) 
at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I basically use the init Methods from the RecordActivity.java class.
The error gets thrown at the recorder.start()- command:

```
recorder = new FFmpegFrameRecorder("rtmp://10.60.113.73/live/test", imageWidth, imageHeight, 1);
recorder.setVideoCodec(28);
recorder.setFormat("mp4");

// recorder.setFormat("mp4");
// recorder.setFormat("mjpeg");
recorder.setSampleRate(sampleAudioRateInHz);
// Set in the surface changed method
recorder.setFrameRate(frameRate);
```

I am using the config in build.gradle is:
```
compile group: 'org.bytedeco', name: 'javacv', version: '1.3.3' 
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.2.0-1.3', classifier: 'android-arm' 
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.0-1.3', classifier: 'android-arm'
```
how to solve this problem, help!!!

**Comment by saudet** [comment]
Errno 101 is "Network is unreachable": Fix your network.
