### ISSUE TITLE
problem when deploy javacv on tomcat

### ISSUE THREAD

**Issue by benjazHuang** [bytedeco/javacv#828]
i have a web project use javacv and deploy on tomcat，i copied the javacv jars to tomcat/lib and deploy my project without javacv jars in its WEB-INF/lib, then tomcat start with the following message, how to resolve it

05-Nov-2017 10:50:49.777 WARN [localhost-startStop-1] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/D:/Programs/apache-tomcat-8
.0.42/lib/javacpp.jar] from classloader hierarchy
 java.io.FileNotFoundException: D:\Programs\apache-tomcat-8.0.42\lib\javacpp.jar 
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60)
        at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49)
        at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:334)
        at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:284)
        at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1898)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1131)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:783)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5213)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:587)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1798)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

this is the javacv jars in tomcat/lib
![image](https://user-images.githubusercontent.com/16398678/32411575-7345b5cc-c219-11e7-9614-f2f29dae6e3d.png)

**Comment by saudet** [comment]
> java.io.FileNotFoundException: D:\Programs\apache-tomcat-8.0.42\lib\javacpp.jar
So please copy that file as well.

**Comment by benjazHuang** [comment]
it is not only that file, so many files, example :
android-4.1.1.4.jar
gluegen-rt-main-2.3.1.jar
gluegen-rt-2.3.1-natives-android-aarch64.jar
jocl-2.3.1-natives-windows-i586.jar

i just deploy on windows, but it warn me for so many other jars, and the jars seems strange

**Comment by saudet** [comment]
You won't need to put the ones you don't need like android or jocl. This is just a warning message.

**Comment by benjazHuang** [comment]
yes, it is just a warning message, but so many warning message take a long time to start tomcat, anywhere to turn off the warning message?

**Comment by saudet** [comment]
That would be somewhere in Tomcat's log settings...

**Comment by benjazHuang** [comment]
you're right.
modify the tomcat/conf/catalina.properties,
change 
tomcat.util.scan.StandardJarScanFilter.jarsToSkip=\
to
tomcat.util.scan.StandardJarScanFilter.jarsToSkip=\,*

and then the problem is solved

**Comment by benjazHuang** [comment]
by communicate with you, it change the idea of solving the problem, thanks
