### ISSUE TITLE
Can't create FileDescription whe using FFmpegFrameRecorder create video file from images.

### ISSUE THREAD

**Issue by nguyenquocchinhdev** [bytedeco/javacv#835]
Hi guy,

In my project, I have using FFmpegFrameRecorder to create a video from Images.
After created video and share to Instagram by call intent and set extra putExtra(Intent.EXTRA_STREAM, URI). 
[Instagram Sharing a video](https://www.instagram.com/developer/mobile-sharing/android-intents/)

But have appeared error below.

`AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.example, PID: 17237
                                                             java.lang.NullPointerException:  FileDescriptor must not be null
                                                                 at android.os.Parcel.readException(Parcel.java:1626)
                                                                 at android.os.Parcel.readException(Parcel.java:1573)
                                                                 at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2659)
                                                                 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
                                                                 at android.app.Activity.startActivityForResult(Activity.java:3930)
                                                                 at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                 at android.app.Activity.startActivityForResult(Activity.java:3890)
                                                                 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                 at android.app.Activity.startActivity(Activity.java:4213)
                                                                 at android.app.Activity.startActivity(Activity.java:4181)
                                                                 at 
...`

Can anybody please help me to solve the issue?

Thaks.

**Comment by saudet** [comment]
That error doesn't look related to JavaCV. You'll probably be better of
asking somewhere else.

**Comment by nguyenquocchinhdev** [comment]
Hi @saudet 

I'm sorry, I not sure understand but I think have related. Because of the reason for error from creating the video by FFmpegFrameRecorder.
create FileDescriptor of the video has the error?
