### ISSUE TITLE
Seems like trimMemory doesn't work on Linux

### ISSUE THREAD

**Issue by egorapolonov** [bytedeco/javacv#860]
Hi,
I tried to write some video encoder. 

My software is:
1. Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
2. java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
3. JavaCV 1.3.3

Encoder source code:
```java
import java.io.File;

import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber.Exception;

public class VideoEncoder {
    
    public static void main(String[] args) throws Exception, org.bytedeco.javacv.FrameRecorder.Exception {
        System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", "1G");
        System.setProperty("org.bytedeco.javacpp.maxbytes", "1G");
        System.setProperty("org.bytedeco.javacpp.logger.debug", "true");
        while(true) {
            System.out.println("Started : " + System.currentTimeMillis());
            encodeVideo();
            System.out.println("Finished : " + System.currentTimeMillis());
        }
    }
    
    public static void encodeVideo() throws Exception, org.bytedeco.javacv.FrameRecorder.Exception {
        File outputFile = new File("encoded_video_" + System.currentTimeMillis() + ".mp4" );
        try (FFmpegFrameGrabber video = new FFmpegFrameGrabber("https://www.dropbox.com/s/2psvxdczy7c6p6c/Celebrity%20Beauty%20and%20Lifestyle%20David%20Laport.mp4?dl=1")) {
            video.start();
            long length = video.getLengthInTime();
            try (FFmpegFrameRecorder rec = new FFmpegFrameRecorder(outputFile, video.getImageWidth(),
                    video.getImageHeight(), video.getAudioChannels())) {
                initializeEncoder(video, rec);
                rec.start();
                Frame frame;
                while (video.getTimestamp() <= length && (frame = video.grab()) != null) {
                    rec.record(frame);
                }
            }
        }
    }
    
    public static void initializeEncoder(FFmpegFrameGrabber grabber, FFmpegFrameRecorder recorder) {
        //video
        recorder.setVideoCodecName("libx264");
        recorder.setFrameRate(grabber.getFrameRate());
        recorder.setVideoBitrate(grabber.getVideoBitrate());
        recorder.setVideoOption("threads", "4");
        recorder.setVideoOption("profile", "main");
        recorder.setVideoOption("level","4");
        //audio
        recorder.setSampleRate(grabber.getSampleRate());
        recorder.setAudioBitrate(grabber.getAudioBitrate());
    }

}

```
I executed this code with JVM parameters -Xmx1g -Xms1g
In 3 iterations I got an error:

```java
Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new PointerPointer(1): totalBytes = 29K, physicalBytes = 1G
	at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:126)
	at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:61)
	at org.bytedeco.javacv.FFmpegFrameGrabber.processSamples(FFmpegFrameGrabber.java:866)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame(FFmpegFrameGrabber.java:975)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grab(FFmpegFrameGrabber.java:877)
	at VideoEncoder.encodeVideo(VideoEncoder.java:31)
	at VideoEncoder.main(VideoEncoder.java:16)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 1G > maxPhysicalBytes = 1G
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:576)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.PointerPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:118)
	... 6 more
```
Analyzing of debug messages shows me something strange:
```java
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb1214960,deallocatorAddress=0x7f1b99d80170]
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb1214940,deallocatorAddress=0x7f1b99d80170]
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb267d810,deallocatorAddress=0x7f1b99d80170]
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb267d7f0,deallocatorAddress=0x7f1b99d80170]
org.bytedeco.javacpp.Pointer.trimMemory()Z
Deallocating org.bytedeco.javacpp.PointerPointer[address=0x7f1bb00d8a30,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb00d8a30,deallocatorAddress=0x7f1b99d80170]]
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb184a490,deallocatorAddress=0x7f1b99d80170]
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb23d33d0,deallocatorAddress=0x7f1b99d80170]
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb23d3570,deallocatorAddress=0x7f1b99d80170]
Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f1bb267d730,deallocatorAddress=0x7f1b99d80170]
```

Seems like this line `org.bytedeco.javacpp.Pointer.trimMemory()Z` means catch of UnsatisfiedLinkError. How can I check is does this method executed correctly or not? Or how can I configure something in order to execute this method?
This method was implemented here [https://github.com/bytedeco/javacpp-presets/issues/423](url)

**Comment by saudet** [comment]
Sorry, ainaries on Maven Central don't have it. Try with the SNAPSHOTs.

**Comment by gkozyryatskyy** [comment]
@saudet So on every linux based OS there is a memory leak? Any suggestion how it can be fixed with out using a SNAPSHOT?

**Comment by saudet** [comment]
You could build an empty class with just `@Platform` on it and it will give you a binary with the function.

**Comment by saudet** [comment]
BTW, I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by gkozyryatskyy** [comment]
@saudet And we just switched to native ffmpeg..
Anyway, thank you! It is a great job!

**Comment by saudet** [comment]
You mean the `ffmpeg` program? Yes, it's often a good option, so that's why that's also bundled these days: http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by gkozyryatskyy** [comment]
@saudet Yes, also the main reason was not a problems, in fact it work quite stable for 3 years, but we need a GPU support =)
And yes, we are still using your package.
