### ISSUE TITLE
java.lang.ClassNotFoundException: org.bytedeco.javacpp.opencv_core

### ISSUE THREAD

**Issue by llakcs** [bytedeco/javacv#879]
FATAL EXCEPTION: main
                                                                           Process: com.dchip.door.testopencv, PID: 17506
                                                                           java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.opencv_core
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:918)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:854)
                                                                               at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13)
                                                                               at com.dchip.door.testopencv.MainActivity.CmpPic(MainActivity.java:159)
                                                                               at com.dchip.door.testopencv.MainActivity$1.handleMessage(MainActivity.java:92)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.opencv_core
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.Class.forName(Class.java:251)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:913)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:854) 
                                                                               at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13) 
                                                                               at com.dchip.door.testopencv.MainActivity.CmpPic(MainActivity.java:159) 
                                                                               at com.dchip.door.testopencv.MainActivity$1.handleMessage(MainActivity.java:92) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.UnsatisfiedLinkError: Couldn't load jniopencv_core from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dchip.door.testopencv-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.dchip.door.testopencv-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                               at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                               at java.lang.System.loadLibrary(System.java:526)
                                                                               at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1191)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:953)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:854)
                                                                               at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
                                                                               at java.lang.Class.classForName(Native Method) 
                                                                               at java.lang.Class.forName(Class.java:251) 
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:913) 
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:854) 
                                                                               at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13) 
                                                                               at com.dchip.door.testopencv.MainActivity.CmpPic(MainActivity.java:159) 
                                                                               at com.dchip.door.testopencv.MainActivity$1.handleMessage(MainActivity.java:92) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.UnsatisfiedLinkError: Couldn't load opencv_imgproc from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dchip.door.testopencv-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.dchip.door.testopencv-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                               at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                               at java.lang.System.loadLibrary(System.java:526)
                                                                               at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1191)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:940)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:854) 
                                                                               at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10) 
                                                                               at java.lang.Class.classForName(Native Method) 
                                                                               at java.lang.Class.forName(Class.java:251) 
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:913) 
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:854) 
                                                                               at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13) 
                                                                               at com.dchip.door.testopencv.MainActivity.CmpPic(MainActivity.java:159) 
                                                                               at com.dchip.door.testopencv.MainActivity$1.handleMessage(MainActivity.java:92) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                               at dalvik.system.NativeStart.main(Native Method)

**Code error location** 
`  public double CmpPic(String faceName, String localName) {
        int l_bins = 20;
        int hist_size[] = {l_bins};

        float v_ranges[] = {0, 100};
        float ranges[][] = {v_ranges};

     
       **# error**
       opencv_core.IplImage Image1 = cvLoadImage(facepath + faceName, CV_LOAD_IMAGE_GRAYSCALE);

        opencv_core.IplImage Image2 = cvLoadImage(facedatapath + localName, CV_LOAD_IMAGE_GRAYSCALE);

        opencv_core.IplImage imageArr1[] = {Image1};
        opencv_core.IplImage imageArr2[] = {Image2};

        opencv_core.CvHistogram Histogram1 = opencv_core.CvHistogram.create(1, hist_size, CV_HIST_ARRAY, ranges, 1);
        opencv_core.CvHistogram Histogram2 = opencv_core.CvHistogram.create(1, hist_size, CV_HIST_ARRAY, ranges, 1);

        cvCalcHist(imageArr1, Histogram1, 0, null);
        cvCalcHist(imageArr2, Histogram2, 0, null);

        cvNormalizeHist(Histogram1, 100.0);
        cvNormalizeHist(Histogram2, 100.0);

        return cvCompareHist(Histogram1, Histogram2, CV_COMP_CORREL);
    }`

**budil.gradle config**
 compile group: 'org.bytedeco', name: 'javacv', version: '1.4'
 compile group: 'org.bytedeco', name: 'javacpp', version: '1.4'

**Comment by llakcs** [comment]
How should I solve this problem！

**Comment by saudet** [comment]
Please read the README.md file: Use `javacv-platform`, not just `javacv`.

**Comment by llakcs** [comment]
And there's a new problem. 
Javacv seems to be in conflict with OPENCV
i don't know how to fix?

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'org/bytedeco/javacpp/windows-x86_64/api-ms-win-crt-locale-l1-1-0.dll'

dependencies 
   compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.4'
    compile group: 'org.bytedeco', name: 'javacpp', version: '1.4'
    implementation project(':openCVLibrary340')
