### ISSUE TITLE
Using ffmpeg NoSuchMethodError in start

### ISSUE THREAD

**Issue by fhqsuhpv** [bytedeco/javacv#882]
Hey guys ,

```
	@Test
	public void outputmp3() {
		String inputFile = "/Users/admin/temp/GZ0304100101.wma";
		String outputFile = "/Users/admin/temp/GZ0304100101.mp3";
		AudioTools.convert(inputFile,outputFile, avcodec.AV_CODEC_ID_MP3, 8000, 16000,1);
	}

```

My Utils Class
```
package com.lily.classonline.utils;

import com.lily.classonline.excpetion.ClassOnlineException;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber;
import org.bytedeco.javacv.FrameRecorder;
import org.bytedeco.javacv.FrameRecorder.Exception;

import java.util.List;

public class AudioTools {

    private static void recorder(FFmpegFrameRecorder recorder, FFmpegFrameGrabber grabber) {
        Frame audioSamples = null;
        try {

            while ((audioSamples = grabber.grab()) != null) {
                recorder.setTimestamp(grabber.getTimestamp());
                recorder.record(audioSamples);
            }
        } catch (org.bytedeco.javacv.FrameGrabber.Exception e1) {

            throw new ClassOnlineException(-1,e1.getMessage());
        } catch (Exception e) {

            throw new ClassOnlineException(-1,e.getMessage());
        }
    }

    public static void convert(String inputFile, String outputFile, int audioCodec, int sampleRate, int audioBitrate,
                               int audioChannels) {
        Frame audioSamples = null;

        FFmpegFrameRecorder recorder = null;

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputFile);
        grabber.setAudioCodec(audioCodec);


        if (start(grabber)) {
            recorder = new FFmpegFrameRecorder(outputFile, audioChannels);
            recorder.setAudioOption("crf", "0");
            recorder.setAudioCodec(audioCodec);
            recorder.setAudioBitrate(audioBitrate);
            recorder.setAudioChannels(audioChannels);
            recorder.setSampleRate(sampleRate);
            recorder.setAudioQuality(0);
            recorder.setAudioOption("aq", "10");

            if (start(recorder)) {
                recorder(recorder,grabber);
                stop(grabber);
                stop(recorder);
            }
        }

    }

    public static void convert(List<String> inputFileList, String outputFile, int audioCodec, int sampleRate, int audioBitrate,
                               int audioChannels) {

        FFmpegFrameRecorder recorder = null;
        recorder = new FFmpegFrameRecorder(outputFile, audioChannels);
        recorder.setAudioOption("crf", "0");
        recorder.setAudioCodec(audioCodec);
        recorder.setAudioBitrate(audioBitrate);
        recorder.setAudioChannels(audioChannels);
        recorder.setSampleRate(sampleRate);
        recorder.setAudioQuality(0);
        recorder.setAudioOption("aq", "10");

        if (start(recorder)) {
            for (String inputFile : inputFileList
                    ) {
                FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputFile);
                if(start(grabber)){
                    recorder(recorder,grabber);
                    stop(grabber);
                }
            }
            stop(recorder);
        }
    }

    public static boolean start(FrameGrabber grabber) {
        try {
            grabber.start();
            return true;
        } catch (org.bytedeco.javacv.FrameGrabber.Exception e2) {
            try {

                grabber.restart();
                return true;
            } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
                try {

                    grabber.stop();
                } catch (org.bytedeco.javacv.FrameGrabber.Exception e1) {

                }
            }

        }
        return false;
    }

    public static boolean start(FrameRecorder recorder) {
        try {
            recorder.start();
            return true;
        } catch (Exception e2) {
            try {

                recorder.stop();
                recorder.start();
                return true;
            } catch (Exception e) {
                try {

                    recorder.stop();
                } catch (Exception e1) {

                }
            }
        }
        return false;
    }

    public static boolean stop(FrameGrabber grabber) {
        try {
            grabber.flush();
            grabber.stop();
            return true;
        } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
            return false;
        } finally {
            try {
                grabber.stop();
            } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {

            }
        }
    }

    public static boolean stop(FrameRecorder recorder) {
        try {
            recorder.stop();
            recorder.release();
            return true;
        } catch (Exception e) {
            return false;
        } finally {
            try {
                recorder.stop();
            } catch (Exception e) {

            }
        }
    }

}

```

```
Input #0, asf, from '/Users/admin/temp/GZ0304100101.wma':
  Metadata:
    WMFSDKNeeded    : 0.0.0.0000
    DeviceConformanceTemplate: L1
    WMFSDKVersion   : 12.0.7601.17514
    IsVBR           : 0
  Duration: 00:00:05.29, start: 0.000000, bitrate: 116 kb/s
    Stream #0:0(chi): Audio: wmav2 (a[1][0][0] / 0x0161), 44100 Hz, 2 channels, fltp, 96 kb/s

java.lang.NoSuchMethodError: org.bytedeco.javacpp.avformat$AVStream.codecpar()Lorg/bytedeco/javacpp/avcodec$AVCodecParameters;

	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:594)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:508)
	at com.lily.classonline.utils.AudioTools.start(AudioTools.java:110)
	at com.lily.classonline.utils.AudioTools.convert(AudioTools.java:63)
	at com.lily.classonline.ClassonlineApplicationTests.outputmp3(ClassonlineApplicationTests.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Can anyone Help ?

**Comment by fhqsuhpv** [comment]
```
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>3.0.2-1.2</version>
		</dependency>
```

**Comment by saudet** [comment]
Please use ffmpeg 3.4.1-1.4
