### ISSUE TITLE
Could not open input  when using SMB connection

### ISSUE THREAD

**Issue by erkan22789** [bytedeco/javacv#895]
Hi,
I want to play video file like this but it gives me

org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -1330794744: Could not open input "smb://10.6.1.28/kayit0/33708/1517208041885_00000001.ts". (Has setFormat() been called?)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:572)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:508)
	at javacv.RecordPlayer.setGrabberOptions(RecordPlayer.java:137)
	at javacv.RecordPlayer$2.run(RecordPlayer.java:95)

` FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("smb://10.6.1.28/kayit0/33708/1517208041885_00000001.ts");
 grabber.setImageHeight(480);
 grabber.setImageWidth(860);
 grabber.start();`

So, maybe you have some ideas how I can resolve this
Thank you.

**Comment by saudet** [comment]
We would need to build FFmpeg with support for SMB:
https://ffmpeg.org/ffmpeg-protocols.html#libsmbclient
We just need to update the cppbuild.sh file accordingly:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh
If you would like to give it a try but are encountering any issues doing it,
please let me know and I will help! Thank you
