### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bytedeco/javacpp/opencv_imgcodecs

### ISSUE THREAD

**Issue by yangdengcheng** [bytedeco/javacv#932]
Hi，all
    I have a problem,
    Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacpp/opencv_imgcodecs
    Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.opencv_imgcodecs
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

   i can run normally with the IDEA ,but when i compile this project , it will hint at the above error.
   Can you tell me how to solve this problem?

**Comment by yangdengcheng** [comment]
Tks.
But i import ffmpeg.jar,ffmpeg-windows-x96.jar,javacpp.jar,javacv-1.3.3.jar,javacv-platform-1.3.3.jar,opencv.jar,opencv-windows-x86_64.jar,why it still hint the error?

**Comment by saudet** [comment]
Try adding more JAR files like maybe opencv-windows-x86.jar?
