### ISSUE TITLE
face detaction example

### ISSUE THREAD

**Issue by proewer** [bytedeco/javacv#950]
I try the javavc lib. I use the version 1.4.1. I copy a example code from this [link](https://gist.github.com/x3n0n-x/99a8bbd3dcec87b80e77) and change the old imports. Now i get a exception. Someone know what i do wrong?

```
OpenCV(3.4.1) Error: Null pointer (Invalid classifier cascade) in cvHaarDetectObjectsForROC, file /home/travis/build/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.4.1/modules/objdetect/src/haar.cpp, line 1238
Exception in thread "main" java.lang.RuntimeException: OpenCV(3.4.1) /home/travis/build/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.4.1/modules/objdetect/src/haar.cpp:1238: error: (-27) Invalid classifier cascade in function cvHaarDetectObjectsForROC

	at org.bytedeco.javacpp.opencv_objdetect.cvHaarDetectObjects(Native Method)
	at org.bytedeco.javacpp.helper.opencv_objdetect.cvHaarDetectObjects(opencv_objdetect.java:66)
	at FaceDetection.detect(FaceDetection.java:27)
	at FaceDetection.main(FaceDetection.java:21)
```
```
import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgcodecs.*;
import static org.bytedeco.javacpp.opencv_objdetect.*;

import static org.bytedeco.javacpp.opencv_highgui.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;

import org.bytedeco.javacpp.opencv_core.CvMemStorage;
import org.bytedeco.javacpp.opencv_core.CvRect;
import org.bytedeco.javacpp.opencv_core.CvScalar;
import org.bytedeco.javacpp.opencv_core.CvSeq;
import org.bytedeco.javacpp.opencv_core.IplImage;
import org.bytedeco.javacpp.opencv_objdetect.CvHaarClassifierCascade;

public class FaceDetection {

	public static final String XML_FILE = "haarcascade_frontalface_default.xml";

	public static void main(String[] args) {
		IplImage img = cvLoadImage("shakira.jpg");
		detect(img);
	}

	public static void detect(IplImage src) {
		CvHaarClassifierCascade cascade = new CvHaarClassifierCascade(cvLoad(XML_FILE));
		CvMemStorage storage = CvMemStorage.create();
		CvSeq sign = cvHaarDetectObjects(src, cascade, storage, 1.5, 3, CV_HAAR_DO_CANNY_PRUNING);
	

		cvClearMemStorage(storage);

		int total_Faces = sign.total();

		for (int i = 0; i < total_Faces; i++) {
			CvRect r = new CvRect(cvGetSeqElem(sign, i));
			cvRectangle(src, cvPoint(r.x(), r.y()), cvPoint(r.width() + r.x(), r.height() + r.y()), CvScalar.RED, 2,
					CV_AA, 0);

		}

		cvShowImage("Result", src);
		cvWaitKey(0);

	}
}
```
haarcascade_frontalface_default.xml from [here](https://github.com/opencv/opencv/tree/2.4/data/haarcascades)

**Comment by proewer** [comment]
i found the original github repo and try the xml from [here](https://github.com/nikhil9/FaceDetection).
i get the same error. it is possible that i must use a newer xml?

my goal i want run the example code with the new lib version.

**Comment by saudet** [comment]
The C API still does not support the newer cascade format. We need to use the C++ API for this:
https://github.com/bytedeco/javacv/blob/master/samples/FaceRecognizerInVideo.java#L36

**Comment by ramesh586** [comment]
Hi with version 1.5.1,
cvHaarDetectObjects(smallImage, classifier, storage, 1.1, 3,
                            CV_HAAR_FIND_BIGGEST_OBJECT | CV_HAAR_DO_ROUGH_SEARCH);
not able to to found the import for this method. can someone explain me how to import?

**Comment by saudet** [comment]
@ramesh586 The package names changed a bit with 1.5:
http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/
