### ISSUE TITLE
Can not read the CascadeClassifier file when run on spark

### ISSUE THREAD

**Issue by blackredscarf** [bytedeco/javacv#954]
If I don't use Spark, the code can run normally.
But when running on Spark, an error was thrown when reading the CascadeClassifier file.
the err_log: https://gist.github.com/blackredscarf/c592709b8dc08b9c5c8f8ad018c66fca

My the code like this:
```java
public static String getPath(String file){
    return getResourcePath() + file;
}
public static String getResourcePath(){
    return Object.class.getResource("/").getPath().substring(1);
}

CascadeClassifier faceDetector  = new CascadeClassifier(getPath("haarcascade_frontalface_alt.xml"));
//...

RectVector faces = new RectVector();
faceDetector.detectMultiScale(img, faces);
```

**Comment by saudet** [comment]
Please try again with OpenCV 3.4.1 and JavaCV 1.4.1.

**Comment by saudet** [comment]
Also, it looks like you're trying to use OpenCL. That's probably not a good idea in a multithreaded application. Disabling OpenCL will most likely fix this.

**Comment by blackredscarf** [comment]
@saudet 
How can I to disable the opencl ?

**Comment by saudet** [comment]
You could try this, for example: opencv/opencv#9852

**Comment by blackredscarf** [comment]
@saudet 
There is another problem. I used the absolute path to read the CascadeClassifier file on spark.  
But throw this error:
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 5, 192.168.240.202): java.lang.RuntimeException: /projects/bytedeco/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.4.0/modules/core/src/persistence.cpp:4198: error: (-27) NULL or empty buffer in function cvOpenFileStorage

        at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.allocate(Native Method)
        at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.<init>(opencv_objdetect.java:679)
        at pers.zjw.face.detector.handler.FaceDetecor.detect(FaceDetecor.java:16)
        at pers.zjw.face.detector.handler.VideoHandle.handle(VideoHandle.java:64)
        at pers.zjw.face.detector.handler.HandleEntrance.handle(HandleEntrance.java:24)
        at pers.zjw.face.detector.spark.StreamUtils$$anonfun$processRdd$1.apply(StreamUtils.scala:19)
        at pers.zjw.face.detector.spark.StreamUtils$$anonfun$processRdd$1.apply(StreamUtils.scala:10)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:894)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:894)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1899)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1899)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:86)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
It looks like no file can be read.

My Code like this:
```java
CascadeClassifier faceDetector  = new CascadeClassifier("/home/hadoop/haarcascade_frontalface_alt.xml");
```

**Comment by saudet** [comment]
Sure, put it as part of your resources and use `Loader.extractResource()`:
https://github.com/bytedeco/javacv/blob/master/samples/FacePreview.java#L123

**Comment by saudet** [comment]
CascadeClassifier does not support that. You'll need to create a temporary file.
