### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_version_info" referenced by "/data/app/com.domain.appname-1/lib/arm/libjniavutil.so"...

### ISSUE THREAD

**Issue by DeKinci** [bytedeco/javacv#970]
I'm currently getting this error on some devices (exactly on Meizu Pro 6) but on others with same cpu (Huawei Honor 9 Lite) everything works fine,
I use manual installation with unpacking .so files into jniLibs and relinker:
```
ReLinker.Logger logger = message -> Log.v("NativeLoader", message);

        ReLinker.log(logger).recursively().loadLibrary(context, "jniavcodec");
        ReLinker.log(logger).recursively().loadLibrary(context, "avcodec");

        ReLinker.log(logger).recursively().loadLibrary(context, "jniavdevice");
        ReLinker.log(logger).recursively().loadLibrary(context, "avdevice");

        ReLinker.log(logger).recursively().loadLibrary(context, "jniavfilter");
        ReLinker.log(logger).recursively().loadLibrary(context, "avfilter");

        ReLinker.log(logger).recursively().loadLibrary(context, "jniavformat");
        ReLinker.log(logger).recursively().loadLibrary(context, "avformat");

        ReLinker.log(logger).recursively().loadLibrary(context, "jniavutil");
        ReLinker.log(logger).recursively().loadLibrary(context, "avutil");

        ReLinker.log(logger).recursively().loadLibrary(context, "jnipostproc");
        ReLinker.log(logger).recursively().loadLibrary(context, "postproc");

        ReLinker.log(logger).recursively().loadLibrary(context, "jniswresample");
        ReLinker.log(logger).recursively().loadLibrary(context, "swresample");

        ReLinker.log(logger).recursively().loadLibrary(context, "jniswscale");
        ReLinker.log(logger).recursively().loadLibrary(context, "swscale");
```
This code is called from the first activity of application, before any library elements used.

This is log I have:
```
  E/ACRA (12118): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_version_info" referenced by "/data/app/com.domain.appname-1/lib/arm/libjniavutil.so"... 
  E/ACRA (12118): at java.lang.Runtime.loadLibrary(Runtime.java:372) 
  E/ACRA (12118): at java.lang.System.loadLibrary(System.java:1076) 
  E/ACRA (12118): at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1220) 
  E/ACRA (12118): at org.bytedeco.javacpp.Loader.load(Loader.java:980) 
  E/ACRA (12118): at org.bytedeco.javacpp.Loader.load(Loader.java:879) 
  E/ACRA (12118): at org.bytedeco.javacpp.avutil.(avutil.java:10) 
```

What I found sometimes it goes with the `com.domain.appname-1` directory, and sometimes with the `com.domain.appname-2`.

Also it worked in a couple of builds, but mostly not (I did not change anything in library loading)

**Comment by saudet** [comment]
Before `jniavutil`, you'll need to load `avutil`, and that before everything else (`avcodec`, `avformat`, etc)

**Comment by DeKinci** [comment]
Well, I loaded all the non jni libs before all non-jni and avutils (with jniavutils) before all of them and that did not help

**Comment by saudet** [comment]
That's fine, but we still need to load `avutil` before anything else.

**Comment by DeKinci** [comment]
Yes, I do it like this:
```
        ReLinker.log(logger).recursively().loadLibrary(context, "avutil");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavutil");

        ReLinker.log(logger).recursively().loadLibrary(context, "avcodec");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavcodec");

        ReLinker.log(logger).recursively().loadLibrary(context, "avdevice");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavdevice");

        ReLinker.log(logger).recursively().loadLibrary(context, "avfilter");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavfilter");

        ReLinker.log(logger).recursively().loadLibrary(context, "avformat");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavformat");

        ReLinker.log(logger).recursively().loadLibrary(context, "postproc");
        ReLinker.log(logger).recursively().loadLibrary(context, "jnipostproc");

        ReLinker.log(logger).recursively().loadLibrary(context, "swresample");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniswresample");

        ReLinker.log(logger).recursively().loadLibrary(context, "swscale");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniswscale");
```
and it is not working

**Comment by saudet** [comment]
Please post the full Android log.

**Comment by DeKinci** [comment]
I don't have one. Error pops on remote phone, and I only get ACRA repot, which (idk why) does not include relinker log (but includes android log, which I already posted)

**Comment by DeKinci** [comment]
Sorry, my bad: I called `av_log_set_level(AV_LOG_DEBUG);` before using relinker

**Comment by saudet** [comment]
Anyway, there's probably another `avutil.so` somewhere on that device that is interfering with the one from JavaCPP/JavaCV. You could rebuild from source and give it another name, but I'm wondering if something like described on https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29 works around that:
```java
Loader.loadLibrary(new URL[0], "avutil");
```

**Comment by DeKinci** [comment]
I'll try that when whill get access to such device

**Comment by saudet** [comment]
FYI, commit bytedeco/javacpp@f1f21ae should take care of this issue.
