### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: **Unable to guess input file format**	

### ISSUE THREAD

**Issue by SnehaJagtap** [bytedeco/javacv#971]
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadStaticModel(WordVectorSerializer.java:2528) 	at org.deeplearning4j.examples.convolution.sentenceclassification.CnnSentenceClassificationExample.main(CnnSentenceClassificationExample.java:134)

I am Using IntelliJ IDE For Deeplearning4j  library. I am trying to run cnnsentenceclassification.java file but I got this issue. Could please help me to resolve this issue.??

**Comment by saudet** [comment]
I'm afraid that's not related to JavaCPP or JavaCV. Please post here:
https://github.com/deeplearning4j/deeplearning4j/issues/
