### ISSUE TITLE
Grab First Frame of Video throws NullPointerException, Frame is null

### ISSUE THREAD

**Issue by NicolaSchueepp** [bytedeco/javacv#985]
i try to get the First frame of a Video, but when i launch my code it says that the Image i'm trying convert is null. But the Frame on the start is not null.
Version:
```
<dependency>
	<groupId>org.bytedeco</groupId>
	<artifactId>javacv</artifactId>
	<version>1.0</version>
</dependency>
```

Code:
```
package controller;

import java.awt.image.BufferedImage;
import java.io.IOException;

import org.bytedeco.javacpp.opencv_core.IplImage;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.Java2DFrameConverter;
import org.bytedeco.javacv.OpenCVFrameConverter;

import javafx.embed.swing.SwingFXUtils;
import javafx.scene.image.Image;

public class FrameOfVideo {
	Image image;
	BufferedImage bImage;

	public FrameOfVideo() throws IOException, Exception {
		FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("src/videos/VIDEO0037.mp4");
		grabber.start();
		
		OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
	        Frame frame = grabber.grabFrame();
            if(frame == null) {
	    	System.out.println("frame");
	    }
	        IplImage iplImage = converter.convert(frame);
	        BufferedImage bImage = IplImageToByteArray(iplImage);
	    
	    if(bImage == null) {
	    	System.out.println("BufferedImage is null");
	    }
	    
	        image = SwingFXUtils.toFXImage(bImage, null);

		grabber.stop();
	}

	public static BufferedImage IplImageToByteArray(IplImage src) {
		OpenCVFrameConverter.ToIplImage grabberConverter = new 
               OpenCVFrameConverter.ToIplImage();
	       Java2DFrameConverter paintConverter = new Java2DFrameConverter();
	       Frame frame = grabberConverter.convert(src);
	       return paintConverter.getBufferedImage(frame,1);
	}

	public BufferedImage getImage() {
		return this.bImage;
	}

	public static void main(String[] args) {
		try {
			FrameOfVideo frameOfVideo = new FrameOfVideo();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```

Exception:

```
BufferedImage is null
java.lang.NullPointerException
	at javafx.embed.swing.SwingFXUtils.toFXImage(SwingFXUtils.java:85)
	at controller.FrameOfVideo.<init>(FrameOfVideo.java:32)
	at controller.FrameOfVideo.main(FrameOfVideo.java:50)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'src/videos/VIDEO0037.mp4':
  Metadata:
    major_brand     : 3gp4
    minor_version   : 0
    compatible_brands: isom3gp4
    creation_time   : 2018-05-03 11:14:05
  Duration: 00:00:03.90, start: 0.000000, bitrate: 47262 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, smpte170m), 3840x2160, 54052 kb/s, SAR 1:1 DAR 16:9, 29.88 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2018-05-03 11:14:05
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 97 kb/s (default)
    Metadata:
      creation_time   : 2018-05-03 11:14:05
      handler_name    : SoundHandle
```

**Comment by saudet** [comment]
Call `grabImage()` instead of `grabFrame()`.
